[2단계 - 주문 기능 구현] 폴로 미션 제출합니다.
woowacourse/jwp-shopping-order pull request #10
Opened 2023-05-30 14:09 UTC by green-kong

2023-05-31 00:04 UTC, jamie9504 requested changes
폴로, 안녕하세요. 리뷰어 제이미입니다 😄 

레벨2의 마지막 미션이네요. 저도 폴로를 만나게 되어 기뻐요.

코멘트를 조금 남겨두었어요. 의견을 묻는 코멘트가 대부분이니 폴로의 의견을 적어주세요. 😃 
이번엔 product 코드 위주로 봐서, 이후 리뷰요청시 테스트 코드도 보도록 하겠습니다!

2023-05-31 00:04 UTC, jamie9504 commented on README.md
> +-[x] Order의 Identity를 통해 주문 내용을 조회 할 수 있다.
1. 띄어쓰기가 잘 되지 않았네요!
    <img width="754" alt="image" src="https://github.com/woowacourse/jwp-shopping-order/assets/59511689/c865aa36-6eb7-4242-b6a4-bf147ed57d76">

2. 이번 협업을 하면서 API 설계를 클라이언트(웹 프론트엔드, 모바일 안드로이드)와 논의하여 진행했을텐데요. 
    1. API 설계면 어느부분까지 같이 설계하였나요? (ex. API URL, Exception Http Status Code ... etc)
    2. 백엔드 크루들과 페어할 때와 다른점이 있었나요?
    3. 서로 의견을 조율할 땐 어떤 방식으로 조율하였나요?
    4. 느낀 점이 있다면 적어줘도 좋을 것 같아요.

2023-05-31 00:04 UTC, jamie9504 commented on src/main/java/cart/DiscountPolicyConfig.java
> +    public PricePolicy configureDiscountPolicy() {
1. `@Configuration` + `@Bean`과 `@Component`
    1. 각각 어떨 때 사용하는 애너테이션인가요?
    2. 지금 상황에서는 어떤 것을 사용하는 것이 적합할까요?
    3. 2번과 같이 답한 이유는 무엇인가요?
2. `DiscountPolicyConfig`와 `WebMvcConfig`는 `JwpCartApplication`와 같은 패키지에 위치하고 있는데요. 이렇게 위치한 이유가 있을까요?

2023-05-31 00:04 UTC, jamie9504 commented on src/main/java/cart/application/OrderService.java
> +    }
1. class명에 `orderController`, `orderService`, `orderRequest`, `orderRepository`가 있는데, Service와 Controller에서 메서드명이 `order`인게 조금 애매한 느낌이 있네요!
폴로는 해당 프로그램에서 order를 동사 + 명사로 각각 사용하고 있네요!
개인적으로는 한 용어를 여러 의미로 사용하게 되면, 직관적이지 않은 느낌이 있는데 이 부분도 역시나 취향 관련된 부분이라서, 폴로의 의견이 궁금하네요 😄 

2. 개인적으로는 괄호가 중첩되면, 평상시 좌 -> 우로 보던 흐름을 깨서 가독성이 떨어진다고 생각하는데요.
이 부분은 취향의 영역이라 폴로는 어떻게 생각하는지 궁금하네요!

    ``` java
    List<CartItem> 변수추출 = cartItemDao.findByIds(cartItemIds);
    final CartItems cartItems = new CartItems(변수추출);
    ```

3. `cartItemDao`를 통해서는 `List<CartItem>`를 받아오고 있고, `orderRepository.saveOrder`를 통해서는 `CartItems`를 넘겨주고 있네요!
    1. Dao에서는 포장되지 않은 List를, Repository에서는 포장된 일급 컬렉션을 받아주고 있는데, 이는 의도된 부분인가요?
    2. 1이 의도된 부분이라면 `new CartItems(cartItemDao.findByIds(cartItemIds))` 이 부분은 service에서 역할을 가지고 있는 것과 repository에서 역할을 가지고 있는 것 중 어느 쪽이 더 폴로의 의도에 맞는 구현 방법일까요?
    3. 1이 의도되지 않은 부분이라면, Dao와 Repository는 각각 어떤 기준으로 분리했는지 궁금해요!

4. 다음과 같은 역할을 하고 있는 아래 로직은 service가 담당하고 있네요. 이 부분을 domain이 담당하는 것과 service가 담당하는 것은 각각 어떤 장/단점이 있을까요?

    ``` java
    cartItems.validateAllCartItemsBelongsToMember(member);
    cartItems.validateExistentCartItems(cartItemIds);

    final Integer totalPrice = cartItems.calculatePriceSum();
    final Integer finalPrice = priceCalculator.calculateFinalPrice(totalPrice, member);
    ```

    1. `cartItems`: cartItems가 해당하는 member인지 검증
    2. `cartItems`: cartItemIds와 cartItems의 수가 일치한지 검증
    3. `cartItems`: cartItems 총 금액 계산
    4. `priceCalculator`: 할인금액 계산

2023-05-31 00:04 UTC, jamie9504 commented on src/main/java/cart/application/OrderService.java
> +    }
`findOrdersByMember`는 member를 통해 orders를 찾는 메서드인데요.
`findOrderById`는 id를 통해 order를 찾을 것이라 생각이 드는 메서드명인데 파라미터로 member도 받고 있네요.
조금 더 적합한 메서드명이 없을까요?

2023-05-31 00:04 UTC, jamie9504 commented on src/main/java/cart/dao/CartItemDao.java
1. `private final RowMapper<CartItem> defaultRowMapper`에서 defaultRowMapper는 어떤 기준으로 default라는 이름이 붙었을까요? `findByMemberId`에서도 rowMapper를 람다로 선언하고 있기도 하고, `cartItemDao`에 위치했지만 Join을 한 Mapper라서 default가 적합한 이름인지 고민해볼 필요가 있을 것 같아요.
2. 사용하지 않는 메서드가 있네요 😄 전반적으로 체크해보고 사용하지 않는 경우 지워볼까요?
3. cartItem의 id가 `cartIds`, `ids`, `id` 등으로 용어가 통일되지 않아보여요.
4. `jdbcTemplate.query(sql, ids.toArray(), defaultRowMapper)`는 deprecated된 메서드로 보이네요! 해당 메서드를 사용하는 부분이 조금 보이는데, 어떻게 개선해볼 수 있을까요?
5. `findByIds`는 메서드명만 보았을 때는 `List`를 반환한다고 예측하기 어려운 것 같은데, 폴로의 생각은 어떠신가요?
6. 메서드명을 훑어보았을 때, dao의 메서드 명명 방법이 일관성이 조금 떨어져 보이는 부분이 있는데, 이 부분 5번의 생각대로 개선해볼까요? (ex - `cartItemDao.findByIds()`, `orderDao.findByMember()`, `orderedItemDao.findItemsByOrderId()`)

2023-05-31 00:04 UTC, jamie9504 commented on src/main/java/cart/dao/OrderDao.java
> +    public Long addOrder(OrderEntity order) {
`cartItemDao`에서는 `save`라는 메서드명을 사용했는데, `OrderDao`에서는 `addOrder`라는 메서드명을 사용하고 있네요.
1. `add-`는 어떤 의미를 담기 위해 사용한 부분일까요?
2. `order`를 접미사로 적어준 이유가 따로 있을까요?

2023-05-31 00:04 UTC, jamie9504 commented on src/main/java/cart/domain/Member.java
> +    }
Member는 식별자가 id라서 위와 같이 equals&hashCode를 재정의한 것 같은데요.
id를 식별자로 가진 다른 domain들은 재정의해주지 않은 이유가 있을까요?

2023-05-31 00:04 UTC, jamie9504 commented on src/main/java/cart/domain/CartItem.java
>  public class CartItem {
`CartItem`은 domain과 entity에서 모두 선언되어 있네요. (`Member`도요)
1. 가지고 있는 변수는 다르지만, 클래스명이 동일한데 이는 의도된 부분일까요?
2. 다른 domain들은 entity와 클래스명이 다르게 선언되어 있는데, 한 방법을 선택해서 통일시켜주면 좋을 것 같네요.

2023-05-31 00:04 UTC, jamie9504 commented on src/main/java/cart/domain/price/discount/grade/Grade.java
> +}
1. `gradeValue`를 int가 아닌 Integer로 선언한 이유는 무엇인가요? 
2. 정적 팩터리 메서드의 일반적인 메서드명을 사용하지 않고, `find-`로 시작하는 이름을 지어준 이유가 있을까요?
3. `findGradeByGradeName`는 `grade.name()`을 사용하고 있는데요. `.name()`을 통해 ENUM 상수명을 그대로 이용하는 것과 동일한 값을 가진 멤버변수를 선언해서 이용하는 것 (ex. `getName()`)은 어떤 차이가 있을까요?
4. Grade를 별도의 테이블에 저장하고 있는데요.
    1. 별도의 테이블에 저장한 이유가 있을까요?
    2. 별도의 테이블에 데이터를 저장하고 있는데, 해당 Enum의 gradeValue만 저장하고 있네요. Grade에 대한 정보는 Enum으로 관리되고 단순히 Table엔 value만 저장하는 것이 의도된 부분이 맞을까요?
    3. 다음의 장/단점은 무엇이 있을까요?
        1. (현재) Table엔 식별자만 저장, Enum에서 관련된 데이터를 모두 가지고 있고 로직 처리
        2. Column엔 식별자만 저장, Enum에서 관련된 데이터를 모두 가지고 있고 로직 처리
        3. Table에서 관련된 데이터를 모두 가지고 있음, Grade는 엔티티로 로직만 처리
        4. Column에서 관련된 데이터를 모두 가지고 있음, Grade는 Member에 속한 도메인으로 로직만 처리
        5. Column에서 관련된 데이터를 모두 가지고 있음, Grade는 Member에 속한 필드로 Member에서 로직만 처리

2023-05-31 00:04 UTC, jamie9504 commented on src/main/resources/application.yml
> +      mode: always
1. test에 대한 설정이 product 설정파일에 있네요! 이는 의도된 바인가요?
2. `application.properties`도 있고, `application.yml`도 있네요. 이렇게 설정한 이유가 무엇일까요?

2023-05-31 02:15 UTC, green-kong commented on README.md
> +-[x] Order의 Identity를 통해 주문 내용을 조회 할 수 있다.
2-1. 우선은 다같이 도메인을 분석하며, 요구사항이었던 `재화요소` 중 어떤 것을 선택할지에 대해 얘기를 나눴습니다.
그 후 API URL, RequestBody의 내용과 ResponseBody의 형식을 정했습니다. 마지막으로 예외가 발생하는 경우 ErrorResponse 형식을 정했습니다.

2-2. 백엔드 크루들로만 구성된 페어를 진행할 때와는 많은 차이점을 느꼈습니다. 백엔드 크루들과 페어를 할때는 도메인의 설계에 대해 주로 얘기를 나눴던 반면, 클라이언트 크루들과는 어떤식으로 요청과 응답을 보내야 각각의 영역에서 처리하기가 수월하고 효율적이게 될지에 대해 얘기를 나눴습니다.

2-3 . 사실 이번 협업미션을 진행하며 크게 의견을 조율할만한 부분이 있지는 않았는데요.
다만, `재화 요소` 를 선택하는 과정에서 안드로이드 크루들과 백엔드 크루들간에 반대의 의견을 갖고 있었습니다.
저를 포함한 백엔드 크루들은 `쿠폰, 할인, 포인트, 배송비 등등 해볼 수 있는 재화요소는 다 집어 넣어 보자` 라는 의견이었고,
안드로이드 크루들은 `가장 핵심적인 요소인 주문 기능에 집중하고 재화요소는 할인정책 정도만 추가하고 싶다` 라는 의견이었습니다.
이 부분에 대해 얘기를 나누다가, 백엔드의 0~1 단계는 서버 배포 작업만 하면 완료가 되는 반면, 안드로이드 크루들은 0~1 단계에서 기존의 코드들을 대거 수정해야 한다는 사실을 알게 되었습니다.
안드로이드 크루들이 맹목적인 이유로 반대하는 것이 아니라 일정상의 이유로 반대한다는 것을 깨닫고, 안드로이드 크루들의 의견에 따라 할인 정책만 추가하는 방향으로 진행했습니다.

2-4. 기존의 백엔드 크루들과 협업을 할때와는 다른 새로운 경헙이었습니다. 백엔드 크루들과 얘기를 나눌때는 도메인의 설계와 내부 코드에 대한 얘기가 주를 이룬 반면, 안드로이드 크루들과 얘기를 얘기를 나눌 때에는 어떠한 방식으로 데이터를 주고받는 것이 서로에게 도움이 되는지와 일정조율 등등 서로의 입장을 이해하는 과정을 얻을수 있었습니다.

2023-05-31 04:56 UTC, green-kong commented on src/main/java/cart/DiscountPolicyConfig.java
> +    public PricePolicy configureDiscountPolicy() {
1-1. `@Configuration + @Bean` 은 수동으로 빈을 등록하는 경우, `@Component`는 스프링의 `ComponentScan`을 통해 자동으로 빈 등록을 하는 경우 사용합니다.
 
1-2. 현재의 코드에서는 `@Component` 을 사용하는것이 적절한것 같습니다.

1-3. 기존의 코드에서는 composite 패턴을 사용하여 DefaultPricePolicy와 BasicPriceDiscountPolicy, BasicGradeDiscountPolicy 모두 DiscountPolicy의 구현체로 작성했었습니다.

```java
// 기존 코드
public class DefaultPricePolicy implements DiscountPolicy {
    private final List<DiscountPolicy> discountPolicies;

    public DefaultPricePolicy(List<DiscountPolicy> discountPolicies) {
        this.discountPolicies = discountPolicies;
    }
    // 후략
}
```

위와 같이 작성된 경우 DefaultPricePolicy에는 `@Component` 를 통한 빈등록이 아닌 @Configuration 을 통한 수동 빈등록이 필요합니다. 하지만 현재는 interface를 분리하여 사용하고 있기에 BasicPriceDiscountPolicy, BasicGradeDiscountPolicy, DefaultPricePolicy 에 `@Component` 를 붙이고, 자동 빈 등록 방식을 이용하는게 더 관리에 용이할 것 같습니다.
interface를 분리하는 과정에서 놓친 부분이었는데, 감사합니다.

2. Config 파일 같은 경우 우선적으로 확인을 하는 것이 코드의 전체 흐름을 파악하기 쉬울것이라 생각하여 `JwpCartApplication` 과 같은 레벨에 위치하는 것이 확인에 용이할 것이라 생각하여 현재와 같이 위치시켰습니다.
그런데 제이미의 리뷰를 통해 곰곰히 생각해보니, 서비스가 확장됨에 따라 Config 파일의 갯수가 늘어나는 경우 오히려 더 확인이 어려울 것 같다는 생각도 드네요.. config 패키지를 통해 패키지를 분리하는 것이 조금 더 적절할 것이라 생각이 듭니다!

2023-05-31 05:15 UTC, green-kong commented on src/main/java/cart/application/OrderService.java
> +    }
1. 오.... 전혀 생각하지 못한 부분인데... 제이미의 말대로 order라는 단어 자체가 동사이기도 하고 명사이기도 하다보니 이렇게 작성을 했습니다. controller와 service 에서는 `상품을 주문을 한다`라는 의미로 `order`를 동사로 사용했고, `repository`와 `dao`에서는 `order data를 저장한다.` 라는의미로  `order`를 명사로 사용했는데, 음.. 보는 사람에 따라 헷갈릴수도 있겠다는 생각이 들기도 하고.. 오히려 더 직관적이지 않나 라는 생각도 들어서 헷갈리는데요... 흠 저는 6:4 정도의 비율로 현재의 코드가 더 직관적이라는 생각이 듭니다..!

2023-05-31 05:18 UTC, green-kong commented on src/main/java/cart/application/OrderService.java
> +    }
2. 이 부분은 저의 명확한 기준 이라기보다는 `제가 보기에 편한 정도`를 척도로 삼고있습니다.
예를 들어, 중첩괄호 depth가 2가 넘어간다거나, 메서드에서 인자를 2개이상 받는 경우는 제이미가 얘기해주신 대로 변수로 사용하는 편인데, 지금정도의 중첩괄호는 크게 가독성을 해치지 않는다고 생각합니다!

2023-05-31 06:47 UTC, green-kong commented on src/main/java/cart/application/OrderService.java
> +    }
3-1. 음.. 이건 자의반, 타의반 으로 구현된 코드인것 같습니다.
`cartItemDao`  같은 경우는 제공받은 기존에 작성된 코드에 포함된 부분이었습니다.
주문 작업을 하는 도중 orderDao에서 JOIN 쿼리를 사용하여 Order domain 객체를 생성하는 작업에 피로감을 느끼기도 했고,
성급한 최적화가 아닌가 하는 의문도 들어,
Repository를 계층을 두어 여러 Dao를 조합하여 domain을 생성하여 반환하는 방식으로 작성했습니다.

3-2. 이부분은 저도 작업을 진행하며 고민을 하던 부분이었는데요.. CartItem도 Repository를 두어  `findAll` method를 통해 포장된 일급 컬렉션을 반환하는 것이 더 좋은 방식이라고는 생각하고 있었습니다. 다만, 이런식으로 뼈대코드를 수정하는 경우 생겨날 사이드이펙트가 예측이 되지 않던 상황이라, 시간을 두고 천천히 수정해보려했었습니다..!

3-3. 제가 repository를 계층을 두는 기준은 `데이터 또는 해당 데이터를 통해 생성할 도메인객체가 단순하냐 단순하지 않냐` 입니다.
예를 들어 Order같은 경우는 JOIN 쿼리를 이용해 값을 가져와서 도메인 객체를 생성하기에는 도메인 객체 복잡하여, repository 계층을 두었습니다. 이러한 기준으로 Dao와 Repository를 사용하였는데, 일관성이 부족하다는 생각이 들었습니다.
현재의 상태에서 굳이 Repository가 필요하지 않은 상황에서도 일관성을 위해 Repository를 둘 필요가 있을지 궁금합니다..

2023-05-31 07:30 UTC, green-kong commented on src/main/java/cart/application/OrderService.java
> +    }
4-1 & 2. 검증을 domain객체를 생성하는 과정에서 진행해준다면, 불완전한 객체가 생성되지 않는 다는 장점이 있을 것 같습니다.
도메인 객체를 생성하고, 검증과정을 따로 호출해주다 보니, 휴먼 에러가 발생할 위험이 있다고 생각이듭니다.

4-3 & 4. 음.. 이 부분은 질문이 잘 이해가 되지 않습니다😭
```java
final Integer totalPrice = cartItems.calculatePriceSum();
final Integer finalPrice = priceCalculator.calculateFinalPrice(totalPrice, member);
```
이 부분을 도메인이 담당하게끔 처리한다는 것 자체가 와닿지가 않는것 같습니다...

2023-05-31 07:35 UTC, green-kong commented on src/main/java/cart/application/OrderService.java
> +    }
`findOrderWithMemberById` 라는 네이밍은 어떨까요??

2023-05-31 08:04 UTC, green-kong commented on src/main/java/cart/domain/Member.java
> +    }
Member 같은 경우는 CartItem내부에서 member를 비교하기 위해 재정의했었습니다.
```java
    public void checkOwner(Member member) {
        if (!Objects.equals(this.member.getId(), member.getId())) {
            throw new CartItemException.IllegalMember(this, member);
        }
    }
```
근데 지금 확인을 해보니  equals & hashcode를 재정의하고 checkOwner method를 수정하지 않았었네요.😥
아무튼... 위와 같이 값의 비교가 필요할 때만 equals & hashcode를 재정의 하는 편이라, 다른 도메인객체에는 재정의 하지 않았었습니다.

2023-05-31 08:06 UTC, green-kong commented on src/main/java/cart/domain/CartItem.java
>  public class CartItem {
아 수정을 하다가 놓친것 같습니다 감사합니다!

2023-05-31 11:49 UTC, green-kong commented on src/main/resources/application.yml
> +      mode: always
1. 의도한 부분입니다! 저번 미션에서 profile에 따른 스프링 설정 변경에 대한 부분을 제대로 학습하지 못했다고 느껴, 조금 더 공부해보고자 위와 같이 작성했습니다.
2. 앗..! application.properties는 제공된 기존 코드에 포함되어있던 파일이고, yaml 파일은 제가 이번 미션을 진행하면서 작성한 파일인데요.. yaml파일과 properties에 같은 설정이 다른 값으로 지정 된 경우 어떤 파일의 설정이 우선적용 되는지 테스트 해보다가, 해당 파일들을 하나로 합치는 걸 깜빡했네요..!

2023-05-31 12:58 UTC, jamie9504 commented on src/main/java/cart/application/OrderService.java
> +    }
@green-kong 
폴로, 4-3 & 4 추가 코멘트 달아보아요~
예를 들자면, `Order`라는 객체를 만드는거죠.
객체 생성 전에 서비스에서 `cartItems`와 `cartItemIds`의 수가 같은지는 검증을 해야겠네요.
`Order` class의 생성자로 `cartItems`, `member`를 받고 `cartItems`가 모두 `member`가 가지고 있는지 내부에서 검증을 합니다.

그 후 `order.calculatePrice` 메서드를 호출하면, FinalPrice가 나오도록 내부에서 `member`와 `cartItems`를 가지고 계산을 하여 반환을 해주는 그런 방식을 생각했었어요 😄

2023-05-31 14:20 UTC, green-kong commented on src/main/java/cart/domain/price/discount/grade/Grade.java
> +}
1.  저는 대부분의 경우 Integer, Double 등과 같은 래퍼클래스의 사용을 선호합니다.
int와 Integer는 여러부분에서 차이가 있지만, int 같은 경우 초기화 되지 않은 경우는 0으로 처리가 되고, Integer는 null로 처리가 됩니다.
그렇기 때문에 해당 데이터가 있는지 없는지를 확연하게 구분할 수 있습니다.

2023-05-31 14:44 UTC, green-kong commented on src/main/java/cart/domain/price/discount/grade/Grade.java
> +}
2.  Enum에서 요소를 조회하는 메서드 또한 정팩메의 일종일 수도 있다는 사실을 제이미 덕에 깨닫게 되었네요! 감사합니다.🙇‍♂️
일반적인 정팩메 메서드명이라고 하시면 `from`, `of`, `getInstance` 등등 을 말씀하시는 걸까요?
개인적인 의견으로는 Enum에서 요소를 조회하는 경우는 `특정 factor를 통해 일치하는 조건의 객체를 찾는다` 라는 의미가 좀더 부합한 것 같아, find로 시작하는 네이밍을 사용하는 편입니다.

2023-06-01 00:13 UTC, green-kong commented on src/main/java/cart/domain/price/discount/grade/Grade.java
> +}
3. 음.. 제이미가 말씀하신 두가지의 케이스 중 후자의 경우가 변경에 조금 더 유연하지 않을까 싶습니다.

2023-06-01 01:47 UTC, green-kong commented on src/main/java/cart/domain/price/discount/grade/Grade.java
> +}
4 - 1 . Grade를 별도의 테이블로 저장한 것은 변경에 유연하게 대처하기 위함입니다.
만약 member table에 grade를 `gold`, 'silver`, `bronze` 같은 grade의 이름을 직접 삽입하게 되면,
grade의 이름이 변경 되는 경우 member table에 전반적인 데이터 수정이 필요하지만,
table을 분리하면, grade의 table만 수정하면 되기에 변경에 유연하게 대처할 수 있다고 판단했습니다.

2023-06-01 02:33 UTC, green-kong commented on src/main/java/cart/domain/price/discount/grade/Grade.java
> +}
4 - 2 & 3. 이 부분은 저와 페어들이 가장 많이 얘기를 나누었지만, 확실하게 결론을 짓지 못한 부분입니다..
grade의 정보를 DB에 저장하는 것에는 모두가 동의 했지만, 할인에 대한 비율을 DB에 저장할지, Enum에서 관리할 지는 결론을 짓지 못했습니다.
작업을 진행하며 해당 부분에 대해 조금 더 고민을 해보았는데요.

DB에 해당 값을 저장하게 되면 등급별 할인율이 변경이 되는 경우에 서버의 코드를 변경할 필요없이 DB에 쿼리를 전송해 데이터를 수정할 수 있는 장점이 있다고 생각합니다. 서버를 한번 껐다 키는 과정이 필요하지 않게되겠죠.

반면 Enum으로 관리하게 되는 경우 변경에 취약하다는 단점이 있지만, 코드만 보고도 정보를 파악할 수 있다는 장점이 있을 것 같습니다.

할인 비율이 변경이 잦은 정보라면, DB에 저장을, 그렇지 않다면 지금처럼 Enum으로 관리하는 것이 유리할 것 같습니다.

2023-06-01 03:44 UTC, green-kong commented on src/main/java/cart/dao/OrderDao.java
> +    public Long addOrder(OrderEntity order) {
1. 별 생각 없이 손가는 대로 add를 사용했는데, 위 메서드는 `데이터를 저장` 하는 개념이니 save가 더 어울릴 듯 합니다.

2. 음.. 어떤것을 추가 또는 저장하는지에 대한 것이 메서드에 드러나면 좋을 것 같다고 생각했습니다. 그런데 다시 코드를 살펴보니 일관성이 전혀 없네요.. 하핳 전체적으로 네이밍을 다시 고민해보도록 하겠습니다!

2023-06-01 11:26 UTC, green-kong commented on src/main/java/cart/dao/CartItemDao.java
1. JOIN하는 테이블의 명을 모두 포함해서 네이밍을 변경해봤습니다!
3. id와 ids 로 통일했습니다..!
4. 앗..! 미처 확인을 못한 부분입니다.. 감사합니다!
5. 음.. 저 같은 경우는 id는 보통 pk를 의미하고 여러개의 id(ids)를 통해 조회하는 메서드 명이니 당연히 여러개의 데이터가 반환되는게 당연하다고 생각되는데.. 제이미는 해당 메서드의 네이밍만 보았을 때 어떤 값을 반환할것이라고 예측하셨나요??
6. 전반적으로 수정해보겠습니다..!

2023-06-01 12:41 UTC, green-kong commented
제이미의 리뷰를 통해 기존에는 미처 생각하지 못한 부분들을 생각하게 되며,
저만의 기준이 더욱 뚜렷하게 생긴 것 같습니다!

리뷰 내용을 반영하는 도중, 클라이언트 측에서 추가적인 기능을 요구하여 추가된 기능이 있습니다.
해당 내용 리팩토링 내용과 함께 아래에 남겨 놓겠습니다!
그리고 고민을 하다가 결정을 못한 부분이 있어 이 또한 함께 남겨 놓을게요. 
감사합니다.

### Refactoring
- [x] 할인정책 빈 자동 등록
- [x] config 파일들 패키지 이동
- [x] orderReposotiry#saveOrder, order 도메인 객체를 전달받아 데이터 저장하도록 수정
- [x] cartItems 검증 로직 내부로 이동
- [x] orderRepository.findOrderById 메서드명 수정
- [x] member.checkOwner equals로 변경
- [x] entity 객체 이름 변경
- [x] 설정파일 합치기
- [x] 전체적으로 메서드명 수정
- [x] dao deprcated method 수정
- [x] service와 매칭되는 repository 구현 

### 추가된 기능
- [x] 중복된 아이템 카트에 담는경우 예외 처리
- [x] 전체 멤버를 조회할 수 있는 api 구현

### Q1.
Order를 조회하는 경우 JOIN 쿼리를 사용함에 어려움을 느껴,
Repository를 두고 각각의 dao 에서 가져온 값을 통해 Order객체를 반환하고 있습니다.
그런데 기존의 코드들에선 repository 없이 service에서 바로 dao를 통해 값을 가져오고 있었는데요.
이 부분에 일관성이 없다고 느껴져 모든 service에서 repository를 이용해 데이터를 가져오는 방식으로 수정을 했는데요.

서비스마다 적용되는 레이어가 다르다면, 추후 다른 사람이 제 작업을 이어하거나, 협업을 하게되는 경우 혼란스럽지 않을까 싶었기 때문입니다.

그런데 이렇게 코드를 수정하고 나니, 
order repository를 제외한 대부분의 repository들이 별다른 기능 없이 그저 dao를 호출하기만 하는..
어떻게 보면 무의미한 클래스가 돼버린 듯한 느낌입니다

이런 상황에서 굳이 무의미한 repository들을 구현할 필요가 있었을 까요..?

2023-06-01 12:48 UTC, green-kong commented on src/main/java/cart/application/OrderService.java
> +    }
어떤 장점이 있을지 머릿속으로 퍼뜩 떠오르지 않아 제이미의 말대로 구현을 해보니, 
구체적 비즈니스 로직이 서비스 레이어에 드러나지 않아 더욱 객체지향스러운 코드가 된 것 같습니다.
감사합니다!🙇‍♂️

2023-06-01 12:59 UTC, jamie9504 commented on README.md
> +
// todo

2023-06-01 12:59 UTC, jamie9504 commented on README.md
> +-[x] Order의 Identity를 통해 주문 내용을 조회 할 수 있다.
// todo

2023-06-01 12:59 UTC, jamie9504 commented on README.md
> +-[x] Order의 Identity를 통해 주문 내용을 조회 할 수 있다.
// todo

2023-06-01 14:55 UTC, jamie9504 requested changes
폴로, 안녕하세요. 리뷰어 제이미입니다 😄 

코멘트를 조금 더 남겨두었어요.
질문주신 부분은 코멘트에 이미 남겨둔 부분이라 코멘트에서 이어서 얘기해보면 좋을 것 같아요!

2레벨 마지막 미션이니까, 시간 여유가 있으시면 레벨1에서 했었던 `의식적인 연습 - 객체지향 생활 체조 원칙`을 적용해보는 것도 좋은 경험이 될 것 같네요~ 😃

2023-06-01 14:55 UTC, jamie9504 commented on src/main/java/cart/application/OrderService.java
> +    }
1. 👍 
2. 👍 
3. 결국 개발은 취향과 선택의 연속이죠 😃 
> 이러한 기준으로 Dao와 Repository를 사용하였는데, 일관성이 부족하다는 생각이 들었습니다.
> 현재의 상태에서 굳이 Repository가 필요하지 않은 상황에서도 일관성을 위해 Repository를 둘 필요가 있을지 궁금합니다.

위와 같이 고민할 때는 장/단점을 분석해보고 조금 더 끌리는 걸 선택해보는 것도 좋을 것 같아요.
아래와 같은 두 상황이 있을 때의 장/단점을 비교해볼까요?
현재 시점에서의 장/단점도 좋고, 다른 누군가가 폴로의 코드를 확인했을 때 또 느껴지는 장/단점들도 좋아요, 많이 고민해보세요!

    1. 현재와 같이 복잡도를 기준으로 Dao와 Repository를 사용
    2. 일관성을 위해 모두 Repository를 사용

4. 👍

2023-06-01 14:55 UTC, jamie9504 commented on src/main/java/cart/application/OrderService.java
> +    }
`findOrderWithMemberById`이름은 뭔가 ID를 통해 Member와 함께하는 Order 객체를 추출해줄 것 같은 느낌이에요!

개인적으로는 `findOrder`, `findOrderBy`여도 파라미터에 의미가 있으니까 충분할 것 같기도 한데,
의미를 담아주고 싶다면 `findOrderByIdAndMember` With보단 And가 괜찮아보이기도 하네요.

폴로가 조금 더 고민해서 생각되는 이름으로 바꿔주세요!

2023-06-01 14:55 UTC, jamie9504 commented on src/main/java/cart/dao/CartItemDao.java
1. 👍 
2. 👍 
3. 👍 
4. 코멘트를 잘못달았네요. 메서드명을 잘못적었습니다. 😢 혼란을 드려 죄송해요. `List<CartItem> findByMemberId(Long memberId)`에 대한 이야기였습니다!
5. 👍

2023-06-01 14:55 UTC, jamie9504 commented on src/main/java/cart/dao/OrderDao.java
> +    public Long addOrder(OrderEntity order) {
`OrderService`에서도 `add`를 쓰고 있어서, 전반적으로 한 번 고민해보면 좋을 것 같아요 😄 👍

2023-06-01 14:55 UTC, jamie9504 commented on src/main/java/cart/domain/Member.java
> +    }
ID가 식별자일 때, 당장 사용하지 않는다고 equals & hashcode를 재정의하지 않는다면

1. 그 객체는 ID가 식별자라고 할 수 있을까요?
2. 다른 개발자가 해당 객체를 HashMap을 이용하거나 하여 값을 비교하는 부분을 추가하려 할 때, equals & hashcode를 재정의해야함을 바로 알아볼 수 있을까요?

2023-06-01 14:55 UTC, jamie9504 commented on src/main/java/cart/domain/price/discount/grade/Grade.java
> +}
1. `private final Integer gradeValue;`

> int와 Integer는 여러부분에서 차이가 있지만, int 같은 경우 초기화 되지 않은 경우는 0으로 처리가 되고, Integer는 null로 처리가 됩니다.
> 그렇기 때문에 해당 데이터가 있는지 없는지를 확연하게 구분할 수 있습니다.

위의 멤버변수에 `null`이 들어갈 수 있는 상황이 있을까요?
해당 멤버변수로 `Integer`를 썼을 때의 장점이 무엇인가요?

2. 저는 `find-`는 데이터 저장소에서 무언가를 조회할 때 사용하곤 해서 그런지 조금 어색하게 느껴지긴 했던 것 같습니다. 데이터 저장소가 아니더라도 Collection이나 값들이 있는 곳에서 무언가를 찾아오는 느낌인데, Enum의 해당 메서드는 정적 팩터리 메서드로 보여서 일치하는 필드를 가진 Enum 상수를 반환했다고 생각했거든요!
이건 어느정도 취향 차이일 수 있으니 참고만 해주세요 😄 
> Enum에서 요소를 조회하는 경우는 특정 factor를 통해 일치하는 조건의 객체를 찾는다 라는 의미가 좀더 부합한 것 같아, find로 시작하는 네이밍을 사용하는 편입니다.

3. 예를 들어 `GOLD(1, 0.05, "GOLD"),`와 같이 선언해둔다면 `getName()`을 통해 값을 받아오기 때문에, Enum 상수명을 누군가 수정했을 때 문제가 발생하지 않죠!
`GOLD(1, 0.05)`만 보았을 때, 해당 Enum의 `name()`을 누가 사용하고 있을지 예측을 할 수 있다면 문제가 되지 않지만, 무심코 변경을 하게 된다면 어떻게 될까요? 이 부분에 대한 폴로의 의견이 궁금하네요~!

> 후자의 경우가 변경에 조금 더 유연하지 않을까 싶습니다.
> 그런데 동일한 값을 가진 멤버변수를 선언해서 이용하는 것은 그렇게 유의미한 차이가 생기지는 않을것 같습니다.

4. 👍 어떤게 항상 좋은 설계다!는 없죠. 상황에 따라 필요에 따라 선택하는 것이 중요합니다. 👏 👏 👏

2023-06-01 14:55 UTC, jamie9504 commented on src/main/resources/application.yml
> +      mode: always
1. test에 대한 설정을 product의 `application.yml`에 넣지 않고도 default와 prod 즉, 각각의 profile이 있는 것 같은데요!
test에 대한 설정도 넣은 함께 넣은 이유가 있을까요?
2. 👍

2023-06-01 14:55 UTC, jamie9504 commented on src/main/java/cart/application/CartItemService.java
> +        cartItems.validateContainDuplicatedProduct(cartItemRequest.getProductId());
현재 방식은 `Member`를 통해 `CartItems`를 추출한 후, `CartItems`에게 `ProductId`를 가지고 있는지 물어보고 있는데요.

`cartItemRepository`에 지금 `member`가 해당 `productId`의 상품을 가지고 있는지 물어보는 방식,
즉 쿼리로 바로 질의하는 방식도 있을 것 같네요.
> Mysql의 count 기능을 이용하거나 해서 boolean을 반환하게끔 

1. 두 방식의 장/단점은 무엇이 있을까요?
2. 폴로가 첫 번째 방식을 선택한 이유는 무엇인가요?

2023-06-01 14:55 UTC, jamie9504 commented on src/main/java/cart/application/OrderService.java
> +            throw new CartItemException("존재하지 않는 cartItemId가 포함되어 있습니다.");
`CartItemException`이라는 예외는 현재 상황에서만 사용되고 있는데 조금 더 적절한 클래스명이 있을지 고민해볼까요?

2023-06-01 14:55 UTC, jamie9504 commented on src/main/java/cart/domain/Order.java
> +        final int finalPrice = priceCalculator.calculateFinalPrice(totalPrice, member);
finalPrice를 `PriceCalculator`를 이용해서 계산을 하고 있는데요.

1. 현재는 `PricePolicy`와 `PriceCalculator`를 이용해서 계산을 하고 있는데 각각 구현체가 한 개씩인 인터페이스네요!
인터페이스를 사용한 이유는 무엇인가요? 

2. Bean으로 등록된 Component들인 `PricePolicy`와 `PriceCalculator`를 Component로 만든 이유는 무엇인가요? Domain 객체가 아닌 Component로 등록한 이유도 궁금하네요!
예를 들자면 이번에 만든 `order`에서 이런 책임을 가져갈 수도 있는 게 아닌가요?!

2023-06-02 02:34 UTC, green-kong commented on src/main/java/cart/application/OrderService.java
> +    }
1. 장점은 관리해야 되는 클래스들을 관리하는 리소스가 적게 듭니다.
단점으로는 협업의 관점에서 사람마다 느끼는 복잡도가 달라서, 기존의 코드들이 어떤 기준으로 나눠져 있는 것 인지 파악이 힘들 것 같습니다. 또한, 무언가 기능이 확장되어 복잡도가 높아지는 상황이 생긴다면, 해당 시점에서 repository 클래스를 구현해야 할건데요. 확장에 유연하지 않은 구조인 듯 싶습니다.

2. 장점으로는 추상화 계층에 일관성이 생겨, 다른 개발자가 개발에 투입되는 overhead가 줄어 들 것 같습니다.
단점으로는 DB에 여러번 접근 하게 되어 성능적으로는 불리하지 않을까 싶습니다.

제이미의 말대로 두가지 케이스의 장단점을 비교해보았을 때 `2. 일관성을 위해 모두 Repository를 사용` 하는 방식이 더 끌리는 것 같습니다. row와 트래픽이 엄청 많은 경우가 아니라면 성능상으로 유의미한 차이가 있을 것 같지 않네요.ㅎㅎㅎ

2023-06-02 04:36 UTC, green-kong commented on src/main/java/cart/domain/Member.java
> +    }
1. 식별자가 아니겠죠..? 하지만 식별자를 쓸일이 없으니까 재정의를 하지 않아도 된다고 생각했었습니다.

2. 이거에 대해 다른 크루들과 얘기를 나눠보며, 사람 성격이 정말 제각각이구나..라는걸 느꼈습니다. 저는 성격상 제이미가 말씀하신 부분을 제가 하게 된다면 equals & hashcode 가 재정의 되어있는지 우선 확인을 해보는 편이라 제이미의 질문이 처음에는 와닿지 않았었는데요. 그렇지 않은 크루들이 상당히 많더라구요..! 어떤 것이 좋다 나쁘다라는 얘기가 아니라 여러 케이스들을 고려하는 자세가 필요하겠구나 라는걸 느꼈습니다!

2023-06-02 05:50 UTC, green-kong commented on src/main/java/cart/domain/price/discount/grade/Grade.java
> +}
1. 현재의 비즈니스에선 `null`이 들어가는 경우는 없을 것 같습니다.
2. 장점을 천천히 생각해보니, `null` 할당을 가능하게 하는 것이 오히려 단점으로 느껴지네요..!
`null`이 들어오는 경우가 없는데, null을 허용하게 해줌으로써 다른 개발자가 제 코드를 볼 때 `null`을 통해 `다른 처리를 해주는 것인가` 에 대한 고민사항만 늘어날 것 같습니다..!
int 와 Integer의 사용에 있어 큰 고민을 해본 적이 없었는데, 이번 기회를 통해 고민해볼 수 있었습니다! 감사합니다🙇‍♂️

2023-06-02 08:01 UTC, green-kong commented on src/main/java/cart/domain/price/discount/grade/Grade.java
> +}
3. Enum 상수명이 변경되는 경우 코드의 변경점이 많을 것 같습니다. 결국 유지보수가 힘들어진다는 단점이 극명하게 드러날것 같습니다. 저도 이 부분은 공감하는데요.
`GOLD(1, 0.05, "gold")` 와 같이 `동일한 값을 가진 멤버변수를 선언해서 이용하는 경우`  gold를 platinum 으로 변경하게 되는 경우
`PLATINUM(1, 0.05, "platinum")` 와 같이 ENUM 상수명도 함께 변경하게 될 것 같았습니다.

등급의 이름은 변경이되도 비즈니스적(사용자의 반응 등등) 으로 크게 문제가 될것 같진 않지만,
할인율이 변경되는 것은 비즈니스적으로 사이드 이펙트가 많을 것 같아, 할인율의 변경이 등급의 이름에 변경보다 잦지 않을 것이라 생각하고,
`할인율에 따라 Enum 상수명을 정의하는 것은 어떨까` 라는 생각을 해봤었습니다.
`FIVE_PERCENT_DISCOUNT_GRADE(1, 0.05, "gold")` 요런 식으로요. ㅎㅎ
이러한 방식으로 하면 변경이 잦은 등급의 이름의 변경에 유연하게 대처할 수 있지 않을까 생각했습니다

2023-06-02 08:06 UTC, green-kong commented on src/main/java/cart/dao/CartItemDao.java
4. 아하! 확실히 그런 느낌이 있네요..! 적절한 네이밍으로 수정해보겠습니다!

2023-06-03 06:38 UTC, green-kong commented on src/main/java/cart/application/OrderService.java
> +            throw new CartItemException("존재하지 않는 cartItemId가 포함되어 있습니다.");
고민해보고 수정하겠습니다..!

2023-06-05 05:04 UTC, green-kong commented on src/main/java/cart/application/CartItemService.java
> +        cartItems.validateContainDuplicatedProduct(cartItemRequest.getProductId());
1. 현재 방식의 장점은 조금 더 객체지향 적인 방식의 코드가 아닌가 싶습니다. 하지만 데이터가 많다면, 많은 row를 가져오는 작업 자체가 그렇게 바람직하다고 느껴지지는 않습니다. 
반대로 쿼리를 통해 `member가 해당 productId의 상품을 가지고 있는지 물어보는 방식` 같은 경우 비즈니스 로직이 변경 되는 경우 쿼리 또한 변경이 있을 것 같아. 변경에 취약 할 듯 합니다. 하지만 row가 많을 경우 효율적으로 처리가 될 것 같긴합니다.
다만, 현재의 상황 처럼 row가 많지 않을 경우에도 과연 효율적인 방식인가에 대한 의문은 조금 있습니다.

2. 사실 제이미가 말씀하신 `쿼리를 통해 member가 해당 productId의 상품을 가지고 있는지 물어보는 방식` 은 생각해보지도 않았던 방식이었는데요..ㅎ. 어떤게 더 좋은지는 사실 기준이 잘 서지는 않네요 ㅠㅠㅠ

2023-06-05 05:32 UTC, green-kong commented on src/main/resources/application.yml
> +      mode: always
1. default는 로컬 환경에서 주로 사용을 했고, prod는 말그대로 실제 product 환경에 대한 설정을 한 프로파일입니다. 
test 프로파일 같은 경우는 이전에 배포 경험에서 로컬에서는 잘 돌아가는데 product 환경에서는 잘 돌아가지 않은 경우가 종종 있었는데요.
그 뒤로는 항상 product환경과 똑같은 test EC2를 하나 더 생성해서 사용했었습니다. 물론 지금은 test EC2가 존재하지는 않아서 필요하진 않을것 같지만, 있다는 가정하에 만들어 봤습니다 ㅎㅎ

2023-06-05 05:50 UTC, green-kong commented on src/main/java/cart/domain/Order.java
> +        final int finalPrice = priceCalculator.calculateFinalPrice(totalPrice, member);
1. 이번 미션에서 구현한 쇼핑몰같은 경우 가격정책 같은 경우는 변경이 잦은 부분일거라 생각하여 interface를 만들어두었습니다. 예를들어 연말이벤트 등 한시적인 기간동안만 다른 가격정책을 사용하고 그 기간이 지나면, 다시 원래의 가격정책을 사용하는 경우가 빈번할 것이라 생각하여, interface를 두어 변경에 유연하게 대처할 수 있게끔 설계했습니다.

2. 관리의 용이성때문에 빈으로 등록하여 사용하였습니다.
이번 미션을 진행하며 클라이언트 측과 얘기를 나눈 부분 중 가장 재밌었던 부분이 `가격을 계산하는 로직을 클라이언트와 서버 둘 중 어디서 관리` 하느냐 였습니다.
간단한 토의를 통해 로직을 백엔드 측에서 관리하기로 하였고, 클라이언트 쪽에서 사용자에게 어떠한 할인을 통해  얼마가 할인되었는지 보여주는 부분역시 서버 api를 통해 응답을 받아 사용하기로 하였습니다.`(GET /discount)` 
`pricePolicy` 같은 경우는 주문을 저장 하는 과정과`(POST /order)`, 할인정보를 조회하는 과정`(/discount)` 두가지에 사용되는데요. 1번에서 대답하였든 가격정책은 변경이 잦을 것으로 예상하였습니다.
이 부분을 빈으로 등록하지 않고 직접 객체를 생성해서 사용하는 경우 휴먼에러가 발생할 확률이 높다고 생각했습니다..! 빈으로 등록하여 사용하면, 하나의 파일만 관리할 수 있기에 빈으로 등록하여 사용했습니다!

2023-06-05 17:17 UTC, jamie9504 requested changes
폴로, 안녕하세요. 리뷰어 제이미입니다. 😄 

코멘트 조금 더 남겨두었습니다.

요구사항은 다 구현하였기 때문에, 반영하고 싶으시다면 반영해주시면 됩니다.
다음 리뷰 요청은 바로 Approve & Merge 예정이니 참고해주세요.

2023-06-05 17:17 UTC, jamie9504 commented on src/main/java/cart/application/OrderService.java
> +    }
👍 

추가적으로 남겨두자면, 위에서 이야기했던 변수 추출부분의 장점이 하나 더 기억이 났는데요!
디버깅을 할 때 한 라인씩 내려오면서 보기가 좋습니다 😃 
무의식적으로 이렇게 쓰고 있었어서 리뷰할 때 떠오르지 않았었네요! 참고만 해주세요!

``` java
List<CartItem> 변수추출 = cartItemDao.findByIds(cartItemIds);
final CartItems cartItems = new CartItems(변수추출);
```

> 이 부분은 저의 명확한 기준 이라기보다는 제가 보기에 편한 정도를 척도로 삼고있습니다.
예를 들어, 중첩괄호 depth가 2가 넘어간다거나, 메서드에서 인자를 2개이상 받는 경우는 제이미가 얘기해주신 대로 변수로 사용하는 편인데, 지금정도의 중첩괄호는 크게 가독성을 해치지 않는다고 생각합니다!

2023-06-05 17:17 UTC, jamie9504 commented on src/main/java/cart/domain/Member.java
> +    }
1. 식별자는 사용하지 않아도 식별자여야 합니다! (즉 Equals & HashCode 재정의) 말씀주신대로 이런 경우는 식별자가 아니겠죠?
2. 👍 다들 기본적으로 이렇게 사용하겠지-가 알고보면 조금씩 다르곤 하죠 😄 

    Domain을 설계했을 때, 적절한 Equals & HashCode를 정의하지 않았다는 건 말그대로 `해당 ID 필드는 식별자가 아닌 도메인`이다. 라는 의미를 내포하고 있어요!

    나중에 ID를 식별자로 사용을 해야 한다고 했을 때, 기존 코드에서 해당 도메인을 Equals 비교 혹은 HashCode를 사용한 부분이 있는지 확인을 해보고, 있다면 전반적으로 많은 수정이 필요할 수 있겠죠?

    위와 같은 이유로 사용 여부와 관계없이 처음 설계해서 도메인을 생성할 때, 식별자 여부는 명확히 잡고 가는 것이 혼동을 주지 않는 방식이라고 생각했는데 이 부분에 대해 폴로의 의견이 궁금하네요 😃

2023-06-05 17:17 UTC, jamie9504 commented on src/main/java/cart/domain/price/discount/grade/Grade.java
> +}
예를 들자면 `GOLD(1, 0.05, "GOLD")`를 `GOLD_GRADE(1, 0.05, "GOLD")` 이렇게 변경할 수도 있는데요.
Enum 상수의 경우 static import시 상수명만 노출되기 때문에 이름을 어떻게 지을지에 대해 취향 차이가 있을 수 있어요.
Enum 상수명은 말그대로 클래스명처럼 개발자들이 구별하기 위해 만들어주는 이름이니까요. 이에 의존적이지 않은게 좋지 않을까?란 생각이었습니다.

`FIVE_PERCENT_DISCOUNT_GRADE(1, 0.05, "gold")`라고한다면, 이 역시 가능하고, 할인율이 이름에 비해 덜 바뀐다면 이 방식이 더 좋을 수도 있겠죠!
하지만, 마찬가지로 할인율도 위와 같이 변경이 될 수 있긴 하니까요! 😃 `ex) DISCOUNT_FIVE_PERCENT_GRADE`

폴로는 이 부분에 대해서 어떤 의견을 갖고 있나요?

2023-06-05 17:17 UTC, jamie9504 commented on src/main/resources/application.yml
> +      mode: always
test에 대한 설정을 test/resources 하위에 구현하는 방법도 있어서 위의 부분 코멘트 남겨놨었어요!

product에 test code가 넘어오지 않는 것을 지향한다면 properties도 마찬가지가 아닐까 싶어서요 😃

2023-06-05 17:17 UTC, jamie9504 commented on src/main/java/cart/application/CartItemService.java
> +        cartItems.validateContainDuplicatedProduct(cartItemRequest.getProductId());
1. 👍 row수가 적더라도 효율적이긴 하겠지만, 그 정도가 미미할 순 있겠죠?
2. 이 부분도 역시 트레이드오프의 영역이라서 현재 상황과 예측해볼 수 있는 상황을 고려해서 어떤 방식을 선택할지는 폴로의 자유입니다 😃

2023-06-05 17:17 UTC, jamie9504 commented on src/main/java/cart/repository/OrderRepository.java
> +                .orElseThrow(() -> new InvalidOrderException("OrderId is not existed; orderId = " + orderId));
1. findOrder를 했을 때, 해당하는 부분이 없다면 dao처럼 Optional로 반환하는 방식과 현재 코드처럼 elseThrow하는 방식으로 각각 구현이 가능할 것 같은데요.

    1. 현재 메서드에서 Optional을 반환
    2. 현재 메서드에서 현재와 같이 Exception을 Throw

    위 두 방식은 각각 어떤 장/단점이 있을지 고민해볼까요?

2. createTable은 뭔가 Table을 만들어줄 것 같은 메서드명인데, 이렇게 명명해준 이유가 있을까요?
사실상 Map을 만들어주는 로직이긴 해서요 😃

2023-06-05 17:17 UTC, jamie9504 commented on src/main/java/cart/ui/ControllerExceptionHandler.java
> +    }
내부 구현이 같은 네 메서드는 하나의 메서드로 묶어줄 수 있지 않을까요?
따로 분리해서 구현한 이유가 있을까요?

2023-06-05 17:17 UTC, jamie9504 commented on src/main/java/cart/application/MemberService.java
> +    }
사용자의 정보를 전부 노출할 수 있는 API인데요!
이 부분은 어떤 경우 필요했을까요? Password까지 모두 필요한 부분이었을까요?

2023-06-05 17:17 UTC, jamie9504 commented on src/main/java/cart/application/OrderService.java
> +        Order order = Order.from(cartItems, member, priceCalculator);
1. 정적 팩터리 메서드로 order를 생성해주고 있는 부분인데요.
정적 팩터리 메서드 네이밍 관련해서 찾아본다면, 현재 상황에서 `from`이라는 이름이 적절할지 고민해볼 수 있을 것 같아요!

2. 아래의 `findOrderByIdAndMember`, `findByMember`는 메서드명에 일관성이 조금 부족한 것 같네요 😃

2023-06-05 17:17 UTC, jamie9504 commented on src/main/java/cart/dto/MemberResponse.java
> +        final String grade = Grade.findGradeByGradeValue(member.getGrade()).name();
`.name()`을 여전히 사용해주고 있네요! 😄 

테스트코드에서 다음과 같이 응답이 확인되는데요.
이 부분이 폴로가 의도한 grade의 이름이 맞을까요? 만약 아니라면, 왜 이 부분이 테스트코드에서 캐치되지 않았을지 고민해볼까요?
``` java
[
    {
        "id": 1,
        "email": "a@a.com",
        "password": "1234",
        "grade": "FIVE_PERCENT_DISCOUNT_GRADE"
    },
    {
        "id": 2,
        "email": "b@b.com",
        "password": "1234",
        "grade": "THREE_PERCENT_DISCOUNT_GRADE"
    },
    {
        "id": 3,
        "email": "c@c.com",
        "password": "1234",
        "grade": "ONE_PERCENT_DISOCUNT_GRADE"
    }
]
```

2023-06-06 12:35 UTC, green-kong commented on src/main/java/cart/application/OrderService.java
> +        Order order = Order.from(cartItems, member, priceCalculator);
1. 하핳.. 정팩메 네이밍 항상 헷갈리네요.... 인자가 여러개라 `of`가 좀더 어울리겠네요ㅎㅎ

2023-06-06 12:46 UTC, green-kong commented on src/main/java/cart/application/MemberService.java
> +    }
아 이게 클라이언트 측에서 요구한 api 인데요.
이번 미션에서 회원가입이나, 로그인 기능을 구현 하지 않고 사용자 별 장바구니 기능과, 주문 기능을 사용하기 위해
클라이언트 측에서 전체 사용자 정보를 api를 통해 전달받아, 화면에서 사용자를 선택한 뒤 위의 기능들을 실행한다고 합니다.
실제 서비스에서는 전혀 필요하지 않은 부분입니다.

2023-06-06 12:54 UTC, green-kong commented on src/main/java/cart/domain/Member.java
> +    }
2. 원래는 사용하지 않는 equals & hashcode를 재정의 할 필요가 없다고 생각했었는데,
제이미와 얘기를 나눠보며, 생각이 바뀌었습니다..! equals & hascode를 재정의 함으로 이 값이 식별자라는 것을 다른 개발자에게 알릴 수도 있고, 다른 개발자의 혼동도 줄일 수 있어 앞으로는 식별자를 통한 equals & hashcode 재정의를 해야겠다는 생각이 드네요!
새로운 관점을 알려주셔서 감사합니다!🙇‍♂️

2023-06-06 14:10 UTC, green-kong commented on src/main/java/cart/domain/price/discount/grade/Grade.java
> +}
`Enum 상수명은 말그대로 클래스명처럼 개발자들이 구별하기 위해 만들어주는 이름` 이라는 말이 와닿네요!
이 부분도 크루들과 얘기를 나눠보니 이러한 이유로 `name()` 를 잘 사용하지 않는다고 하더라구요.

2023-06-06 16:16 UTC, green-kong commented on src/main/java/cart/repository/OrderRepository.java
> +                .orElseThrow(() -> new InvalidOrderException("OrderId is not existed; orderId = " + orderId));
```java
public Optional<Order> findOrderByIdAndMember(Long orderId, Member member) {
    Optional<OrderEntity> orderEntityOptional = orderDao.findById(orderId);
    if (orderEntityOptional.isPresent()) {
        OrderEntity orderEntity = orderEntityOptional.get();
        List<OrderedItemEntity> orderedItems = orderedItemDao.findAllByOrderId(orderId);
        final CartItems cartItems = orderedItemsToCartItems(member, orderedItems);
        return Optional.of(new Order(orderEntity.getId(), orderEntity.getPrice(), member, cartItems));
    } else {
        return Optional.empty();
    }
}
```
1-1 은 이런 코드를 말씀하신 거겠죠?
예를 들어 OrderId를 통해 Order를 조회했을 때 데이터가 없다면, Order를 생성 한다던가.. 의 비즈니스라면 1-1 의 방법을 쓸 것 같지만, 현재의 비즈니스에선 service에서 orderId를 통해 조회된 데이터의 결과에 따라 분기처리를 해줄 필요가 없다고 판단하여, 지금의 코드처럼 repository에서 예외를 발생시켰습니다.

그런데 제이미의 얘기를 듣고 조금 더 고민을 해보니, OrderService의 코드만 보아서는 `Order 없을 수도 있다` 라는 사실을 모를 수도 있겠다. 라는 생각도 듭니다. 

또한 `계층형 아키텍처`의 관점에서 생각해보면, repository는 business Layer 보다는 persistence Layer 와 더 가깝다고 생각하고 있었는데요. `ID를 통한 데이터 조회가 실패하면 예외가 발생한다`는 business Layer에 있는 게 시스템 분석이나, 계층간 구조에 따른 재사용성이 높아질 것 같네요!

좋은 인사이트를 얻은 것 같습니다. 감사합니다!🙇‍♂️

2023-06-06 16:17 UTC, green-kong commented on src/main/java/cart/repository/OrderRepository.java
> +                .orElseThrow(() -> new InvalidOrderException("OrderId is not existed; orderId = " + orderId));
2. 앗.. ID 와 해당객체의 MappingTable을 만들어 준다는 의미로 사용했는데... 의미가 모호한 듯 하네요. 고민해보고 수정해보겠습니다!

2023-06-06 16:23 UTC, green-kong commented on src/main/java/cart/dto/MemberResponse.java
> +        final String grade = Grade.findGradeByGradeValue(member.getGrade()).name();
아.. Grade Enum의 static method에서는 name() 의 사용을 변경했는데, DTO로 변환하는 과정에서는 이부분을 변경해주지 않았었네요... 전혀 의도치 않은 오류네요😭😭

제이미의 말대로 테스트 코드를 허술하게 작성해서 이런 실수가 생긴 것 같습니다..ㅠ
너무.. 부끄럽네요😥

2023-06-06 16:26 UTC, green-kong commented on src/main/java/cart/ui/ControllerExceptionHandler.java
> +    }
음.. 저도 고민을 했었는데, `뭔가 예외마다 다른 처리가 들어갈 수도 있지 않을까..?` 란 생각에 이대로 내비뒀었는데요.
사실 머릿속에 딱히 떠오르는 케이스도 없고, 현재 비즈니스에서 필요하지 않은 부분이니 하나로 합치는게 나으려나요..?ㅎㅎ

2023-06-06 17:23 UTC, green-kong commented
안녕하세요 제이미!
이번 미션의 마지막 리뷰요청이 될 듯 하네요.ㅎㅎ
제이미 덕분에 인사이트도 많이 얻을 수 있었고, 적지않은 성장도 이뤄낸 것 같습니다!👍
부족한 제 코드 봐주시느라 수고 많으셨어요..!🤣
정말 감사합니다!!🙇‍♂️

2023-06-07 01:47 UTC, jamie9504 approved these changes
폴로, 안녕하세요. 리뷰어 제이미입니다 😄 

2레벨 마지막 미션인 장바구니 협업 미션 고생하셨습니다.
이번 미션을 통해 성장하셨다고 느끼셨다니 저도 기쁘네요. 😃 

방학이 얼마 남지 않았는데, 즐거운 방학 보내시구요.
3레벨 팀프로젝트도, 그 이후 4레벨 5레벨도 즐거운 여정이 되시길 바랍니다. 🎵 

코멘트는 나중에 시간되실 때 확인해보시면 좋을 것 같아요.
이만 Approve & Merge합니다.

2023-06-07 01:47 UTC, jamie9504 commented on src/main/java/cart/ui/ControllerExceptionHandler.java
> +    }
이 부분도 현재처럼 예외마다 나눠두어 추후 수정을 용이하게 두는 것과,
같은 처리일 때는 하나의 메서드로 통합하여 불필요한 코드를 줄이는 것 중 폴로의 취향으로 가시면 됩니다 😃

2023-06-07 01:47 UTC, jamie9504 commented on src/main/java/cart/application/CartItemService.java
> +        cartItems.validateContainDuplicatedProduct(cartItemRequest.getProductId());
1. `productId`를 넘겼을 때, Validate를 `cartItems` 내부에서 진행을 해주고 있는데요.

    다음 두 경우는 어떤 차이가 있을지 고민해보는 것도 좋을 것 같아요!
    1. 현재와 같이 validate를 `cartItems` 내부에서 진행 (즉 도메인에서 예외 발생)
    2. `cartItems`에서는 boolean을 반환하고 (ex. `containsProductId()`) 예외는 service에서 발생

2. `final`은 어떤 경우에 선언하고 있을까요?
    `remove()`에서는 변수에 따로 선언되어있지 않아서요 😃 

3. `add`는 뭔가 기존 리스트에 새로운 무언가를 추가하는 느낌도 드네요 (ex. Collection). `create`나 다른 메서드명도 고민해봐도 좋을 것 같아요!

2023-06-07 01:47 UTC, jamie9504 commented on src/main/java/cart/application/OrderService.java
> +    private final OrderRepository orderRepository;
service에서 dao와 repository를 각각 사용하고 있는데, 이 부분은 의도된 부분일까요?

2023-06-07 01:47 UTC, jamie9504 commented on src/main/java/cart/domain/CartItems.java
> +    }
보편적인 메서드 선언 순서는 getter가 조금 아래에 위치할 것 같네요 😄 
별 건 아니지만 지켜준다면, 가독성을 조금 향상시킬 수 있습니다 👍

2023-06-07 01:47 UTC, jamie9504 commented on src/main/java/cart/domain/Member.java
> +    private final int grade;
1. `Member`의 `grade`는 int를 사용하고 있는데요. 기본 타입을 사용한 이유가 있을까요?
2. `grade`의 getter에서는 Integer를 반환해주고 있네요!

2023-06-07 01:47 UTC, jamie9504 commented on src/main/java/cart/domain/price/discount/grade/BasicGradeDiscountPolicy.java
> +        return grade.calculate(price);
Member에서 Grade를 int or integer 타입으로 갖고 있는 것이 아니라, Grade 타입를 들고 있는 방식은 지금의 방식과 어떤 차이가 있을까요?

2023-06-07 01:47 UTC, jamie9504 commented on src/main/java/cart/domain/price/discount/price/BasicPriceDiscountPolicy.java
> +    private static final double MAXIMUM_DISCOUNT_RATE = 0.1;
용어는 `MAX`와 `MAXIMUM` 중 하나로 통일하면 좋겠죠?

2023-06-07 01:47 UTC, jamie9504 commented on src/main/java/cart/repository/CartItemRepository.java
> +    }
quantity를 update할 때, `cartItem`을 받고 있는데요. `cartItem`을 받는 것과, 식별자와 `quantity`를 받는 것은 어떤 차이가 있을지 고민해볼까요?

2023-06-07 01:47 UTC, jamie9504 commented on src/main/java/cart/repository/OrderRepository.java
> +    private CartItems orderedItemsToCartItems(Member member, List<OrderedItemEntity> orderedItems) {
메서드명으로 조금 더 적합한 이름이 있을 것 같아요!

2023-06-07 01:47 UTC, jamie9504 commented on src/main/java/cart/ui/CartItemApiController.java
> +    public ResponseEntity<Void> updateCartItemQuantity(Member member, @PathVariable Long id,
ArgumentResolver에서 `Member`를 넣어주고 있는데, 로그인된 사용자의 인증정보 중 서비스에서 실제 사용하는 필드는 어떤 필드가 있을까요?
`password` 같은 필드들은 서비스에서 사용하지 않을 것 같은데, 그 부분까지 함께 넘겨주는 방식 (Domain을 통째로 넘겨주는 방식)이 좋을지, 필요한 정보만 DTO로 담아서 넘겨주는 것이 좋을지 고민해보세요!

2023-06-07 01:47 UTC, merged