[2단계 - 주문 기능 구현] 우가(윤정욱) 미션 제출합니다.
woowacourse/jwp-shopping-order pull request #11
Opened 2023-05-31 03:08 UTC by wugawuga

안녕하세요 바다 😆 우가입니다!!!

저의 첫 리뷰어이자 마지막리뷰어가 되어주셔서 감사합니다!!!

페어끼리 의논해서 이전 코드를 불러와서 api 명세에 맞게 수정 후 구현을 해보았습니다.
커밋
리뷰 잘 부탁드리겠습니다!!!!ㅎㅎㅎㅎ 🙇‍♂️

2023-06-01 15:07 UTC, xrabcde requested changes
안녕하세요 우가 ~ 바다입니다 🌊
다시 만나게 되어 반가워요 ㅎㅎ 
못본사이 엄청난 고수가 되셨군요 +_+

몇 가지 코멘트 남겼으니 확인해보시고
궁금한 점은 언제든 코멘트나 DM으로 알려주세요 ~

2023-06-01 15:07 UTC, xrabcde commented on src/main/java/cart/config/OpenApiConfiguration.java
> +        @Server(url = "http://localhost:8080", description = "로컬"),
Swagger 를 사용해주셨군요 👏👏
이번에 리드미는 따로 안적어주신건가요?

2023-06-01 15:07 UTC, xrabcde commented on src/main/java/cart/controller/MemberCouponController.java
> +public class MemberCouponController {
`CouponController` 와 `MemberCouponController` 를 분리해주신 이유는 무엇인가요? 
사용자 쿠폰 로직이 `/coupons` 하위에 들어갈수도 있지 않을까요?

2023-06-01 15:07 UTC, xrabcde commented on src/main/java/cart/dao/CartItemDao.java
> +    public int deleteById(final Long cartItemId, final Long memberId) {
이 경우 id 가 이미 PK이기 때문에 `cartItemId` 만 받아 삭제시켜도 될 것 같은데 `memberId` 까지 받는 이유가 있나요? 
혹시 리뷰범위가 아니었다면 알려주세요 !

2023-06-01 15:07 UTC, xrabcde commented on src/main/java/cart/dao/CouponDao.java
> +public class CouponDao {
Dao에 `@Repository` 와 `@Component` 를 혼용해서 사용하셨는데
어떤 기준으로 선택하신 건가요? 두 어노테이션은 어떤 차이가 있을까요?

2023-06-01 15:07 UTC, xrabcde commented on src/main/java/cart/dao/MemberCouponDao.java
> +        jdbcTemplate.update(sql, memberId, id);
이 경우도 PK 가 고유하기 때문에 id 만 가지고 쿠폰 사용처리가 가능할 것 같아요

2023-06-01 15:07 UTC, xrabcde commented on src/main/java/cart/domain/Order.java
> +                 final List<OrderItem> orderItems) {
생성자 체이닝 👍🏻

2023-06-01 15:07 UTC, xrabcde commented on src/main/java/cart/domain/coupon/policy/DiscountPolicyType.java
> +    NONE((value) -> new NonDiscountPolicy());
우가.... 못본사이 enum 고수가 되어버리셨군요 ?!

2023-06-01 15:07 UTC, xrabcde commented on src/main/java/cart/dto/CouponSaveRequest.java
> +    private final String discountPolicyType;
꼼꼼한 validation과 메시지 정의 💯💯

2023-06-01 15:07 UTC, xrabcde commented on src/main/java/cart/controller/CouponController.java
> +    public ResponseEntity<Void> save(@RequestBody final CouponSaveRequest request) {
request 에 꼼꼼하게 작성해주신 valid 가 동작하지 않는 것 같아요?! 🧐

2023-06-01 15:07 UTC, xrabcde commented on src/main/java/cart/dto/OrderSaveRequest.java
> +
여기뿐 아니라 모든 Request에 걸어준 valid를 동작하게 하려면 controller 에 valid 설정을 해주는 게 좋은데요
ProductController의 80번 라인을 참고하시고 [이 글](https://tecoble.techcourse.co.kr/post/2020-09-20-validation-in-spring-boot/)도 읽어보세요 ~

2023-06-01 15:07 UTC, xrabcde commented on src/main/java/cart/repository/OrderRepository.java
> +    }
- 함수(또는 메서드)의 길이가 10라인을 넘어가지 않도록 구현한다.

정적 팩토리 메서드를 활용해볼 수 있을 것 같아요 ~

2023-06-01 15:07 UTC, xrabcde commented on src/main/java/cart/service/MemberCouponService.java
> +    public List<MemberCouponDto> findByMemberId(final Long memberId) {
Transactional을 다양하게 사용해주셨네요 ㅎㅎ
클래스단과 메서드단에 정의해주는 것은 각각 어떻게 다를까요?
Transactional 의 readOnly 옵션은 어떻게 동작하고 어떨 때 설정하나요?

2023-06-01 15:07 UTC, xrabcde commented on src/main/java/cart/service/OrderService.java
> +    public List<OrdersDto> findAllBy(final Long memberId) {
```suggestion
    public List<OrdersDto> findAllByMemberId(final Long memberId) {
```
를 의도하신걸까요 ? ㅋㅋ

2023-06-01 15:07 UTC, xrabcde commented on src/main/resources/data.sql
> +values ('피자스쿨 치즈피자', 'https://t1.daumcdn.net/cfile/tistory/2647BE3754B7E8B733', 8900, 1, 1);
훌륭한 샘플이미지네요 ㅎㅎ

<img src="https://github.com/woowacourse/jwp-shopping-order/assets/56033755/ebf60316-80d3-4330-ba1a-4197fc8d516f" width="400">

2023-06-01 15:07 UTC, xrabcde commented on src/test/java/cart/controller/CouponControllerTest.java
> +                .ignoringExpectedNullFields()
usingRecursiveComparison을 잘 활용하시네요 !! 👏👏

2023-06-01 15:07 UTC, xrabcde commented on src/test/java/cart/dao/OrderDaoTest.java
> +                .isEqualTo(List.of(savedOrderEntity1, savedOrderEntity2, savedOrderEntity3, savedOrderEntity4));
💯💯

2023-06-02 12:52 UTC, wugawuga commented on src/main/java/cart/config/OpenApiConfiguration.java
> +        @Server(url = "http://localhost:8080", description = "로컬"),
리드미를 깜빡했습니다ㅠㅠ 죄송합니다

2023-06-02 12:54 UTC, wugawuga commented on src/main/java/cart/controller/MemberCouponController.java
> +public class MemberCouponController {
Coupon 과 MemberCoupon 은 비슷하지만 전혀 다른 도메인이라고 생각하여 분리를 했습니다.
그렇게 됐을 때 저희가 정한 api 명세는
- 사용자 쿠폰 조회 GET /coupons 였습니다.

하지만 이렇게 되다보니 coupon 과 memberCoupon 을 어떻게 따로 관리할지 고민을 많이 했는데,
바다 말씀대로 /coupons 하위에 들어가면 훨씬 좋을 것 같습니다!!!

2023-06-02 12:57 UTC, wugawuga commented on src/main/java/cart/dao/CartItemDao.java
> +    public int deleteById(final Long cartItemId, final Long memberId) {
해당 사용자의 장바구니가 아니라 마구잡이로 삭제가 될 수도 있겠다라는 생각을 하여 둘 다 받아서 삭제하는 형식으로 했습니다.

2023-06-02 12:58 UTC, wugawuga commented on src/main/java/cart/dao/MemberCouponDao.java
> +        jdbcTemplate.update(sql, memberId, id);
이 부분도 아까 위에서 장바구니 삭제와 비슷한 경우입니다. 아무 쿠폰이나 업데이트가 될 수도 있다고 생각하여서 memberId 도 같이 넘겨주는 식으로 처리했습니다!

2023-06-02 12:58 UTC, wugawuga commented on src/main/java/cart/domain/coupon/policy/DiscountPolicyType.java
> +    NONE((value) -> new NonDiscountPolicy());
ㅎㅎㅎ 감사합니다,,,

2023-06-02 13:16 UTC, wugawuga commented on src/main/java/cart/service/OrderService.java
> +    public List<OrdersDto> findAllBy(final Long memberId) {
넵 맞습니다,, ㅎㅎㅎ 리팩터링하였습니다!!!

2023-06-03 06:59 UTC, wugawuga commented on src/main/java/cart/dto/OrderSaveRequest.java
> +
요청 관련된 클래스를 열심히 체크해 놓고 정작 valid 설정을 하지 않았군요,,, 좋은 글 감사합니다!!!!

2023-06-03 07:24 UTC, wugawuga commented on src/main/java/cart/dao/CouponDao.java
> +public class CouponDao {
dao 는  ```@Component``` 를 적용하고자 했지만, 꼼꼼하지 못한 부분이 있었던 것 같습니다.
```@Repository``` 는 여러 dao 를 가지고 있는 클래스로 사용했습니다. repository 와 dao 의 차이를 공부하고자 저번 미션에서 봤었는데, ddd 얘기가 많이 나와 많이 어려워서 학습을 더 이상 하지 않았습니다.

dao 는 자신이 해당하는 테이블과 1대1 관계를 가진다고 생각합니다.
그래서 접근을 하는 entity 클래스 (테이블과 1대1 매칭이 되는 필드를 가지는)를 가지는 dao 클래스 입니다.

repository 는 entity 와는 다르게 domain 클래스를 가지고 있습니다. domain 클래스는 entity 와 다르게 1대1로 매칭이 될 수는 있지만 그게 값이 아닌 객체를 들고 있으며 비즈니스 로직을 포함할 수 있습니다. 객체를 들고 있으려면 여러 dao 에 접근을 하여 객체를 조립을 해야합니다.
```@Repository``` 가 붙은 클래스는 여러 dao 에 접근을 하여 해당 domain 클래스를 반환합니다!! 그래서 명시적으로도 이 클래스는 ```Repository``` 를 알 수 있게 하고 싶어서 나누어서 적용해보았습니다.

바다가 말씀해주신 부분을 토대로 이제 두 차이를 학습해 보았습니다.
```@Repository``` 가 붙은 클래스는 스프링에서 지원하지 않는 예외들을 스프링 예외로 전환하여 보여주는 역할을 합니다.
```jdbcTemplate``` 도 jdbc 예외를 스프링 예외로 전환을 해줍니다.

1. ```@Repository``` 는 벤더마다 다른 예외를 스프링 예외로 전환을 해준다.
2. ```jdbcTemplate```은 jdbc예외를 스프링 예외로 전환을 해준다.

여기까지 학습을 해보았습니다!! ```@Repository``` 의 예외전환을 테스트해보고 싶었는데 어떻게 할지 몰라서 넘어갔습니다ㅠㅠ

2023-06-03 09:17 UTC, wugawuga commented on src/main/java/cart/service/MemberCouponService.java
> +    public List<MemberCouponDto> findByMemberId(final Long memberId) {
제가 학습한 부분을 정리해 말씀드려보겠습니다!!!! 😆

먼저 Transactional 의 우선순위는
1. 클래스 내부의 메소드
2. 클래스
3. 인터페이스 메소드
4. 인터페이스
입니다.
즉, 클래스에 설정이 되어 있다고 하더라도 클래스 내부 메소드에 정의를 한다면 해당 메소드에 Transactional 옵션들을 수행?되게 됩니다.

그리고 readOnly 는 제대로 알고 사용한 것이 아니라 조회 시 성능상 이점이 있다고 알고 있어서 사용했습니다.

하지만 readOnly 를 사용하면 스프링이 hibernate 세션 플러시 모드를 MANUAL 로 설정을 한다고 합니다. 이렇게 되면 플러시가 발생하지 않는다고 합니다.
그러면 entity 의 등록, 수정, 삭제 등의 동작을 막을 수 있고,
변경 감지를 위한 스냅샷을 보관하지 않게 되어 성능이 조금 향상된다고 합니다.
즉, readOnly 라는 옵션은 JPA 를 구현한 spring arm 기술에서 적용이 됩니다!!

2023-06-03 12:12 UTC, wugawuga commented
안녕하세요 바다 🌊 우가입니다 🥳

말씀 주신 부분들을 고민해 보고 리팩터링 진행했습니다.

dao 에서는 최대한 해당 테이블 pk 로 조회를 해오고, repository 에서 객체 조합을 하여서
service 에서 사용자(Member) 검증을 객체가 하게끔 해보았습니다.

이렇게 객체에서 검증을 하게끔 작성을 하고도 고민인 부분이 있습니다.
애초에 argumentResolver 에서 검증하고 나서 받을 수 있는 데이터를 다시 요청을 주는 느낌인데, 

1. Member 검증을 또 해야하는 것인지
2. 꼼꼼하게 한번더 검증을 하는게 좋은것인지
궁금합니다!!! 항상 열심히 리뷰해주셔서 감사합니다 🙇‍♂️ 행복한 주말되세요!!!!

2023-06-05 12:31 UTC, xrabcde requested changes
안녕하세요 우가 ~ 바다입니다 🌊
피드백 깔끔하게 잘 반영해주셔서 이만 머지해도 될 것 같지만 
실패하는 테스트가 몇 개 있어서 수정요청드립니다 
수정 후 다시 요청보내주세요 ~! 🙌

2023-06-05 12:31 UTC, xrabcde commented on img.png
오호 DB 구조도 깔끔하게 정리해주셨네요 💯💯

2023-06-05 12:31 UTC, xrabcde commented on src/main/java/cart/controller/CouponController.java
> +    public ResponseEntity<Void> save(@Valid @RequestBody final CouponSaveRequest request) {
👍🏻👍🏻

2023-06-05 12:31 UTC, xrabcde commented on src/main/java/cart/controller/CouponController.java
> +    public ResponseEntity<List<MemberCouponDto>> findAll(@Auth final Credential credential) {
API 명세가 달라졌는데 프론트분들과는 어떤식으로 논의하셨나요? 
혼자서 명세를 정의하던 이전 미션들과 비교해서 협업을 해보니 어떤 점들을 더 고려하게 되었나요?

2023-06-05 12:31 UTC, xrabcde commented on src/main/java/cart/domain/Order.java
> +        return memberCoupon.getDiscountValue();
오 할인 계산 로직이 훨씬 깔끔해졌네요 ~!

2023-06-05 12:31 UTC, xrabcde commented on src/main/java/cart/service/CartItemService.java
> +        cartItem.checkOwner(member);
권한에 대한 확인 후 삭제하는 로직이 훨씬 명확해진 것 같습니다 👏

2023-06-05 12:31 UTC, xrabcde commented on src/test/java/cart/controller/CouponControllerTest.java
> +    void 해당멤버의_모든_쿠폰을_조회한다() throws Exception {
실패하는 테스트들이 있는데 확인부탁드려요 ~

<img width="250" alt="image" src="https://github.com/woowacourse/jwp-shopping-order/assets/56033755/662258a5-0a47-41bc-baa7-af26e328d851">

2023-06-05 12:31 UTC, xrabcde commented on src/test/java/cart/controller/OrderControllerTest.java
> +        assertThat(findOrder.getCalculateDiscountPrice().longValue()).isEqualTo(18000);
expect 하는 Order 객체를 만들어 usingRecursive로 비교해도 좋을 것 같아요 ㅎㅎ

2023-06-05 12:47 UTC, wugawuga commented on src/test/java/cart/controller/CouponControllerTest.java
> +    void 해당멤버의_모든_쿠폰을_조회한다() throws Exception {
명세에 맞춰서 수정했는데 data.sql 이랑 몇몇 빼먹은 부분이 있어서 리팩터링 진행하였습니다!!

2023-06-05 13:07 UTC, wugawuga commented on src/main/java/cart/controller/CouponController.java
> +    public ResponseEntity<List<MemberCouponDto>> findAll(@Auth final Credential credential) {
주고 받는 데이터부터 서로 더 편한점과 불편한 점을 고려하면서 명세를 정의했습니다.

이전에는 저혼자 그냥 막무가내로 데이터를 내려주었던 것 같은데 앞으로 한번 더 생각하고 프론트분들과 많은 얘기를 통해서 명세를 정의를 할 것 같아요!!!

2023-06-05 13:08 UTC, wugawuga commented
안녕하세요 바다!!
우가입니다 ㅎㅎㅎ

명세에 대해서 수정을 하고나서 data.sql 과 몇몇 부분을 까먹어 테스트를 놓치고 말았습니다.
앞으로 테스트를 항상 꼼꼼히 테스트를 돌려보고 올리겠습니다.

정말 너무 감사드립니다 🥳

2023-06-05 13:23 UTC, xrabcde approved these changes
안녕하세요 우가 ~ 
수정해주신 내용 확인했습니다 이번 미션은 여기서 머지할게요 
마지막 미션까지 정말 수고 많으셨습니다 
앞으로 남은 과정도 화이팅이에요 🎉

2023-06-05 13:23 UTC, xrabcde commented on src/test/java/cart/controller/OrderControllerTest.java
> +                .isEqualTo(new Order(Long.valueOf(orderId), memberCoupon, member, List.of(orderItem1, orderItem2)));
👍🏻👍🏻

2023-06-05 13:23 UTC, merged