[2단계 - 주문 기능 구현] 마코(이규성) 미션 제출합니다.
woowacourse/jwp-shopping-order pull request #15
Opened 2023-05-31 18:26 UTC by aak2075

안녕하세요 마코입니다~

이번 미션에서 기본으로 제공된 뼈대 코드를 사용하지 않고, 저번 미션에서 작성했던 코드를 이번 미션의 api명세에 맞게 수정하여 사용했습니다.

요구사항에서 제시한 재화 정책 중 쿠폰을 구현 했으며, 쿠폰을 구현하다 보니 자연스럽게 할인까지 구현이 된 것 같습니다.

## 도메인

쿠폰은 중복 적용이 불가능 하고, 주문 금액에 따라 조건을 설정하였습니다.
api 명세와 db 구조를 먼저 설계하고 도메인을 구현했더니 조금 부자연스러운 부분들이 있습니다.

1. db에 배달비는 저장하지만 주문 금액을 저장하지 않기 때문에 Order 객체에서는 주문 금액을 상태로 가질 필요가 없다고 판단하여 상태로 가지지 않았습니다.
실제로 사용할 때 주문 금액과 배달비의 생명 주기가 같아서 묶어서 이 둘을 관리하는 도메인을 만들고 싶었는데 상태로 가지지 않게 하려니 주기가 달라지고 관리가 어려워지는 것 같아서 사용하지 않았습니다.
차라리 상태로 갖도록 하여 Order 정적 팩터리 메서드에서 (주문 금액 + 배달비)를 관리하는 객체를 상태로 갖도록 하는 것이 나을까요?

2. 현재 할인 정책에는 정가, 퍼센트, 배달비 할인이 있습니다. 이 세 구현체는 같은 인터페이스를 구현하는데 배달비 할인은 필요 없는 value를 파라미터로 받는 등 조금 어울리지 않는 것 같습니다.

## 주문 객체 협력 구조

![주문](https://github.com/woowacourse/jwp-shopping-order/assets/35948985/4f8123e3-60e2-4f23-ba63-ba125f014504)

생명 주기가 같은 도메인 객체들끼리는 객체 참조갖도록 하였고 주기가 다르다고 생각한 객체는 id를 가져 약한 결합도를 갖게 하였습니다. 이러한 협력 구조에 대해서 어떻게 생각하시는지 궁금합니다!

## DB 구조

<img width="1005" alt="스크린샷 2023-06-01 오전 2 41 07" src="https://github.com/woowacourse/jwp-shopping-order/assets/35948985/1003d7e0-056a-42f8-9116-04fdde2c1a75">

구조가 복잡해지는 것을 고려하여 쿠폰 테이블의 정책과, 조건을 분리하지 않았습니다. 

## 변경 예정

MemberCouponController의 url이 "/coupons"로 되어있어 헷갈려서 "/member-coupons"로 변경 예정이나 프론트와 아직 협의되지 않아 TODO주석으로 달아놨습니다.

## api 명세

Swagger를 사용하여 문서화했습니다.
(https://m4co.shop/swagger-ui/index.html#/)

---

궁금한 점이나 부족한 부분이 있다면 언제든지 DM 주시면 감사하곘습니다.
리뷰 잘 부탁드립니다~ 😄

2023-06-01 15:53 UTC, choijy1705 requested changes
안녕하세요 마코!
미션 잘진행해주셨네요!
swagger어노테이션이 controller에서 차지하는 비중이 너무커서
핵심 로직들이 눈에 잘 안들어오고 있어요
다른 방법은 없을지 고민해봐주시면 좋을것 같아요
다른 코멘트들도 남겼으니 확인부탁드려요!

2023-06-01 15:53 UTC, choijy1705 commented on src/main/java/cart/auth/BasicAuthorizationParser.java
> +        if (authorizationHeader.isBlank()) {
authorizationHeader가 null 이면 npe가 발생하지 않을까요?

2023-06-01 15:53 UTC, choijy1705 commented on src/main/java/cart/auth/CredentialThreadLocal.java
> +@Component
스프링 빈으로 등록되면 싱글톤일텐데
꽤 심각한 성능저하를 발생시키지 않을까요?

2023-06-01 15:53 UTC, choijy1705 commented on src/main/java/cart/auth/AuthInterceptor.java
> +                .orElseThrow(() -> new AuthenticationException("올바르지 않은 이메일입니다. 입력값: " + credential.getEmail()));
email에 대해 unique 제약조건까지 잘 해주셨네요👍
index 도 고려해보면 어떨까요?

2023-06-01 15:53 UTC, choijy1705 commented on src/main/java/cart/auth/AuthArgumentResolver.java
> +        credentialThreadLocal.clear();
get을 한 이후에는 clear가 반드시 되야할거 같은데
반드시 되야하는 경우라면 하나의 메서드로 만들어서 
잘못 쓰일 가능성을 제거하는게 좋지 않을까요?

2023-06-01 15:53 UTC, choijy1705 commented on src/main/java/cart/controller/CartItemController.java
> +    })
swagger를 사용하는건 좋지만
이렇게 쓰는게 좋아보이지는 않네요 ㅠ 핵심 로직이 잘 안보여요 ㅠ
다른 방법은 없을까요?

2023-06-01 15:53 UTC, choijy1705 commented on src/main/java/cart/controller/CartItemController.java
> +        return ResponseEntity.created(URI.create("/cart-items/" + id)).build();
create, update 하는 경우에도 body를 반환해주는게 좋을것 같아요
큰 서비스들의 developer 문서를 보시면 
delete를 제외한 create, update, read 경우 body를 반환하는걸 볼 수 있을거에요

2023-06-01 15:53 UTC, choijy1705 commented on src/main/java/cart/controller/ProductController.java
> +        final List<ProductDto> productDtos = productService.findAll();
ProductResponse가 되야하지 않을까요?
dto의 클래스 명은 통일되면 좋을것 같아요

2023-06-01 15:53 UTC, choijy1705 commented on src/main/java/cart/domain/Money.java
> +    private final long value;
돈은 bigDecimal 활용해주세요!
달러 등의 소수점 연산이 필요할 수도 있고
나누기 등에 의해서 값 오차가 발생할 가능성이 있습니다

2023-06-01 15:53 UTC, choijy1705 commented on src/main/java/cart/domain/CartItem.java
> +    private Integer quantity;
수량이 null일 수 있나요?
아니라면 int를 사용하는게 좋을것 같아요

2023-06-01 15:53 UTC, choijy1705 commented on src/main/java/cart/domain/coupon/Coupon.java
> +    private final long value;
coupon의 value는 어떤의미인가요
직관적으로 느낌이 확 오지 않는 필드명인것 같아요!

2023-06-01 15:53 UTC, choijy1705 commented on src/main/java/cart/domain/coupon/discountPolicy/PolicyType.java
> +    public static PolicyType from(final String name) {
그냥 valueOf를 사용해도 되지 않을까요?

2023-06-01 15:53 UTC, choijy1705 commented on src/main/java/cart/domain/member/MemberCoupon.java
> +public class MemberCoupon {
MemberCouponEnttiy와 MemberCoupon은 거의 똑같네요
id냐 객체냐의 차이인거 같은데 
MemberCoupon이라는 도메인이 있다면 객체지향이 아닌 데이터 지향적인 설계가 아닐까요?
Member에서 coupon 및 cartItem을 가지고 있어야 하지 않을까요?
요건 좀 복잡해서 바로 반영하기보단 우선 고민한번 해보시고 의견을 얘기해주시면 좋을것 같아요

2023-06-01 15:53 UTC, choijy1705 commented on src/main/java/cart/exception/CartItemNotFoundException.java
> +public class CartItemNotFoundException extends CartException {
에러를 너무 많이 정의한게 아닐까요?
새로운 도메인이 추가되면 또 그만큼 추가되어야할것 같은데요
실제 서비스에서 이렇게 에러를 정의해버리면 100개는 가뿐하게 넘어갈것같아요😭

2023-06-01 15:53 UTC, choijy1705 commented on src/main/java/cart/service/CartItemService.java
> +    public List<CartItemDto> findAll(final Long memberId) {
service에서 dto를 반환하시는 이유가 있나요? 
저는 service에서는 보통 도메인을 반환하는데요 이유는
1. 여기서 반환되는 dto는 클라(프론트) <-> 컨트롤러 에서의 dto일텐데 지금 구조라면 변경사항이 발생하면 service의 코드도 변경이 필요할것 같아요
2. 이 메서드를 호출하여 사용할 수 있는곳은 controller에서 뿐 (재사용을 할 수 없음) 다른 service에서 cartItem을 찾아올 필요성이 생길 수 있을텐데 이러면 재사용을 할 수 없을것 같네요!

2023-06-01 15:53 UTC, choijy1705 commented on src/main/java/cart/domain/member/MemberCoupon.java
> +    private final boolean used;
used 정보때문에 member는 coupon이 아닌 memberCoupon을 가지고 있어야 할것 같긴하네요
member에서 필드로 List<MemberCoupon>, List<Order> 를 가지고
MemberCoupon, Order 에서는 member가 정보가 없는쪽이 객체지향적일것 같네요

2023-06-03 02:15 UTC, aak2075 commented on src/main/java/cart/auth/BasicAuthorizationParser.java
> +        if (authorizationHeader.isBlank()) {
널체크도 해주도록 수정했습니다.

2023-06-03 02:15 UTC, aak2075 commented on src/main/java/cart/auth/AuthInterceptor.java
> +                .orElseThrow(() -> new AuthenticationException("올바르지 않은 이메일입니다. 입력값: " + credential.getEmail()));
이메일로 조회가 많이 일어나기 때문에 이메일도 index를 걸어주면 좋을 것 같네요 👍

2023-06-03 02:19 UTC, aak2075 commented on src/main/java/cart/auth/AuthArgumentResolver.java
> +        credentialThreadLocal.clear();
가능성 자체를 제거하는 것이 좋은 것 같습니다 👍

2023-06-03 02:19 UTC, aak2075 commented on src/main/java/cart/controller/CartItemController.java
> +    })
커스텀 어노테이션을 정의하여 줄이는 방법을 생각해봤지만 비슷할 것 같습니다.
그렇다면 rest docs를 사용할 수 있을 것 같은데요,
Rest docs는 적용하기 어렵고 작성하는데 공이 많이 들 것 같습니다.
영이는 swagger와 Rest docs중 무엇을 더 선호하며 어떤 기준으로 선택하시는지 궁금합니다!

2023-06-03 02:20 UTC, aak2075 commented on src/main/java/cart/controller/CartItemController.java
> +        return ResponseEntity.created(URI.create("/cart-items/" + id)).build();
body를 반환하는 이유는 변경의 결과를 확인시켜주기 위함인가요?

또 궁금한 점이 생긴게, 지금 제 코드는 request에서 Id만 보내서 로직을 수행하고 있습니다.  request에서 이름이나, 가격 등 모든 정보도 같이 보내서 검증을 수행하는것이 주문을 하는 동안 관리자가 Product를 변경해서 불일치하는 문제를 막아야한다는 생각이 들었습니다. 보통 이렇게 Id만 보내지 않고 데이터를 최대한 담아서 request를 보내는 편인가요?

2023-06-03 02:20 UTC, aak2075 commented on src/main/java/cart/controller/ProductController.java
> +        final List<ProductDto> productDtos = productService.findAll();
반영했습니다.

2023-06-03 02:20 UTC, aak2075 commented on src/main/java/cart/domain/Money.java
> +    private final long value;
반영했습니다.

2023-06-03 02:20 UTC, aak2075 commented on src/main/java/cart/domain/CartItem.java
> +    private Integer quantity;
동의합니다. nullable한 래퍼타입을 사용하면 다른 동료 개발자가 이 값이 null이 될 수 있는지 고민해야 한다거나 버그를 발생시킬 여지가 될 수 있을 것 같습니다. int를 사용하도록 수정했습니다.

2023-06-03 02:20 UTC, aak2075 commented on src/main/java/cart/domain/coupon/Coupon.java
> +    private final long value;
할인 가격, 할인 비율, 할인 배달비 모두를 나타내는 discountValue로 수정했습니다.

2023-06-03 02:20 UTC, aak2075 commented on src/main/java/cart/domain/coupon/discountPolicy/PolicyType.java
> +    public static PolicyType from(final String name) {
valueOf는 Enum 상수의 이름을 사용해야 합니다. 상수의 이름을 직접 사용하기 보다 따로 name필드로 사용하는 것이 api 명세가 바뀌거나 db에 저장하는 이름이 바뀌었을 때 변경에 더 안전하다고 생각합니다. 또한, valueOf는 일치하는 enum이 없을 경우 IllegalArgumentException이 발생하는데, 이보다 명확한 예외를 던져주는 것이 에러를 파악하기 쉽다고 생각했습니다.

2023-06-03 02:20 UTC, aak2075 commented on src/main/java/cart/domain/member/MemberCoupon.java
> +public class MemberCoupon {
말씀하신대로 MemberCouponEnttiy와 MemberCoupon은 거의 똑같지만 엔티티로 분리한 이유는 2가지가 있습니다.
1. dao에서 MemberCoupon을 직접 접근하게 됐을 때 MemberCoupon을 생성하기 위해 Member와 Coupon을 조인쿼리로 같이 만들어줘야 합니다. 이렇게 관리하기 보다 dao에서는 단순한 쿼리만 실행하고, 다른 객체를 조립해주는 것은 한 층 추상화된 repository에서 해주는 것이 코드를 이해하기 쉽고, 변경하기 쉬울거라고 생각했습니다. 따라서 dao에서는 id값만 갖는 entity를 사용하도록 했습니다.
2. 다른 도메인 객체들도 1번의 이유로 도메인과 엔티티를 분리해서 사용했습니다. 하지만 MemberCoupon만 엔티티와 비슷하다고 분리하지 않으면 아키텍처의 일관성이 깨지고 다른 동료 개발자들이 명확한 기준이 없다고 생각하여 코드를 유지보수하기 어려울 것이라고 생각합니다. 

---

Member에서 Coupon과 CartItem을 가지고 있는 것이 더 객체지향적인 설계이고, MemberCoupon 도메인은 다대다 맵핑테이블인member_coupon 테이블을 도메인으로 만든 느낌이 들어서 데이터 지향적인 설계라는 느낌이 드는 데에는 동의합니다.
하지만, Member가 직접 Coupon과 CartItem을 갖고 있는다면 기능이 확장되었을 때 Member의 책임이 너무 커질것 입니다. 또한 Member가 다른 도메인인 Coupon이나 CartItem을 강하게 의존하고 있다면 시스템을 모듈화하여 분리할 때 어려울 것이라고 생각합니다. 물론 Order와 OrderItems와 같이 비즈니스적으로 강한 협력이 필요하고 영속성 컨텍스트에 접근하는 주기가 같은 경우에는 묶어놓는것이 좋습니다.
하지만 이렇게 해결하려는 문제 영역이 다른 도메인을 분리하고, 중간 협력 객체인 MemberCoupon으로 두 객체간의 협력에 관한 로직을 갖고 있으면 두 객체 협력에 변경이 생겨도 각 Member와 Coupon은 변경에 안전하다는 장점이 있습니다. 
정리하면 문제 해결 영역이 다른 도메인간의 의존성을 줄여 모듈화의 가능성을 열어두고 두 객체의 협력에 관한 로직만 관리하여 책임을 분리하고 변경에 더 쉽게 대응할 수 있다고 생각합니다.

2023-06-03 02:20 UTC, aak2075 commented on src/main/java/cart/exception/CartItemNotFoundException.java
> +public class CartItemNotFoundException extends CartException {
에러가 많으면 어떤 단점이 있을지 고민해봤습니다.
에러를 관리하는데 어느정도 리소스가 든다는 단점이 있을 것 같습니다.
하지만 이에 비해 에러를 세분화하여 얻는 이점이 더 크다고 생각합니다.
추상화된 예외를 재사용하거나 표준 예외를 사용하면 에러의 원인을 에러 메시지에 의존하게 되며 예외를 던질 때마다 일관된 메시지를 담기 어렵습니다. 반대로 예외를 세분화한다면 에러의 원인도 빠르고 명확하게 파악하며 에러 메시지 관리도 편할것 같습니다.

2023-06-03 02:21 UTC, aak2075 commented on src/main/java/cart/service/CartItemService.java
> +    public List<CartItemDto> findAll(final Long memberId) {
정말 고민이 되는 내용입니다.
말씀해주신 1번의 이유로 클라(프론트) <-> 컨트롤러의 dto와 컨트롤러 <-> service의 dto를 분리한다면 해결할 수 있을 것 같습니다. 하지만 이는 dto가 너무 많아지고 두 dto가 비슷한 경우가 많아 과한 분리가 되지 않을까 싶습니다.
다른 서비스에서의 재사용 문제는 큰 단점이네요. 
이론적으로는 레이어간 의존성을 끊어서 컨트롤러에서 도메인 변경에 대해 영향을 받지 않기 위해 서비스에서 dto를 반환하도록 했으나 사실 도메인이 변경된다고 해서 컨트롤러가 바뀌는 부분이 크지 않을 것 같고 도메인의 변경에 영향을 받는 것도 나쁘진 않다는 생각이 듭니다. 가장 중요한 것은 도메인이니까요.
따라서, 레어이간 격리를 통해 변경에 조금 유연한 것 보다 재사용의 장점이 더 크다고 생각하여 도메인을 반환하는 것이 좋겠습니다.

2023-06-03 02:25 UTC, aak2075 commented on src/main/java/cart/domain/member/MemberCoupon.java
> +    private final boolean used;
Coupon은 관리자가 만든 원본 쿠폰이고 사용자가 사용하는 쿠폰은 원본 쿠폰을 복사해서 발행한 MemberCoupon 이여서 used 정보를 추가로 갖도록 설계했습니다.
Member에 책임을 부여한다면
```java
public class Member {
    private final Long id;
    private final String email;
    private final String password;
    List<MemberCoupon> memberCoupons;
    ...
}
```

```java
public class Order {
    private final Long id;
    private final OrderItems orderItems;
    private final Money deliveryFee;
    private final Member member;
    ...
```

이런 구조가 될 것 같습니다.

2023-06-03 05:46 UTC, aak2075 commented
안녕하세요 영이!
리뷰 열심히 반영해봤습니다.
반영하면서 들었던 의문이나 기존에 작성했던 코드의 의도도 코멘트에 달았으니 확인해주시고 의견 주시면 감사하겠습니다.

서비스에서 도메인을 반환하다보니 다음과 같이 컨트롤러에서 도메인 로직을 수행해야하는 경우가 생겼습니다.
```java
    @GetMapping("/{orderId}")
    public ResponseEntity<OrderResponse> findById(@Auth final Credential credential, @PathVariable final Long orderId) {
        final Order order = orderService.findById(credential.getMemberId(), orderId);
        return ResponseEntity.ok(OrderResponse.of(order, order.getOrderPrice(), order.discountOrderPrice(), order.discountDeliveryFee()));
    }
```
모든 경우에 서비스에서 도메인을 반환하기 보다 이런 경우에는 dto를 반환하는 것에 대해서 어떻게 생각하시나요?

2023-06-03 15:24 UTC, aak2075 commented on src/main/java/cart/auth/CredentialThreadLocal.java
> +@Component
일반적으로 ThreadLocal을 빈으로 관리하는 것은 권장하지 않고 있네요.
 ThreadLocal은 특정 스레드 내에서만 사용되므로 이 스레드가 종료되면 ThreadLocal에 저장된 데이터를 해제해주어야 하는데 빈으로 등록되면 생명 주기가 애플리케이션 전체로 바뀌고 이 데이터를 해제해주어야 하며 이를 꼼꼼하게 수행하지 못할 경우 메모리 누수가 발생할 수 있어 좋지 않네요.
관리도 어렵고 유지보수를 어렵게 하는 요인이 될 것 같아 제거했습니다.

2023-06-04 16:52 UTC, choijy1705 requested changes
안녕하세요 마코
피드백 잘 반영해주셨네요👍
추가적인 코멘트 조금 남겼는데
확인부탁드려요

2023-06-04 16:52 UTC, choijy1705 commented on src/main/java/cart/auth/AuthInterceptor.java
> +        final Credential credential = basicAuthorizationParser.parse(authorizationHeader);
threadLocal을 사용안하시는군요
Credentail을 얻는과정이 인터셉터와 리졸버에서 중복인것 같은데
다른 해결방법은 없을까요?

2023-06-04 16:52 UTC, choijy1705 commented on src/main/java/cart/auth/BasicAuthorizationParser.java
> +@Component
이 클래스도 util 클래스에 가까운것 같은데
굳이 스프링 빈이 관리하도록 할필요가 있을까요?

2023-06-04 16:52 UTC, choijy1705 commented on src/main/java/cart/controller/CartItemController.java
> +    })
아 저는 swagger 이외의 대안을 물어본게 아니라
swagger 어노테이션을 좀 더 간단하게 사용할 수 있을것 같아서 물어본거였습니다
굳이 코드 가독성을 포기하면서까지 swagger 문서에 많은 정보를 내려줄 필요는 없을것 같아서요
만약 자세한 api명세가 필요한 경우는 따로 직접 문서를 작성하지 swagger를 통해서 모든 정보를 내려주도록 하는 경우는 거의 없는것 같아요

2023-06-04 16:52 UTC, choijy1705 commented on src/main/java/cart/domain/CartItem.java
>      }
MemberValidator가 꼭 필요한가요?
파라미터로 memberId를 받아와서 cartItem의 memberId와 일치하는지 확인하면 될것 같은데

2023-06-04 16:52 UTC, choijy1705 commented on src/main/java/cart/domain/member/MemberCoupon.java
> +    public static final class NullMemberCoupon extends MemberCoupon {
쿠폰이 없다면 null을 반환해주면 되지 않을까요?

2023-06-04 16:52 UTC, choijy1705 commented on src/main/java/cart/domain/coupon/discountPolicy/PolicyType.java
> +    public static PolicyType from(final String name) {
enum 이름과 필드 이름이 동일하여서 굳이 필드를 만들기보단 enum 만으로 관리되는게 더 좋아보여서요
개수가 3개뿐이긴 하지만 시간복잡도도 valueOf는 O(1) 일거라
안전성을 고려한다면 db를 만들때 policyType을 만들어서 테이블을 생성하는건 어떨까요?
![image](https://github.com/woowacourse/jwp-shopping-order/assets/63634505/5ce9a11d-b946-4c95-8aa7-5acdb19eeaba)

2023-06-04 16:52 UTC, choijy1705 commented on src/main/java/cart/controller/CartItemController.java
> +        return ResponseEntity.created(URI.create("/cart-items/" + id)).build();
넵 body를 반환하는건 변경의 결과를 확인 시켜주기 위함입니다. request에 없는 정보가 함께 생성될 수도 있고 이를 통해서 다음 로직들을 수행할 수도 있을것 같네요

id만 보내도 로직이 충분히 수행가능하다면 id만 보내도 문제는 없을것 같아요. 보통은 어느정도 데이터를 담아 request를 보내긴합니다. 그리고 장바구니에 들어간 상품이 수정되어서 불일치가 되는 부분은 기획적으로 문제가 있는 부분일것 같네요. request, response에 관한 것들은 회사들 문서를 보면서 감을 잡으면 좋을것 같아요
https://shopify.dev/docs/api/admin-rest/2023-04/resources/product

2023-06-04 16:56 UTC, choijy1705 commented
> 서비스에서 도메인을 반환하다보니 다음과 같이 컨트롤러에서 도메인 로직을 수행해야하는 경우가 생겼습니다.
> 
>     @GetMapping("/{orderId}")
>     public ResponseEntity<OrderResponse> findById(@Auth final Credential credential, @PathVariable final Long orderId) {
>         final Order order = orderService.findById(credential.getMemberId(), orderId);
>         return ResponseEntity.ok(OrderResponse.of(order, order.getOrderPrice(), order.discountOrderPrice(), order.discountDeliveryFee()));
>     }

여기서 딱히 도메인 로직을 수행한다는 느낌이 안드는데 어떤 부분을 도메인 로직이라고 생각하셨나요?
그리고 `OrderReponse.of(order)` 만 으로도 충분히 dto를 만들 수 있을것 같아요

2023-06-05 08:14 UTC, aak2075 commented on src/main/java/cart/auth/AuthInterceptor.java
> +        final Credential credential = basicAuthorizationParser.parse(authorizationHeader);
Request에 담아서 전달하면 중복으로 얻는 과정을 수행하지 않아도 됩니다.
```java
public class AuthInterceptor implements HandlerInterceptor {
    @Override
    public boolean preHandle(
            final HttpServletRequest request,
            final HttpServletResponse response,
            final Object handler
    ) {
        ...
        request.setAttribute("credential", savedCredential);
        ...
    }
}
```

```java
public class AuthArgumentResolver implements HandlerMethodArgumentResolver {
    @Override
    public Object resolveArgument(
            final MethodParameter parameter,
            final ModelAndViewContainer mavContainer,
            final NativeWebRequest webRequest,
            final WebDataBinderFactory binderFactory
    ) {
        return webRequest.getAttribute("credential", NativeWebRequest.SCOPE_REQUEST);
    }
}
```

다만, 걱정이 되는 부분이 있습니다.
request에 수정을 가해서 사용자가 보낸 request와 겹치는 속성이 생기는등 controller에서 문제가 발생하는 경우는 없는지 현업에서도 request에 수정을 가하는 방식이 자주 사용되는지 궁금합니다.

2023-06-05 08:14 UTC, aak2075 commented on src/main/java/cart/auth/BasicAuthorizationParser.java
> +@Component
util클래스라 ioc 컨테이너에게 di를 받을 필요가 없어서 static으로 관리해도 괜찮을 것 같습니다.

2023-06-05 08:15 UTC, aak2075 commented on src/main/java/cart/domain/CartItem.java
>      }
파라미터를 Long memberId로 받는다고 했을 때 이름만으로 memberId가 들어온다고 가정한 상황이고 무조건 memberId가 들어온다는 보장이 없어서 객체로 다른 id가 들어오는 상황이 없게 만들었습니다.
또한, memberId로 검증을 할 수 있겠지만 Member에 속하는 memberId를 다른 객체인 CartItem 에서 검증 로직을 수행하는 것은 단일 책임 원칙 위반이라고 생각했습니다. 이 검증 로직이 Order에서도 사용하고 있어서 중복이기도 해서 검증 객체를 따로 만들어서 사용했습니다.

2023-06-05 08:15 UTC, aak2075 commented on src/main/java/cart/domain/member/MemberCoupon.java
> +    public static final class NullMemberCoupon extends MemberCoupon {
Order에서 memberCoupon을 가지고 있어서 쿠폰이 없을 때 NullMemberCoupon을 가지도록 했습니다.
만약 null을 갖도록 한다면 쿠폰을 적용할 때 마다 null검사를 해줘야 하고, 검사를 빠뜨리면 NPE에 빠지기 쉽다고 해서 이런 객체를 만들었습니다.

2023-06-05 08:43 UTC, aak2075 commented on src/main/java/cart/domain/coupon/discountPolicy/PolicyType.java
> +    public static PolicyType from(final String name) {
시간복잡도면에서는 확실히 valueOf를 사용하는 것이 좋을 것 같습니다.
db에 enum을 사용하는 것은 생각해보지 못했네요!
이중으로 안전성을 보장할 수 있어서 좋은 것 같습니다. 👍

2023-06-05 08:51 UTC, aak2075 commented on src/main/java/cart/controller/CartItemController.java
> +    })
동의합니다.
굳이 자세하게 작성하면서 가독성을 떨어뜨리는 것은 좋지 않은 것 같네요.
`@Operation(summary = "장바구니 상품 주문", description = "장바구니에 담긴 상품을 주문한다.")`
이렇게 @Operation 정보만 나타내도 충분한 것 같습니다.

2023-06-05 08:53 UTC, aak2075 commented
안녕하세요 영이~
이번 미션에서는 의문들이 생기는 부분들이 많네요!
코멘트에 제 생각과 함께 달았으니 확인부탁드립니다.

---

추가 질문에 대한 답변입니다.

> 여기서 딱히 도메인 로직을 수행한다는 느낌이 안드는데 어떤 부분을 도메인 로직이라고 생각하셨나요?

```java
    public Money discountOrderPrice() {
        return memberCoupon.discount(orderItems.sumPrice());
    }
    public Money discountDeliveryFee() {
        return memberCoupon.discountDeliveryFee(orderItems.sumPrice(), deliveryFee);
    }
```
response를 만들 때 `discountOrderPrice()`, `discountDeliveryFee()`를 호출하는데 이들은 Order에서 필드로 갖고있는 것이 아니라 위 코드처럼 로직을 수행해서 얻는 결과입니다. 차라리 이런 경우는 도메인에 필드로 갖도록 해서 getter로 꺼내도록 하는 것이 나을까요?

> 그리고 OrderReponse.of(order) 만 으로도 충분히 dto를 만들 수 있을것 같아요

이것도 dto에서 로직을 수행한다는 느낌이 들어서 분리를 했었습니다.

2023-06-06 02:39 UTC, choijy1705 commented on src/main/java/cart/auth/AuthInterceptor.java
> +        final Credential credential = basicAuthorizationParser.parse(authorizationHeader);
request는 하나의 요청에 대해서 하나만 존재하기 때문에 겹치는 문제가 발생할것 같지는 않네요
하나의 요청에 대한 하나의 흐름이니까요
interceptor에서는 email, password를 넘겨주고 authArgumentResolver에서는 Member를 만들어 내려주면 credential 객체를 굳이 만들 필요는 없을것 같네요

현업에서는 대부분 spring security를 사용할것 같은데요 우테코에서는 미션중 사용하면 안되는걸로 알고있어요
어떤 방향으로 사용하는가는 회사마다 다를것 같네요
주변에 물어보니 threadLocal을 사용하는 경우도 있다고 합니다. (빈으로는 안등록하고요)

2023-06-06 02:45 UTC, choijy1705 commented on src/main/java/cart/domain/member/MemberCoupon.java
> +    public static final class NullMemberCoupon extends MemberCoupon {
상속이라는 관점에서도 지금 구조는 어색하고
가독성 측면에서도 좋지 않은것 같아요
다른 사람이 코드를 봤을때도 NullMemberCoupon을 이해하긴 쉬워보이진 않습니다

2023-06-06 03:23 UTC, choijy1705 approved these changes
안녕하세요 마코
이번 미션은 이만 머지하겠습니다!
밤사이 마코의 학습로그가 핫플이 되었네요
몇가지 코멘트 남겼으니 확인해주시고
다음 레벨도 화이팅입니다. 레벨2 고생많으셨어요

2023-06-06 03:23 UTC, choijy1705 commented on src/main/java/cart/service/OrderService.java
> +        applicationEventPublisher.publishEvent(order);
제이슨랑 많은 얘기를 나눈것 같아서 따로 많은 코멘트를 남기진 않을게요

이벤트를 사용해버리면 transactional도 보장이 안되지 않을까요?

2023-06-06 03:23 UTC, choijy1705 commented on src/main/java/cart/domain/order/Order.java
> +    private final MemberCoupon memberCoupon;
order에서는 orderPrice, deliveryFee가 필드로 있는것이 좋을것 같고
memberCoupon은 order에서 굳이 필요없지 않을까요?
coupon 사용여부 정도는 서비스 기획에 따라 필요할수는 있을것 같네요

2023-06-06 03:23 UTC, choijy1705 commented on src/main/java/cart/controller/CartItemController.java
> +        final List<CartItemDto> result = cartItems.stream()
어떤곳에서는 repsonse 어떤곳은 dto인데
response로 통일되면 좋을것 같네요!

2023-06-06 03:23 UTC, choijy1705 commented on src/main/java/cart/controller/OrderController.java
> +    })
여긴 그대로 있어요!

2023-06-06 03:23 UTC, choijy1705 commented on src/main/resources/schema.sql
> +    `policy_type`    ENUM('PRICE', 'PERCENT', 'DELIVERY')     NOT NULL,
👍

2023-06-06 03:23 UTC, choijy1705 commented on src/main/java/cart/domain/CartItem.java
>      }
memberId가 아닌 다른 id가 들어오면 exception을 던지면 되는거 아닌가요?
member객체를 잘 조회하고 member.getId()를 하여 파라미터로 넘겨주면 문제없을것 같은데요😭

2023-06-06 03:23 UTC, merged

2023-06-06 10:51 UTC, aak2075 commented on src/main/java/cart/service/OrderService.java
> +        applicationEventPublisher.publishEvent(order);
이런 저런 시도를 해보려다가 많은 이야기를 나눴네요😅

확실하게 트랜잭션을 보장하려면 @TransactionalEventListener(Phase = TransactionPhase.AFTER_COMMIT)으로 리스너를 구현하여 주문이 커밋이 되면 장바구니 상품 삭제 트랜잭션을 시작하는 것이 좋을 것 같습니다. 상품 삭제가 실패해서 주문이 실패하는 것도 문제이고, 만약 주문이 성공하지 않았는데 장바구니 상품이 삭제되지 않는 것이 좋기 때문이죠.

2023-06-06 11:02 UTC, aak2075 commented on src/main/java/cart/domain/order/Order.java
> +    private final MemberCoupon memberCoupon;
memberCoupon은 말씀하신대로 서비스 기획에 따라 달라질 것 같습니다.
주문 정보에서 쿠폰의 정보가 필요하다면 포함을 시키는 것이 좋을 것이고, 쿠폰의 정보가 필요가 없고 할인 금액을 Order객체 외부에서 협력을 통해 계산한다면 필요 없을 것 같습니다.