[2단계 - 주문 기능 구현] 에단(김석호) 미션 제출합니다.
woowacourse/jwp-shopping-order pull request #17
Opened 2023-06-01 11:05 UTC by cookienc

안녕하세요 제이온:) 리뷰이 에단입니다.
레벨2 마지막 미션을 함께하게 되어서 기쁘네요.
미션 진행하면서 궁금했던 점은 아래에 남겨 놓겠습니다.
미리 리뷰 감사드립니다!!🙇‍♂️🙇🙇‍♀️

2023-06-01 11:17 UTC, cookienc commented
## 설계시 도메인과 데이터베이스 중 어떤 걸 먼저 설계 하시나요?
저번 미션은 도메인 먼저 설계를 했지만, 이번엔 설계할 때 데이터베이스를 먼저 설계를 했습니다. 
도메인을 먼저 설계하게 되면, 비즈니스 로직에 집중할 수 있다는 장점이 있지만 쿼리가 깔끔하지 못하게 날라가는 단점이 있었습니다.
이번엔 데이터베이스를 먼저 설계를 하니 쿼리가 깔끔하게 날라가는 모습이 보였습니다. 지하철과 달리 비즈니스 로직이 복잡한게 아니라 따로 로직에 대한 단점은 느끼지 못했습니다. 
결국엔 답이 없는 질문인 것 같은데, 제이온은 어떤 설계 방식을 좋아하시나요?

2023-06-03 05:41 UTC, pjy1368 requested changes
안녕하세요 에단! 이번 미션 리뷰어를 맡은 제이온입니다 🙋‍♂️
처음으로 협업 미션을 하면서 재밌고 어려운 경험을 하셨을 것 같은데 전반적으로 기능 구현을 잘 해 주신 것 같습니다 👍
개선하면 좋은 포인트가 몇 가지 보여서 그 위주로 피드백 남겨 놓았습니다.
PR에서 질문 주신 내용은 해당 본문에 답변 드릴게요~

Q. 설계시 도메인과 데이터베이스 중 어떤 걸 먼저 설계 하시나요?
저는 개인적으로 도메인을 먼저 설계하는 편입니다. 모든 요구 사항이 데이터를 데이터베이스에 저장하거나 조회할 일이 있는 것은 아니기도 하고, 데이터베이스 자체가 없는 서비스도 많은만큼 도메인을 열심히 설계한 후, 필요하다면 거기서 테이블을 자연스럽게 뽑아내는 편입니다.
물론 저의 성향이고 테이블을 먼저 설계한 후 객체를 설계하는 것도 정답이기때문에 스스로 해 보시면서 더 적합해 보이는 방법을 취하면 어떨까 합니다 ㅎㅎ
저도 무조건 도메인만 먼저 설계하지는 않고, 이미 정의된 테이블 위에서 작업해야할 때는 테이블 스키마를 고민할 때도 있답니다.

Q. 할인 방법은 프론트와 백엔드에서 어느쪽에서 구현해야할까요?
양쪽에 구현되는 것이 베스트이나, 백엔드는 필수라고 생각합니다.
일반적으로는 요청이 프론트를 거쳐서 백엔드로 날아오겠지만, 백엔드의 API를 알아내서 직접 호출하는 케이스를 무시할 수 없습니다. 또한, 실무로 넘어가면 백엔드와 백엔드끼리 내부 호출을 하는 경우도 종종 있어서 (마이크로서비스면 매우 많이) 백엔드는 반드시 할인 정책이 있어야 합니다!

2023-06-03 05:41 UTC, pjy1368 commented on src/main/java/cart/controller/ControllerExceptionHandler.java
> +    }
IllegalArgumentException, NoSuchElementException과 같이 내장 JDK 예외를 항상 400번으로 처리하면 어떠한 문제점이 있을까요?

2023-06-03 05:41 UTC, pjy1368 commented on src/main/java/cart/controller/CouponController.java
> +    public ResponseEntity<Void> issueCoupon(final Member member, @PathVariable Long couponId) {
1. 어노테이션 기반 아규먼트 리졸버를 사용하지 않은 이유가 무엇인가요?
2. 클라이언트 요청을 도메인 Member로 받았을 때 장단점은 무엇이 있을까요?

2023-06-03 05:41 UTC, pjy1368 commented on src/main/java/cart/service/order/OrderProvider.java
> +}
해당 로직은 Service 안에 포함하지 않고 Provider로 분리하신 이유가 뭔가요~?

2023-06-03 05:41 UTC, pjy1368 commented on src/main/java/cart/dao/entity/CouponTypeCouponEntity.java
> +public class CouponTypeCouponEntity {
Entity는 가능한 테이블과 1:1 매핑되도록 해주세요! (일반적으로 협업할 때 스키마를 일일이 확인할 수 없으므로 Entity를 테이블로 생각하고 개발을 많이합니다.)
만약 복잡한 SQL 과정에서 여러 테이블의 일부 컬럼들이 혼합된 결과물을 반환해야한다면 dto 패키지에 해당 객체를 만들어주시거나, dao 혹은 repository 단에서 적절히 날것의 결과물을 도메인으로 반환부탁드려요~

2023-06-03 05:41 UTC, pjy1368 commented on src/main/resources/schema.sql
> +CREATE TABLE orders
order가 아니라 왜 orders인가요?

2023-06-03 05:41 UTC, pjy1368 commented on src/main/resources/application-prod.yml
> +    password: ${DB_PASSWORD}
이건 반영하라는 의미는 아니고 참고 사항으로 코멘트 적어드립니다.
`${PRIVATE_IP:localhost}`와 같이 환경 변수의 기본 값을 설정하면 application.yml 하나만으로 local, dev, stg, prod 등의 세팅이 가능합니다. 부분적으로는 가끔 적용하면 유용할 때가 있습니다 ㅎㅎ

2023-06-03 05:41 UTC, pjy1368 commented on src/test/resources/schema.sql
> +);
main에도 스키마가 있고, test에도 스키마가 있네요.
만약 main에서 스키마가 달라지면 test의 스키마를 수정하지 않는다면 에러가 날 것 같아요 😥
하나로 관리해 보면 어떨까요?

2023-06-03 05:41 UTC, pjy1368 commented on src/main/java/cart/domain/coupon/DiscountAmount.java
> +        if (discountAmount <= 0) {
0을 상수로 빼면 어떨까요?

2023-06-03 05:41 UTC, pjy1368 commented on src/main/java/cart/exception/CartItemException.java
>  public class CartItemException extends RuntimeException {
예외를 좀 더 계층화하면 어떨까요?
가장 연습하기 쉬운 방법은 NetworkException, InternalException로 구분해놓고 다시 NetworkException 안에서 401, 402, ... 을 나누고 그 안에 적절한 도메인 예외를 넣는 것입니다. 단점도 존재하나 어떤 단점이 있을지 고민해 보시는 것도 좋은 훈련이 될 것 같습니다 ㅎㅎ

2023-06-03 05:41 UTC, pjy1368 commented on src/main/java/cart/controller/ControllerExceptionHandler.java
> +    }
만약 401이 아닌 다른 종류의 CartItemException을 상속해서 예외를 던진다면 어떻게 될까요?

2023-06-03 05:41 UTC, pjy1368 commented on src/main/java/cart/service/dto/OrderRequest.java
> +    private final Long couponId;
Request Dto들을 Controller 패키지가 아닌 Service 패키지 안에 정의하신 이유가 궁금합니다

2023-06-03 05:41 UTC, pjy1368 commented on src/test/java/cart/service/CouponProviderTest.java
> +        coupon3 = new Coupon(3L, 3L, "3000원 할인 쿠폰", "3000원이 할인 됩니다.", 3000, false);
다른 테스트 클래스에도 사용되는 객체들은 Test Fixture로 분리해보면 어떨까요?

2023-06-03 05:41 UTC, pjy1368 commented on README.md
> +- [명세서](https://documenter.getpostman.com/view/17539086/2s93mBwJWq)
Swagger를 사용하여 API 문서 자동화를 해 보면 어떨까요?

2023-06-03 05:41 UTC, pjy1368 commented on README.md
> +## API 명세서
API 설계를 클라이언트(웹 프론트엔드, 모바일 안드로이드)와 논의했을 때 달라진 점이 있었나요? 또한 논의 경험을 하면서 느낀 점이 있는지 편하게 알려주세요 ㅎㅎ

2023-06-08 07:42 UTC, cookienc commented
안녕하세요 제이온! 수정해서 다시 PR 보냅니다!
다만 지난 PR에서 질문에 답이 안달린게 있어서 다시 써서 올리겠습니다.(링크가 안되네요ㅜㅜ)

## 도메인 필드를 VO로 감싸면 생성자에서는 raw type을 사용해도 될까요?
도메인 필드에서 VO를 감싸봤습니다. VO를 사용하면 VO에 검증이 추가될 수 있고, 개발자들이 필드를 혼동하여 실수를 줄이는 역할을 할 수 있습니다.
그 중에서 VO의 가장 중요한 장점은 실수를 줄이는 부분이라고 생각하는데요. 생성자에서 raw 타입을 사용해서 객체를 만들면 객체 생성하기 쉽다는 장점이 있지만, VO의 장점이 줄어든다고 생각합니다. 반면에 VO를 만들어 생성자에 주입해서 만들면 VO의 장점은 살리지만 코드를 짜는게 복잡할 것 같습니다.
제이온은 어떤식으로 하는 걸 선호하시나요?

##주문할 때 쿠폰이 없으면 어떻게 처리를 해야하나요?
주문할 때, 쿠폰을 사용하지 않으면 프론트에서 null을 주기로 했습니다. 하지만 null을 필드로 받는다라는게 위험해보입니다.
더 좋은 방법이 생각이 안나서 어쩔 수 없이 놔두긴 했습니다. 더 좋은 방법이 있을까요?
현업에서는 request를 할 때 null값을 일부로 보내기도 하나요?

2023-06-09 00:17 UTC, cookienc commented on src/main/java/cart/domain/order/Order.java
> +        this.orderItems = OrderItems.from(orderItems);
## 도메인 필드를 VO로 감싸면 생성자에서는 raw type을 사용해도 될까요?
도메인 필드에서 VO를 감싸봤습니다. VO를 사용하면 VO에 검증이 추가될 수 있고, 개발자들이 필드를 혼동하여 실수를 줄이는 역할을 할 수 있습니다. 
그 중에서 VO의 가장 중요한 장점은 실수를 줄이는 부분이라고 생각하는데요. 생성자에서 raw 타입을 사용해서 객체를 만들면 객체 생성하기 쉽다는 장점이 있지만, VO의 장점이 줄어든다고 생각합니다. 반면에 VO를 만들어 생성자에 주입해서 만들면 VO의 장점은 살리지만 코드를 짜는게 복잡할 것 같습니다.
제이온은 어떤식으로 하는 걸 선호하시나요?

2023-06-09 00:17 UTC, cookienc commented on src/main/java/cart/service/dto/OrderRequest.java
> +    private final Long couponId;
## 주문할 때 쿠폰이 없으면 어떻게 처리를 해야하나요?
주문할 때, 쿠폰을 사용하지 않으면 프론트에서 null을 주기로 했습니다. 하지만 null을 필드로 받는다라는게 위험해보입니다. 
더 좋은 방법이 생각이 안나서 어쩔 수 없이 놔두긴 했습니다. 더 좋은 방법이 있을까요?

2023-06-09 00:17 UTC, cookienc commented on src/main/java/cart/controller/ControllerExceptionHandler.java
> +    }
주어진 코드를 보면 stacktrace를 로그에 기록하기 떄문에 백엔드 입장에서는 어디서 오류가 났는지 확인할 수 있습니다. 하지만 클라이언트에서는 일괄적인 예외를 반환하기 떄문에, 정확히 어떤 에러가 났는지 확인하지 못할 것 같습니다. badRequest를 내보내는 것도 좋지만 추가로 오류 코드를 정의해서 클라이언트 개발자가 어떤 오류가 발생했는지 확인할 수 있게 변경하겠습니다.

2023-06-09 00:17 UTC, cookienc commented on src/main/java/cart/controller/CouponController.java
> +    public ResponseEntity<Void> issueCoupon(final Member member, @PathVariable Long couponId) {
제가 뼈대코드를 안짜서 의도를 정확히 파악하지는 못했습니다! 

그래도 장단점을 생각해보자면

- 장점
    - 어노테이션 기반을 안쓰면 Member라는 객체가 자주쓰이는 코드인 만큼 중복을 줄일 수 있다.
- 단점
    - @Modelattribute가 생략되어 있어 QueryParam으로 Member로 매핑하는 것으로 착각할 수 있다.

제가 생각한 장단점은 이 정도인데 추가로 다른게 있을까요?

2023-06-09 00:17 UTC, cookienc commented on src/main/java/cart/service/order/OrderProvider.java
> +}
실제 로직을 보면 OrderService가 로직이 별로 없어서 분리를 안해도 됐지만, 테스트할 때 Service 테스트가 많아 유지 보수하기 쉽게 Read쿼리를 분리를 했습니다!

2023-06-09 00:17 UTC, cookienc commented on src/main/java/cart/dao/entity/CouponTypeCouponEntity.java
> +public class CouponTypeCouponEntity {
실수했었네요. 수정하겠습니다! MyBatis에서 join할 때 ResultMap을 사용한다고 해서 이름을 dto 대신 ResultMap이라고 수정했습니다.

2023-06-09 00:17 UTC, cookienc commented on src/main/resources/schema.sql
> +CREATE TABLE orders
MySQL 예약어에 order by가 있어서 테이블 이름을 관례적으로 orders로 사용한다고 알고있습니다.

2023-06-09 00:17 UTC, cookienc commented on src/main/resources/application-prod.yml
> +    password: ${DB_PASSWORD}
오.. 이런 방법도 있었네요! 나중에 한 번 적용해봐야겠습니다! 감사합니당.

2023-06-09 00:17 UTC, cookienc commented on src/test/resources/schema.sql
> +);
그게 더 좋은 방법인것 같아요! 수정했습니다.

2023-06-09 00:17 UTC, cookienc commented on src/main/java/cart/domain/coupon/DiscountAmount.java
> +        if (discountAmount <= 0) {
놓쳤었네요. 수정했습니다!

2023-06-09 00:17 UTC, cookienc commented on src/main/java/cart/exception/CartItemException.java
>  public class CartItemException extends RuntimeException {
변경했습니다! 예외를 계층화하면 어떤 예외인지 정확히 파악할 수 있을 것 같습니다. 그러다보니 커스텀 예외를 많이 만들게 돼 관리가 힘들어 질 것 같습니다. 하지만 관리의 어려움 vs 예외의 빠른 발견 이면 예외의 빠른 발견이 좀 더 나은것 같습니다.

2023-06-09 00:17 UTC, cookienc commented on src/main/java/cart/controller/ControllerExceptionHandler.java
> +    }
이 부분은 제가 이해를 잘 못하겠습니다ㅜㅜ 만약 CartItemException에 내부 클래스로 다른 예외가 들어있으면 어떤 예외가 발생하냐고 물어보신건가요? 그렇게된다면 예외를 잡지 못하니 새로운 exceptionhandler를 정의해야 할 것 같습니다!

2023-06-09 00:17 UTC, cookienc commented on src/main/java/cart/service/dto/OrderRequest.java
> +    private final Long couponId;
request dto를 컨트롤러에 패키지에 위치하면 service 패키지가 controller 패키지에 의존관계가 생기기 때문에 이런식으로 구현을 했습니다. 하지만 Swagger를 적용하고나니 dto에 presentation관련 연관관계가 생겨 request를 controller 패키지로 옮기고, 새로운 service dto를 정의해서 값을 넘겨주는 형식으로 변경했습니다.

2023-06-09 00:17 UTC, cookienc commented on src/test/java/cart/service/CouponProviderTest.java
> +        coupon3 = new Coupon(3L, 3L, "3000원 할인 쿠폰", "3000원이 할인 됩니다.", 3000, false);
fixture를 사용하도록 변경했습니다.

2023-06-09 00:17 UTC, cookienc commented on README.md
> +- [명세서](https://documenter.getpostman.com/view/17539086/2s93mBwJWq)
Swagger를 추가해서 반영햇습니다.

2023-06-09 00:17 UTC, cookienc commented on README.md
> +## API 명세서
API에서 반환하는 이름이 변경된게 있었습니다. 주문 목록 조회를 할 때 현재는 orderItem을 반환하지만 원래는 cartItem을 반환하도록 되어있었습니다. 주문할 때 장바구니에 있는 상품이니까 괜찮다고 처음에는 생각했습니다.

하지만 개발을 하다보니 장바구니 아이템은 주문이 성공하면 삭제가 되어야하는데 이렇게 되면 삭제된 cartItem을 반환하는게 어색하게 됩니다. 그래서 cartItem을 반환하는 대신 orderItem을 만들어 따로 저장하게 하고 주문목록을 조회할 때 orderItem을 반환하도록 했습니다.

2023-06-09 00:40 UTC, pjy1368 approved these changes
안녕하세요 에단!
1차 피드백을 잘 적용해 주셨고, 질문 주신 내용도 답변 적어드렸습니다.
질문 내용 외의 부가적인 피드백을 작성하였으나 굳이 한 번 더 핑퐁하지 않고도 에단이 충분히 해결하실 수 있는 부분이라 미션은 여기서 마쳐도 될 것 같습니다 ㅎㅎ🙇‍♂️
혹시나 하시면서 궁금한 점이 있다면 DM 부탁드려요

2023-06-09 00:40 UTC, pjy1368 commented on README.md
> +## API 명세서
네~ 이런 식으로 클라이언트의 요구 사항에 따라 객체가 자주 변경될 수 있다는 사실을 잘 염두하면서 개발해주세요!

2023-06-09 00:40 UTC, pjy1368 commented on src/main/java/cart/controller/ControllerExceptionHandler.java
> +    }
그 부분도 맞습니다!
제가 말씀드리고 싶었던 포인트는 내장 JDK는 시스템의 결함으로도 발생할 수 있는 500번대 에러 성질을 갖고 있는데, 시스템의 결함도 일괄적으로 400번으로 클라이언트에게 주어지기 때문에 이것이 정말 클라이언트의 잘못인지 서버의 잘못인지 확인하기 어렵다는 단점이 있습니다.

2023-06-09 00:40 UTC, pjy1368 commented on src/main/java/cart/controller/CouponController.java
> +    public ResponseEntity<Void> issueCoupon(final Member member, @PathVariable Long couponId) {
네 우선 어노테이션 기반 아규먼트 리졸버를 안 쓰면 Member를 보았을 때 이게 무슨 용도로 쓰인지 알기가 어렵습니다 ㅠ
그래서 어노테이션을 붙여주면 아규먼트 리졸버로 쓰는 것으로 판단할 수 있죠 ㅎㅎ
그리고 클라이언트의 요청을 Member로 받으면 Dto가 아닌 Domain으로 받는 것이기 때문에 클라이언트의 요청이 달라지면 Domain이 수정되어야하는 단점이 있습니다!

2023-06-09 00:40 UTC, pjy1368 commented on src/main/java/cart/service/order/OrderProvider.java
> +}
그런 맥락이면 시도해볼 법 하네요!

2023-06-09 00:40 UTC, pjy1368 commented on src/main/resources/schema.sql
> +CREATE TABLE orders
아 예약어때문이군요 ㅎㅎ
사실 백틱(₩)을 사용해서 order를 묶어주면 가능은 한데, 실수할 여지가 있으니 알아두시기만 하면 됩니다 👍

2023-06-09 00:40 UTC, pjy1368 commented on src/main/java/cart/exception/CartItemException.java
>  public class CartItemException extends RuntimeException {
우선 많이 계층화해보시고 거기서 불필요하게 추상화해 둔 부분을 줄이는 연습을 해 보시면, 말씀 주신 두 개의 장단점을 완화할 수 있게 됩니다 ㅎㅎ

2023-06-09 00:40 UTC, pjy1368 commented on src/main/java/cart/controller/ControllerExceptionHandler.java
> +    }
아 맞습니다 ㅎㅎ 지금은 CartItemException이 늘 401을 던지도록 설계 되었지만, 동료 개발자의 실수든 본인의 실수든 CartItemException의 하위 클래스로 401이 아닌 다른 404 상태 코드와 같은 예외를 만들게 되면 이 ExceptionHandler는 오동작하게 됩니다. 위에 드린 코멘트처럼 그래서 상위 클래스의 이름을 401Exception, 402Exception과 같이 명시적이게 만들라는 것도 이 맥락과 유사합니다.

2023-06-09 00:40 UTC, pjy1368 commented on src/main/java/cart/service/dto/OrderRequest.java
> +    private final Long couponId;
그 방법도 괜찮고, service dto를 제거하는 것도 괜찮습니다~
물론 지금은 연습 단계니 service dto도 만들어서 두 계층의 dto를 상이하게 이용해보셔도 좋습니다.

2023-06-09 00:40 UTC, pjy1368 commented on src/main/java/cart/domain/order/Order.java
> +        this.orderItems = OrderItems.from(orderItems);
저는 도메인의 특정 필드가 예외 처리를 넘어서, 그 필드 자체가 부가 기능(ex. Amount의 경우 예외 처리말고 값을 덧셈하거나, 뺄셈하는 부가 기능이 있을 수 있음)이 있다고 할 때만 VO로 포장해 줍니다.
무분별하게 VO로 포장하면 말씀 주신대로 코드를 짜는 것이 복잡해지기 때문이죠!

2023-06-09 00:40 UTC, pjy1368 commented on src/main/java/cart/service/dto/OrderRequest.java
> +    private final Long couponId;
네 저도 그 경우에는 null로 반환합니다. 실제로 서드파티 api를 사용할 때도 dto는 null을 받아오는 경우도 많고, 백엔드에서 도메인으로 변환할 때 Optional 등을 통해 안전하게 null-checking만 잘해주시면 됩니다!

2023-06-09 00:40 UTC, pjy1368 commented on src/main/java/cart/auth/CredentialsArgumentResolver.java
> +public class CredentialsArgumentResolver implements HandlerMethodArgumentResolver {
어노테이션을 이용하여 명시적으로 잘 구현해 주셨네요 👏

2023-06-09 00:40 UTC, pjy1368 commented on src/main/java/cart/config/SwaggerConfig.java
> +        @Server(url = "https://dev-king-ethan.n-e.kr", description = "운영 서버")
이런 부분은 application.yml 상수로 관리해도 나쁘지 않아보이네요.

2023-06-09 00:40 UTC, pjy1368 commented on src/main/java/cart/config/WebMvcConfig.java
> +    }
Presentation 영역에 가까운 Configuration 객체에 Dao를 사용하면 어떠한 문제점이 생길 수 있을까요?

2023-06-09 00:40 UTC, pjy1368 commented on src/main/java/cart/exception/network/IllegalCartItemMemberException.java
> +}
이런 방법도 괜찮고, 필드로 code, message를 갖는 방식도 많이 사용합니다!
더불어 어떤 분들은 NetworkException을 상속한 거니까 status도 필드로 가지고, 그 status를 이용해서 RestControllerAdvice로 ResponseEntity 만드시더라고요~ 참고해보세요 :)

2023-06-09 00:40 UTC, merged