[2단계 - 주문 기능 구현] 지토(김지민) 미션 제출합니다.
woowacourse/jwp-shopping-order pull request #21
Opened 2023-06-01 14:24 UTC by apptie

안녕하세요 터틀! 이번 미션 리뷰이 지토입니다! 

이번 미션은 협업이라 그런지 미션 자체는 이전 지하철 미션보다 비교적 간단했지만 안드로이드 및 백엔드 페어와의 의사소통으로 인해 시간이 많이 소모가 된 것 같습니다..
주문 취소나 포인트 유효기간 등 여러모로 구현하지 못한 기능이 있어 아쉽네요 ㅜㅜ

피드백해 주신 내용은 최대한 반영해보도록 노력하겠습니다!
잘 부탁드립니다! 🙇

하단에 간략하게 구현 내용에 대해 정리해놓도록 하겠습니다!

---

### 리뷰 범위 & 문서

[Rest Docs 문서 링크](http://13.125.207.155:8080/docs/docs.html)에서 API 명세를 확인하실 수 있습니다.

### 미션 진행 방식

미션을 진행하면서, 다음과 같은 경우를 제외하고는 최대한 뼈대 코드는 수정하지 않는 방향으로 진행했습니다.

- 조회 시 `Optional`로 변경
- `deprecated`된 메소드 변경

### 포인트 정책

- 포인트 유효 기간은 존재하지 않음
- 포인트 최대 사용 가능 금액은 해당 주문 총 금액의 10%
- 포인트 적립 금액은 해당 주문 총 금액의 10%

### 주문 로직 흐름

1. 주문 전 주문서를 확인하기 위해 장바구니에 담긴 상품 중 주문하고자 하는 장바구니 상품 ID 전달  `GET /cart-items/checkout`
2. 주문 `POST /orders`
3. 주문 시 전달한 사용 포인트가 회원이 가지고 있는 포인트보다 많은지 검증
4. 주문 시 전달한 사용 포인트가 포인트 최대 사용 가능 금액보다 같거나 적은지 검증
5. 주문 도메인(`Order`) 저장
6. 회원 포인트에서 사용한 포인트 차감
7. 주문한 장바구니 상품 삭제

### 인프라 관련

- 배포 자동화를 위해 젠킨스를 사용했습니다.
- 빌드 스크립트와 젠킨스 파이프라인 스크립트는 `/script` 디렉토리에 위치시켜 형상관리를 적용했습니다.

2023-06-03 04:49 UTC, begaonnuri requested changes
안녕하세요 지토!
전반적으로 잘 구현해주셨네요 👍🏻 몇가지 코멘트 남겼는데 확인해주세요.

2023-06-03 04:49 UTC, begaonnuri commented on src/main/java/cart/authentication/MemberStore.java
> +    private final ThreadLocal<Member> localMember = new ThreadLocal<>();
스레드로컬을 사용해주셨군요! 사용자를 스레드 로컬로 관리했을때 어떤 장점이 있으셨나요?

2023-06-03 04:49 UTC, begaonnuri commented on src/main/java/cart/configuration/PolicyConfiguration.java
> +public class PolicyConfiguration {
ENUM 타입이고 복잡한 정책이 있는것도 아닌데 빈으로 관리하신 이유가 있을까요?

2023-06-03 04:49 UTC, begaonnuri commented on src/main/java/cart/configuration/WebMvcConfig.java
> +                .allowedOrigins("*")
지금처럼 클라이언트가 웹 프론트나 모바일로 명확한 상황에선 해당 Origin을 명시적으로 지정해주는 것이 좋지 않을까요?

2023-06-03 04:49 UTC, begaonnuri commented on src/main/java/cart/configuration/WebMvcConfig.java
> +                memberStore());
매번 인스턴스를 생성해서 사용하는 경우가 아니라면 빈으로 관리하는건 어떨까요? 불필요한 의존성도 제거할 수 있을 것 같아요.

2023-06-03 04:49 UTC, begaonnuri commented on src/main/java/cart/configuration/WebMvcConfig.java
> +    }
`WebMvcConfig`이 빈을 등록하는 책임까지 너무 많은 책임을 갖는게 아닐까요?

2023-06-03 04:49 UTC, begaonnuri commented on src/main/java/cart/configuration/resolver/AuthMember.java
> +    boolean required() default true;
지금은 애노테이션 지정 여부로 확인하니 불필요한 필드는 제거하는게 어떨까요?

2023-06-03 04:49 UTC, begaonnuri commented on src/main/java/cart/configuration/resolver/CheckoutArgumentResolver.java
> +    public Object resolveArgument(
`@RequestParam` 대신 이렇게 처리해주신 이유가 있을까요? 프레임워크가 해주는 일을 상당 부분 구현하신것같아요.

2023-06-03 04:49 UTC, begaonnuri commented on src/main/java/cart/domain/Member.java
> +        return new Member(this.id, this.email, this.password, this.point.add(earnedPoints));
캡슐화가 잘 되어있네요 👍🏻

2023-06-03 04:49 UTC, begaonnuri commented on src/main/java/cart/domain/Money.java
> +    }
전반적으로 불변으로 잘 유지해주셨네요 👍🏻 

다만 int와 혼용되는 부분이 있는데 이런 경우 에러 발생 없이 캐스팅 과정에서 은연중에 오차가 생길 위험이 있지 않을까요? 이런 경우 디버깅도 어렵고 돈과 관련된 부분이라 치명적일 수 있을 것 같아요.

2023-06-03 04:49 UTC, begaonnuri commented on src/main/java/cart/dto/response/CheckoutResponse.java
> +
포인트 계산은 핵심 비즈니스 로직이기 때문에 도메인이나 서비스 영역에서 처리하는게 어떨까요? Response DTO에서 로직이 이루어지는 것에 대해 어떻게 생각하시나요?

2023-06-03 04:49 UTC, begaonnuri commented on src/main/java/cart/exception/AuthenticationException.java
> +        }
두 예외는 공통으로 메시지를 처리하지 않으셨는데 지토만의 기준이 있을까요?

2023-06-03 04:49 UTC, begaonnuri commented on src/main/java/cart/exception/ControllerExceptionHandler.java
>          logger.info("", ex);
`예외`라는 상황은 기본적으로 일반적인 상황은 아니지 않을까요? 더 상위 레벨의 로그를 남겨보면 어떨까요? 

https://www.tutorialspoint.com/log4j/log4j_logging_levels.htm

2023-06-03 04:49 UTC, begaonnuri commented on src/main/java/cart/ui/api/OrderApiController.java
> +public class OrderApiController {
API 스펙은 클라이언트 개발 크루와 미리 정하신걸까요? 소통 과정이 궁금합니다!

2023-06-03 06:34 UTC, apptie commented on src/main/java/cart/authentication/MemberStore.java
> +    private final ThreadLocal<Member> localMember = new ThreadLocal<>();
저는 다음과 같은 장점을 느껴 `ThreadLocal`을 사용했었습니다!

- 제네릭을 적용해 `MemberArgumentResolver`에서 사용자 정보를 전달받기 위한 과정 중 타입 캐스팅을 생략할 수 있었습니다.
- 자원을 등록하고 해제하는 코드를 통해 동작 과정을 명확하게 표현할 수 있다고 느꼈습니다.

다만 답변드리면서 좀 애매하다고 느낀 부분이 있었습니다.

- `ThreadLocal`이 가질 수 있는 위험성을
- `Thread`와 관련해 고려하지 못한 문제가 발생할 수 있음

그래서 지금은 또 `ThreadLocal`보다는 `@RequestScope`가 낫나? 싶기도 하네요..

2023-06-03 06:58 UTC, apptie commented on src/main/java/cart/configuration/PolicyConfiguration.java
> +public class PolicyConfiguration {
정책이 추가되거나 변경되는 경우, 코드의 변경 범위를 `Service`가 아닌 `Configuration`으로 제한하고 싶었습니다.

다만 지금 생각해보면 정책이 간단해서 `enum`을 사용한 건데, 빈으로 관리하는 상황이 상당히 어색하네요..

지금과 같이 정책이 간단한 상황에서 정책이 추가되거나 복잡해지는 등 요구사항이 변경될 경우 `enum`으로 관리하던 정책 자체가 변경될 가능성이 높을 것 같습니다..
`enum`을 빈으로 관리한다는 것 자체도 `enum`의 특성상 다른 빈과 이질적이기도 해서 지양해야 할 것 같네요 ㅜㅜ

빈으로 관리하던 부분을 리펙토링 하도록 하겠습니다!

2023-06-03 07:08 UTC, apptie commented on src/main/java/cart/configuration/WebMvcConfig.java
> +                .allowedOrigins("*")
넵 명시적으로 지정해주는 것이 더 좋을 것 같습니다!
이 부분은 일단 빠르게 적용하고 나중에 적용하려고 했는데 누락한 것 같습니다...
리펙토링 하도록 하겠습니다!

2023-06-03 07:17 UTC, apptie commented on src/main/java/cart/configuration/WebMvcConfig.java
> +                memberStore());
말씀해주신 대로 빈으로 관리하기 좋아 보입니다.
`enum`을 빈으로 관리한 것도 그렇고 빈으로 관리할 대상을 적절히 선택하지 못했네요..ㅜㅜ

말씀해주신대로 리펙토링 하도록 하겠습니다!

2023-06-03 07:26 UTC, apptie commented on src/main/java/cart/configuration/WebMvcConfig.java
> +    }
`Interceptor`를 등록할 때 관련된 빈도 명시해주면 좋겠다 싶었는데, 
말씀해주신대로 `Spring MVC` 관련 설정을 처리하는 책임을 지닌 `WebMvcConfigurer`가 빈을 등록하는 책임까지 갖는 건 너무 과한 책임을 갖게 된 것 같습니다..

리펙토링 하도록 하겠습니다!

2023-06-03 07:27 UTC, apptie commented on src/main/java/cart/configuration/resolver/AuthMember.java
> +    boolean required() default true;
말씀해주신 대로 사용하지 않는 필드는 제거하도록 하겠습니다! 감사합니다!

2023-06-03 08:25 UTC, apptie commented on src/main/java/cart/configuration/resolver/CheckoutArgumentResolver.java
> +    public Object resolveArgument(
`@Checkout` 애노테이션을 통해 조금 더 가독성을 높일 수 있지 않을까 싶어서 시도해봤습니다.
지금 보면 썩 좋은 접근 방법은 아니었던 것 같습니다..

`@RequestParam + Converter` 방식으로 리펙토링 하겠습니다!

2023-06-03 09:20 UTC, apptie commented on src/main/java/cart/dto/response/CheckoutResponse.java
> +
앗..말씀해주신 바가 맞습니다! 이 부분은 그냥 돌아가게만 하고 나중에 수정해야겠다 싶었는데 리펙토링을 까먹었네요 ㅜㅜ

`Response DTO`에서 비즈니스 로직을 수행하는 것은 지양해야 한다고 생각합니다..
리펙토링 하도록 하겠습니다!

2023-06-03 09:32 UTC, apptie commented on src/main/java/cart/ui/api/OrderApiController.java
> +public class OrderApiController {
넵 개발 이전에 API 스펙을 결정하는 방식으로 진행했었습니다! 
개발 이후 API 스펙은 최대한 변경하지 않으려고 했는데, 계속 개발하면서 조금씩 스펙이 변경되기는 하더라고요...

다음과 같은 과정으로 API 스펙을 결정했습니다!

1. 클라이언트 측에서 필요한 기능 & UI 공유
2. 백엔드 측에서 기초적인 API 스펙 정의 후 공유
3. 팀 회의를 통해 API 스펙 확정
4. 개발을 진행하며 변경 사항이 발생할 경우 팀 회의를 통해 API 스펙 변경

2023-06-03 09:36 UTC, apptie commented on src/main/java/cart/exception/ControllerExceptionHandler.java
>          logger.info("", ex);
클라이언트 측의 잘못인 400번대의 경우에는 애플리케이션의 문제가 아니니 `info`로 충분하다고 판단했었습니다.
다만 말씀하신 것처럼 `정상적인 흐름`은 아니니, `info`로 처리하기에는 조금 애매하네요..

`warn`을 사용하는 방식으로 리펙토링 하도록 하겠습니다!

2023-06-03 09:48 UTC, apptie commented on src/main/java/cart/exception/AuthenticationException.java
> +        }
왠만하면 공통으로 메세지를 처리하는 것을 기준으로 두고, 하나의 예외 메세지로 표현하기도 애매하고, 별도의 예외로 분리하기도 애매한 경우에만 위와 같이 외부에서 예외 메세지를 주입받는 식으로 진행하고 있었습니다.

다만 이 경우에는 `InvalidTokenFormat`으로 표현하기에는 어울리지 않는 상황이 있네요...
(Basic 토큰이 아닌 경우 / Basic 토큰 형식이 아닌 경우)

해당 부분 리펙토링 하도록 하겠습니다!

2023-06-03 10:18 UTC, apptie commented on src/main/java/cart/domain/Money.java
> +    }
말씀해주신 부분은 생각하지 못한 부분이네요..

일단 로직 상 소수점이 나오지 않도록 처리하고, `Money`에서 `int`를 반환할 때 `intValue()`가 아닌 `intValueExtract()`를 통해 `int`가 아닐 경우 예외가 발생하도록 리펙토링 하도록 하겠습니다!

2023-06-03 14:05 UTC, apptie commented on src/main/java/cart/authentication/MemberStore.java
> +    private final ThreadLocal<Member> localMember = new ThreadLocal<>();
`@RequestScope`를 사용하는 방법으로 리펙토링을 진행했습니다!

2023-06-03 14:41 UTC, apptie commented
안녕하세요 터틀! 
리뷰를 받을 수 있는 마지막 미션이라서 최대한 빨리 제출하려고 하다 보니 놓친 부분이 많아, 많이 미흡한 상태로 제출했었네요..ㅜㅜ

남겨주신 피드백 모두 적용했으며, `EC2`에서 적용하던 운영 환경용 `application-prod.yml`을 `git submodule`을 통해 관리하도록 변경했습니다.

리펙토링을 하다가 궁금한 점이 생겼는데, 밑에 남겨놓도록 하겠습니다!
다시 한 번 잘 부탁드립니다! 🙇

## 질문

현재 제 코드는 `Interceptor`에서 `MemberRepository`를 통해 `Member`를 조회하고 있습니다.
그러다보니 현재는 `웹 요청 / 응답` 전후에서 `Repository`에 접근하고 있는 상황인데, 이 상황이 상당히 어색하게 느껴졌습니다.

그래서 이를 어떤 식으로 처리할지 고민하다가 그나마 떠올린 방식은 

- 서비스에 대한 프록시 객체를 빈으로 등록하고, 컨트롤러에서 서비스를 호출할 때 내부적으로 실제 `Service`의 파라미터로 `Repository`로 조회한 `Member` 전달
- `Service`의 파라미터에 `AuthInfo & Member`를 갖는 별도의 객체를 전달하고, `AOP`를 통해 `Service`의 파라미터를 꺼내 `Repository`에서 조회한 `Member`를 별도의 객체에 세팅

이었습니다.
다만 이 방식도 좀....애매한 적용하지는 않았습니다.

그래서 현업에서는 어떤 방식으로 토큰을 통해 인증한 사용자의 정보를 `DB`에서 조회하는지 궁금합니다!

2023-06-05 11:36 UTC, begaonnuri commented
### MemberRepository 질문

말씀해주신 2가지 방법 모두 간접적으로 우회하는것이지 사실상 `MemberRepository`를 의존하고 있는 구조는 동일하다고 생각됩니다. 

아마 Controller -> Service -> Repository의 의존 관계가 익숙해서 어색하게 느껴지셨을 것 같아요. 만약 회원팀이 따로 있는 경우를 생각해보죠. 이땐 MemberRepository가 아닌 회원팀의 API를 요청하는 빈을 사용하게 될 거에요. 이건 괜찮게 느껴지시나요?

두 가지 방법은 내가 관리하는 데이터베이스에 회원 정보가 있는지, 외부 팀에서 관리하는 데이터베이스의 회원 정보가 있는지의 차이 일 뿐이지 사실상 구조는 유사합니다. 저는 관리하는 데이터베이스에 회원 정보가 있다면 지금 구조도 크게 문제될 건 없어보이네요.

2023-06-05 11:39 UTC, begaonnuri approved these changes
리뷰 잘 반영해주셨네요 지토!
코드만 봤을땐 이미 잘 해주셔서 머지해도 충분할 것 같네요.
이번 미션은 여기서 머지하겠습니다.

코멘트는 조금 더 논의해보면 좋을 것 같은데요, 코멘트에 답변 달아주시고 DM 주시면 다시 확인해보겠습니다.
레벨2도 고생 많으셨습니다!

2023-06-05 11:39 UTC, begaonnuri commented on src/main/java/cart/application/CartItemService.java
> +        Money moneyCondition = PointDiscountPolicy.DEFAULT.calculatePointCondition(totalPrice);
리팩토링 잘 해주셨네요 👍🏻 

지금도 잘 해주셨지만 지토가 얼만큼 추상화할 것이냐에 따라 `DEFAULT` 정책을 드러내지 않을 수도 있을 것 같아요.

```suggestion
        Money earnedPoints = PointEarnPolicy.calculateEarnPoints(totalPrice);
        Money moneyCondition = PointDiscountPolicy.calculatePointCondition(totalPrice);
```

이렇게 되면 추후 새로운 정책이 추가되거나 조건에 따라 정책을 다르게 지정하더라도 변경되는 범위가 `calculateXX()` 함수로 한정될 수 있을 것 같네요.

2023-06-05 11:39 UTC, begaonnuri commented on src/main/resources/logback-spring.xml
> +  <appender name="FILE-ERROR" class="ch.qos.logback.core.rolling.RollingFileAppender">
이런 경우 로컬에서도 파일이 남지 않나요?

그래서 일반적으로 profile에 따라 로컬, 테스트 환경인 경우 console appender만 사용하도록 하고 지토가 지정해준 prod와 같이 배포환경에서는 file appender를 사용하기도 한답니다!

2023-06-05 11:39 UTC, begaonnuri commented on src/test/java/cart/application/CartItemServiceTest.java
> +class CartItemServiceTest {
Service 영역에 `@JdbcTest`를 사용해주신 이유가 있나요?

지금은 외부 컴포넌트가 데이터베이스만 있지만 서비스 영역에선 메시지 큐, 이메일 서비스, MMS 서비스 등 다양한 컴포넌트와 통합이 이루어질 수 있습니다. 어떤 테스트 애너테이션을 붙이면 좋을까요?

2023-06-05 11:39 UTC, begaonnuri commented on src/test/java/cart/application/CartItemServiceTest.java
> +        assertThat(actual).hasSize(2);
테스트의 데이터셋이 `data.sql`로 분리되어있군요. 그리고 TestFixtures까지 구현해주셔서 테스트 영역의 코드는 훨씬 깔끔해진 것 같아요.

하지만 이 테스트를 처음 읽는 팀원은 어떻게 파악하게 될까요? 사람마다 다르겠지만 일반적으로 이런 흐름일 것 같아요.

1.  테스트 상단으로 이동해 `@Sql` 애너테이션을 확인한다.
2. 없는 것을 확인하고 resources 디렉터리에 있는 `schema.sql` 또는 `data.sql` 파일을 확인한다.
3. 어떤 데이터가 생성됐는지 확인한 후 테스트로 돌아온다.
4. Fixture로 지정되어있는 것을 확인하고 MEMBER_A가 정의된 곳을 확인한다.
5. sql 파일로 지정된 데이터와 비교한다.

반면에 해당 테스트 메서드 내에서 데이터를 셋업한다면 장황해지고 테스트의 given 영역이 길어지겠지만 이를 읽는 팀원은 파일 이동 없이 단순히 테스트 메서드를 읽어나가기만 하면 됩니다.

드리고 싶은 말은 깔끔한 테스트가 항상 정답은 아닐 수 있습니다. 이미 잘 작성해주셔서 모든 테스트를 이렇게 변경하기엔 과할것같아요. 추후 미션에선 이렇게도 한번 시도해보세요! 정답이 없는 영역이라서 지토만의 답을 만들어가보시면 좋을 것 같아요.

2023-06-05 11:39 UTC, begaonnuri commented on src/test/java/cart/integration/OrderIntegrationTest.java
> +    @DisplayName("주문을 세 번 한 뒤, 주문 목록 조회를 요청한다.")
전반적으로 테스트도 꼼꼼하게 잘 작성해주셨네요 👍🏻

2023-06-05 11:39 UTC, begaonnuri commented on src/main/java/cart/configuration/resolver/CheckoutArgumentResolver.java
> +    public Object resolveArgument(
Converter 없이 `@RequestParam`만 붙여도 `/cart-items/checkout?ids=1,2,3`와 같은 형태로 요청 받을 수 있는걸로 알고있는데 이렇게 하면 잘 안되셨었나요?

2023-06-05 11:39 UTC, begaonnuri commented on src/main/java/cart/authentication/MemberStore.java
> +    private final ThreadLocal<Member> localMember = new ThreadLocal<>();
`@RequestScope`가 낫다고 생각하신 이유는 뭘까요? 전 개인적으로 ThreadLocal이 더 낫다고 느껴지네요 ㅎㅎ

2023-06-05 11:39 UTC, begaonnuri commented on src/main/java/cart/ui/api/OrderApiController.java
> +public class OrderApiController {
논의 순서만 봤을땐 잘 해주신것 같네요 👍🏻

API 스펙을 먼저 합의하게 된 덕분에 양쪽에 병렬적으로 작업을 진행할 수 있었겠군요!

2023-06-05 11:39 UTC, merged

2023-06-05 15:03 UTC, apptie commented on src/main/java/cart/authentication/MemberStore.java
> +    private final ThreadLocal<Member> localMember = new ThreadLocal<>();
제가 `ThreadLocal`에서 `@RequestScope`로 변환한 이유는 주로 방어적인 목적이 큰데, 설명드리자면 다음과 같습니다!

### 1. `Tomcat`의 멀티 스레드 애플리케이션 & ThreadLocal에 대한 이해 부족
제가 알기로 `ThreadLocal`은 `Thread 단위`로 로컬 변수를 할당하는 기능으로 알고 있으며, `Tomcat`은 멀티 스레드를 지원해주는 것으로 알고 있습니다.

제가 아는 것은 이 정도 수준이라, 멀티 스레드 환경에서의 `ThreadLocal`을 사용했을 때 발생할 수 있는 문제점을 파악할 수가 없다는 생각이 들었습니다. 
구글링을 하면서 찾아봤는데, `주의해서 사용해야 한다` 정도의 정보밖에는 찾지 못했습니다...

그래서 다음과 같이 생각했습니다.

- 어처피 매번 요청이 올 때마다 `Authorization` 헤더로 사용자 인증을 하니 `Request` 단위로 사용자 정보를 해제해도 상관 없을 것 같다.
- `Spring MVC`에서 `Request Scope`에 대한 기능을 지원해주기 때문에, 스프링에서 제공하는 검증된 기능이므로 `ThreadLocal`보다 조금 더 안정적일 것 같다.

### 2. 직접 명시적으로 자원을 해제할 필요가 없음

이전에 `ThreadLocal`에 대한 장점으로 `명시적으로 자원을 해제하기 때문에 개인적으로 가독성이 좋은 것 같다`고 말씀드렸는데, 여기서 떠올리게 된 의문입니다.

`ThreadLocal`의 특징 상 메모리 누수와 데이터의 정확성을 유지하기 위해 사용 후 반드시 명시적으로 자원을 해제해야 합니다.
개인적으로 할당하고 해제하는 과정을 스스로 작성하는걸 선호하기는 하지만, 오히려 명시적으로 자원을 해제해야 할 정도로 위험하다는 생각이 들었습니다.

물론 `Interceptor`에서 `afterCompletion()`에서 `ThreadLocal`의 자원을 해제하기 때문에 이런 일이 발생하지는 않을 것 같지만, `현 시점에서의 ThreadLocal 용도를 대체할 수 있고, 생성과 해제를 스프링에서 처리해주는 기능이 있는데 굳이 ThreadLocal을 써야하나? `라는 의문이 들어 `@RequestScope`로 변경하게 되었습니다.

2023-06-05 15:16 UTC, apptie commented on src/main/java/cart/configuration/resolver/CheckoutArgumentResolver.java
> +    public Object resolveArgument(
피드백을 보고 다시 확인해봤습니다.

이전에는 `java.lang.IllegalStateException: Cannot convert value of type - ` 예외가 발생했는데, 지금은 말씀해주신 대로 그냥 요청받을 수가 있네요...
제가 뭔가 `@RequestParam` 대신에 `@RequestBody`를 쓴건지 `List`대신에 클래스를 넣었던건지..아무튼 이상한 코드를 작성한 것 같습니다..
별도로 프로젝트를 생성해서 테스트까지 해본건데 부끄럽네요 ㅜㅜ

`@RequestParam`에 대한 학습도 더 해야 할 것 같습니다...피드백 감사합니다!

2023-06-05 15:23 UTC, apptie commented on src/main/java/cart/ui/api/OrderApiController.java
> +public class OrderApiController {
감사합니다!

2023-06-05 15:31 UTC, apptie commented on src/main/java/cart/application/CartItemService.java
> +        Money moneyCondition = PointDiscountPolicy.DEFAULT.calculatePointCondition(totalPrice);
오 말씀해주신 부분은 떠올리지 못했네요!

말씀하신대로 `enum`에서 해당 메소드를 호출할 때, 메소드 내부에서 직접 해당 정책을 지정해주는 편이 더 좋을 것 같습니다!

제 경우 이를 해결하기 위해서 정책을 사용하는 행위를 인터페이스로 추상화하고, 구현체에서 `PolintDiscountPolicy.DEFAULT`를 사용하는 방법밖에는 떠오르지 않아서 이와 같이 고정해버리는 식으로 리펙토링을 진행했고, 정책이 변경될 때 마다 해당 정책을 사용하는 모든 코드가 영향을 받는다는게 좀 찝찝했었는데 왜 이런 방법을 떠올리지 못했나 싶네요..

정말 감사합니다!

2023-06-05 15:43 UTC, apptie commented on src/main/resources/logback-spring.xml
> +  <appender name="FILE-ERROR" class="ch.qos.logback.core.rolling.RollingFileAppender">
넵 로컬에서도 파일로 남는 바람에 로컬 경로에 대한 로그는 .gitignore에 등록하는 식의 임시방편을 사용했었습니다.

말씀해주신 대로 `springProfile` 태그를 활용해서 `profile`에 따라 특정 `appender`를 사용할 수 있도록 설정할 수 있었을 것 같습니다!
뭔가 알기는 하는데 자꾸 활용을 못하는 경우가 생겨서 좀 아쉽네요..ㅜㅜ 

현업에서 로그 사용 방법에 대해 알려주셔서 감사합니다!

2023-06-05 15:52 UTC, apptie commented on src/test/java/cart/application/CartItemServiceTest.java
> +class CartItemServiceTest {
`Service`는 핵심 비즈니스 로직을 호출하는 곳이기 때문에 중요하다고 판단해 통합 테스트를 진행해야 한다고 느꼈고, 지금 당장은 `DB 연동`만을 신경쓰면 되고, 빠른 테스트를 위해  `@JdbcTest`를 사용했습니다.

다만 말씀해주신 것처럼 `다양한 컴포넌트와 통합`된다는 의미로는 `@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)`를 사용하는 것이 제가 의도한 바와 더 부합할 것 같습니다!

지금 이렇게 작성하고 보니 `통합 테스트`라는 의미가 작성해주신 `다양한 컴포넌트와 통합을 테스트하기 위함`이라는 생각이 들었습니다. 
사실상 제가 한 테스트는 통합 테스트가 아닌 어정쩡한 단위 테스트 비슷한 테스트가 되었네요...
이전부터 계속 이런 식으로 서비스에 대한 통합 테스트를 진행했었는데, 말씀해주시지 않으셨다면 한참 뒤에 알아차리거나, 아니면 아예 못 알아차릴수도 있었을 것 같습니다..
정말 감사합니다!

2023-06-05 16:20 UTC, apptie commented on src/test/java/cart/application/CartItemServiceTest.java
> +        assertThat(actual).hasSize(2);
확실히 말씀해주신 협업의 영역에서의 가독성을 고려하지 못했었습니다.

미션을 계속 진행하면서 대부분 페어 프로그래밍 단계에서 `Fixture`를 사용할 것인지, 더미 데이터를 사용할 것인지를 정하고 진행해서 가독성보다는 코드의 깔끔함을 위주로 테스트 코드를 작성했었습니다.
페어가 끝난 뒤 개별적으로 코드를 작성할 때에도 이미 정해놓은 규칙이 있어서 이후 페어의 코드를 분석할 때도 큰 불편함을 느낀 적은 없었습니다.

테스트 코드에 `Fixture`를 적용할지 고려할 시점에 `처음 본 팀원`이라는 가정을 해본 적이 없었는데, 예시로 흐름을 보여주시니 체감이 확 되네요..

다음부터는 꼭 고려해서 말씀해주신 대로 제 나름의 기준을 세워보도록 하겠습니다. 감사합니다!

2023-06-05 16:25 UTC, apptie commented on src/test/java/cart/integration/OrderIntegrationTest.java
> +    @DisplayName("주문을 세 번 한 뒤, 주문 목록 조회를 요청한다.")
감사합니다!

2023-06-05 17:17 UTC, apptie commented
어색하다고 느낀 이유는 확실히 말씀해주신 `Controller-Service-Repository`가 익숙하다는 점과, 해당 `Layer`를 벗어난 곳에서 `Repository`를 호출해 트랜잭션을 `MVC 외부`에서 호출한다는 느낌을 받았기 때문인 것 같습니다.

외부 API 같은 기능을 예시로 들어주시니 감을 잡은 것 같습니다.

트랜잭션 같은 부분도 `Interceptor`가 `Repositorty`를 의존하는 상태에서  `@Transcational`을 붙여도 되겠지만, 외부 API를 사용하듯이 `AuthService` 같은 사용자 인증용 서비스를 만들고 거기서 트랜잭션을 관리하도록 하고, `Interceptor`가 서비스에 의존하는 방식으로 개선할 수 있을 것 같습니다.

좋은 답변 감사합니다!

2023-06-10 00:38 UTC, begaonnuri commented on src/main/java/cart/authentication/MemberStore.java
> +    private final ThreadLocal<Member> localMember = new ThreadLocal<>();
이유를 갖고 사용하신건 좋네요! 말해주신 장단점도 합리적이지만 추가적으로 말씀드리면,

ThreadLocal의 경우 Spring Security에서 지토가 최초로 사용한 방식으로 사용하기도 해요.

그리고 Tomcat 서버에선 스레드 1개당 1개의 요청을 처리하지만 멀티스레드로 처리하게 되는 경우 @RequestScope의 빈을 여러 스레드에서 상태를 변경하기 때문에 오히려 스레드세이프 하지 않아서 위험할 수 있어요. ThreadLocal의 위험성을 어떤걸 말씀하신진 모르겠지만 오히려 더 안전할 수도 있습니다.

2023-06-10 00:39 UTC, begaonnuri commented on src/main/resources/logback-spring.xml
> +  <appender name="FILE-ERROR" class="ch.qos.logback.core.rolling.RollingFileAppender">
> 뭔가 알기는 하는데 자꾸 활용을 못하는 경우가 생겨서 좀 아쉽네요..ㅜㅜ

처음부터 잘 알수는 없죠 ㅎㅎ 전 이럴때 ChatGPT를 활용하거나 구글에 `~~ best practice`로 검색해보기도 하는 편이에요.