[2단계 - 주문 기능 구현] 하디(전동혁) 미션 제출합니다.
woowacourse/jwp-shopping-order pull request #22
Opened 2023-06-01 18:14 UTC by jundonghyuk

안녕하세요 현구막! 리뷰이 **하디**입니다 !

또 만나뵙게되어 영광입니다 :)

# 테이블 구조
![table](https://github.com/woowacourse/jwp-shopping-order/assets/84345881/d00f8555-dc28-49ca-8d1e-d3cab39a5b14)

#### 구현하면서 겪은 어려움에 대해 조언을 듣고 싶어서 몇가지 정리해봤습니다..!

## 1. Api가 Ui에 영향을 받아야 하는가 ?
저희의 Api는 여러 사용자가 사용하는(예를 들면 지도 api) 서버가 아니라고 생각합니다. 단 한명의 클라이언트가 존재하는데, 바로 Ui를 통해 사용자와 소통하는 프론트입니다. 그렇기에 Ui에 영향을 어느정도 받는다고 생각하는데요.
예를 들면 데이터 A와 데이터 B를 같은 화면 안에 뿌려야하는 경우가 많을 경우, 한 번의 요청으로 A와 B 데이터를 모두 내려주게 응답을 설계할 수 있습니다. 하지만, 데이터 A와 데이터 B가 결이다른? 데이터라면 저희는 A데이터만 내려주는 api, B데이터만 내려주는 api를 따로 설계해야할까요?
즉, 사용자에게 보여지는 화면은 신경쓰지 않고 응답을 설계해야 할까요? 
협업이 처음이라 고민이 들어 여쭤봅니다!
<br/>
## 2.

2023-06-03 02:58 UTC, Hyeon9mak requested changes
안녕하세요 하디, 오랜만에 뵙네요 😄 주문 기능 구현 고생하셨어요.
리뷰 시간이 여유가 있어서, 코멘트를 조금 많이 남겼어요. 👍 

> API 가 UI 에 영향을 받아야 하는가?

받으면 안되는 이유가 무엇일까요? 😄 
어떤 환경에서든 기술을 통해 제공하고자 하는 가치가 잘 전달되고,
비즈니스가 잘 수행되는게 1순위 인 것 같아요.
Application Programming Interface 에서 Interface 는 상호간 규약을 나타내는걸텐데요.
모두가 비즈니스를 최우선시한 규약을 잘 만들고 잘 지킨다면 문제될 건 없어보여요.

말씀처럼 사용군을 특정할 수 없을 정도로 사용자가 다양한 환경에서는 제공자가 API 명세를 주도해야겠죠.
사용자들의 입맛에 맞는 API 명세를 제공하다가 시간이 다 흐를테니까요.
(제공자가 생각하기에 적합한 형태로 API 를 명세할 수 있다는 장점도 있지만,
사용자가 너무 많기 떄문에 API 명세를 함부러 바꿀 수 없어서
자신이 명세한 API 에 자신이 갖혀버릴 수 있다는 단점도 있겠네요.)

사용자가 하나 뿐인 환경에서는 어떨까요? 사용자의 니즈에 꼭 맞춘 API 를 제공할 수 있기 때문에, 
사용자가 만족도를 높게 느낄 수 있는 API 를 전달할 수 있겠어요.
프론트가 원하는 API 명세로 개발이 진행된다면 
프론트가 서버보다 빠르게 주도적으로 개발이 가능하겠고, 더 유려한 화면이 그려지겠죠.
그게 더 좋은 제품을 만들고, 비즈니스에 기여하는 방법이라면 그렇게 하는게 올바른거 같아요. 😄 
그리고 저희는 그런 요청사항에도 빠르게 대응할 수 있는 서버를 만들기 위해 공부하는게 아닐까요 💪 

> 외래키 걸기 ?

FK 에 대한 생각이 변하셨군요 😄 
FK 는 당연히 걸 수 있는 환경에서는 거는게 좋겠는데요. (데이터 신뢰도가 올라가니까)
아무래도 말씀하신 상황이나 단점들 때문에 사용이 기피되는 것 같아요.
특히 바빠 죽겠는데 FK 제약조건에 걸려서 일이 진행되지 않는 상황을 경험해본다면... 😱 
때문에 제가 경험한 환경들에선 '기본 베이스는 걸지 않고, 정말 필요할 때 건다'... 가 기본 기조였어요.

FK 제약조건에는 위배되지만 그렇게 하는 것이 비즈니스적으로 더 가치있는 상황도 있고,
FK 제약조건을 통해 지키고자 하는 내용들이 애플리케이션 코드상에 녹아들면
꼭 테이블 스키마를 확인하지 않더라도 비즈니스 규칙을 확인할 수 있다는 장점도 생기는 것 같아요.

> 주문과 포인트(적립, 사용)와의 관계

말씀하신대로 현재 테이블 구조상에선 결합이 강해보여요. 
때문에 Order 의 로직도 복잡하게 느껴졌던거 같아요.
더 쉬운 유지보수를 위해선 개선이 필요하겠네요.
그러나 테이블 설계는 이미 완료되었으니, 테이블 구조를 변경하진 않았으면 좋겠어요.
데이터가 억 단위로 쌓이는 환경에서도 "테이블 구조가 마음에 안드니까 바꾸고 싶어." 라고 할 순 없어요.
테이블 구조를 변경하지 않고, 애플리케이션 상에서 주문과 포인트간 결합을 분리하는 경험을 하는게 좋겠어요.
(DB 테이블의 형상을 나타내는 객체와, 실제 비즈니스 로직을 수행하는 객체의 분리가 시작되겠네요 😄)

> 서비스가 서비스를 의존?

충분히 가능하고, 많이 쓰여요. 대신 가능하면 의존이 한 방향으로만 흐르는게 좋겠어요.
https://hyeon9mak.github.io/legacy-system-refactoring-techniques/#1-%EC%9D%98%EC%A1%B4%EC%84%B1%EC%9D%84-%ED%95%9C-%EB%B0%A9%ED%96%A5%EC%9C%BC%EB%A1%9C-%EC%A0%95%EB%A6%AC%ED%95%98%EB%9D%BC

주문시 포인트를 사용할 수 있긴 하지만, 포인트가 적립되는 것은 분명히 생명주기가 다르게 느껴지네요.
이 부분은 말씀하신 이벤트 발행을 통해 해소해봐도 좋겠네요. 

궁금하신 점 코멘트, DM 남겨주세요 🙇‍♂️

2023-06-03 02:58 UTC, Hyeon9mak commented on README.md
> +### 장바구니관리
여전히 꼼꼼한 요구사항 관리 👍

2023-06-03 02:58 UTC, Hyeon9mak commented on README.md
> +```
👍 👍 curl 을 남기는 것도 좋아 보여요 😄 
https://www.lesstif.com/software-architect/curl-http-get-post-rest-api-14745703.html

2023-06-03 02:58 UTC, Hyeon9mak commented on src/main/java/cart/ui/PageController.java
>      }
`ModelAndView` 를 반환하는 것도 좋아보여요.

2023-06-03 02:58 UTC, Hyeon9mak commented on src/main/java/cart/ui/api/CartItemApiController.java
>  public class CartItemApiController {
꼼꼼한 검증 👍 
`@Validated` 와 `@Valid` 의 차이는 무엇일까요?

2023-06-03 02:58 UTC, Hyeon9mak commented on src/main/java/cart/exception/handler/ControllerExceptionHandler.java
> +    }
예상치 못한 에러에도 대응되는 핸들러 👍 다만 사용자에게 다음 행동을 결정해줄 수 있으면 좋겠네요.
https://hyeon9mak.github.io/writing-helpful-error-messages/#%ED%95%B4%EA%B2%B0-%EB%B0%A9%EB%B2%95%EA%B3%BC-%EC%98%88%EC%8B%9C-%EC%A0%9C%EA%B3%B5

2023-06-03 02:58 UTC, Hyeon9mak commented on src/main/java/cart/exception/customexception/CartItemQuantityExcessException.java
> +}
커스텀한 예외 클래스가 생성될 때마다 `ControllerExceptionHandler`의 길이가 어마어마 해질 것 같네요..
현재 구조상 각 예외들은 에러코드만 다른 것 같은데요,
에러코드를 모아둔 enum class 를 사용하고, 생성자에 에러코드를 전달 받는 하나의 exception 클래스를 활용하는 방법도 있겠어요 🤔

2023-06-03 02:58 UTC, Hyeon9mak commented on src/main/java/cart/config/MemberArgumentResolver.java
>      public MemberArgumentResolver(MemberDao memberDao) {
arguments resolver 에서 dao 를 사용하는 것과 service 를 사용하는 것에는 각각 어떤 장단점이 있을까요?

2023-06-03 02:58 UTC, Hyeon9mak commented on src/main/java/cart/config/MemberArgumentResolver.java
>      public MemberArgumentResolver(MemberDao memberDao) {
arguments resolver 는 request 전달 과정 중 거의 마지막에 해당되는데요,
(filter -> dispatcher servlet -> interceptor -> arguments resolver)
인증 절차는 어떤 공간에서 진행하는게 좋을까요?

2023-06-03 02:58 UTC, Hyeon9mak commented on src/main/java/cart/config/MemberArgumentResolver.java
>          }
부정형으로 물어보거나 내부에서 exception 을 던지도록 할 수 있겠네요 😄

2023-06-03 02:58 UTC, Hyeon9mak commented on src/main/java/cart/dto/cartitem/CartItemQuantityUpdateRequest.java
> +    }
jackson 2.13 버전부터 request dto 에 no args constructor 가 꼭 필요하지 않더라구요.
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.13#no-constructor-deserializer-module

2023-06-03 02:58 UTC, Hyeon9mak commented on src/main/java/cart/dto/cartitem/CartItemResponse.java
- `final` 키워드를 붙여줄 수 있겠네요.
- `Long` 과 `long` 이 혼용되는 것 같은데 이유가 있을까요?

2023-06-03 02:58 UTC, Hyeon9mak commented on src/main/java/cart/application/CartItemService.java
>          cartItem.checkOwner(member);
`cart_item.member_id` 와 `cart_item.product_id` 를 한번에 물어볼 수 있지 않을까요?
영속화 대상에게 이정도 질의는 비즈니스 로직에 의존적이지 않게 느껴져요. 해도 괜찮을 것 같아요.

2023-06-03 02:58 UTC, Hyeon9mak commented on src/main/java/cart/application/CartItemService.java
> +    @Transactional(readOnly = true)
`@Transactional(readOnly = true)` 가 쓰이고 안쓰이고 혼용중인데요, 통일이 되면 좋겠어요.

2023-06-03 02:58 UTC, Hyeon9mak commented on src/main/java/cart/application/OrderService.java
> +        Timestamp createdAt = new Timestamp(calendar.getTimeInMillis());
계속해서 2 row 가 반복되고, '현재 주문 시간 구한다.' 라는 하나의 행위로 바라볼 수 있을 것 같아요.
메서드로 묶거나, 객체로 분리하기 용이해보이네요.

특히나 "현재 시간 주문을 구하는 방법을 변경하겠습니다." 라는 요구사항이 전달되었을 때
모든 클래스를 뒤지며 2개의 row 를 변경할 필요 없이
분리된 객체(클래스 파일)를 열어서 수정만 하면 되겠어요.

2023-06-03 02:58 UTC, Hyeon9mak commented on src/main/java/cart/application/OrderService.java
> +        return cartItems;
`cartItemDao` 로부터 `List<CartItem>` 를 받아온 다음 검증을 진행하면 쿼리 1회로 종료되지 않을까요? 🤔

2023-06-03 02:58 UTC, Hyeon9mak commented on src/main/java/cart/application/OrderService.java
> +    }
`deletAllIdIn` 등으로 시도해볼 수도 있겠어요.

2023-06-03 02:58 UTC, Hyeon9mak commented on src/main/java/cart/application/OrderService.java
> +                order.getCreatedAt().toString().split(" ")[0],
`order.getCreatedAt().toString().split(" ")[0],` 서비스 계층에서 알아야 할 정보일까요?

2023-06-03 02:58 UTC, Hyeon9mak commented on src/test/java/cart/integration/IntegrationTest.java
> +    }
모든 테스트 수행 전에 한번씩 비워준다면, 테스트 수행 후에 굳이 지워줄 필요는 없을 것 같아요 😄 
(혹은 반대로도)

2023-06-03 02:58 UTC, Hyeon9mak commented on src/test/java/cart/fixture/ProductFixture.java
> +            10L);
픽스쳐를 미리 만들어주신 덕분에 테스트 작성이 편리하겠네요 👍

2023-06-03 02:58 UTC, Hyeon9mak commented on src/test/java/cart/fixture/MemberFixture.java
> +    public static final Member 현구막 = new Member("hyeongumak@naver.com", "abcd");
😎

2023-06-03 02:58 UTC, Hyeon9mak commented on src/test/java/cart/domain/order/OrderTest.java
> +    private Member 현구막_멤버 = new Member(2L, "hardy", "1234");
😞

2023-06-03 02:58 UTC, Hyeon9mak commented on src/test/java/cart/domain/point/RatePolicyTest.java
> +    }
👍 👍 적립률이 얼마고, 그로 인해 이런 값이 나온다도 알려주면 좋겠네요.
그렇게 되면 적립률이 변경될 때 테스트가 일치하지 않고, 자동으로 유지보수 손길이 닿아야하는 테스트가 될 것 같아요 👍

2023-06-03 02:58 UTC, Hyeon9mak commented on src/main/java/cart/dao/cartitem/CartItemDao.java
> +public interface CartItemDao {
repository 와 dao 의 차이는 무엇일까요?
또, `CartItemDao` 인터페이스를 사용하는 사용처의 관심사는 무엇일까요? 저장하는 행위? 저장하는 방법?
`CartItemDao` 의 패키지 경로에 대해 하디의 생각을 공유해주세요.

2023-06-03 02:58 UTC, Hyeon9mak commented on src/main/java/cart/domain/cartitem/CartItem.java
> +        this.quantity = 1L;
수량도 포장할 수 있겠네요.

2023-06-03 02:58 UTC, Hyeon9mak commented on src/main/java/cart/domain/cartitem/CartItem.java
> +
id 를 이용한 동등성 부여 👍

2023-06-03 02:58 UTC, Hyeon9mak commented on src/main/java/cart/domain/order/Order.java
> +    private Long id;
주문도 동등성 부여가 가능하겠네요.

2023-06-03 02:58 UTC, Hyeon9mak commented on src/main/java/cart/domain/order/Order.java
> +    private List<OrderItem> orderItems;
final ?

2023-06-03 02:58 UTC, Hyeon9mak commented on src/main/java/cart/domain/point/RatePointPolicy.java
> +public class RatePointPolicy implements PointPolicy {
`OrderPoint` 와 달리 bean 으로 등록되었네요? 어떤 의사결정이 있었는지 궁금해요.

2023-06-04 05:49 UTC, jundonghyuk commented on src/main/java/cart/exception/customexception/CartItemQuantityExcessException.java
> +}
반영해보겠습니다 ! 저도 익셉션 핸들러를 작성하면서 비슷한 생각을 했었습니다..
이넘으로 관리하면 편하겠네요 ㅎㅎ

2023-06-04 06:41 UTC, jundonghyuk commented on src/main/java/cart/config/MemberArgumentResolver.java
>      public MemberArgumentResolver(MemberDao memberDao) {
`arguments resolver 에서 dao 를 사용하는 것과 service 를 사용하는 것에는 각각 어떤 장단점이 있을까요?`
현재 Arguments resolver는 헤더정보를 파싱해서 `Member`로 만들고 리턴해주면 되는 책임을 갖고 있습니다.
`MemberDao`나 `MemberService`에 의존하여 실제 존재하는 유저인지는 알 필요가 없다고 생각합니다.

그 이전 단계인 `Filter`나 `Interceptor`에서 검증하면 된다고 생각합니다. 
즉, 인증절차를 분리한다면 `Argument Resolver`에는 `DAO`든 `Service`든 의존할 필요가 없어집니다.

만약 이전의 구조와같이 `Argument Resolver`에서 인증 절차까지 진행한다면, Service를 의존하도록 하는 것이 좀 더 나을 것 같습니다.
`DAO`를 의존한다면, 현재 구조에선 `email`에 해당하는 맴버를 찾아온 후 `equals`로 검증을 하는데 이러한 검증 로직을 알 필요가 없을 것 같습니다. 
만약(이런일은 없겠지만..) 비밀번호가 1자리 틀려도 인증을 해준다고 가정하면.. DAO에서 사용자 정보를 꺼내고, 한 자리를 틀려도 인증 성공이 된게끔 만드는 것 자체가 비지니스 요구 사항이라고 생각하여 이런 작업을 인증을 해주는 곳에서 다 처리해야합니다.

그럴 바에 인증 서비스를 만들어서 그 안에서 일관되게 처리해주는게 좋을 것 같습니다..
현구막의 생각을 어떤가요 ?

2023-06-04 06:59 UTC, jundonghyuk commented on src/main/java/cart/config/MemberArgumentResolver.java
>      public MemberArgumentResolver(MemberDao memberDao) {
`arguments resolver 는 request 전달 과정 중 거의 마지막에 해당되는데요,
(filter -> dispatcher servlet -> interceptor -> arguments resolver)
인증 절차는 어떤 공간에서 진행하는게 좋을까요?`

**답변**: 필터가 어느 순간에 작동하는지는 알고있지만, 한 번도 써보지 않았습니다.
필터에서 basic 인증을 처리한다고 가정하면, 데이터베이스에서 사용자 정보를 가져와 유효한 사용자인지 확인을 해야합니다.
만약 일치하지 않는다면 예외를 던지는데요. 
필터에서 던진 예외는 `@ControllerAdvice`가 처리하지 못한다고 알고있습니다. 개인적으로는 이러한 이유 때문에 `Interceptor`에서 인증을 하는게 더 맞아보입니다. 

만약 토큰의 유효성만 검사한다면, 필터에서 진행해도 될 것 같은데. 어떨 땐 필터, 어떨 땐 인터셉터에서 진행하는지 명쾌한 해답을 못내리겠습니다.

그럼에도 제가 생각하는 차이는 다음과 같습니다.
필터에서 인증 -> 인증 실패시 예외를 던지면 `@ControllerAdvice`작동 안함 -> error-Page 리다이렉트 등으로 해결?
인터셉터에서 인증 -> 인증 실패시 예외 던지면 `@ControllerAdvice`작동 안함 -> 일관되게 예외처리 가능

2023-06-04 08:24 UTC, jundonghyuk commented on src/main/java/cart/config/MemberArgumentResolver.java
>          }
넵 가독성을 위해 부정형으로 만들어야겠네요

2023-06-04 08:24 UTC, jundonghyuk commented on README.md
> +### 장바구니관리
감사합니다 👍

2023-06-04 08:27 UTC, jundonghyuk commented on src/main/java/cart/ui/PageController.java
>      }
변경해보겠습니다:)

2023-06-04 08:34 UTC, jundonghyuk commented on src/test/java/cart/domain/order/OrderTest.java
> +    private Member 현구막_멤버 = new Member(2L, "hardy", "1234");
ㅜㅜ 고치겠습니다..!

2023-06-04 12:18 UTC, jundonghyuk commented on src/main/java/cart/application/CartItemService.java
> +    @Transactional(readOnly = true)
읽기 작업을 할 때는 readOnly 옵션을 걸어서 읽기 작업만 한다라는 것을 명시적으로 알려줄 수 있고, 데이터베이스 벤더에 따라 다르겠지만, 일반적으로 읽기전용으로 최적화한다고 알고있는데 혹시 잘못 알고있는 것일까요 ?

2023-06-04 12:28 UTC, jundonghyuk commented on src/main/java/cart/application/OrderService.java
> +        Timestamp createdAt = new Timestamp(calendar.getTimeInMillis());
감사합니다 한 번 만들어 봐야겠네요 ㅎㅅㅎ

2023-06-04 12:38 UTC, jundonghyuk commented on src/test/java/cart/integration/IntegrationTest.java
> +    }
`@Jdbctest`는 기본적으로 테스트 트랜잭셔널을 포함하고있고 `@SpringBootTest`도 definedPort나, randomPort를 사용하지 않으면 @Transactioanl 어노테이션을 통해 롤백이 가능한데
그럼 여기서 문제는 진짜 서버를 띄우는 `@SpringBootTest`에서 definedPort나 randomPort를 띄우는 테스트라고 생각합니다.
이 테스트들은 실제 서버를 띄워서 `RestAssured`를 사용한다면, 데이터를 되돌릴 수 없다고 알고 있습니다.(별도의 쓰레드로 띄우기 때문)

그렇다면 @BeforeEach로는 해결이 안되는 것 아닌가요??
@AfterEach로 통합 테스트의 마지막 테스트 메서드가 끝난 후 지워줘야 다른 테스트들이 영향을 안받을 것 같은데
잘못 알고있는 건지 궁금합니다!
(제가 생각하기에 @BeforeEach는 필요없다고 생각해서 지웠습니다!)

2023-06-04 12:41 UTC, jundonghyuk commented on src/test/java/cart/fixture/ProductFixture.java
> +            10L);
처음 이용해봤는데 꽤 좋았습니다.
그런데 한글로 작성하는건 좀 더 생각해봐야겠습니다.
한글로 작성하니 인텔리제이에서 자동완성을 잘 안해주더라고요 ㅠㅠ

2023-06-04 12:44 UTC, jundonghyuk commented on src/test/java/cart/domain/point/RatePolicyTest.java
> +    }
아 그렇군요 저는 적립률이 바뀌어도 일관되게 통과해야 된다고 생각했는데, 적립률이 변경되면 자동으로 유지보수해야하는 테스트가 되어 더 좋아지겠군요...

2023-06-04 12:46 UTC, jundonghyuk commented on src/main/java/cart/domain/order/Order.java
> +    private Long id;
아이디가 같은 주문은 같은 주문이니 그렇겠네요 :)

2023-06-04 12:58 UTC, jundonghyuk commented on src/main/java/cart/domain/order/Order.java
> +    private List<OrderItem> orderItems;
final은 일종의 방어코드 같은 것인가요 ?
사실 필요성을 크게 못느끼겠어서 여쭤봅니다.
외부에서 해당 필드를 read할 순 있지만, write할 순 없는데요.

그렇다면 객체내부에서 필드값을 바꾸는 경우에만 값이 변하는데,
이러한 실수를 방지하기 위해서인가요 ?

final이 달려있으면 딱 봤을 때 이 값은 수정되면 안되는 값이구나를 누군가에게 알려줄 수 있다.
이게 가장 큰 장점일까요?

현구막은 바뀌면 안되는 모든 필드에 final을 붙이시는 편인지 궁금해서 여쭤봅니다.
파라미터로 넘어온 값이나 지역변수에도 final을 붙이는 경우를 봤는데 이는 어떻게 생각하시는지 궁금합니다.

가독성이 나빠진다 생각하여 저는 지양한다는 주의입니다...ㅠ

2023-06-04 13:09 UTC, jundonghyuk commented on src/main/java/cart/dao/cartitem/CartItemDao.java
> +public interface CartItemDao {
`repository 와 dao 의 차이는 무엇일까요?`

dao의 역할은 도메인보다는 데이터베이스에 영속화하는 것에 더 초점을 둔 것 같습니다.
이름자체도 Data Access Object인데, 저희 어플리케이션과 외부의 데이터베이스 사이에 위치하는 계층입니다.

제가 생각하는 repository는 데이터베이스보단, 도메인쪽에 더 가까운 느낌이라고 생각되는데요.
예를 들어 데이터베이스가 아니라, 컬렉션에 저장해도 repository라고 명명할 것 같습니다.

`CartItemDao 인터페이스를 사용하는 사용처의 관심사는 무엇일까요? 저장하는 행위? 저장하는 방법?`
이 인터페이스를 사용하는 사용처는 저장하는 방법에 대해는 알 필요가 없을 것 같습니다.
그것을 알면 너무 깊이 아는 것이라고 생각합니다.
그렇기에 저장한다라는 기능만 알고 있으면 됩니다.

`CartItemDao 의 패키지 경로에 대해 하디의 생각을 공유해주세요.`
위의 질문들에 답변을 하다가 생각을 정리해봤습니다.
인터페이스의 위치는 `repository`라는 패키지를 따로 만들어 두고, 구현체들은 dao패키지에 그대로 놔두는 것입니다.

`CartItemDao`를 의존하는 서비스들은 이들이 dao패키지 즉 데이터베이스에 영속화한다는 것을 몰라도됩니다.
컬렉션으로 저장하던지 데이터베이스에 저장하던지 알 필요가 없다고 생각합니다.
하지만 구현체들은 dao 패키지에 있어야된다고 생각되는데요. 구현체들은 외부의 데이터베이스를 활용해  영속화한다는 것을 알고있기 때문이죠

사실 entity를 따로 설계해서 controller -> servcie -> repository -> dao의 의존관계를 만들어
dao에서는 entity를 반환하고 레포지토리에선 그들을 조합하여 도메인을 반환하는 흐름이 되었으면 좀 더 깔끔했을 것 같습니다.
현재 dao가 persistence layer에서 dao가 사용하는 엔티티라는 개념과 저희 비지니스 로직의 도메인이 같이 사용되어 혼동이 생기는 것 같습니다.

현구막의 생각도 듣고싶습니다!

2023-06-05 04:14 UTC, jundonghyuk commented on src/main/java/cart/dto/cartitem/CartItemQuantityUpdateRequest.java
> +    }
바인딩되는 과정을 좀 공부해야봐야겠네요 !
좋은 키워드 제공 감사합니다 ㅎㅎ

2023-06-05 05:42 UTC, jundonghyuk commented on README.md
> +```
한 번 읽어보고 적용해보겠습니다 :)

2023-06-05 06:44 UTC, jundonghyuk commented on src/main/java/cart/application/CartItemService.java
>          cartItem.checkOwner(member);
현재 약간 복잡하게 된 원인이 장바구니에 담긴 아이템에 해당하는 상품이 삭제되었을 때 장바구니를 조회하면 해당 장바구니가 상품이 삭제되어서 조회가 안되는 문제 때문이었습니다.

Outer Join을 통해서 상품이 삭제되어도 유저가 담은 장바구니 CartItemDao를 통해 조회가 되도록 변경하였습니다.

2023-06-05 06:45 UTC, jundonghyuk commented on src/main/java/cart/application/OrderService.java
> +        return cartItems;
이 문제 또한 위와 마찬가지입니다!
```
현재 약간 복잡하게 된 원인이 장바구니에 담긴 아이템에 해당하는 상품이 삭제되었을 때 장바구니를 조회하면 해당 장바구니가 상품이 삭제되어서 조회가 안되는 문제 때문이었습니다.

Outer Join을 통해서 상품이 삭제되어도 유저가 담은 장바구니 CartItemDao를 통해 조회가 되도록 변경하였습니다.
```
코드를 수정했습니다!

2023-06-05 07:14 UTC, jundonghyuk commented on src/main/java/cart/application/OrderService.java
> +                order.getCreatedAt().toString().split(" ")[0],
그렇네요 오직 응답을 위한 포맷팅이니 리스폰스 내부에서 아는게 좀 더 바람직한 것 같습니다!

2023-06-05 07:21 UTC, jundonghyuk commented on src/main/java/cart/domain/point/RatePointPolicy.java
> +public class RatePointPolicy implements PointPolicy {
RatePointPolicy는 다양해 질 수 있고 OrderPoint는 다양한 PointPolicy를 그때 그떄 마다 사용하여 조립해주기 위해서 빈으로 등록을 안했던것 같습니다. 현재상황에서는 빈으로 등록해도 될 것같아요

2023-06-05 07:46 UTC, jundonghyuk commented on src/main/java/cart/exception/handler/ControllerExceptionHandler.java
> +    }
블로그 잘 읽어봤습니다! 감사합니다
그 다음 행동을 정의해줘도 좋겠군요
다만, 특정 예외메시지를 안드로이드 크루들과 이미 정해놔서 그 부분 빼고 수정해보겠습니다!

2023-06-05 07:46 UTC, jundonghyuk commented on README.md
> +```
시도해보겠습니다 :)

2023-06-05 07:48 UTC, jundonghyuk commented on src/main/java/cart/dto/cartitem/CartItemResponse.java
통일성 있게 `Long`으로 변경하였습니다.
이 정도 객체로 감싸는 것은 성능상 크게 문제되지 않을것같은데 어떻게 생각하시나요?

2023-06-05 07:48 UTC, jundonghyuk commented on src/main/java/cart/application/OrderService.java
> +    }
시도해보겠습니다!

2023-06-05 08:23 UTC, jundonghyuk commented on src/main/java/cart/ui/api/CartItemApiController.java
>  public class CartItemApiController {
`@Valid`는 ArgumentResolver에서 해주며 예외로 MethodArgumentNotValidException
를 던집니다 ArgumentResolver에서 해주는 만큼 컨트롤러에서 밖에 사용을 못한다고 알고 있습니다.
`@Validated`는 AOP기반으로 메서드의 요청을 가로채어 검증을 수행한다고 알고있는데요.
그렇기에 컨트롤러를 제외하고도 서비스 등 다양한 곳에서 활용할 수 있다고 알고있습니다.
예외로는 ConstraintViolationException를 던지는 것으로 알고있습니다..!!

혹시 틀린부분이 있을까요 ?

2023-06-05 08:25 UTC, jundonghyuk commented on src/main/java/cart/domain/cartitem/CartItem.java
> +        this.quantity = 1L;
시간이 부족하여 추후 반영하도록 하겠습니다 ㅠㅠㅠ

2023-06-05 08:27 UTC, jundonghyuk commented
안녕하세요 현구막
하디입니다..

6시까지 시간이 부족하여 리뷰를 다 반영하지 못했습니다.
반영한곳에는 답변을 달아놨습니다! 감사합니다
추후에 반영하겠습니다 ㅠㅠ

**1. 포인트 서비스의 분리**
**2. 값 포장**

위 두가지 작업을 더 해보겠습니다.
감사합니다.

2023-06-06 07:51 UTC, Hyeon9mak commented on src/main/java/cart/ui/api/CartItemApiController.java
>  public class CartItemApiController {
👍 👍

2023-06-06 07:51 UTC, Hyeon9mak commented on src/main/java/cart/exception/handler/ControllerExceptionHandler.java
> +    }
넵넵 안드로이드 크루들에게 전달할 메세지로 정해봐도 좋겠네요.

2023-06-06 07:57 UTC, Hyeon9mak commented on src/main/java/cart/config/MemberArgumentResolver.java
>      public MemberArgumentResolver(MemberDao memberDao) {
> arguments resolver 에서 dao 와 service

하디가 말씀해주신 예시 상황에 대해선 개인적으로 
`Member` 객체가 해당 로직을 갖게 되면 dao 와 service 모두 동일하지 않을까.. 싶긴하네요 😄 
저는 개인적으로 service 사용을 선호하는 편이에요.

1. 인증에 필요한 정보를 가져오는 출처가 어딘지 알려주기 싫다.
2.  인증에 필요한 정보를 가져올 떄 부가적인 데이터도 조립해서 가져와야 할 수도 있다.

특히 2번은 계정관련 시스템이 복잡하게 얽혀있을 때 service 계층을 통해, arugments resolver 가 이를 몰라도 되게 만들 수 있겠죠.
현재 구조에서는 큰 역할을 수행하지 않는 계층을 한번 스킵한다는 장점을 느낄 수도 있겠네요.

2023-06-06 08:02 UTC, Hyeon9mak commented on src/main/java/cart/config/MemberArgumentResolver.java
>      public MemberArgumentResolver(MemberDao memberDao) {
> filter interceptor

필터에서 `@ControllerAdvice` 가 동작하지 않는 이유는 무엇일까요! (hint: spring mvc)

사실 '인증인가' 라는 행위와 spring mvc 구조가 공학적으로 "여기서 해야하는게 좋아, 나빠" 정해진 건 아니라고 생각해요.
취사선택하면 되는 부분이라 하디의 의견을 여쭤보았어요 😄 
대부분은 filter 에서 인증인가를 모두 수행하거나, filter 에서는 인증, interceptor 에서 인가를 결정하는 것 같은데요,
filter 에서 인증을 먼저 수행하는 것에 어떤 장점이 있을지도 한번 고민해보면 재밌겠네요.

2023-06-06 08:03 UTC, Hyeon9mak commented on src/main/java/cart/dto/cartitem/CartItemResponse.java
네네 웹프로그래밍에서 요거 감싸는 걸로 회사에 타격이 생기진 않죠 😄 👍

2023-06-06 08:04 UTC, Hyeon9mak commented on src/main/java/cart/application/CartItemService.java
> +    @Transactional(readOnly = true)
하디가 남겨주신 코멘트를 잘 이해하지 못했는데요.. 😢 
조회만 수행하는 메서드에 `@Transactional(readOnly = true)` 이 있을 때도 있고 없을 때도 있어서 남긴 코멘트였어요.

2023-06-06 08:14 UTC, Hyeon9mak commented on src/test/java/cart/integration/IntegrationTest.java
> +    }
- 식당에 도착한 학생들은 컵을 사용하기 전 무조건 컵을 세척 후 사용한다. 사용한 컵은 그냥 자리에 제자리에만 둔다.
- 식당에 도착한 학생들은 컵을 곧바로 사용한다. 사용한 컵은 무조건 세척 후 제자리에 둔다.

학생들은 동일하게 깨끗한 컵을 사용하게 되지 않을까요 😄

2023-06-06 08:15 UTC, Hyeon9mak commented on src/test/java/cart/fixture/ProductFixture.java
> +            10L);
대신 그만큼 영어로 작성된 코드들 사이에서 뛰어난 가독성을 갖기도 하죠 ㅎㅎ
장단이 있는 것 같아요.

2023-06-06 08:16 UTC, Hyeon9mak commented on src/test/java/cart/domain/point/RatePolicyTest.java
> +    }
넵, 귀찮긴 하겠지만 그만큼 중요하게 확인해야하는 값이라는 뜻이 될테니까요 😄

2023-06-06 08:19 UTC, Hyeon9mak commented on src/main/java/cart/dao/cartitem/CartItemDao.java
> +public interface CartItemDao {
👍 👍 저도 repository 는 domain 에, dao 는 db 에 가까운 개념들이라고 생각해요.
저는 극단적으로 `repository 에 저장해서 영속화한다.` 까지를 로직이라고 봐서, domain 계층에 두는 걸 선호합니다.
아래와 같이 되겠네요.

```
domain
ㄴ Paper
ㄴ Book
ㄴ PaperRepository
ㄴ BookRepository

persistence
ㄴ PaperDao
ㄴ BookDao
```

2023-06-06 08:24 UTC, Hyeon9mak commented on src/main/java/cart/domain/order/Order.java
> +    private List<OrderItem> orderItems;
> - 실수를 방지하기 위해서인가요 ?
> - 누군가에게 알려줄 수 있다, 이게 가장 큰 장점일까요?

👍 👍 💯 

네 저는 대부분 붙이는 편이고, 자바가 아닌 코틀린을 사용중이라 자동으로 `final` 키워드를 사용중이에요.
방어 코드를 작성하는 건 나 자신의 실수를 막기 위함도 있지만, 동료들의 실수를 막기 위함이기도 한 것 같아요.
내 의중과 다르게 코드를 해석하고 변경시켜선 안될 값을 변경시켜 사용하는 로직을 추가할 수도 있겠구요.
하디의 말씀대로 5글자 추가되는 것 대비 효과가 미미하다고 볼 수도 있겠네요~

2023-06-06 08:59 UTC, Hyeon9mak requested changes
안녕하세요 하디, 피드백 반영 고생하셨어요.
월요일 리뷰요청 마감 때문에 급하게 진행된 느낌이 드네요.
한번 더 request changes 를 드릴테니 
여유있게 이전 피드백도 다시 확인해보시고, 리팩터링 해보시면 좋겠어요 😄 
답변이나 추가로 질문주셨던 코멘트에도 제 생각 남겼습니다. 함께 확인해주세요.
궁금하신 점 코멘트, DM 남겨주세요 🙇‍♂️

2023-06-06 08:59 UTC, Hyeon9mak commented on build.gradle
> +    implementation 'mysql:mysql-connector-java:8.0.33'
`applicaiton.properties` 에 스프링 프로필 별로 사용할 데이터베이스를 나누어주시면 실행하기 훨씬 용이하겠네요 😄 👍

2023-06-06 08:59 UTC, Hyeon9mak commented on README.md
> +##### Response
<img width="1314" alt="image" src="https://github.com/woowacourse/jwp-shopping-order/assets/37354145/7ac38ef6-c14e-4309-a043-a15c3549f27d">

오, 덕분에 편리하게 확인할 수 있게 되었네요 😄 👍

2023-06-06 08:59 UTC, Hyeon9mak commented on src/main/java/cart/application/AuthService.java
> +    }
사소하게 생각해볼 부분인데, 인증절차에 있어서 꼭 사용자에게 
"회원정보가 없습니다.", "비밀번호가 틀렸습니다." 를 구분지어 알려줄 필요가 있을까요?
보안상 이점을 살리기 위해 통일시키는 방법은 어떤지 고민해봐도 재밌을거 같아요.

2023-06-06 08:59 UTC, Hyeon9mak commented on src/main/java/cart/config/MemberArgumentResolver.java
> +        String email = emailAndPasswordWithDecryption[0];
오, arguments resolver 가 정말 하나의 역할만 수행하게 되었네요 😄 👍

2023-06-06 08:59 UTC, Hyeon9mak commented on src/main/java/cart/dto/order/OrderRequest.java
> +    @PositiveOrZero(message = "아이템을 1개 이상 주문해주세요.")
`@Positive` ?

2023-06-06 08:59 UTC, Hyeon9mak commented on src/main/java/cart/exception/customexception/ErrorCode.java
> +    ORDER_TOTAL_PRICE_UNMATCHED(HttpStatus.BAD_REQUEST, 3, "주문 가격과 상품 가격의 합이 맞지 않습니다. 확인 후 재주문 부탁드립니다."),
오, 한참 줄어들었군요 😄 👍

2023-06-06 08:59 UTC, Hyeon9mak commented on src/main/java/cart/exception/customexception/ErrorCode.java
> +    ORDER_TOTAL_PRICE_UNMATCHED(HttpStatus.BAD_REQUEST, 3, "주문 가격과 상품 가격의 합이 맞지 않습니다. 확인 후 재주문 부탁드립니다."),
각각의 에러 코드는 어떤 의도로 사용되나요?

2023-06-08 05:09 UTC, jundonghyuk commented on src/main/java/cart/config/MemberArgumentResolver.java
>      public MemberArgumentResolver(MemberDao memberDao) {
필터는 요청이 디스패쳐서블릿에 도착하기 전에 작동하는 것으로 알고 있습니다.
반대로 인터셉터는 디스패쳐서블릿에 요청이 도착 후 핸들러메서드를 실행 하기 전에 prehandle을 작동시키는 것으로 알고있습니다.

그렇기에 `@ControllerAdvice`는 디스패쳐서블릿에 의해 요청이 들어온 경우 처리하여 필터에서의 예외는 동작하지 않는다고 알고있습니다.
잘못된 부분이 있을까요 ?

2023-06-08 05:15 UTC, jundonghyuk commented on src/main/java/cart/application/CartItemService.java
> +    @Transactional(readOnly = true)
`CartItemServcie`에서 혹시 어디부분인지 알려주실 수 있나요? 조회용 메서드에는 이미 readOnly옵션을 건것 같은데 제가 볼 때는 안보여서요..!

2023-06-08 05:22 UTC, jundonghyuk commented on src/test/java/cart/integration/IntegrationTest.java
> +    }
저는 자기가 썼던 컵은 자기가 세척해야한다고 생각하는데요!
이미 다른 테스트들은 @Transactional이 걸려있어 다른 테스트들의 환경을 오염시키지 않습니다.

@SpringBootTest의 randomPort, definedPort를 사용하는 테스트들만 @AfterEach로
컵을 쓴 뒤 세척해주면 된다고 생각하는데요.

제가 생각하는 것은
- 식당에 도착한 학생들은 컵을 사용한 후 무조건 컵을 세척한 뒤 제자리에 둔다.

이 룰만 지켜진다면, 식당에 도착한 학생들이 컵을 사용하기전에 세척한다는 불필요한 작업을 안해줘도 된다고 생각합니다.
(저는 @SpringBootTest의 randomPort, definedPort를 사용하는 테스트들만 @AfterEach를 사용했습니다.)

제가 이해한게 현구막이 의도하신 내용과 같을까요..?

2023-06-08 05:46 UTC, jundonghyuk commented on src/main/java/cart/dto/order/OrderRequest.java
> +    @PositiveOrZero(message = "아이템을 1개 이상 주문해주세요.")
감사합니다:) 놓쳤었군요..

2023-06-08 05:47 UTC, jundonghyuk commented on src/main/java/cart/exception/customexception/ErrorCode.java
> +    ORDER_TOTAL_PRICE_UNMATCHED(HttpStatus.BAD_REQUEST, 3, "주문 가격과 상품 가격의 합이 맞지 않습니다. 확인 후 재주문 부탁드립니다."),
안드로이드와 소통하기위해 필요합니다.
앞단에서 에러코드로 화면 전환 등을 하기위해서 협의하여 맞췄습니다!

2023-06-08 05:53 UTC, jundonghyuk commented on src/main/java/cart/application/AuthService.java
> +    }
그렇군요 인증되지 않는다는 사실만 알려주고 왜 실패했는지는 알려주지 않는게 보안상 이점이 크겠네요!

2023-06-08 06:11 UTC, jundonghyuk commented on build.gradle
> +    implementation 'mysql:mysql-connector-java:8.0.33'
넵 테스트용 yml은 테스트패키지 밑에 따로 두었고 
프로덕션용 yml에서는 profile을 `dev`, `prod`두 개로 두었는데 뒤에는 배포용이라 `dev`만 푸쉬하겠습니다!

2023-06-08 08:30 UTC, jundonghyuk commented on src/main/java/cart/domain/cartitem/CartItem.java
> +        this.quantity = 1L;
현구막은 포장하는 기준이 있으신가요?
전 사실 필드 포장하는 것이 한눈에 안들어오더라고요.

검증을 해야하는 필드는 모두 포장하시는 편이신가요?

2023-06-08 08:53 UTC, jundonghyuk commented
안녕하세요 현구막 질문에 대한 답변 남겼습니다 !

주요 변경점은
- PointService분리
- 포인트 적립이 안되어도 주문은 가능하게 `Propagation = NESTED` 적용 포인트 적립 실패시 로깅 (대신 주문이 안되면 적립도 안됨)
- Repository, Dao 패키지 변경
- 인증 실패시 예외 통일

입니다. 좋은 하루되세용:)

2023-06-09 11:58 UTC, Hyeon9mak commented on src/main/java/cart/config/MemberArgumentResolver.java
>      public MemberArgumentResolver(MemberDao memberDao) {
하디가 말씀해주신 "디스패쳐서블릿에 의해 요청이 들어온 경우 처리하며, 필터에서의 예외는 동작하지 않는다" 의 원리, 원인이 무엇일까요?

2023-06-09 12:00 UTC, Hyeon9mak commented on src/main/java/cart/application/CartItemService.java
> +    @Transactional(readOnly = true)
다른 클래스에 대해 말씀드린거였는데, 추가해주셨네요 ㅎㅎ

2023-06-09 12:12 UTC, Hyeon9mak commented on src/test/java/cart/integration/IntegrationTest.java
> +    }
아하~ `OrderServiceTest` 를 보고 나니 이해가 되네요. 이런.. 제가 하디 의도를 늦게 파악했어요 🙏 
제 이야기의 의도는 "모든 테스트에서 beforeEach 로 클렌징을 진행할 경우 다른 테스트를 오염시키지 않는다." 였어요. 🙏 
현재는 `@Transactional` 어노테이션을 사용하는 테스트들에서는 별개로 데이터 클렌징을 진행하지 않아서 영향을 받게 되겠군요.

2023-06-09 12:12 UTC, Hyeon9mak commented on src/test/java/cart/integration/IntegrationTest.java
> +    }
현재 구조에서는 하디 말씀대로 afterEach 를 사용하는게 beforEach 보다 훨씬 편리해보여요!

2023-06-09 12:15 UTC, Hyeon9mak commented on src/main/java/cart/domain/cartitem/CartItem.java
> +        this.quantity = 1L;
검증에도 좋지만, 널리 쓰이는 값의 데이터타입이 변경되는 경험을 한 뒤로 포장하는 편이에요. entity 의 id  까지도...
가령 모든 entity id 의 데이터타입이 `Long` 에서 `String(UUID)` 로 변경될 때를 상상해보면 어떨까요? 😱

2023-06-09 12:32 UTC, Hyeon9mak approved these changes
안녕하세요 하디! 피드백 반영 고생하셨어요.
간단하게 고민해보시면 좋을 부분들 추가 코멘트 남겼습니다.
추가로 남겨주신 질문에도 모두 답변 남겼으니 확인해주세요 😄 

피드백도 잘 반영해주셨고, 미션 요구사항도 모두 충족된 것 같아 approve 합니다.
방학동안 푹 쉬시고, 팀 프로젝트 즐겁게 진행하시길 바랄게요. 💪 
고생많으셨습니다!

2023-06-09 12:32 UTC, Hyeon9mak commented on src/main/java/cart/domain/cartitem/CartItemRepository.java
> +    Optional<CartItem> findCartItemByMemberIdAndProductId(Long memberId, Long productId);
오.. 엄청나게 빠른 반영.. 잘 만들어두신 덕분에 유지보수가 쉬웠었나보군요 ㅎㅎ

2023-06-09 12:32 UTC, Hyeon9mak commented on src/main/java/cart/application/PointService.java
> +    }
트랜잭션 전파레벨 활용 👍 고민해보면 좋을 부분이 있어요.

`PointService` 를 의존하는 추가 로직이 생겨날 경우 트랜잭션의 전파레벨을 예측하기가 힘들어져요.
`PointService` 의 세부구현 내용을 모르는 동료 개발자들은 일반적인 전파레벨로 생각하고 사용할 수도 있구요.
혹은 포인트 적립 도중에 예외가 발생하면 현재처럼 로그를 남기는 것 외에 핸들링이 힘들다는 문제도 생기겠네요.

이럴 때 사용해보면 좋은 방법은 이벤트 발행일거 같아요.
주문과 포인트 적립에 대한 생명주기가 온전히 다르다고 바라보고,
`주문 완료` 라는 이벤트가 발행되면, 그 이벤트가 발생되길 주시하고 있던 리스너가
포인트 적립을 시작하는거죠.

2023-06-09 12:32 UTC, Hyeon9mak commented on src/main/java/cart/domain/cartitem/CartItem.java
>      }
(대부분 그럴리 없겠지만) "수량 기본 값은 5개" 라는 정책이 생긴다면, `Quantity` 와 `CartItem` 중 어떤 클래스를 먼저 열어보게 될까요?

2023-06-09 12:32 UTC, Hyeon9mak commented on src/test/java/cart/application/PointServiceTest.java
> +
꼼꼼한 테스트 👍

2023-06-09 12:32 UTC, merged