[2단계 - 주문 기능 구현] 이오(이지우) 미션 제출합니다.
woowacourse/jwp-shopping-order pull request #30
Opened 2023-06-02 11:13 UTC by LJW25

안녕하세요 검프, 이오입니다!
이번 미션은 처음으로 협업을 진행하며 빠르게 구현하는데에 중점을 두었습니다.
나름대로 리팩토링을 하긴 했는데 아직 부족한 부분이 (상당히…) 많이 보이네요. 🥹
계속 혼자 고민하는 것 보다는, 리뷰를 받으며 보완하는 편이 좋을 것 같아 리뷰요청드립니다 :)

Product, Member 와 CartItem 대부분의 기능들은 뼈대코드로, 꼭 필요한 부분을 제외하고는 수정하지 않았습니다. 리뷰시 참고해주시면 감사하겠습니다!

---

## 실행

- 배포한 서버는 [여기](http://43.200.169.154:8080/admin) 입니다.

- 서버로 배포를 진행하면서, application 설정은 보안을 위해 서버에서 별도로 관리하고 있습니다.
    프로젝트를 pull 하신 후 로컬에서 실행 시, resources 폴더에 아래의 내용으로 application.properties를 추가해주세요.
    
    ```
    spring.thymeleaf.cache=false
    spring.h2.console.enabled=true
    spring.h2.console.settings.web-allow-others=true
    spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL
    spring.datasource.driver-class-name=org.h2.Driver
    log.directory=${dir:./log}
    ```
    
- 테스트를 위한 더미데이터가 포함되어있습니다.
    rich@mail.com 계정에 31건의 주문 내역과 포인트가 부여되어있으니 필요시 해당 계정을 사용해 주시면 됩니다 :)
    
- 구현한 API 명세는 [여기](http://43.200.169.154:8080/docs/docs.html)서 확인할 수 있습니다.
    2단계 구현 내용은 “주문 API” 항목입니다.

2023-06-05 02:09 UTC, Livenow14 requested changes
안녕하세요 이오. 수고많으셨어요.,

몇가지 간단한 피드백 남겼으니 확인해주시고 궁금한 부분 있으면 코멘트 남겨주세요.

2023-06-05 02:09 UTC, Livenow14 commented on http/Test.http
> +Authorization: Basic YUBhLmNvbToxMjM0
인증키의 경우 foo.env.json 등에서 관리되어도 좋을 것 같아요 :)

2023-06-05 02:09 UTC, Livenow14 commented on src/docs/asciidoc/docs.adoc
> +
adoc.. 저도 참 즐겨쎴었는데 💯

2023-06-05 02:09 UTC, Livenow14 commented on script/build.sh
> +        kill -9 ${CURRENT_PID}
사용자 요청이 처리중이라면 어떻게 동작하게 되는걸까요?
키워드: graceful shutdown

2023-06-05 02:09 UTC, Livenow14 commented on README.md
> +
기능 요구사항이 아닌, 소프트웨어 요구사항(사용자 스토리 등등)도 적어주면 좋을 것 같아요. 

이오만의 문서를 만들어보면 좋겠네요 :)

2023-06-05 02:09 UTC, Livenow14 commented on src/main/java/cart/application/CartItemService.java
> +            throw new CartItemException.AlreadyExist(member, cartItemRequest.getProductId());
CartTiemException을 상속받게 작성되었어도 좋았겠네요!

2023-06-05 02:09 UTC, Livenow14 commented on src/main/java/cart/domain/pointmanager/DefaultPointManager.java
> +public final class DefaultPointManager implements PointManager {
Manager보단 Policy의 성격이 조금더 가깝게 느껴지네요 :) 
Mananger -> Policy 는 어떠락요?

2023-06-05 02:09 UTC, Livenow14 commented on src/main/java/cart/domain/pointmanager/DefaultPointManager.java
> +
책임을 나눠도 충분할 것 같아요

2023-06-05 02:09 UTC, Livenow14 commented on src/main/java/cart/domain/pointmanager/PointManager.java
> +}
계산 정책이 늘어나면 interface의 메서드도 늘어나게 되는 구조일까요?

2023-06-05 02:09 UTC, Livenow14 commented on src/main/java/cart/domain/Member.java
> +
이 경우엔 정적 메서드로 빼는건 어떨까요?!?

2023-06-05 02:09 UTC, Livenow14 commented on src/main/java/cart/ui/MemberArgumentResolver.java
> +    private void validateAuthorizationHeader(String header) {
해당 parameter에는 final이 붙여있지 않네요.
혹시 의도된 동작이었을까요?

2023-06-05 02:09 UTC, Livenow14 commented on src/main/java/cart/ui/MemberArgumentResolver.java
header에 잘못된 값을 입력했다면, 여기선 indexoutofboundsexception 여지가 있는걸까요?

2023-06-05 02:09 UTC, Livenow14 commented on src/main/java/cart/ui/CartItemApiController.java
> +    public static final String DELIMITER = ",";
외부에서 사용되는 상수값일까요?

2023-06-05 02:09 UTC, Livenow14 commented on src/main/java/cart/ui/ControllerExceptionHandler.java
>  }
logger를 쓰기위한 재정의 과정이였을까요?

2023-06-05 02:09 UTC, Livenow14 commented on src/main/java/cart/ui/ControllerExceptionHandler.java
> +        logger.info("", ex);
logger가 excpetion을 잡아먹게 작성되면 안됩니다. 

exception을 뱉을 때 작성되게 해주세요.

2023-06-08 10:43 UTC, LJW25 commented on src/main/java/cart/domain/pointmanager/DefaultPointManager.java
> +public final class DefaultPointManager implements PointManager {
저도 이름 지을 때 고민했던 내용이네요! Policy로 변경하였습니다 :)

2023-06-08 10:46 UTC, LJW25 commented on src/main/java/cart/ui/MemberArgumentResolver.java
> +    private void validateAuthorizationHeader(String header) {
앗 아닙니다! 해당 파일은 뼈대코드에서 수정하지 않아, 미처 확인하지 못했네요. 통일성을 위해 모두 final 추가하였습니다 :)

2023-06-08 10:50 UTC, LJW25 commented on src/main/java/cart/ui/CartItemApiController.java
> +    public static final String DELIMITER = ",";
`CartItemApiController` 내부에서만 사용되는 상수입니다. 접근제어자 private로 변경하였습니다.

2023-06-08 11:05 UTC, LJW25 commented on src/main/java/cart/domain/pointmanager/DefaultPointManager.java
> +
혹시 이 부분에서 책임을 나눈다는게 어떤 의미인지 여쭤봐도 될까요?🥲
 더 작은 단위의 클래스로 나누는 것인지, 아니면 다른 의미인지 여쭤보고싶습니다.

2023-06-08 11:07 UTC, LJW25 commented on src/main/java/cart/domain/pointmanager/PointManager.java
> +}
네 포인트와 관련된 계산이 늘어난다면 새로운 메서드가 필요할 것이라고 생각합니다. 만약 동일한 동작이지만 할인 등의 이유로 계산 비율이 달라지는 것이라면 해당 부분은 PointManager를 상속받는 객체 내에서 수행할 것 같습니다!

2023-06-08 11:10 UTC, LJW25 commented on src/main/java/cart/domain/Member.java
> +
이 경우는 생성자보다는 정적 팩토리 메서드가 더 적절하겠네요! 수정하였습니다 :)

2023-06-08 12:02 UTC, LJW25 commented on src/main/java/cart/ui/MemberArgumentResolver.java
적절한 Member가 존재하지 않을 경우 indexoutofboundsexception이 발생한다는 것을 발견하여 MemberDao에서 사용자 조회 시 get(0)이 아닌, 적절한 예외를 던질 수 있는 방식으로 수정하였습니다. 😀

2023-06-08 12:03 UTC, LJW25 commented on src/main/java/cart/ui/ControllerExceptionHandler.java
>  }
네 맞습니다. exception을 로그로 남기기 위해 위와 같이 사용하였습니다. 혹시 잘못 사용된 부분이 있을까요?🤓

2023-06-08 12:06 UTC, LJW25 commented on src/main/java/cart/ui/ControllerExceptionHandler.java
> +        logger.info("", ex);
혹시 더 구체적으로 설명해주실 수 있으실까요? exception을 뱉는다는 표현이 잘 이해가지 않습니다. 🥲
logger.info가 아닌 logger.error를 사용하도록 변경하였는데 이러한 방식을 의도하신게 맞으실까요?

2023-06-08 12:21 UTC, LJW25 commented on script/build.sh
> +        kill -9 ${CURRENT_PID}
현재의 설정 상에서는 만약 어플리케이션에서 처리중인 요청이 있더라도 강제 종료되게 구성되어있었습니다.
알려주신 키워드를 통해 [graceful shutdown](https://jaime-note.tistory.com/45)을 사용한다면 기존에 처리중이던 요청을 완전히 처리 한 후 종료되게 설정할 수 있음을 알게되었습니다!
실제 사용자가 어플리케이션을 사용한다고 가정한다면 이런 오류를 방지하는 것도 중요하겠네요. 감사합니다 😊

2023-06-08 12:37 UTC, LJW25 commented
안녕하세요 검프, 이오입니다!
이번주에 레벨인터뷰와 기획서 발표 준비가 겹치다 보니 리뷰 반영이 많이 늦어졌네요 😂

리뷰 주신 내용 반영하였습니다 :)
일부 이해가 잘 가지 않는 부분이 있어 코멘트 남겨놓았으니 확인해주시면 감사하겠습니다!

리뷰해주셔서 감사합니다. 좋은하루 되세요! 😄

2023-06-10 11:24 UTC, Livenow14 commented on src/main/java/cart/domain/pointmanager/DefaultPointManager.java
> +
각 Rate들을 책임으로 가지는 객체를 만들면 좋을 것 같다는의견이었습니다..!

2023-06-10 11:26 UTC, Livenow14 commented on src/main/java/cart/ui/ControllerExceptionHandler.java
> +        logger.info("", ex);
statck strace를 log에서 표출되게 하면 안된다는 피드백이었어요..!! 

throw new xxxExceptino("message", ex) 등등으로 trace를 exception이 뱉을 수 있게 하는 것이 사이드 이펙트를 많이 줄일 수 있어요 :)

2023-06-10 11:27 UTC, Livenow14 commented on src/main/java/cart/ui/ControllerExceptionHandler.java
>  }
아뇨..! 조금더 간단히 구현될 수 있지 않았을까? 하는 의문점이었지만. 이대로도 괜찮아요..!

2023-06-10 11:37 UTC, Livenow14 approved these changes
안녕하세요 이오! 리팩터링 잘해주셨어요 :) 

단위 테스트 코드가 조금 부족한 것 같아 추가적으로 말씀드리고 싶은 것은,향후 개발을 진행하게 될 떄 요구사항에 대한 단위테스트는 꼭 작성하시길 바란다는 점입니다 :) 

구현해야할 기능들이 많아지면 자신이 작성한 코드가 레거시가 되어 돌아오는데, 이 때 테스트가 작성되어 있으면 정말 편하거든요..! 

다른부분은 충분히 잘 구현하신 것 같아 이번 미션을 여기서 마무리 하겠습니다 수고많으셨습니다.

2023-06-10 11:37 UTC, Livenow14 commented on src/main/java/cart/domain/pointmanager/PointPolicy.java
> +}
향후에는 계산하라~ 라는 메세지를 던지도록 해봐도 좋을 것 같아요 :) 

인터페이스의 경우 최대한 public 메서드는 1개로 가지는게 이해하기가 쉽긴 하더라고요.. (쉽지 않고, 코드가 더 많아지지만요..)

2023-06-10 11:37 UTC, Livenow14 commented on src/main/java/cart/exception/CartItemNotFoundException.java
> +}
excpeiont 메세지의 경우 exception을 사용하는 객체에서 메세지를 주입해주는 방향이 수정이 더 쉬울 것 같아요 :)

2023-06-10 11:37 UTC, merged