[2단계 - 주문 기능 구현] 코코닥(이승용) 미션 제출합니다.
woowacourse/jwp-shopping-order pull request #45
Opened 2023-06-03 07:04 UTC by kokodak

안녕하세요 서브웨이! 코코닥이라고 합니다.

이번 미션에서는 단순 구현을 넘어서, 객체간의 의존성을 신경써보려 했습니다. 최대한 비즈니스를 이해하려고 했고, 이에 따라 도메인의 범위를 나눠서 의존성의 방향과 트랜잭션의 범위를 고려해보려고 노력했습니다.

따끔한 피드백 부탁드려요! 열심히 리팩터링 해보겠습니다. 잘 부탁드립니다 서브웨이 😁

(API 명세서는 따로 툴을 써서 협업하진 않았고 노션으로 적어가며 설계를 했었는데, 다소 지저분한 감이 있어서 http 파일로 간단하게 API를 정리해두었습니다!)

2023-06-04 06:01 UTC, joseph415 requested changes
안녕하세요. 코코닥!

1단계 미션 1차리뷰 남겼습니다.
각 도메인 객체 의존성에 집중해주셨다고 하셨는데, 잘 해주신 것 같습니다ㅎㅎ
궁금한 점있으면 DM 이나 코멘트 남겨주세요. 확인이 완료된 리뷰는 resolve conversation 눌러주시면 감사하겠습니다!

2023-06-04 06:01 UTC, joseph415 commented on http/cartitem.http
> +### 회원의 장바구니 목록을 조회한다
API 설계를 클라이언트와 논의했을 때, 평소 혼자 작성했을 때와 달라진 점이 있는지, 논의 경험에서 어떤 차이점을 느끼셨는지 알려주실수 있을까요~?

2023-06-04 06:01 UTC, joseph415 commented on src/test/resources/application.yml
> +    url: jdbc:h2:mem:testdb;MODE=MySQL
test database url이 현재 dev와 동일한데 구별됐으면 좋겠습니다~

2023-06-04 06:01 UTC, joseph415 commented on src/main/resources/application-prod.yml
> +    driver-class-name: ${RDS_DRIVER}
해당 환경 변수는 어디서 관리하나요?

2023-06-04 06:01 UTC, joseph415 commented on src/main/resources/application.yml
> +spring:
현재 profile 설정이 따로 없어서 default 로 시작이 되는데, spring active profile을 사용해서 기본 profile을 설정해줘도 좋을 것 같아요.

local 전용 profile을 만들어도 좋을 것 같고, 현재 작성해주신 dev를 local에서 공통으로 사용하시는거라면 dev로 active profile을 기본으로 설정해주세요

2023-06-04 06:01 UTC, joseph415 commented on src/test/java/cart/acceptance/AcceptanceTest.java
> +public class AcceptanceTest {
test context caaching 👍

테스트 커버리지가 100%에 가깝네요!

2023-06-04 06:01 UTC, joseph415 commented on src/test/java/cart/cartitem/infrastructure/persistence/dao/CartItemDaoTest.java
> +@DaoTest
💯

2023-06-04 06:01 UTC, joseph415 commented on src/main/java/cart/JwpCartApplication.java
> +        System.out.println("!!f!");
?!

2023-06-04 06:01 UTC, joseph415 commented on src/main/java/cart/cartitem/application/CartItemService.java
> +        List<CartItem> cartItems = cartItemRepository.findByMemberId(member.getId());
의도하신 건지는 모르겠지만ㅎㅎ service와 repositroy 에서 추상화 레벨이 나뉘진것 같아서 좋네요.
네이밍에서도 그런 것들이 들어난것 같아서 좋은것 같아요~
ex) service에서는 Member로 CartItem을 찾지만, 내부에서는 repositry단에서 id로 찾는것

2023-06-04 06:01 UTC, joseph415 commented on src/main/java/cart/cartitem/application/CartItemService.java
> +        return cartItems.stream().map(CartItemResponse::from)
CartItemResponse 을 리턴하도록 해주셨는데, 만약에 다른 서비스에서는 CartItem을 가져올땐, Service 를이용하는게 아니라, repository를 이용할텐데요. 그러면 중복 코드가 생겨나지 않을까요?

위의 상황이 아니더라도, response dto를 리턴하면 외부 서비스에서 해당 서비스를 의존하면, 클라이언트로 나갈 dto를 받아서 처리하게 되는건데 이게 맞는건지도 한번 생각해볼 수 있을 것 같아요!

저는 서비스에서 도메인 엔티티를 리턴해야한다고 생각하는데, 코코닥은 어떻게 생각하고 계신가요?

2023-06-04 06:01 UTC, joseph415 commented on src/main/java/cart/cartitem/application/CartItemService.java
>      public void updateQuantity(UpdateCartItemQuantityCommand command) {
Transaction이 빠진 이유가 있을까요?

2023-06-04 06:01 UTC, joseph415 commented on src/main/resources/schema.sql
> +    product_price INT          NOT NULL,
product_id 를 갖고있는데, product_price, image_url 등 다른 테이블의 정보를 갖고있을 필요가 있나요?
정규화가 잘 이루어지지 않은것 같습니다.

전체적으로 한번 확인해주세요. 정규화가 잘 이루어지지 않게되면, 데이터 정합성이 깨질 수 있습니다.

---

위의 코드 단에서 드리는 리뷰는 db 모델과 도메인 모델이 다를 수 있다는 전제로 리뷰남길게요

2023-06-04 06:01 UTC, joseph415 commented on src/main/java/cart/cartitem/domain/CartItem.java
> +    private final Long productId;
```
    private final Product product;
    private final Member member;
```

를 다 풀어서 써주셨는데요. 그렇게 하게 된 이유가 있나요? 내부에서 풀어야할 이유가 없는거 같아서요. 객체지향적인 코드를 작성하려면, 객체와 의존을 만들면 좋겠다고 생각듭니다.

혹시 cartItem 패키지에서는 product 를 직접참조 하지 않기 위해 객체 의존을 없앤거라면, id만 갖고있도록 하면 좋을 것 같아요.

그리고 추가 질문이 있는데요!

CartItem에 Member를 참조해야하나요~? Member당 장바구니가 하나로 알고있는데요.
```
Cart {
  Member 
  List<CartItem>
}
```
이게 맞는 형태가 아닌가 해서요!

2023-06-04 06:01 UTC, joseph415 commented on src/main/java/cart/cartitem/infrastructure/persistence/dao/CartItemDao.java
> +@Dao
👍

2023-06-04 06:01 UTC, joseph415 commented on src/main/java/cart/cartitem/domain/CartItem.java
>  public class CartItem {
나중에 List<CartItem> 을 사용하는 도메인로직이 생긴다면, 일급컬렉션을 만들 수도 있을 것 같습니다~!

2023-06-04 06:01 UTC, joseph415 commented on src/main/java/cart/coupon/domain/CouponType.java
> +public interface CouponType {
CouponType이라고 되어있어서 enum 으로 생각하고 있었는데요. 인터페이스로 전략으로 주입하는거라면, 네이밍을 다르게가면 어떨까 하는데요ㅎㅎ 어떻게 생각하시나요?! 아니면, enum으로 만들어서 할 수 있을 것 같고요ㅎㅎ

다른 네이밍으로는 다음과같이 chat gpt가 추천해주네요ㅋㅋ
```
CouponStrategy: 쿠폰 전략 패턴을 적용하는 클래스입니다.
CouponApplicabilityStrategy: 쿠폰 적용 가능성에 대한 전략을 다루는 클래스입니다.
CouponValidationStrategy: 쿠폰 유효성을 확인하는 전략을 다루는 클래스입니다.
CouponAvailabilityStrategy: 쿠폰의 유효성과 적용 가능 여부를 판단하는 전략을 다루는 클래스입니다.
CouponApplicationStrategy: 쿠폰 적용에 대한 전략을 다루는 클래스입니다.
```

2023-06-04 06:01 UTC, joseph415 commented on src/main/java/cart/coupon/domain/CouponValidator.java
> +    private void validateMultipleApply(List<CartItem> cartItems, List<Coupon> coupons) {
메서드 네이밍이 모호하다고 느끼는데요. 
1. 구매하기 전에 하나의 쿠폰이 여러 상품에 중복돼서 적용되는것을 validate하는 것인지
2. 하나의 상품에 여러 쿠폰이 중복적용되는것을 막는것인지 
애매하다는 생각이 들었습니다!..

테스트를 보면, 하나의 물품에 여러 쿠폰이 적용되는것만을  막는 메서드임을 알 수 있긴 한데요. 이름만 보면 한번에 파악할 수 없는것 같아서요. readme에 요구사항이 없어서 헷갈리는것 같기도 하네요..

1번 기능은 따로 없어도 되는건가요~?

메서드 시그니처를 의미가 좀 더 명확히 전달되게 변경해도 좋을 것 같습니다!

2023-06-04 06:01 UTC, joseph415 commented on src/main/java/cart/coupon/domain/RateDiscountPolicy.java
> +    public int calculatePrice(int price) {
금액 관련한 로직은 BigDecimal을 사용하는게 좋습니다! 부동소수점들어보셨나요?

2023-06-04 06:01 UTC, joseph415 commented on src/main/java/cart/coupon/domain/SpecificCouponType.java
> +public class SpecificCouponType implements CouponType {
productId 말고 다른 타겟쿠폰이 나온다면, SpecificCouponType 이라는 네이밍이 모호해질것 같습니다. 특정 상품관련 쿠폰이라는 네이밍으로 변경했으면 합니다!

2023-06-04 06:01 UTC, joseph415 commented on src/main/java/cart/coupon/infrastructure/dao/CouponDao.java
> +    public Long save(CouponEntity coupon) {
save 용어보단, insert를 사용하는게 좋을 것 같습니다. save는 repositroy에서 쓰는 용어로 update까지 의미를 내포하고 있어서요

2023-06-04 06:01 UTC, joseph415 commented on src/main/java/cart/coupon/infrastructure/repository/JdbcCouponRepository.java
> +    public Long save(Coupon coupon) {
dao에 save 리뷰와 이어지는데요ㅎㅎ save 내에서는 insert와 update를 같이 진행하면 되겠네요ㅎㅎ

2023-06-04 06:01 UTC, joseph415 commented on src/main/java/cart/order/application/OrderQueryService.java
> +        List<Order> orders = orderRepository.findAllByMemberId(memberId);
findByIdAndMemberId 에서는 validateOwner 를 하는데, 여기서는 안하고있네요. 전체조회는 validate가 누락된걸까요?

2023-06-04 06:01 UTC, joseph415 commented on src/main/java/cart/order/application/OrderService.java
> +                .map(cartItemRepository::findById)
findAll로 가져와도 좋겠네요ㅎㅎ

2023-06-04 06:01 UTC, joseph415 commented on src/main/java/cart/order/domain/OrderItem.java
> +    private final Long productId;
이전에 남긴것과 마찬가지로 외부참조는 id만 참조할 수 있도록 하면 좋을 것 같아요. Product내 모든 필드를 풀어서 갖고 있으면 객체 의존을 끊은 주된 이유가 퇴색되는것 같습니다.

2023-06-04 06:01 UTC, joseph415 commented on src/main/java/cart/order/domain/OrderItem.java
> +    private static int applyCoupon(CartItem cartItem, List<Coupon> coupons) {
쿠폰 validator에서 유효성 검사를 하잖아요.

validateMultipleApply에서 하나의 CartItem에 List<Coupon> coupons를 적용할 수 있을 때, exception을 던지는데, 여기서는 인자가 그렇게 받도록 되어있어서요.. 메서드 파라미터를, CartItem에 적용할 하나의 쿠폰을 주도록 하는게 어떨까요?

혹시 제가 잘못 이해한거라면, 코멘트 달아주세요!

2023-06-04 06:01 UTC, joseph415 commented on src/main/java/cart/order/domain/OrderValidator.java
> +    private final ProductRepository productRepository;
도메인 패키지 내에서는 저장소에 접근하는 로직을 없애면 하는데요!(비지니스 로직 흐름을 담당하는것은 서비스의 책임이라고 생각해서요!)

validate 파라미터로 에서 Prodcut를 받을 수 있을 것 같은데, 그렇게 변경할 수 있을까요?

2023-06-04 06:01 UTC, joseph415 commented on src/main/java/cart/product/infrastructure/persistence/dao/ProductDao.java
> +    public Long save(ProductEntity product) {
전체적으로 save 네이밍 한번 봐주세요!

2023-06-04 06:01 UTC, joseph415 commented on src/main/java/cart/coupon/domain/CouponValidator.java
> +    private void validateMultipleApply(List<CartItem> cartItems, List<Coupon> coupons) {
ex)
```
POST http://localhost:8080/orders
Authorization: Basic YUBhLmNvbToxMjM0=
Content-Type: application/json

{
  "cartItemIds": [1, 2],
  "couponIds": [1, 9]
}
```

2개 상품에 2개 쿠폰을 넣게되면, 
```
{
  "code": 404,
  "message": "한 상품에 하나의 쿠폰만 적용 가능합니다."
}
```
이런 에러가 떨어지는데, 쿠폰을 상품에 적용한다는 의미보단, 같은 종류 쿠폰을 여러개 못사용하는 에러가 내려오면 쫌 더 좋은 것 같기도 하네요! 아니면, 2가지 상황을 모두 잘 분류해서 그 상황에 맞게 내려줘도 좋을 것 같구요.

기능요구사항을 한번 정리해주시면, 다음 리뷰시 다시한번 확인해보겠습니다!

2023-06-04 06:01 UTC, joseph415 commented on src/main/java/cart/cartitem/domain/CartItem.java
>  public class CartItem {
Order 처럼 CartItem 을 리스트로 같는 Cart는 필요없는걸까요~? 유저가 관리하는 장바구니(Cart)가 있고, 그 안에 CartItem 리스트를 갖고있는 형태가 아닌가해서요!

2023-06-05 04:48 UTC, kokodak commented on http/cartitem.http
> +### 회원의 장바구니 목록을 조회한다
협업이라는 것을 이번에 처음 해봤는데, 별 마찰 없이 부드럽게 흘러가서 혼자 API 설계했을 때와 크게 다른 점은 없었던 것 같아요. 그나마 다른 점이 있었다면, API 설계를 하고 수정사항이 생겼을 때, 프론트엔드 크루분들에게 미리 물어보고 협의해서 최종적으로 수정한다는 점이 가장 달랐던 부분인 것 같습니다.

2023-06-05 06:15 UTC, kokodak commented on src/main/resources/application-prod.yml
> +    driver-class-name: ${RDS_DRIVER}
처음에는 서브모듈을 사용해서 관리를 하다가, 다른 사람이 볼 수는 없다곤 하지만 온라인 상에 민감한 정보가 올라가있다는게 마음에 걸려서, EC2 인스턴스 내부에서 export로 관리해주었습니다!

2023-06-05 06:30 UTC, kokodak commented on src/test/resources/application.yml
> +    url: jdbc:h2:mem:testdb;MODE=MySQL
로컬 환경과 테스트 환경 모두 인메모리로 돌리려고 하다보니 datasource url 이 겹치게 되었습니다. 근데 이게 겹치더라도 main 코드와 test 코드의 동작 환경이 격리된다는 것으로 알고 있는데, 혹시 구별되어야 할 이유가 있을까요?!

2023-06-05 07:01 UTC, kokodak commented on src/main/java/cart/JwpCartApplication.java
> +        System.out.println("!!f!");
앗 ㅋㅋㅋ 지우도록 하겠습니다

2023-06-05 08:07 UTC, kokodak commented on src/main/java/cart/cartitem/application/CartItemService.java
> +        return cartItems.stream().map(CartItemResponse::from)
이 부분은 고민을 좀 하긴 했는데요.
일단 현재 상황에서는 서비스에서 도메인 엔티티를 반환하는 방법도 좋다고 생각합니다. 현재 서비스 계층이 컨트롤러 계층의 DTO를 알고 있는 상황(CartItemResponse)이기 때문에, 사실 패키지 의존성 순환이 생기고 있긴 합니다. 따라서, 서비스의 반환 값을 도메인으로 설정해주어 패키지 의존성 순환을 끊어주는 방법도 존재할 것 같아요. 또한, 서브웨이 말씀대로 외부 서비스에서 `CartItemService`를 의존하고 있을 때, 클라이언트에 나갈 DTO를 반환받는 것이 의미적으로 이상한 느낌이기도 하죠.

다만, 다른 서비스에서 CartItem을 가져와야 한다면, Service가 아닌 Repository를 의존하여 가져오는 게 좋다고 생각합니다. CartItem 도메인을 가져오는 책임은 Service보다는 Repository의 책임에 가까운 것 같아요. 도메인의 컬렉션 같은 느낌이니까요. 따라서, 다른 서비스에서 클라이언트에 나갈 DTO를 받을 일은 없다고 생각하는 것 같아요.
또한, 서비스 계층에서 도메인 엔티티를 반환해버리면 계층화 아키텍처를 사용하는 이유가 좀 퇴색되는 느낌이 있을 것 같아요. Controller가 Service를 거치치 않고 바로 Domain 계층에 접근하는 것인데, 저는 이러한 코드들이 계층형 아키텍처의 일관성을 해친다고 생각해서요. 사실 Controller에서 영속성 계층에 바로 접근해서 필요한 것만 바로 가져오는 것도 괜찮은 방법일 수 있지만, 그럼에도 이런 식으로 사용하지 않는 이유는 계층간의 역할을 분리하기로 약속을 한거고, 개발자들은 이런 컨벤션을 지켜서 협업을 하고 있으니 오히려 혼란의 여지를 줄 수도 있다 생각합니다.
또 한가지 이유가 더 있을 것 같은데요, 지금 상황에 어울리는 문제는 아닌 것 같지만 Open Session In View의 문제가 있을 것 같아요. 서비스에서 도메인을 반환한다고 했을 때, 해당 도메인 엔티티가 불완전한 엔티티일 수도 있다는 문제가 있습니다. 서비스에서 컨트롤러로 넘어올 때는 이미 영속성 컨텍스트가 닫힌 상황이니까요. 따라서 영속성 컨텍스트가 열려있는 서비스 계층에서 응답 DTO에 필요한 필드들을 꽉 채워서 내보내는 것이 더 안전한 방법이라고 생각되네요!

2023-06-05 08:14 UTC, kokodak commented on src/main/java/cart/cartitem/application/CartItemService.java
>      public void updateQuantity(UpdateCartItemQuantityCommand command) {
뼈대 코드와 섞이다 보니 놓쳤던 것 같네요 🥲 붙여주도록 하겠습니다!

2023-06-06 12:59 UTC, joseph415 commented on src/main/java/cart/cartitem/domain/CartItem.java
> +    private final Long productId;
만약에 Product 의 변경과는 무관해야할 필드라면, Product 도메인과는 별개의 value object로 관리를 해야하는게 맞지 않을까 생각이 듭니다.

2023-06-07 01:59 UTC, kokodak commented on src/main/resources/schema.sql
> +    product_price INT          NOT NULL,
이건 제가 설명을 못드려서 그런 것 같아요. 다음 리뷰 요청때 최대한 다시 정리를 해서 올려보겠습니다 😭
일단 정규화는 일부러 깨지도록 설계했습니다. 장바구니에 담았을 시점의 상품과, 주문할 시점의 상품이 서로 다를 수 있기 때문인데요! 예를 들어, 장바구니에 상품을 담고 주문을 하기 전에 상품 판매자가 가격을 바꿔버린다면, 이를 클라이언트에게 알릴 필요가 있다고 생각했습니다. 따라서 이를 검증하기 위해 최신의 상품정보(product_id)와 장바구니에 담았을 시점의 정보들(product_price, image_url..)을 테이블에 같이 저장하게 되었습니다.

추가적으로, 테이블에서 장바구니에 담았을 시점의 정보들을 따로 저장하지 않고 product_id만 가지도록 한 뒤, 장바구니 화면에서 주문하기 버튼을 클릭했을 때, '프론트에서 당시 장바구니에 담겨있던 상품 정보들을 포함해서 요청을 보내주면 되지 않을까?' 라는 생각도 해봤었는데요. 하지만 사실 프론트 단의 정보들은 마음만 먹으면 쉽게 변형될 수 있다는 생각에, ‘프론트의 정보를 어디까지 믿을 수 있을까?’ 라는 의문이 생겼었습니다. 그래서 일단 서버 DB에서 장바구니에 담겼을 시점의 상품 정보까지 모두 관리해주는 것이, 리소스는 더 들더라도 확실한 검증이 될 것 같아서 product의 내용물을 다 까서 저정하는 방식을 최종적으로 선택하게 되었습니다. 서브웨이는 두번째 방법에 대해 어떻게 생각하시나요?

2023-06-07 12:18 UTC, kokodak commented on src/main/java/cart/cartitem/domain/CartItem.java
> +    private final Long productId;
> CartItem에 Member를 참조해야하나요~? Member당 장바구니가 하나로 알고있는데요.

생각해보니 Cart를 만들어서 Cart에 Member를 참조시키는 방법이 깔끔한 설계일 것 같네요. 변경해보도록 하겠습니다!

> 만약에 Product 의 변경과는 무관해야할 필드라면, Product 도메인과는 별개의 value object로 관리를 해야하는게 맞지 않을까 생각이 듭니다.

VO가 적절한 것 같습니다. 검증시에 동등성 비교를 해야하는데, VO 개념에 가장 알맞는 것 같네요. 감사합니다!

2023-06-07 12:23 UTC, kokodak commented on src/main/java/cart/coupon/domain/RateDiscountPolicy.java
> +    public int calculatePrice(int price) {
부동소수점.. 실수형 계산이 굉장히 위험하다는 건 알고 있었는데, 무지성으로 가격 계산에 double을 사용해버렸네요. BigDecimal을 사용하도록 변경하겠습니다!

2023-06-07 17:05 UTC, kokodak commented on src/main/java/cart/coupon/domain/CouponType.java
> +public interface CouponType {
아 그렇게 생각이 될 수 있겠네요. 확실히 Type이란 이름은 enum 같은 느낌이 드는 것 같아요. 일단 이 부분은 전략 패턴을 사용하려고 했어서 Strategy 로 네이밍을 변경해보겠습니다!

2023-06-07 17:09 UTC, kokodak commented on src/main/java/cart/coupon/domain/SpecificCouponType.java
> +public class SpecificCouponType implements CouponType {
동의합니다! 좀 더 명시적으로 네이밍을 바꾸도록 하겠습니다 😎

2023-06-08 02:55 UTC, kokodak commented on src/main/java/cart/order/domain/OrderItem.java
> +    private static int applyCoupon(CartItem cartItem, List<Coupon> coupons) {
서브웨이가 말씀하신대로, 한 상품에 2개 이상의 쿠폰이 적용될 수 없다는 룰이 있었습니다.
먼저 OrderItem.withCoupon() 이 실행되기 위해선 couponValidator를 먼저 거쳐야하기 때문에, OrderItem.withCoupon() 를 호출하는 시점의 List<Coupon>은 예외가 터질 수 없는 조건을 만족하는 상태라고 생각했습니다. 따라서 List<Coupon>을 OrderItem에 넘기고, '알아서 적용되는 쿠폰을 찾아서 적용해라!' 라는 의미로 저렇게 작성하게 되었습니다.

다만, 이런 방식은 couponValidator의 실행이 선행된다는 전제 안에서만 성립할 것 같습니다. 다른 개발자가 couponValidator를 실행하지 않고 그냥 OrderItem.withCoupon()을 실행할 수 있는 상황이기 때문에, 서브웨이가 말씀해주신대로 파라미터로 하나의 쿠폰만 주도록 하는게 더 안전해보여서 다시 수정하였습니다. 또한 적용되는 쿠폰을 찾는 책임은 OrderItem이 갖기 보다는 주문 서비스에서 가지는게 더 적절해보이기도 하네요 ㅎㅎ

2023-06-08 03:54 UTC, kokodak commented on src/main/java/cart/order/domain/OrderValidator.java
> +    private final ProductRepository productRepository;
> 비지니스 로직 흐름을 담당하는것은 서비스의 책임이라고 생각해서요!

동의합니다! 생각해보니 Validator는 단순 검증 도메인인데 자기 일에 집중하지 않는 모습이었던 것 같네요 ㅎㅎ.. 저장소 로직은 서비스로 옮기도록 하겠습니다!

2023-06-08 05:04 UTC, kokodak commented on src/main/java/cart/coupon/domain/CouponValidator.java
> +    private void validateMultipleApply(List<CartItem> cartItems, List<Coupon> coupons) {
제가 외부 클라이언트를 위한 기능요구사항에 너무 신경을 쓰지 않은 것 같네요 ㅠㅠ..
먼저 메서드명이 모호하다는 부분에 동의합니다. 중복 적용이 되는 주체가 빠져있어서 더 모호해진 것 같네요. 이 부분은 수정하도록 하겠습니다!
여기에 대략적으로 쿠폰에 대한 정책을 설명해보자면, 쿠폰의 종류는 크게 두 가지입니다. 하나는 모든 상품에 적용되는 '전체 상품 할인 쿠폰', 다른 하나는 특정 상품에만 적용되는 '특정 상품 할인 쿠폰' 입니다!
프론트와 협의를 해보면서, '장바구니 상품에 쿠폰 할인을 중복 적용할 수 있을까?' 를 고민했었는데 결과적으로는 '중복적용이 되면 안된다!' 로 협의가 됐습니다. 따라서 이를 구현하기 위해, 상품 입장에서 봤을 때 자신에게 적용될 수 있는 쿠폰이 2개 이상이라면 예외를 터뜨리도록 설계를 하게 되었습니다.
이런 룰에 따라서 생각해보면, '전체 상품 할인 쿠폰'을 사용한 경우에는 어떠한 '특정 상품 할인 쿠폰'도 적용할 수 없습니다. 전체 할인 쿠폰을 사용하면 이미 상품 전체에 한개의 쿠폰이 적용된 셈이니까요! 또한 그 역도 성립합니다. '특정 상품 할인 쿠폰'을 사용한 경우에는 어떠한 '전체 상품 할인 쿠폰'도 적용할 수 없게 되는 방식입니다.

서브웨이가 적용해주신 1, 9번 쿠폰은 모두 전체 할인 쿠폰이라, 한 상품에 2개 이상의 쿠폰이 적용되는 경우입니다. 이 경우에 발생하는 404코드 에러 메시지는 꽤 직관적인 내용을 담고 있다고 생각해서 일단은 그대로 두게 되었습니다~!

2023-06-08 05:26 UTC, kokodak commented on src/main/java/cart/cartitem/application/CartItemService.java
> +        List<CartItem> cartItems = cartItemRepository.findByMemberId(member.getId());
사실 뼈대 코드의 잔재이긴 했습니다(머쓱).. 서브웨이가 언급해주셔서 네이밍으로 추상화 레벨을 나누는 것도 정말 좋은 방법이겠다 싶었거든요. 그래서 앞으로 이런 식으로 좀 작성을 해보려고 하는데 궁금한 점이 생겨서요!
findById와 같이 자기 자신의 식별자를 사용해서 찾는 기능의 경우에는, 서비스단의 메서드 명을 어떻게 지으시나요? 서비스에서 Id 같은 네이밍이 들어가는 것은 지양하려고 하시는 편인가요?

2023-06-08 05:38 UTC, kokodak commented on src/main/java/cart/order/application/OrderQueryService.java
> +        List<Order> orders = orderRepository.findAllByMemberId(memberId);
전체조회에서는 validate가 필요없을 것 같아 의도적으로 하지 않았습니다!
전체적인 시나리오를 생각해보자면, Controller에서 Member로 들어오는 사용자의 정보는 이미 인증이 완료된 상태일 것이구요.
따라서, memberId로 자신의 주문 목록만 전체 조회하는 `findAllbyMember`는 인가된 사용자에 한해서만 호출이 될 것이므로 따로 인가가 되었는지 확인할 필요가 없습니다.
다만, `findById`는 조금 다릅니다. id로 조회하는 경우는 인가되지 않은 리소스에도 접근할 수 있다는 뜻이 되기 때문에, 이 경우에는 인가된 사용자인지 검증할 필요가 있습니다. 다른 사람의 리소스에 함부로 접근하게 두면 안되니까요! 그래서 이런 식으로 코드를 작성하게 되었습니다~! 혹시 제가 잘못 생각한 부분이 있다면 알려주세요!

2023-06-08 06:06 UTC, kokodak commented
안녕하세요 서브웨이! 전체적으로 질문해주신 코멘트에 제 생각에 대한 답변을 달아놨습니다 ㅎㅎ 좋은 리뷰해주셔서 감사했습니다 🥹
추가적으로 README에 간략한 기능요구사항을 정리해놨어요. 한번 참고해주세요! 감사합니다 서브웨이 😁

2023-06-08 09:46 UTC, joseph415 commented on src/test/resources/application.yml
> +    url: jdbc:h2:mem:testdb;MODE=MySQL
나중에 인메모리로 안하게 될때, 문제생길수 있어서 말씀드렸어요. 테스트에서는 truncate까지 하고있어서요.

2023-06-08 09:47 UTC, joseph415 commented on http/cartitem.http
> +### 회원의 장바구니 목록을 조회한다
넵 협의하는 과정에 대한 경험을 얻어가는 것이 중요한거같아요ㅎㅎ api 설계할때, 항상 클라이언트쪽과 지속적인 협의를 해야해서요.👍

2023-06-08 10:25 UTC, joseph415 commented on src/main/java/cart/cartitem/application/CartItemService.java
> +        List<CartItem> cartItems = cartItemRepository.findByMemberId(member.getId());
저같은 경우는 지양한다고 하기보단, 의식적으로 그렇게 하려는 편인데요ㅎㅎ 서비스에서는 어떻게 찾는가에 대한 동작보단 기능에 신경쓰는것 같아요. 간단한 예를 들면, 맴버를 찾는 기능이라면, findMember(..) 내부에서는 어떻게 찾는지 동작에 집중해서 findByid

```
findMember{
  findById(..)
}
```

2023-06-08 10:28 UTC, joseph415 commented on src/main/java/cart/order/domain/OrderItem.java
> +    private static int applyCoupon(CartItem cartItem, List<Coupon> coupons) {
코드를 작성할 때, 그런 세부 사항을 고려하도록 작성할 거면, 코드단에서 명식적으로 들어나도록 하던가(validate 로직을 내부 추가), 그런 오해를 부르지 않게 작성하도록 하는 방향이 좀 더 좋아보여서 의견 달았는데, 수용해주셔서 감사합니다~

2023-06-08 10:30 UTC, joseph415 commented on src/main/java/cart/order/application/OrderQueryService.java
> +        List<Order> orders = orderRepository.findAllByMemberId(memberId);
아 그래서 차이가 난것이군요ㅎㅎ 이건 코코닥이 말씀해주신대로 해도 좋을 것 같아요👍

2023-06-08 18:07 UTC, joseph415 commented on src/main/resources/schema.sql
> +    product_price INT          NOT NULL,
https://github.com/woowacourse/jwp-shopping-order/pull/45#discussion_r1219606815 해당 리뷰와 이어지는 것 같은데요.

만약에 실제 상품(Product) 와는 무관한 값들이라면, Product 도메인과 별개로 id없는 VO 로 관리를 해야할텐데 말씀해주신 상황은 그런 상황이 아닌것 같아서, id 필드만 갖도록 해야할 것 같아요.

코코닥이 우려한 상황은 다른 방식으로 해결할 수 있는데, 방학 때, lock 방식에 대해서 공부해보시면 좋을 것 같습니다.

2023-06-08 18:40 UTC, joseph415 commented on src/main/java/cart/cartitem/application/CartItemService.java
> +        return cartItems.stream().map(CartItemResponse::from)
이거 관련해서는 이전에 다른 크루와 똑같이 이야기한적이 있어서요. 그거 링크 참조로 달아두겠습니다.
제가 서비스에서 도메인엔티티를 리턴해야한다고 생각하는 이유는 해당링크에 있어요ㅎㅎ https://github.com/woowacourse/jwp-racingcar/pull/71#discussion_r1166859737

맨아래에 코코닥이 말씀해주신 상황도 그렇고, 제가생각한 상황은 도메인 별로 controller, domain, service.. 이렇게 패키지를 다시 구성해서 응집성을 높이도록 하는데요.(현재 코코닥 패키지 구성도 그렇게 되어있네요) repository를 의존해서 쓰게 된다면, 서비스에서 다른 서비스에서 처리해야할 것들이 섞이게 되고, 그로인해서 중복코드들이 생겨날거라고 생각했습니다.

예를들어, CartItemService에서는  CartItem에 대한 서비스기능들이 들어갈텐데요. ProductService에서 CartItemRepository로 가져와서 처리한다면, 도메인별로 패키지를 나눠서 쓰는 이유들이 점점 퇴색된다고 생각합니다.

이런 상황들때문에 도메인엔티티를 리턴하는게 맞지 않나 생각합니다. 사실 dto를 리턴해도 큰 문제는 없지만, 한번 생각해볼 점 같아서 남겼어요~

그리고 추가로 답변주신거 읽고 궁금한점 달아두어요.

> 현재 서비스 계층이 컨트롤러 계층의 DTO를 알고 있는 상황(CartItemResponse)이기 때문에, 사실 패키지 의존성 순환이 생기고 있긴 합니다.

```mermaid
graph TD
controller --> service
controller --> dto
service --> dto
```

패키지 구조가 이렇게 되어있을텐데, 제가 놓친게 있을까요? 순환구조는 아닌거 같아서요!

> Controller가 Service를 거치치 않고 바로 Domain 계층에 접근하는 것인데, 저는 이러한 코드들이 계층형 아키텍처의 일관성을 해친다고 생각해서요

컨트롤러는 도메인 계층을 알아도 되는 곳인데, 왜 일관성이 깨지는지 구체적으로 말해주실 수 있나요?

2023-06-08 18:55 UTC, joseph415 requested changes
안녕하세요. 코코닥

리뷰 잘 적용해주셨네요💯
리뷰 적용한 코드들은 확인하였고, 잘 적용해 주신 것 같아서 따로 추가 코멘트는 안 남겼어요~!
첫번째 리뷰에서 resolve conversation 되지 않은 것들 추가로 답변 달아두었습니다. 확인 부탁드려요!

2023-06-08 18:55 UTC, joseph415 commented on src/main/java/cart/cartitem/domain/CartItem.java
> +    private final Long productId;
요거 관련해서 https://github.com/woowacourse/jwp-shopping-order/pull/45#discussion_r1223388546 에 답변 달아두었습니다!

변경없이 우선 그대로 가고 이런 방식으로 우려하신 것을 해결할 수 있다는것 정도 알고있으면 좋을 것 같습니다!

2023-06-08 18:55 UTC, joseph415 commented on README.md
> +
👍

2023-06-09 01:05 UTC, kokodak commented on src/main/java/cart/cartitem/application/CartItemService.java
> +        List<CartItem> cartItems = cartItemRepository.findByMemberId(member.getId());
이해했습니다! 저도 앞으로는 의식적으로 네이밍을 이런 식으로 해보겠습니다 ㅎㅎ 좋은 방법인 것 같아요

2023-06-09 04:35 UTC, kokodak commented on src/main/java/cart/cartitem/application/CartItemService.java
> +        return cartItems.stream().map(CartItemResponse::from)
링크 잘 봤어요 서브웨이. 전체적으로 다 공감이 가는데요. 좋은 관점 알려주셔서 감사합니다. 다시 한번 진지하게 고민을 해볼 필요가 있겠네요.
일단 먼저 질문해주신 부분부터 답변을 해보자면,

> 패키지 구조가 이렇게 되어있을텐데, 제가 놓친게 있을까요? 순환구조는 아닌거 같아서요!

저는 패키지 의존성을 말한거였습니다! `CartItemResponse` 는 Controller에 속한 DTO인데, Service에서 이를 의존하고 있기 때문에 패키지로 보면 `Service -> Controller` 의 의존성을 가집니다. Controller도 Service를 알고 있으니 패키지 의존성으로 봤을 때 `Controller <-> Service` 처럼 양방향 의존성이 생겼다는 의미였습니다!

> 컨트롤러는 도메인 계층을 알아도 되는 곳인데, 왜 일관성이 깨지는지 구체적으로 말해주실 수 있나요?

제가 생각한 계층 구조에서의 도메인 영역은 application 계층에서 캡슐화되어 보호돼야 한다고 생각했습니다. 따라서 컨트롤러 계층에서 도메인을 아는 것이 어색하다는 생각을 한 것 같습니다. 일관성을 언급했던 부분은, 계층화 아키텍처에서는 컨트롤러 계층에서 서비스 계층을 의존하고, 서비스 계층에서 도메인 계층에 의존해야 하는 것이라 생각해왔습니다. 따라서 컨트롤러가 서비스를 거치치 않고 도메인에 접근하는 것은 한 계층을 뛰어넘는 행위라고 생각해서 일관성을 해친다는 말을 하게 됐는데요. 서브웨이가 '컨트롤러는 도메인을 알아도 된다' 라는 말을 하셔서, 이에 대해 곰곰이 생각해봤는데 사실 큰 문제가 없어보여요. 현실적으로 컨트롤러에서 도메인이 오용될 확률도 적다고 생각하구요. 어쩌면 제가 계층화 아키텍처를 잘못 이해했을 확률이 높은 것 같아요. 제가 생각해오던 관성에 너무 붙잡혀서 주관없이 '컨트롤러는 도메인을 알면 안돼!' 라고 생각해왔던 것 같아 반성하게 되네요.

서브웨이에게 두 가지 질문이 있는데요!
1. 서브웨이는 A 도메인 영역의 서비스에서 B 도메인 영역에 접근해서 가져와야 할때, 대부분 Repository가 아닌 Service를 의존하여 가져오시나요? 사실 서비스가 서비스를 의존하는 형태로 설계를 하다보면, 아무래도 순환참조를 막기 위해 도메인 영역간의 양방향 의존성에 더 신경쓸 수 있다는 장점이 있는 것 같습니다.
2. Controller가 Domain을 알아도 된다면, Controller → Service 에서도 도메인을 넘기는 편이신가요? 아니면 이런 경우에는 DTO로 분리하려고 하시나요?

2023-06-09 04:37 UTC, kokodak commented on src/main/resources/schema.sql
> +    product_price INT          NOT NULL,
아 제가 리뷰를 잘못 해석했군요. 말씀해주신대로 lock에 대해 공부해보고, 이번 상황에 대해 다시 고민을 해보도록 하겠습니다! 알려주셔서 감사합니다

2023-06-09 04:40 UTC, kokodak commented on src/test/resources/application.yml
> +    url: jdbc:h2:mem:testdb;MODE=MySQL
제가 이 부분이 잘 이해가 안가는데 혹시 다시 한번 설명해주실 수 있을까요? 😭

2023-06-10 16:21 UTC, joseph415 commented on src/test/resources/application.yml
> +    url: jdbc:h2:mem:testdb;MODE=MySQL
아 죄송해요ㅎ;

현재야 테스트 환경이나 개발 환경이나 in-memory DB를 사용하므로 문제가 없지만, 추후에 개발용 서버(MySQL 등)을 사용한다면 문제가 될 수 있지않을까 해서요. truncate까지 하고있는데, 개발디비를 날려버린다면, 문제가 되지 않을까요ㅎㅎ

2023-06-10 17:06 UTC, joseph415 commented on src/main/java/cart/cartitem/application/CartItemService.java
> +        return cartItems.stream().map(CartItemResponse::from)
1. 서비스를 의존해서 가져오는 편입니다ㅎㅎ 뭔가 기능이 필요하다면 서비스에서 로직을 만들고 참조해서 사용하려고 합니다.

2. 저도 크루때는 dto를 넘기도록 하려고 했는데요. 말씀드린 이유로 도메인을 넘기도록 하려고 하고있습니다. 

이거는 팀마다 의견이 다를 수 있고, 서비스에 따라 다를 수 있을 것 같아요. 장단점을 경험해보고 장점으로 더 크게 느껴지는 것에 대해서 팀과 논의하여 결정하면 좋을 것 같아요. 

제가 정답은 이거야! 라고 말씀드리려고 주제를 꺼낸건 아니고, 각각 장단점을 생각해보면 좋지 않을까 하여서 꺼내봤습니다~ 리뷰어들마다 생각이 다 다를 수 있잖아요!? 그래서 코코닥도 다양하게 생각해보시면 좋을 것 같아서요ㅎㅎ 제가 크루였을 때 생각해보면, 이거에 대해서 크게 고민을 안했던 것 같아서 꺼내봤습니다!

2023-06-10 17:08 UTC, joseph415 approved these changes
안녕하세요. 코코닥.

2단계 구현하느라 고생하셨습니다. 이번 단계는 이만 merge하려고 해요!
코멘트에 추가로 질문주신 답변은 남겨두었으니 확인 부탁드려요!

레벨2도 고생 많으셨어요👍 남은 기간도 응원하겠습니다. 화이팅입니다!

2023-06-10 17:08 UTC, merged