[2단계 - 주문 기능 구현] 비버(전인표) 미션 제출합니다.
woowacourse/jwp-shopping-order pull request #60
Opened 2023-06-03 17:18 UTC by ingpyo

2023-06-06 11:46 UTC, lowoon requested changes
반가워요 비버! 리뷰어 로운입니다! 😄
코멘트 몇 가지 남겨봤으니 확인 부탁드려요.
궁금한 점이 생기면 언제든지 DM 혹은 댓글남주세요 ^-^

2023-06-06 11:46 UTC, lowoon commented on src/main/java/cart/application/service/cartitem/CartItemReadService.java
> +public class CartItemReadService {
일반적으로 서비스를 기능별로 나누지는 않는것 같은데요.
나눈 이유가 있을까요??
그리고 Transactional은 dao와 service중 어디 한곳에 작성이 되어야할까요?? 아니면 두곳 모두 작성이 되어야할까요?
어디에 작성되어야할지 고민해보시면 좋을것 같습니다~

2023-06-06 11:46 UTC, lowoon commented on src/main/java/cart/application/service/cartitem/CartItemWriteService.java
> +    private final ProductRepository productRepository;
하나의 서비스가 여러개의 repository를 가지고 있는데요.
service를 가질 수는 없을까요??
서비스의 역할과 책임은 무엇일까요?

2023-06-06 11:46 UTC, lowoon commented on src/main/java/cart/application/service/cartitem/CartItemWriteService.java
> +        if (cartItemUpdateDto.getQuantity() == 0) {
장바구니의 아이템 삭제 요청이 따로 있는게 아니라 수량이 0이면 삭제가 되는 걸까요??
밑에 삭제 메서드가 따로 있는데 0인 경우에도 처리가 될 수 있도록 한걸까요??
이러한 부분은 0을 선택하지 못하도록 막을 방법도 있을텐데요.
따로 0에 대한 기능을 추가한 이유가 있을까요??
만약 0을 선택하지 못하도록 정책을 정했다면 검증이 필요할텐데 이러한 검증은 클라에 있어야할까요 아니면 서버에 있어야할까요?

2023-06-06 11:46 UTC, lowoon commented on README.md
> +    product_name VARCHAR(255) NOT NULL,
cart item 처럼 product_id가 아닌 따로 필드들을 가진 이유가 있을까요?

2023-06-06 11:46 UTC, lowoon commented on src/main/java/cart/application/service/product/dto/ProductCreateDto.java
> +public class ProductCreateDto {
업데이트 시에도 해당 dto가 사용되는 것 같은데요.
create로 클래스명을 사용하는 것이 맞을까요?

2023-06-06 11:46 UTC, lowoon commented on src/main/java/cart/application/service/product/dto/ProductResultDto.java
> +public class ProductResultDto {
contoller와 service가 메세지를 주고받을때 dto로 주고받고 있는데요.
어떤 장단점을 느끼셨는지 궁금하네요ㅎㅎ
도메인을 주고받으면 어떻게 될까요? 반영하는 것이 아니라 고민을 해보시면 좋을것 같아 코멘트 드립니다~

2023-06-06 11:46 UTC, lowoon commented on src/main/java/cart/ui/exception/ControllerExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
http status만 주로 설정이 되어 있고 body가 없는데 어떤 에러가 어떠한 상황에서 발생했는지 정확하게 확인이 힘든 형태이지 않나요?
현재 에러 응답 뿐만이 아니라 일반 응답의 경우에도 모두 다른 형태가 내려가고 있는데요.
프론트에서 매 응답마다 다른 형태로 확인하는걸까요??
모두 공통된 형태로 응답을 주고 받고 에러에 대해서도 서로 정의하면 에러에 따라 어떤 상황이 발생했는지 인지하고 사용자에게 보여줄 메세지를 정의할 수 있지 않을까요??
아래는 예시입니다~
```java
private String code;
private String message;
private T data
```

2023-06-06 11:46 UTC, lowoon commented on src/main/java/cart/ui/order/OrderReadController.java
> +    public OrderReadController(final OrderReadService orderReadService) {
controller도 기능별로 나뉘지는 않는것 같은데요
나눈 이유가 있을까요??
RequestMapping도 2가지가 중복되지 않나요?

2023-06-06 11:46 UTC, lowoon commented on src/main/java/cart/domain/discountpolicy/StoreDiscountPolicy.java
> +    public int calculateStoreDiscount(final int totalPrice, final Coupons coupons, final Point point) {
개인적인 의견입니다~
다른 할인 정책이 추가되면 parameter가 추가될 것 같은데요. 전략패턴을 사용하는 이유 중에 하나가 확장성이고 다른 것을 추가더라도 기존의 코드가 영향을 최대한 받지 않게 하는 것인데 추가될 때마다 기존 전략이 수정되지 않을까요??
상위 서비스의 로직을 보니 기본적으로 member가 모두 사용되는 것 같아요.
parameter로 member를 받고 각 정책에서 필요한 정보를 조회하여 할인을 적용할 수 있지 않을까요??
이 경우 객체가 정책의 역할과 책임을 넘어서는 것 같다면 service로 만들 수 있을것 같아요~

2023-06-06 11:46 UTC, lowoon commented on src/test/java/cart/ui/point/PointReadControllerTest.java
> +//    @Test
사용하지 않는 메서드, 테스트는 주석처리하기보다 제거하는 것이 좋습니다~

2023-06-08 06:25 UTC, ingpyo commented on src/main/java/cart/application/service/cartitem/CartItemReadService.java
> +public class CartItemReadService {
1. 서비스를 기능 별로 나눈이유는 책임분리 이유로 나눈거같습니다. 하나의 서비스에 여러기능이있을 때 가독성이 떨어진다고 판단해서 읽어오는 기능과 수정,삭제,추가 기능을 따로 분리하는게 더 가독성이 좋다고 판단해서 분리했습니다!
(혹시 로운의 의견을 들을 수 있을까요?...🥹🥹🥹🥹🥹🥹)
2.서비스가 하나의 작업묶음을 나타내고 그러한 하나의 작업을 수행할 때 ACID를 보장하기 위해 Service단에 Transactional을 작성해야된다고 생각합니다!

2023-06-08 06:29 UTC, ingpyo commented on src/main/java/cart/application/service/cartitem/CartItemWriteService.java
> +        if (cartItemUpdateDto.getQuantity() == 0) {
원래 뼈대코드에 0일때 삭제하는 로직이 있어서 그대로 미션을 진행했습니다...
만약 0에 대한 기능을 추가했을 때 검증은 클라에서도 하고 서버에서도 할거같습니다!
왜냐하면 클라에서 검증을했다고해도 클라에서 서버로 넘어오는 과정에서 데이터변경이 취약하기때문에 2중으로 검증할거같습니다!!

2023-06-08 06:31 UTC, ingpyo commented on README.md
> +    product_name VARCHAR(255) NOT NULL,
일단 소비자가 구매를 한시점에서의 상태를 알고싶어할거 같아서 id가 아닌 그때 구매한 상품의 정보를 저장했습니다!
만약 상품의 가격,사진이 변경됐을때 소비자는 그때의 상품의 사진이나 가격을 알고싶을 수 있다고 판단해서 다음과같은 테이블을 설계한거같습니다!

2023-06-08 06:34 UTC, ingpyo commented on src/main/java/cart/application/service/product/dto/ProductResultDto.java
> +public class ProductResultDto {
만약 도메인을 주고받을 때 controller에서 데이터의 변경이일어났을때 도메인이 바껴야한다는 단점이있을거같습니다.
그래서 dto를 주고받았고, 이러한 행위을했을때 단점으로는 간단한 crud나 dto와 도메인에 필드가 중복이일어나도 일관성에 의해 dto로 포장해줘야되서 복잡성이 증가한다는 단점이 있었습니다!

2023-06-08 06:36 UTC, ingpyo commented on src/test/java/cart/ui/point/PointReadControllerTest.java
> +//    @Test
감사합니다! 주석을 제거했어야됐는데,,, 수정하겠습니다!

2023-06-08 06:42 UTC, ingpyo commented on src/main/java/cart/domain/discountpolicy/StoreDiscountPolicy.java
> +    public int calculateStoreDiscount(final int totalPrice, final Coupons coupons, final Point point) {
짧게나마 제 의견을 말씀드리겠습니다,.🥹
만약 많은 정책을 추가되고 관리해야된다면 정책에 필요한 정보를 조회해서 할인적용하는데 유지보수 측면에서 좋을거같습니다!
하지만 지금 2개의 정책 밖에 없기때문에 service단에서 검증때문에 불러온 객체들(member,cartItems)을 통해서 정보를 찾아오는게 조금 더 효율적이다 라고 판단했습니다.

혹시 제가 잘못 생각하고 있는걸까요?... 로운의 생각이 궁금합니다!!!🥹

2023-06-08 06:44 UTC, ingpyo commented on src/main/java/cart/ui/exception/ControllerExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
이건 제가 예외 헨들러에 대해 제대로 완성을 안시킨거같습니다,,,,
수정하고 리뷰 올리겠습니다!!

2023-06-08 07:25 UTC, ingpyo commented on src/main/java/cart/application/service/product/dto/ProductCreateDto.java
> +public class ProductCreateDto {
하나의 dto를 재사용하니까 Command라는 클래스명이 더 적확할거같습니다! 수정하겠습니다!

2023-06-08 07:53 UTC, ingpyo commented on src/main/java/cart/ui/order/OrderReadController.java
> +    public OrderReadController(final OrderReadService orderReadService) {
저도 생각해보니 controller를 분리하는게 조금 어색했습니다!
controller를 유즈케이스 하나씩 만들고 mock테스트를 사용하지않는 이상 하나의 controller로 사용하는게 더 좋을거같습니다!

2023-06-08 08:24 UTC, ingpyo commented on src/main/java/cart/application/service/cartitem/CartItemWriteService.java
> +    private final ProductRepository productRepository;
서비스는 하나의 작업 묶음으로 각 동작등을 조율하는 역할을 합니다!
각 서비스가 독립적으로 동작하도록 설계하는게 서비스를 재사용하기 유리하다고 생각합니다!
그래서 service에서 예외가 중복은 
```
default Product getById(Long id) {
        return findById(id)
                .orElseThrow(() -> new NoSuchElementException("일치하는 상품이 없습니다."));
    }
```
이러한 방법으로 제거하는 방법을 채택했습니다!!

2023-06-09 00:23 UTC, lowoon commented on src/main/java/cart/application/service/cartitem/CartItemReadService.java
> +public class CartItemReadService {
1. 이렇게 될 경우 관리해야하는 서비스가 너무 많아질 수 있어서요. service의 역할이 비지니스로직을 담당하는 것이고 해당 service의 역할과 책임에 포함되는 것이라면 분리를 안해도 되지 않을까요?? 예를 들어 하나의 서버에 서비스가 30개라고 한다면 기능별로 나누게 될때 2~3배의 서비스가 생기게 될텐데 관리가 될까요?
2. 현재와 같은 구조에서는 이슈가 없을거에요
jpa를 예시로 이슈가 생기는 상황을 설명드릴게요.
jpa의 경우 entity 자체에 다른 테이블의 entity를 매핑할 수 있습니다. (one to many, many to one 등)
그래서 조회시에 jpa 내부적으로 join query를 실행하여 결과를 return하는데요.
(위와 같은 방식은 현재의 dao에도 적용할 수 있겠죠?? 어떤 차이가 있을지 고민해보시면 좋을것 같네요ㅎㅎ)
반대로 저장을 하는 경우에도 내부의 entity변경되면 변경된 사항이 함께 저장이 되게됩니다.
이렇게 되면 repository(현재의 dao)에서 하나의 entity를 저장하는데 여러개의 entity가 변경되겠죠??
이 경우 위에서 설명주신 것처럼 하나의 트랜잭션으로 묶여 여러개의 변경이 함께 진행이 되어야합니다.
그렇기 때문에 저는 dao에 기본적으로 @Transactional을 붙여야 하고 추가적으로 비지니스적으로 묶여야하거나 readOnly처럼 트랜잭션 설정이 따로 필요한 경우에 service에 붙여야하지 않나라고 생각합니다~
상위 클래스와 하위클래스에 @Transactional이 모두 붙여있을때 어느 transaction으로 동작하시는지는 아시죠??ㅎㅎ

2023-06-09 00:30 UTC, lowoon commented on src/main/java/cart/application/service/cartitem/CartItemWriteService.java
> +    private final ProductRepository productRepository;
독집적이라는 의미가 애매한 것 같은데요.
productService에 getById가 있는 것과 CartItemWriteService에 getProductById가 있는 것이 독립적인건가요?
서비스라고 하는 것이 비지니스 로직을 담당하게 되고 db와 관련된 작업도 비지니스 로직에 포함되기 때문에 serivce에서 관리를 하게 되는데요.
여러개의 서비스에서 각자 repository를 관리하게 되면 각자의 service에서 각자 db동작들이 관리되게 되지 않나요?
productService처럼 클래스명에서도 제품에 대한 관리를 담당하는 서비스라고 한다면 db동작들은 productService를 통해 될 것 이라고 이해하게 되지 않을까요?
일반적으로 주문에 대한 정보를 변경한다고 했을때 메뉴팀에 요청하지 않고 주문팀에 요청하게 되는데요. 각 명칭과 역할과 책임, service의 역할과 책임의 범위를 어떻게 가지는게 맞을지 고민해보시면 좋을것 같습니다.

2023-06-09 00:34 UTC, lowoon commented on src/main/java/cart/application/service/product/dto/ProductResultDto.java
> +public class ProductResultDto {
controller에서 데이터의 변경이 일어났을때 도메인이 바뀌어야한다는 점이 이해가 잘 안가는데요.
controller의 데이터를 service에 전달하는 부분만 변경이 되고 도메인은 변경되지 않지 않나요?
controller에서 데이터의 변경이 일어났을때 dto를 사용하더라도 dto가 변경이 될텐데 이 경우에도 도메인이 바뀌는 걸까요?
비버의 생각을 이야기할때 근거나 예시를 들어 설명해주고 좀더 자세하게 설명해주는 것이 서로 토론을 하거나 의견을 주고받을때 좋을것 같습니다~

2023-06-09 00:37 UTC, lowoon commented on src/main/java/cart/domain/discountpolicy/StoreDiscountPolicy.java
> +    public int calculateStoreDiscount(final int totalPrice, final Coupons coupons, final Point point) {
아니요 맞습니다!
일반적으로 전략패턴을 적용하는 것은 2개이상의 정책이 생기게 되면서 추후에 확장성을 위해 구조를 바꾸게 되는 것 같습니다.
처음부터 확장성을 위해 개발하기보다 필요가 생겼을때 구조를 변경하는 것도 좋은 방법이라고 생각합니다ㅎㅎ

2023-06-09 00:49 UTC, lowoon approved these changes
안녕하세요 비버!😄
이제 그만 주문 미션을 마무리해도 될 것 같아요.
간단한 코멘트만 남겼으니 확인 부탁드려요.
미션은 끝났지만 궁금한점 있으면 DM이나 코멘트로 남겨주세요!

2단계 주문 미션 수고하셨습니다!

2023-06-09 00:49 UTC, lowoon commented on src/main/java/cart/domain/order/Order.java
> +    private final Long id;
아래는 알고만 계시면 될 것 같은데요.
추가적으로 택배 주문과 음식 주문의 형태가 다르기는 하지만 주문에는 상태도 있을 수 있습니다~
우리가 실생활에서 사용하는 배민, 쿠팡, 스마트 스토어 등을 생각해보시면 좋을것 같습니다~

2023-06-09 00:49 UTC, lowoon commented on src/main/java/cart/domain/order/Order.java
> +    private final Coupons coupons;
결제와 관련된 정보는 객체로 따로 만들어서 관리할 수 있지 않을까요?

2023-06-09 00:49 UTC, lowoon commented on src/main/java/cart/application/config/StoreConfig.java
> +    public StoreDiscountPolicy discountPolicy() {
정책을 bean으로 등록하는 것이 맞을까요?
어떤 할인 정책을 적용할지는 service의 역할이 될텐데 service에서 정책들을 관리해야하지 않을까요?
service나 controller, 다른 bean들처럼 정책 또한 spring자체에서 관리되어야하는 class일까요?

2023-06-09 00:49 UTC, merged

2023-06-09 00:53 UTC, lowoon commented on src/main/java/cart/ui/CorsConfig.java
> +public class CorsConfig implements WebMvcConfigurer {
webMvcConfIg 파일이 있는데 cors 설정 클래스를 따로 만든 이유가 있을까요?
설정을 따로 관리해야할 정도의 크기여서 관리의 명확성이 필요한 수준일까요?