[2단계 - 주문 기능 구현] 허브(방대의) 미션 제출합니다.
woowacourse/jwp-shopping-order pull request #7
Opened 2023-05-27 15:08 UTC by greeng00se

안녕하세요 카일 😄

이번에 협업 미션에서 리뷰이가 된 허브🌿  라고합니다.

이번 2단계 주문 기능에서 재화 관련 요소는 쿠폰, 할인을 선택했습니다.
요구사항이 많이 어려워서, 일단 돌아만 가도록 구현을 했습니다.

### 쿠폰

쿠폰은 아래와 같이 구현하였습니다.
쿠폰은 할인 정책과, 할인 조건을 가지고 있고
할인 조건과 정책이 여러가지 일 경우를 고려하지 않고 하나씩만 가지도록 했습니다.

```mermaid
flowchart RL
    DiscountPolicy --> Coupon
    DiscountCondition --> Coupon
    
    AmountDiscountPolicy --> DiscountPolicy
    PercentDiscountPolicy --> DiscountPolicy
    DeliveryFeeDiscountPolicy --> DiscountPolicy

    MimimumPriceDiscountCondition --> DiscountCondition
    NoneDiscountCondition --> DiscountCondition
```

DB에 종류 저장,  API에 어떤 쿠폰 타입인지 반환하기 위해서 
각각의 할인 정책과 할인 조건에 Type Enum을 필드로 가지고 있도록 했습니다.
이 부분에서 고민을 많이 했는데, 말로 설명하지 못하는 약간 애매한 느낌이 많이 들었습니다.
현재의 쿠폰 정책에 관련해서 카일의 의견을 들어보고 싶습니다.

### db 구조

<img width="787" alt="image" src="https://github.com/woowacourse/jwp-shopping-order/assets/58586537/1015c2db-4779-413b-ba98-3b1093a0b6a1">

쿠폰의 경우 정책이나 조건을 따로 저장하지 않고, 하나의 쿠폰 테이블에 저장하도록 했습니다.
(팀원들과 고민을 많이 했었는데, 일단 제일 간단한 방법이라고 생각되었습니다.)

### 다음 리뷰 요청시 반영 예정

다음 리뷰 요청시에 다음과 같은 부분들을 해보려고 합니다.

- [ ] 인수테스트
- [ ] Fixture 추가
- [ ] README 개선
- [ ] 장바구니에 있는 상품을 다중 제거기능 구현 (프론트와 추가로 협의한 부분)
- [ ] 코드 및 테스트 코드 리팩터링
- [ ] DB Profile 분리(다음주에 팀원들과 같이 AWS에 DB를 설정하기로 했습니다.)

추가적으로 구조에 대해서 고민을 해보다가 궁금증이 더 생긴다면 PR에 남겨놓도록 하겠습니다!
이번 협업 미션동안 잘 부탁드립니다. 감사합니다!!

2023-05-29 14:26 UTC, KIMSIYOUNG requested changes
안녕하세요 허브.
리뷰가 늦어서 죄송합니다.
전체적으로 깔끔하게 잘 구현해주셨네요.
몇가지 코멘트 남겼는데 확인 부탁드립니다.

2023-05-29 14:26 UTC, KIMSIYOUNG commented on README.md
> +    - [x] 조건 없이 쿠폰을 적용할 수 있는 조건이 존재한다.
바로 아래에 있는 조건과 상충되는 조건인 것 같아요. 의미를 조금 더 명확하게 작성해주면 좋을 것 같습니다.

2023-05-29 14:26 UTC, KIMSIYOUNG commented on src/main/java/cart/controller/CouponController.java
> +    @ApiResponse(
`Swagger`와 `RestDocs`의 장단점에 대해서도 학습해보고 적용해주신 내용이실까요? 어떤 장점으로 인해서 스웨거를 사용하셨는지 궁금합니다.

2023-05-29 14:26 UTC, KIMSIYOUNG commented on src/main/java/cart/controller/CouponController.java
> +    public ResponseEntity<List<CouponResponse>> findAll(@Auth final Credential credential) {
`CouponResponses`라는 객체내에 `List<CouponResponse>`를 리턴하는 것과, 현재의 구조는 어떤 것이 다를까요?

2023-05-29 14:26 UTC, KIMSIYOUNG commented on src/main/java/cart/dao/CartItemDao.java
> +    public List<CartItemEntity> findByIds(final List<Long> ids, final Long memberId) {
`ids`로 찾는 경우 이미 식별자로 찾는 것인데 `memberId`를 추가조건으로 주는 것은 어떤 의미일까요?

2023-05-29 14:26 UTC, KIMSIYOUNG commented on src/main/java/cart/dao/OrderItemDao.java
> +@Repository
전체적으로 `DAO`에서도 트랜잭션을 보장해주면 좋을 것 같습니다.

2023-05-29 14:26 UTC, KIMSIYOUNG commented on src/main/resources/schema.sql
> +    `condition_type`        varchar(255)     NOT NULL,
어떤 조건에서 사용할 수 있다라는 것이 `DB`칼럼으로 관리되어야 하는 이유가 있을까요?

2023-05-29 14:26 UTC, KIMSIYOUNG commented on src/main/resources/schema.sql
> +    `policy_type`           varchar(255)     NOT NULL,
테이블을 모두 분리하는 것과 현재와 같이 `Type`을 중심으로 나누는 것 각각은 장단점이 있는 것 같아요.
말씀하신대로 더 단순하게 사용할 수 있고 직관적이지만 `어떤 값이 비어있을 수 있다는 것을 잘 인지해야할 것 같아요.` 그런 의미에서 `NOT NULL`은 오히려 혼선을 주지 않을까요? (기본값으로 들어가는게 중요한게 아니라 비어있을 수 있다는게 중요할 것 같아요.)

2023-05-29 14:26 UTC, KIMSIYOUNG commented on src/main/resources/schema.sql
> +    `discount_percent`      int              NOT NULL,
Type + Value로 유추할 수 있는 값들일 것 같은데 모두 풀어서 작성되어 있는 이유는 무엇인가요? 어떤 장점이 있을까요

2023-05-29 14:26 UTC, KIMSIYOUNG commented on src/main/java/cart/domain/cart/Item.java
> +public interface Item {
추상화되어야 하는 이유가 무엇인가요? 어떤 장점을 가지고 있는지 잘 모르겠어요.

2023-05-29 14:26 UTC, KIMSIYOUNG commented on src/main/java/cart/domain/cart/Member.java
> +package cart.domain.cart;
`Member`가 카트에 포함되는 도메인인가요?

2023-05-29 14:26 UTC, KIMSIYOUNG commented on src/main/java/cart/domain/cart/OrderItem.java
> +            throw new InvalidCartItemOwnerException();
복사붙여넣기가 잘못된 것 같아요🙂

2023-05-29 14:26 UTC, KIMSIYOUNG commented on src/main/java/cart/domain/common/Money.java
> +package cart.domain.common;
`Common`은 해석하기에 따라 다르기에 `VO` 정도로 정의해보면 어떨까요?
그렇게 된다면 `VO`의 성격은 훼손하지 않으면서 도메인 로직은 포함하지 않도록 유지보수 될 것 같아요.
반대로 `Common`하지만 도메인 로직을 포함하겠다라고 한다면 현재의 구조가 더 적절할 것 같네요.

2023-05-29 14:26 UTC, KIMSIYOUNG commented on src/main/java/cart/domain/common/Money.java
> +public class Money {
추가로 VO를 설계할 땐 빈값/Null에 대한 입출력을 어떻게 다룰건지에 대해서도 고민되어야 합니다. 그래야 어플리케이션 전반에 사용되며 이에 대한 방어가 될 수 있을 것 같아요.

2023-05-29 14:26 UTC, KIMSIYOUNG commented on src/main/java/cart/domain/coupon/DiscountCondition.java
> +    boolean isSatisfiedBy(final Money totalPrice);
`최소주문금액을 만족하는지`와 `이 할인조건 자체를 사용할 조건이 되는지` 중의적 의미를 포함하고 있는 것 같아요.

2023-05-29 14:26 UTC, KIMSIYOUNG commented on src/main/java/cart/domain/coupon/DiscountPolicyType.java
> +public enum DiscountPolicyType {
전체적으로 `Enum` + `인터페이스` 를 가져가기보단 `Enum + 정적클래스`를 사용해서 Enum내부에 람다를 사용해도 충분할 것 같아요. 

구현해주신 형태는 결과적으로 어떤 `타입, 조건`인지를 알아야하는데 그렇다면 인터페이스 기반으로 이를 계산하여 타입을 구하기보단 `타입이 중심이 되면 ` 흐름이 더 자연스러울 것 같아요.

2023-05-29 14:26 UTC, KIMSIYOUNG commented on src/main/java/cart/entity/OrderEntity.java
> +    private final Long couponId;
1. 쿠폰과 주문의 관계에서 주문이 쿠폰을 알고 있는 이유는 무엇인가요?
2. 한 주문에 두가지 이상의 쿠폰이 사용될 수 있는 구조를 고려하지 않은 이유는 무엇인가요?

2023-05-29 14:26 UTC, KIMSIYOUNG commented on src/main/java/cart/service/OrderService.java
> +    public List<OrderResponse> findAll(final Long memberId) {
`readOnly`조건이 누락된 것 같아요. 해당 조건을 넣으면 어떤 변화가 생기는지 아시나요?

2023-05-29 14:26 UTC, KIMSIYOUNG commented on src/main/java/cart/domain/coupon/DiscountConditionType.java
> +public enum DiscountConditionType {
`말로 설명하지 못하는 약간 애매한 느낌이 많이 들었습니다` 은 어떤 의미일까요?
일단 기본적으로 깔끔하게 잘 구현해주신 것 같아요. 그렇기에 너무 `부족하다`라는 느낌은 받으실 필요는 없을 것 같습니다.

조금 더 고민해보자면 쿠폰의 타입 또는 할인조건이 현재는 Enum을 사용하여 정적으로 픽스되어있어요. 이 값을 동적으로 변화시키면 어떤 장단점이 있을까요? 동적으로 변화시킨다는건 예를들어 디비에 저장함으로써 어플리케이션이 동작하고 있는 와중에도 쿠폰정책이 달라지는 경우 새로운 쿠폰 정책을 추가로 넣고 제공할 수 있는 방법이 될 것 같아요.

2023-05-29 15:00 UTC, greeng00se commented on README.md
> +    - [x] 조건 없이 쿠폰을 적용할 수 있는 조건이 존재한다.
다음과 같이 할인 정책과 할인 조건에 대한 내용을 조금 더 명확하게 변경해보았습니다! 👍 

- [x] 쿠폰을 사용하면 할인이 된다.
- [x] 쿠폰은 하나의 할인 정책, 하나의 할인 조건을 포함한다.
- [x] 할인 정책은 3가지 종류가 존재한다.
    - [x] `고정 금액 할인 정책`이 존재한다.
    - [x] `비율 할인 정책`이 존재한다.
    - [x] `배달비 할인 정책`이 존재한다.
- [x] 할인 조건이 존재한다.
    - [x] 최소 주문 금액 이상 주문해야지 쿠폰을 적용할 수 있는 `최소 주문 금액 조건`이 존재한다.
    - [x] 무조건 쿠폰을 적용할 수 있는 `빈 조건`이 존재한다.
- [x] 쿠폰을 적용 후 주문 금액이 0원 미만으로 내려갈 수 없다.
- [x] 쿠폰을 적용 후 주문하는 경우 사용한 쿠폰이 제거된다.

2023-05-29 15:09 UTC, greeng00se commented on src/main/java/cart/controller/CouponController.java
> +    @ApiResponse(
Swagger는 적용하기 쉽고, 문서를 제공받는 쪽에서 API를 직접 테스트 해볼 수 있는 장점이 있습니다. 
하지만 Swagger 관련된 코드가 Controller나 DTO에 남아있다는 단점이 있고 동기화를 직접 하지 않으면 안된다는 단점이 있습니다.

RestDocs의 경우 테스트가 성공해야 문서가 작성되는 점, Controller나 DTO에 코드를 작성하지 않아도 된다는 장점이 있지만 Swagger에 비해 적용하기 다소 어렵다는 단점이 있습니다.

미션 기간이 짧기에 RestDocs에 비해 간편하고 빠르게 적용 후 문서를 제공할 수 있다는 장점, 프론트엔드 팀원이 API를 조금 더 간편하게 테스트 할 수 있도록 Swagger를 선택했습니다!

2023-05-29 15:14 UTC, greeng00se commented on src/main/java/cart/controller/CouponController.java
> +    public ResponseEntity<List<CouponResponse>> findAll(@Auth final Credential credential) {
현재 프론트엔드와 협의한 API 명세는 다음과 같이 배열 내부에 CouponResponse가 있는 형태를 반환하도록 했습니다.
```json
[
  {
    "id": 1,
    "name": "생일 쿠폰",
    "type": "percent",
    "discountPrice": 0, 
    "discountPercent": 10, 
    "discountDeliveryFee": false,
    "minimumPrice": 0
  }
]
```

만약 CouponResponses라는 객체가 존재하고 필드로 `List<CouponResponse> contents`를 가지고 있다면 다음과 같은 형태가 될 것 같습니다!

```json
{
  "contents": [
    {
      "id": 1,
      "name": "생일 쿠폰",
      "type": "percent",
      "discountPrice": 0, 
      "discountPercent": 10, 
      "discountDeliveryFee": false,
      "minimumPrice": 0
    }
  ]
}
```

2023-05-31 12:48 UTC, greeng00se commented on src/main/java/cart/dao/CartItemDao.java
> +    public List<CartItemEntity> findByIds(final List<Long> ids, final Long memberId) {
사용자의 장바구니에 있는 상품을 검색하기 위해 조건을 추가로 주었는데 사실상 메서드명과 다르게 동작해서 많이 어색해 보입니다! memberId 제거했습니다! 👍 
Repository도 똑같이 memberId를 받는데 이 부분은 메서드명을 변경하는 방향으로 수정하겠습니다!

2023-05-31 12:54 UTC, greeng00se commented on src/main/java/cart/dao/CartItemDao.java
> +    public List<CartItemEntity> findByIds(final List<Long> ids, final Long memberId) {
memberId를 받음에도 메서드명에 어떤 의미인지 나타내고 있지 않네요 😢 
findAllByIdsAndMemberId로 메서드명에 조금 더 정확한 정보를 표현하도록 변경하겠습니다!

2023-05-31 12:58 UTC, greeng00se commented on src/main/resources/schema.sql
> +    `condition_type`        varchar(255)     NOT NULL,
DB 테이블 관련해서 남겨주신 내용들 팀원들과 이야기를 나눠봤는데 타입을 제거하는게 좋다고 생각해서 제거했습니다 😄 
현재 조건이 최소 값에 대한 부분 밖에 없고, 조건이 없다면 0으로 충분히 표현이 가능하다고 생각했어요!

2023-05-31 12:59 UTC, greeng00se commented on src/main/resources/schema.sql
> +    `policy_type`           varchar(255)     NOT NULL,
해당 부분에 있어 사용시 혼선이 있을 것 같아 아래 댓글 남겨주신대로 Type + Value로 표현하도록 변경했습니다!

2023-05-31 13:03 UTC, greeng00se commented on src/main/resources/schema.sql
> +    `discount_percent`      int              NOT NULL,
해당 테이블에 어떤 값이 들어갈 지 정할 때, Type + Value도 고려했었는데, price와 delivery의 경우 할인하는 값으로 충분히 표현이 가능할 것 같았지만, 비율 할인 정책을 표현할 때 명시적인 느낌이 들지 않아서 풀어서 작성하기로 결정했어요!

남겨주신 코멘트를 보고 팀원들과 상의 후 조금 더 간결한 방법인 Type + Value로 값을 저장하기로 결정했습니다.
해당 방법으로 데이터를 저장하니, 도메인 로직 작성할 때 기존의 복잡한 구조에서, 조금 더 간결하게 작성할 수 있었습니다 👍

2023-05-31 13:06 UTC, greeng00se commented on src/main/java/cart/domain/cart/Member.java
> +package cart.domain.cart;
member 패키지로 이동하는 것이 더 좋아보입니다! 😢 수정했습니다!

2023-05-31 13:20 UTC, greeng00se commented on src/main/java/cart/domain/common/Money.java
> +package cart.domain.common;
VO로 변경하는 것이 더 명확한 것 같아서 좋아보입니다 👍 
`isGreaterThanOrEqual` 과 같은 메서드는 단순 값 비교로 존재할 수 있는 메서드라고 생각해 유지하도록 하겠습니다!

2023-05-31 13:25 UTC, greeng00se commented on src/main/java/cart/domain/cart/Item.java
> +public interface Item {
이 부분을 추상화했던 이유는 작성 당시에 주문이 완료된 OrderItem이 테이블에 있는 값이 CartItem 클래스로 변경되는 부분이 어색하게 느껴졌습니다.

주문 완료된 것도 사실 장바구니에 들어있던 것이니 CartItem 클래스 하나로 충분할 것 같습니다! 👍

2023-05-31 13:26 UTC, greeng00se commented on src/main/java/cart/domain/cart/OrderItem.java
> +            throw new InvalidCartItemOwnerException();
추상화한 부분 제거하면서, 같이 제거했습니다!

2023-05-31 13:43 UTC, greeng00se commented on src/main/java/cart/domain/common/Money.java
> +public class Money {
정적 팩터리 메서드에서 null값이 대한 검증이 이루어지도록 했습니다!
Money의 생성자를 private으로 두고, 정적 팩터리 메서드만 사용하게 끔 변경했습니다~ 👍

2023-05-31 13:51 UTC, greeng00se commented on src/main/java/cart/domain/coupon/DiscountCondition.java
> +    boolean isSatisfiedBy(final Money totalPrice);
isUpperThanMinimumPrice는 어떨까요?!
-> 현재는 위에 다른 코멘트 반영하면서 현재는 조건에 대한 인터페이스를 제거했습니다!

2023-05-31 15:16 UTC, greeng00se commented on src/main/java/cart/domain/coupon/DiscountPolicyType.java
> +public enum DiscountPolicyType {
코멘트 남겨주신대로 타입이 중심이 되도록 변경했습니다!
대신 현재 할인된 가격, 배달비 계산이 분리되어 있는 구조라 람다 대신 인터페이스를 사용했는데 이 부분은 괜찮을까요?

2023-05-31 15:50 UTC, greeng00se commented on src/main/java/cart/entity/OrderEntity.java
> +    private final Long couponId;
1. 처음에 쿠폰에 대한 부분을 최대한 간단히 만들어보려고 주문이 쿠폰을 가지게 했습니다.
이 부분에 대해서 고민을 많이 해봤는데, 주문 취소를 할 때 문제가 생길 것 같았습니다.
따라서 주문이 MemberCoupon(사용자의 쿠폰)을 가지도록 했습니다.
이 경우에 추후에 한 주문이 두가지 이상 쿠폰이 사용될 수 있는 구조로 만들 때 더욱 전환이 편할 것 같습니다!

2. 두 가지 이상의 쿠폰을 사용하는 경우 고려해야 할 부분(쿠폰의 적용 순서, 상품마다 쿠폰을 적용할 지?)이 많아질 것 같아, 일단 한 개의 주문에서 하나의 쿠폰만 사용이 가능하도록 정하고 시작을 했습니다.

2023-05-31 16:22 UTC, greeng00se commented on src/main/java/cart/service/OrderService.java
> +    public List<OrderResponse> findAll(final Long memberId) {
간단히 조회 시 성능이 조금 더 좋아진다 정도로 알고 있어서 살짝 더 공부해보았습니다!

Transactional(readOnly = true)를 사용하는 경우 setReadOnly(true) 설정이 된 Connection으로 연결을 시도를 한다고 합니다!
이 설정을 하는 경우 DB마다 다르게 동작할 수 있을 것 같습니다.

현재는 h2를 사용하고 있는데 이 경우 h2의 Connection 구현체는 readOnly 설정을 무시하는 방향으로 구현되었기 때문에 Transactional(readOnly = true)가 적용이 안될 것 같습니다!
또한 추후에 사용할 MySQL 8.0의 기본 스토리지 엔진인 InnoDB의 경우 읽기 전용으로 알려진 트랜잭션의 경우 트랜잭션 ID를 설정하지 않기 때문에 조회 속도가 더 빨라질 것 같습니다.

다음 문서를 참고했습니다! https://dev.mysql.com/doc/refman/8.0/en/innodb-performance-ro-txn.html

추가로 ORM 프레임워크를 사용한다면 readOnly = true 설정시 prepareTransactionalConnection를 호출한다고 합니다!
<img width="776" alt="image" src="https://github.com/woowacourse/jwp-shopping-order/assets/58586537/aad73a4e-abd1-43eb-8d3d-668c18277eff">

2023-05-31 16:24 UTC, greeng00se commented on src/main/java/cart/service/OrderService.java
> +    public List<OrderResponse> findAll(final Long memberId) {
아 추가로 빠진 부분 찾아서 설정 완료했습니다! 👍

2023-06-01 06:32 UTC, greeng00se commented on src/main/java/cart/dao/OrderItemDao.java
> +@Repository
알려주신대로 Dao에 `@Transactional` 애너테이션을 적용했습니다!

2023-06-01 08:35 UTC, greeng00se commented on src/main/java/cart/domain/coupon/DiscountConditionType.java
> +public enum DiscountConditionType {
현재 고정 비용 할인, 비율 할인, 배달비 할인을 기준으로 고민해봤을 때

```
1. Enum 사용시 => DB에 Type + Value 값 저장
2. Enum 사용하지 않는 경우 => Type은 DB에 저장하지 않고 Price, Percent, DeliveryFee 필드를 저장하여 사용
```
1. Type + Value로 구현하는 경우 코드레벨에서 조금 더 명확한 느낌을 많이 받았습니다.
하지만 이 경우 고정 비용과 배달비 할인을 동시에 적용하고 싶은 경우, 코드를 수정해야 한다는 단점이 있을 것 같습니다.

2. 동적으로 변경시키는 경우 유연하긴 하지만, 사용시 분기 처리와 같이 불편한 점이 많을 것 같습니다.

전체적으로 쿠폰을 통한 할인의 경우 Type을 저장하는게 더 좋아보입니다.
Type에 따라 할인을 수행하는 클래스나 람다를 이용하여 할인 로직을 분리해서 작성할 수 있는 장점이 있을 것 같습니다.

하지만 사용자의 등급마다 할인율을 조정하거나, 포인트를 차등 지급하는 경우 DB를 통해 동적으로 변경시키는 것이 좋아보입니다.

2023-06-01 08:43 UTC, greeng00se commented
안녕하세용 카일!
2번째 변경사항에 해당하는 범위는 다음과 같습니다. 
[범위](https://github.com/woowacourse/jwp-shopping-order/pull/7/files/6848c857c5ed26df71bb611c19f9eef4f6f73e96..ede83bf36061cacd64a96e86780e2829baf26fb5)

패키지 구조를 조금 변경해서 변경된 파일 수가 많네요.. 😢 

DB 구조는 아래와 같이 약간 변경되었고, 코멘트 위주로 리팩터링 해보았습니다!
<img width="668" alt="image" src="https://github.com/woowacourse/jwp-shopping-order/assets/58586537/1cc936da-6f78-457f-8803-514d9a556115">

Swagger [링크](https://h3rb.shop/swagger-ui/index.html)도 첨부해봅니다!

2023-06-02 15:46 UTC, KIMSIYOUNG commented on src/main/java/cart/controller/CouponController.java
> +    @ApiResponse(
장단점에 대해서 잘 이해하고 사용해주셨네요🙂

2023-06-02 15:48 UTC, KIMSIYOUNG commented on src/main/java/cart/controller/CouponController.java
> +    public ResponseEntity<List<CouponResponse>> findAll(@Auth final Credential credential) {
네네 맞습니다. 모양이 어떠한지에 대해서 궁금하다기보단 위 아래의 구조의 장단점은 무엇일까요?
예를들어서 프론트에서 페이징을 위해 쿠폰의 전체 갯수는 몇개인지가 응답으로 필요하다고 하면 어떨까요?
중단없이 배포한다고 가정하고 고민해보시면 좋을 것 같아요.

2023-06-02 15:50 UTC, KIMSIYOUNG commented on src/main/java/cart/dao/CartItemDao.java
> +    public List<CartItemEntity> findByIds(final List<Long> ids, final Long memberId) {
네네 그 의도도 있었지만, id자체가 식별자인데 memberId를 추가로 쿼리 조건에 넣는다는 것 자체가 어색하지 않으신가요?

2023-06-02 15:55 UTC, KIMSIYOUNG commented on src/main/java/cart/domain/coupon/DiscountCondition.java
> +    boolean isSatisfiedBy(final Money totalPrice);
`이 할인 조건을 적용받을 수 있는` 이라는 의미에 가까운 것 같은데 네이밍이 쉽지않네요😭 말씀주신 방법도 괜찮은 것 같습니다.

2023-06-02 15:55 UTC, KIMSIYOUNG commented on src/main/java/cart/domain/coupon/DiscountPolicyType.java
> +public enum DiscountPolicyType {
오 네네! 람다와 인터페이스의 차이가 무엇인지 인지하고 계신가요?

2023-06-02 15:58 UTC, KIMSIYOUNG commented on src/main/java/cart/entity/OrderEntity.java
> +    private final Long couponId;
1. 사용자의 쿠폰을 만들었을 때 장점은 무엇인가요? 잘 이해하지 못한 것 같아요. 주문 취소할 때 문제가 되는 이유도 잘 모르겠어요 조금 더 구체적으로 설명해주시면 좋을 것 같습니다!
2. 좋은 결정인 것 같습니다. 1:1 과 1:N은 아주 약간 다를 것 같지만 실제로 구현하다보면 매우 많은 것이 달라지는 것 같아요. 특히 1:N이 중첩되는 경우는 더 심한 것 같습니다. 굳이 프로그램을 처음부터 복잡하게 설계할 필요는 없을 것 같아요.

2023-06-02 16:01 UTC, KIMSIYOUNG commented on src/main/java/cart/service/OrderService.java
> +    public List<OrderResponse> findAll(final Long memberId) {
간단하게 드린 질문이었는데 많은 부분을 잘 학습해주셨네요🙂
추가로 현업에서는 고가용성 내결함성 등을 위하여 클러스터를 구성하여 사용하는 경우가 많습니다. (리더, 팔로워 또는 마스터 슬레이브)
이 경우에 리드온리 옵션이 있다면 읽기전용 디비로 질의가 들어가는 효과도 있습니다🙂

2023-06-02 16:05 UTC, KIMSIYOUNG commented on src/main/java/cart/domain/coupon/DiscountConditionType.java
> +public enum DiscountConditionType {
잘 고민해주신 것 같습니다.
말씀해주신대로 동적으로 구현한다면 할인조건을 추가하거나 하는 행위들이 배포없이 이루어질 수 있는 장점이 있지만 또 반대로 가독이 더 어려운 코드가 될 수 있을 것 같아요.
잘 고민해주신대로 장단을 고민하시면서 개발하면 좋을 것 같습니다.
애매한 느낌이라는건 조금 정리가 되셨나요?

2023-06-02 16:30 UTC, KIMSIYOUNG requested changes
안녕하세요 허브
리뷰 반영 깔끔하게 잘 해주셨네요.
몇가지 추가 리뷰 남겼는데 확인 부탁드립니다.

2023-06-02 16:30 UTC, KIMSIYOUNG commented on src/main/java/cart/auth/BasicAuthorizationParser.java
> +        if (Objects.isNull(authorizationHeader) || authorizationHeader.isBlank()) {
Spring에서 제공하는 StringUtils 라는 클래스가 좋더라구요🙂

2023-06-02 16:30 UTC, KIMSIYOUNG commented on src/main/java/cart/controller/CouponIssuanceController.java
> +@RequestMapping("/issuance")
`/coupons` 가 아니라 이름을 `inssuance` 로 정의해주신 이유가 무엇일까요?

2023-06-02 16:30 UTC, KIMSIYOUNG commented on src/main/java/cart/controller/CouponIssuanceController.java
> +    public ResponseEntity<Void> save(@RequestBody final CouponSaveRequest couponSaveRequest) {
Validation이 누락된 것 같아요🙂

2023-06-02 16:30 UTC, KIMSIYOUNG commented on src/main/java/cart/domain/cart/MemberCoupon.java
> +public class MemberCoupon {
기존에는 주문-쿠폰간의 관계를 설계해주신 것 같아요. 변경이 된다하더라도 이 둘의 관계에서 변경될 것 이라 생각했는데 회원-쿠폰의 관계가 추가된 이유는 무엇인가요?

2023-06-02 16:30 UTC, KIMSIYOUNG commented on src/main/java/cart/domain/cart/Order.java
> +    private final MemberCoupon memberCoupon;
회원-쿠폰-주문간의 관계가 어떻게 되나요? 여러 문장으로 정의해주실 수 있나요?

예를들면 아래와 같습니다. 정리하면서 의도했던 것이 모두 만족되는지 확인해보시면 좋을 것 같습니다.
1. 하나의 주문은 하나의 쿠폰만 가질 수 있다.
2. 회원은 여러개의 쿠폰을 가질 수 있다.

2023-06-02 16:30 UTC, KIMSIYOUNG commented on src/main/java/cart/domain/cart/Order.java
> +    private final List<CartItem> items;
주문이 주문아이템이 아니라 카트아이템을 가지고 있는게 자연스러울까요?
현재는 장바구니에 들어있는 주문을 주문한다라는 개념이기에 자연스러울지 모르지만, 이미 주문한 주문내역을 볼 때 주문과 카트내역을 보여준다라는 개념은 어색하지 않나요?

주문은 주문상품과 엮이는 것이고, 현재는 카트에 들어있는 상품들이 주문상품이 되어 주문되는 것 같아요.

2023-06-02 16:30 UTC, KIMSIYOUNG commented on src/main/java/cart/service/OrderService.java
> +        final List<CartItem> items = cartItemRepository.findAllByIdsAndMemberId(request.getOrderItemIds(), memberId);
여기서도 OrderItemIds와 CartItem이 혼재되어 있는 것 같아요.

2023-06-02 16:30 UTC, KIMSIYOUNG commented on src/main/resources/application.yml
> +  profiles:
프로파일의 개념도 학습해주셨네요👏

2023-06-02 16:30 UTC, KIMSIYOUNG commented on src/main/java/cart/domain/coupon/DiscountPolicyType.java
> +    public Money calculateDiscountValue(final Long discountValue, final Money money) {
수정해주시면서 사용하는 곳들이 깔끔해졌네요🙂
인터페이스 + 클래스로 구현해주신 이유가 있나요?

2023-06-03 04:38 UTC, greeng00se commented on src/main/java/cart/auth/BasicAuthorizationParser.java
> +        if (Objects.isNull(authorizationHeader) || authorizationHeader.isBlank()) {
`StringUtils.hasText()`로 변경해보겠습니다 👍

2023-06-03 04:52 UTC, greeng00se commented on src/main/java/cart/controller/CouponController.java
> +    public ResponseEntity<List<CouponResponse>> findAll(@Auth final Credential credential) {
편하고 간단하다고 배열을 사용하게 된다면 결국에는 확장성을 가지지 못한 구조를 가지게 되고,
중단없이 배포할 때 추가로 페이징 요소나, 요구사항이 변경됨에 따라 추가적인 정보의 반환이 필요할 때 쉽게 추가하지 못한다는 문제가 생길 것 같습니다!

2023-06-03 15:24 UTC, greeng00se commented on src/main/java/cart/domain/coupon/DiscountCondition.java
> +    boolean isSatisfiedBy(final Money totalPrice);
코드를 같이 보는 사람이 바로 이해할 수 있도록 네이밍에 대한 고민도 항상 해봐야겠습니다.. 코멘트 남겨주셔서 감사합니다 😄

2023-06-03 17:35 UTC, greeng00se commented on src/main/java/cart/dao/CartItemDao.java
> +    public List<CartItemEntity> findByIds(final List<Long> ids, final Long memberId) {
해당 부분 뿐만이 아니라 사용하는 곳을 보니 더 어색한 느낌이 많이 드는 것 같습니다.
검증 로직을 도메인으로 옮기고 해당 부분은 단순하게 id로 조회하도록 변경했습니다!

2023-06-03 17:51 UTC, greeng00se commented on src/main/java/cart/domain/coupon/DiscountPolicyType.java
> +public enum DiscountPolicyType {
람다는 함수형 인터페이스의 구현을 간단하게 만들어주고, 인터페이스는 보통 타입을 정의하는 용도로 사용됩니다!
함수형 인터페이스 -> 람다 / 인터페이스 -> 구현체의 관계에서
위에 제가 단 코멘트에서 람다 대신 인터페이스의 구현체를 사용했다고 남겼어야 더 정확할 것 같습니다.

2023-06-03 18:12 UTC, greeng00se commented on src/main/java/cart/entity/OrderEntity.java
> +    private final Long couponId;
### 주문 취소할 때 문제가 된 부분에 대한 생각

팀원들과 초기 설계 과정에서 동일한 쿠폰을 여러개 발급한다면 쿠폰의 정보가 중복되는 것이 아닐까? 라고 생각했고 
따라서 MemberCoupon 테이블을 추가했습니다.

`처음에 쿠폰에 대한 부분을 최대한 간단히 만들어보려고 주문이 쿠폰을 가지게 했습니다.` <- 이 상황에서 이미 MemberCoupon 테이블이 존재했고, MemberCoupon을 가지는게 아닌 Coupon을 가지도록 해서 문제가 발생했습니다.

<img width="773" alt="image" src="https://github.com/woowacourse/jwp-shopping-order/assets/58586537/f34b52c2-bb1a-4cd4-98b7-b9ecc14c5bd5">

Coupon1을 사용자1에게 여러 개 발급한다면, 사용여부를 미사용으로 되돌릴 때 어떤 쿠폰을 미사용으로 되돌릴 지 명확하지 않다는 것이 문제라고 생각했습니다. (현재 구현은 안되어있지만, 추후에 유효기간 등을 고려했었습니다.)

---

중복을 제거하기 위해 MemberCoupon 테이블을 추가한 것이 현재 상황에서 복잡도를 증가시켰다고 생각합니다.
애초에 MemberCoupon 테이블을 만들지 않고 다음과 같이 하나의 주문이 하나의 쿠폰을 가지고 있으면 별 문제가 없었을 것 같습니다.

<img width="600" alt="image" src="https://github.com/woowacourse/jwp-shopping-order/assets/58586537/3583e140-2e96-4646-a2f3-0eaa1c0c5fab">

2023-06-03 18:14 UTC, greeng00se commented on src/main/java/cart/service/OrderService.java
> +    public List<OrderResponse> findAll(final Long memberId) {
읽기 전용 DB가 따로 있다면 readOnly 설정을 할 때 읽기 전용 DB로 부하가 가는군요! 좋은 정보 감사합니다 😄

2023-06-03 18:16 UTC, greeng00se commented on src/main/java/cart/domain/coupon/DiscountConditionType.java
> +public enum DiscountConditionType {
덕분에 정리가 많이 된 것 같습니다!
좋은 질문 해주셔서 정말 감사합니다!
잘 정리되어있지 않다면 앞으로 카일이 질문해주신 것 처럼 어떤 장단이 있을 지 자신에게 질문을 해보면서 정리하는 것이 좋을 것 같습니다!

2023-06-03 18:21 UTC, greeng00se commented on src/main/java/cart/controller/CouponIssuanceController.java
> +@RequestMapping("/issuance")
/coupons에 다음과 같이 인증관련 인터셉터가 설정되어 있었습니다.
```java
registry.addInterceptor(authInterceptor)
        .addPathPatterns("/cart-items/**")
        .addPathPatterns("/coupons/**")
        .addPathPatterns("/orders/**");
```

이 때 HttpMethod 별로 설정하는 좋은 방법을 찾지 못해 일단 분리했습니다.. 😢 
혹시 좋은 방법에 대한 힌트를 얻을 수 있을까요?

또한 관리자 페이지에서 동작하는 기능이라 컨트롤러를 분리해도 괜찮을 것 같았다고 생각했습니다. 
서비스는 따로 분리하지 않았는데 이 경우 서비스도 분리해야 할까요?

2023-06-03 18:38 UTC, greeng00se commented on src/main/java/cart/controller/CouponIssuanceController.java
> +    public ResponseEntity<Void> save(@RequestBody final CouponSaveRequest couponSaveRequest) {
전반적으로 Validation 다시 확인해서 빠진 부분 추가했습니다!

2023-06-03 18:49 UTC, greeng00se commented on src/main/java/cart/domain/cart/MemberCoupon.java
> +public class MemberCoupon {
[관련 내용](https://github.com/woowacourse/jwp-shopping-order/pull/7#discussion_r1215701346)

팀원들과 초기 설계 과정에서 동일한 쿠폰을 여러개 발급한다면 쿠폰의 정보가 중복되는 것이 아닐까? 라고 생각했고
따라서 MemberCoupon 테이블을 추가했습니다.
하지만 구현할 때 잘못 생각하여 Order가 MemberCoupon이 아닌 Coupon을 들고 있도록 작성을 했습니다.
(초기 단계에 MemberCoupon 테이블은 있었지만 MemberCoupon 클래스를 만들지 않았습니다.)

---

작은 중복을 제거하기 위해 MemberCoupon 테이블을 추가한 것이 복잡도를 증가시켰다고 생각합니다.
따라서 다음과 같이 구현하는 것이 더욱 명료하다고 생각합니다.

<img width="600" alt="image" src="https://github.com/woowacourse/jwp-shopping-order/assets/58586537/3583e140-2e96-4646-a2f3-0eaa1c0c5fab">

2023-06-03 18:58 UTC, greeng00se commented on src/main/java/cart/domain/cart/Order.java
> +    private final MemberCoupon memberCoupon;
회원 - Member, 쿠폰 - Coupon, 주문 - Order, 회원 쿠폰 - MemberCoupon 이라고 하겠습니다.

1. `회원`은 여러 개의 `회원 쿠폰`을 가질 수 있다.
2. 하나의 `주문`은 하나의 `회원 쿠폰`만 적용이 가능하다.
3. `회원 쿠폰`은 하나의 `쿠폰`을 가지고 있다.

글로 정리하니까 의도한 부분은 만족되지만, 회원 쿠폰 부분이 많이 어색한 것 같습니다. 😢

2023-06-04 08:09 UTC, greeng00se commented on src/main/java/cart/domain/cart/Order.java
> +    private final List<CartItem> items;
자연스럽지 않다고 생각되어 order와 cart 패키지를 분리하고 OrderItem 클래스를 추가하였습니다!
아래와 같이 OrderService에서 CartItem을 조회해서, OrderItem으로 변경한 뒤 저장을 했습니다.

```java
final List<Long> orderItemIds = request.getOrderItemIds();
final List<OrderItem> orderItems = cartItemRepository.findAllByMemberId(memberId).stream()
        .filter(cartItem -> orderItemIds.contains(cartItem.getId()))
        .collect(collectingAndThen(toList(), this::toOrderItems));

final Coupon coupon = couponRepository.findById(request.getCouponId())
        .orElse(Coupon.EMPTY);

final Order order = Order.of(coupon, memberId, orderItems);
```

남겨주신 코멘트로 연관관계를 적당히 끊으니, 테스트도 더욱 간단하고 깔끔해졌습니다! 감사합니다 😄

2023-06-04 08:09 UTC, greeng00se commented on src/main/java/cart/service/OrderService.java
> +        final List<CartItem> items = cartItemRepository.findAllByIdsAndMemberId(request.getOrderItemIds(), memberId);
위에 코멘트 반영하면서 같이 반영했습니다 👍

2023-06-04 08:47 UTC, greeng00se commented on src/main/java/cart/domain/coupon/DiscountPolicyType.java
> +    public Money calculateDiscountValue(final Long discountValue, final Money money) {
클래스에 아래와 같이 0원 아래로 내려간다면 0원을 반환하는 로직을 두었습니다.

```java
final Money subtrahend = price.times(Double.valueOf(discountValue) / RATIO_DIVISOR);
final Money result = price.minus(subtrahend);
if (result.isGreaterThanOrEqual(Money.ZERO)) {
    return result;
}
return Money.ZERO;
```

로직이 생각보다 많아져서 인터페이스 + 클래스로 분리했었습니다.
지금 생각해보니 enum에 계산 로직을 넣고, 계산하는 메서드 내에 해당 로직을 넣어두는 것이 더 간결할 것 같습니다.
또한 BiFunction<Long, Money, Money> 부분을 커스텀 함수형 인터페이스로 만들어서 조금 더 비즈니스 로직과 가깝게 표현해볼 수 있을 것 같습니다.

```java
public enum DiscountPolicyType {
    NONE(
            (discountValue, price) -> price,
            (discountValue, price) -> price
    ),
    PRICE(
            (discountValue, price) -> price.minus(Money.from(discountValue)),
            (discountValue, price) -> price
    ),
    PERCENT(
            (discountValue, price) -> price.minus(price.times(Double.valueOf(discountValue) / 100L)),
            (discountValue, price) -> price
    ),
    DELIVERY(
            (discountValue, price) -> price,
            (discountValue, price) -> price.minus(Money.from(discountValue))
    ),
    ;

    private final CalculateFunction discountValueCalculator;
    private final CalculateFunction deliveryFeeCalculator;

    DiscountPolicyType(final CalculateFunction discountValueCalculator, final CalculateFunction deliveryFeeCalculator) {
        this.discountValueCalculator = discountValueCalculator;
        this.deliveryFeeCalculator = deliveryFeeCalculator;
    }

    public static DiscountPolicyType from(final String name) {
        return Arrays.stream(values())
                .filter(discountPolicyType -> discountPolicyType.name().equalsIgnoreCase(name))
                .findFirst()
                .orElseThrow(DiscountPolicyNotFoundException::new);
    }

    public Money calculateDiscountValue(final Long discountValue, final Money money) {
        return discount(discountValueCalculator, discountValue, money);
    }

    private Money discount(final CalculateFunction calculateFunction, final Long discountValue, final Money money) {
        if (discountValue == 0L) {
            return money;
        }
        final Money result = calculateFunction.apply(discountValue, money);
        if (Money.ZERO.isGreaterThanOrEqual(result)) {
            return Money.ZERO;
        }
        return result;
    }

    public Money calculateDeliveryFee(final Long discountValue, final Money money) {
        return discount(deliveryFeeCalculator, discountValue, money);
    }
}

```

2023-06-04 12:02 UTC, greeng00se commented
[리뷰 범위](https://github.com/woowacourse/jwp-shopping-order/pull/7/files/e98d593f80ebaf1197487f596cfc1515f7ce1f4f..e3bbe379e521dd9a1e21f2d5dd342f7b7f0c6119)

안녕하세요 카일!
너무 필요한 리뷰를 많이 남겨주셔서 힘을 내어 리뷰를 반영해보았습니다.

큰 변경사항은 다음과 같습니다.
1. MemberCoupon 제거
2. 할인 정책 부분 인터페이스 + 구현체 -> 함수형 인터페이스 + 람다로 변경
3. CartItem과 OrderItem 분리
4. cart 패키지와 order 패키지 분리
5. 인수테스트 추가

감사합니다 😄

2023-06-05 08:56 UTC, KIMSIYOUNG commented on src/main/java/cart/controller/CouponController.java
> +    public ResponseEntity<List<CouponResponse>> findAll(@Auth final Credential credential) {
잘 인지하고 계신 것 같습니다🙂

2023-06-05 08:58 UTC, KIMSIYOUNG commented on src/main/java/cart/domain/coupon/DiscountPolicyType.java
> +public enum DiscountPolicyType {
네네 잘 인지하고 계신 것 같습니다.

2023-06-05 09:05 UTC, KIMSIYOUNG commented on src/main/java/cart/controller/CouponIssuanceController.java
> +@RequestMapping("/issuance")
아하 관리자페이지를 위한 기능이라면 다른 용어로 사용하기 보단(coupon, issuance) path에 어드민을 작성해주는 것이 더 가독에 어려움이 없을 것 같아요. 

추가로 저는 분리하는 것이 좋은 것 같습니다. 일반적으로 관리, VOC, 데이터처리에 해당하는 요구사항과 사용자향서비스에 들어오는 요구사항은 그 성향이 다른 경우가 많습니다.

그렇기에 한 곳에서 관리한다면 2가지 경우에 대한 복잡도를 한 곳에서 관리해야하여 어려움이 있을 것 같아요.

2023-06-05 09:10 UTC, KIMSIYOUNG commented on src/main/java/cart/domain/cart/MemberCoupon.java
> +public class MemberCoupon {
아하 설명 감사합니다. 현재의 구조에 대해서는 이해했습니다. 조금 더 이야기해보자면

`동일한 쿠폰을 여러개 발급한다면 쿠폰의 정보가 중복되는 것이 아닐까`라는 것은 `MemberCoupon`이 생기게되는 이유와 어떻게 이어지는걸까요? 아직 조금 이해가 안된 부분이 있는 것 같아요.

2023-06-05 09:12 UTC, KIMSIYOUNG commented on src/main/java/cart/domain/cart/Order.java
> +    private final List<CartItem> items;
잘 변경해주신 것 같습니다🙂
collectingAndThen 보단 map으로 변환해주어도 될 것 같네요

2023-06-05 09:14 UTC, KIMSIYOUNG commented on src/main/java/cart/domain/coupon/DiscountPolicyType.java
> +    public Money calculateDiscountValue(final Long discountValue, final Money money) {
넵넵🙂 잘 수정해주신 것 같습니다.

2023-06-05 09:24 UTC, KIMSIYOUNG approved these changes
안녕하세요 허브
리뷰 반영 잘 해주신 것 같습니다.
마지막 미션(?) 여기서 머지하려고 하는데요.
궁금하신 내용이나 더 이야기 나누고 싶은 내용 있으시면, 디엠주시면 같이 논의해보면 좋을 것 같습니다.
고생 많으셨습니다.

2023-06-05 09:24 UTC, KIMSIYOUNG commented on src/main/java/cart/controller/CouponIssuanceController.java
> +        return ResponseEntity.ok().build();
수정해주신대로 꼭 201을 사용할 필요는 없습니다🙂
이전 미션들에서 규약을 지키는 연습을 해보셨으니 이제는 편리한 방향 또는 협의된 방향으로 개발해도 충분할 것 같네요.

2023-06-05 09:24 UTC, KIMSIYOUNG commented on src/main/java/cart/domain/cart/CartItem.java
> +    private final Long memberId;
member에서 memberId로 변경된 이유는 무엇인가요? 이 둘을 어떻게 구분하시나요

2023-06-05 09:24 UTC, KIMSIYOUNG commented on src/main/java/cart/domain/coupon/CalculateFunction.java
> +    Money apply(final Long discountValue, final Money price);
아래와 동일한데 클래스로 있는 이유는 네이밍으로 명확하게 보장하기 위함인가요?
```java
private final BiFunction<Long, Money, Money> discountValueCalculator;
```

2023-06-05 09:24 UTC, KIMSIYOUNG commented on src/test/java/cart/acceptance/CartItemAcceptanceTest.java
> +        요청_결과의_상태를_검증한다(요청_결과, 정상_생성);
가독이 좋으시다면 문제없지만 굳이 모두 한글로 작성하지 않아도 괜찮을 것 같네요🙂
1. IDE지원이 좋지 않음.
2. 의미는 이해했지만 어떠한 코드를 예상하고 봐야함. (코드만으로 의미를 이해시키며 잘 읽히게 할 수 있다면 그게 더 나을 것 같음)
의미가 잘 와닿지 않는 부분만 작성해보면 어떨까요?

2023-06-05 09:24 UTC, merged

2023-06-05 14:40 UTC, greeng00se commented on src/main/java/cart/controller/CouponIssuanceController.java
> +@RequestMapping("/issuance")
말씀해주신대로 /admin/coupons 정도가 적당하다고 생각합니다!
저도 관리용과 사용자를 위한 api를 분리하는 것이 좋다고 생각합니다! 
너무 좋은 인사이트 감사합니다 👍 👍

2023-06-05 14:47 UTC, greeng00se commented on src/main/java/cart/domain/coupon/CalculateFunction.java
> +    Money apply(final Long discountValue, final Money price);
비즈니스 로직과 관련된 함수형 인터페이스를 만드려고 했습니다. 근데 지금보니 네이밍이 별로인 것 같네요 😢 
이펙티브 자바의 `아이템 44. 표준 함수형 인터페이스를 사용하라`를 따라서 BiFunction을 사용하는 게 코드를 보는 입장에서 더욱 빠르게 해당 코드를 이해할 수 있을 것 같습니다.

2023-06-05 14:48 UTC, greeng00se commented on src/main/java/cart/controller/CouponIssuanceController.java
> +        return ResponseEntity.ok().build();
꼼꼼하게 봐주셔서 감사합니다! 👍

2023-06-05 14:52 UTC, greeng00se commented on src/test/java/cart/acceptance/CartItemAcceptanceTest.java
> +        요청_결과의_상태를_검증한다(요청_결과, 정상_생성);
확실히 이번에 작성해보면서 IDE 지원이 좋지 않은 걸 느꼈습니다.
시간 효율이 많이 떨어진다는 느낌이 많이 들었습니다.
말씀해주신대로 필요한 부분에 적절하게 한글 메서드를 이용해보는것도 좋을 것 같습니다! 👍

2023-06-05 14:57 UTC, greeng00se commented on src/main/java/cart/domain/cart/Order.java
> +    private final List<CartItem> items;
CartItem에 값을 가져오는 메서드를 추가하고 아래와 같이 수정했습니다! 👍 

```java
final List<Long> orderItemIds = request.getOrderItemIds();
final List<OrderItem> orderItems = cartItemRepository.findAllByMemberId(memberId).stream()
        .filter(cartItem -> orderItemIds.contains(cartItem.getId()))
        .map(cartItem -> new OrderItem(
                cartItem.getProductName(),
                cartItem.getProductImageUrl(),
                cartItem.getProductPrice(),
                cartItem.getQuantity()
        ))
        .collect(toList());

final Coupon coupon = couponRepository.findById(request.getCouponId())
        .orElse(Coupon.EMPTY);

final Order order = Order.of(coupon, memberId, orderItems);
```

2023-06-05 15:00 UTC, greeng00se commented on src/main/java/cart/domain/cart/CartItem.java
> +    private final Long memberId;
Member를 가지지 않아도 된다고 생각했습니다. Member 관련된 비즈니스 로직이 내부에 존재하지 않고, 해당 CartItem의 소유자 확인의 경우 memberId로 충분하다고 생각했습니다!

현재 CartItem을 제외한 다른 클래스를 보면 Member를 가지고 있는게 아닌 memberId를 가지고 있습니다. 따라서 일관성을 이유로 memberId로 변경한 이유도 있습니다.

2023-06-05 15:47 UTC, greeng00se commented on src/main/java/cart/domain/cart/MemberCoupon.java
> +public class MemberCoupon {
예를 들어 new Coupon("3만원 이상 5000원 할인 쿠폰", PRICE, 5000, 30000) 라는 정보를 가진 클래스가 있다면, 이를 여러장 발급하고 싶을 때 DB에 "3만원 이상 5000원 할인 쿠폰", PRICE, 5000, 30000 라는 값이 중복으로 들어가는게 아닐까? 라는 생각을 했습니다. 

MemberCoupon이 있다면 10000장을 발급한다고 할 때 동일한 쿠폰에 대한 정보를 10000번 저장하지 않고 쿠폰의 id와 사용자의 id 그리고 사용 여부 중복을 제거할 수 있지 않을까? 라고 생각했습니다!

하지만 조금 더 고민해 본다면, 애플리케이션 크기에 비해 필요 이상으로 복잡도를 증가시킨 것이 아닌지? 
해당 정보에 대해 중복을 제거하려고 애플리케이션의 복잡도를 올린 것이 비용 측면에서 더 좋은가에 대해서 고민해볼 수 있을 것 같습니다.

관리 비용, 유지 보수 비용을 생각해보았을 때 현재 데이터를 저장하는 비용보다 더 비싸다고 생각되는데 카일은 어떻게 생각하시나요?

2023-06-15 01:55 UTC, KIMSIYOUNG commented on src/main/java/cart/domain/cart/MemberCoupon.java
> +public class MemberCoupon {
아하 쿠폰이 항상 고정된 쿠폰이 되는군요🙂 이해했습니다.
만약에 저라면 확장성을 위해선 모두 동적으로 만들겠지만 현재의 프로그램이라면 쿠폰에 대한 정보는 어플리케이션에서 관리하고 그 쿠폰의 번호정도만 DB에 기록하는 형태로 진행할 것 같습니다. 
분명 단점과 한계도 있지만 어플리케이션을 이해하는데 가장 직관적인 방법인 것 같아요. 

현재의 구조도 괜찮다고 생각합니다. 다만 말씀하신대로 중복을 제거하는 방법을 고려하실 때, 쿠폰이 항상 테이블로 존재하지 않아도 되고 그렇게 했을 때도 복잡도를 낮출 수 있다 정도로만 이해해주시면 될 것 같습니다.

2023-06-15 01:57 UTC, KIMSIYOUNG commented on src/main/java/cart/domain/cart/CartItem.java
> +    private final Long memberId;
아하 네네 객체를 직접참조하는 것과 아이디를 참조하는 것은 조금 더 고민해보면 좋은 주제인 것 같습니다. 객체지향적인 관점으로 바라보았을 때 객체를 참조함으로써 얻을 수 있는 장점과 객체 그래프를 그릴 수 있다는 장점이 존재하지만, 반대로 단점으로는 불필요한 쿼리가 나갈 수 있고, 의존관계가 강하게 결합된다는 단점도 있을 것 같아요.

전후자에 대한 장단점은 옳다 그르다 또는 이상적이다로 판단하지 않으셨으면 좋겠고, 프로젝트를 진행하면서 어떤 이점을 택하는게 조금 더 개발에 용이할까를 주로 고민해주시면 좋을 것 같습니다.

2023-06-15 01:58 UTC, KIMSIYOUNG commented on src/main/java/cart/domain/coupon/CalculateFunction.java
> +    Money apply(final Long discountValue, final Money price);
네네🙂 이미 잘 제공되고 있고, 그것에 익숙한 사람이 더 많지 않을까 조심스럽게 추측해봅니다.
물론 허브가 함께하는 사람이 별도의 인터페이스를 정의하는게 더 익숙하신 분들이 많다면 지금 구조가 더 나은 구조이겠지요