[2단계 - 주문 기능 구현] 밀리(김미성) 미션 제출합니다.
woowacourse/jwp-shopping-order pull request #71
Opened 2023-06-04 10:00 UTC by miseongk

안녕하세요 라빈! 밀리입니다😊
2단계는 박스터와 함께 진행했습니다.
[2단계 커밋](https://github.com/woowacourse/jwp-shopping-order/commit/631bb910f59bbebc1eccd66698bf5bd2c408d32b) 부터 확인해주세요!

생각보다 구현하는게 어려워서 리뷰요청이 늦어졌습니다..
저희는 일정 금액 이상 주문 시 쿠폰을 발급해주는 방식을 선택했습니다.
쿠폰의 특성 상 다양한 경우가 많아서 확장성 있는 구현을 하려고 많은 고민을 했습니다.
그런데 모든 경우의 수를 만족하도록 구현하기가 너무 어려워서, 
일단은 금액에 따른 쿠폰을 발급해주는 것에 맞춰 구현했습니다!

리뷰 잘 부탁드립니다!
감사합니다.

2023-06-05 16:18 UTC, giantim requested changes
밀리 안녕하세요! 리뷰어 라빈입니다 👋
전체적인 도메인간의 관계나 계층별 역할을 잘 설계해주신거 같아요. 서비스 계층이 간결하고 도메인 클래스들에 요구사항 기능 구현을 위한 것들이 다 잘 정의되어있네요 👍 또한 테스트도 계층별로 잘 작성하신것 같습니다! 
몇 가지 리뷰 남겨드렸는데 확인 부탁드릴께요~~

2023-06-05 16:18 UTC, giantim commented on src/main/java/cart/domain/Item.java
> +    }
Item의 내부 필드를 변경할 수 있는거 같은데 불변객체로 설계하지 않으신 이유가 있을까요?

2023-06-05 16:18 UTC, giantim commented on src/main/java/cart/domain/Order.java
> +        this.id = null;
이미 기본으로 null이어서 굳이 작성하지 않아도 될것 같네요!

2023-06-05 16:18 UTC, giantim commented on src/main/java/cart/domain/coupon/MemberCoupon.java
> +        }
메소드 이름이 부정문인데 거기에 ! 연산까지 진행해서 구조가 이해하기 어려울 수 있을것 같아요. 메소드를 긍정문으로 바꿔보면 어떨까요?

2023-06-05 16:18 UTC, giantim commented on src/main/java/cart/domain/coupon/discountpolicy/FixedDiscountPolicy.java
> +        return isGreaterThanZero;
```suggestion
        return discountValue.compareTo(BigDecimal.ZERO) > 0;
```
위 처럼 간결하게 바꿔보면 어떨까요? 전체적으로 비슷한 메소드들이 많은데 다같이 바꿔보면 좋을것 같아요!

2023-06-05 16:18 UTC, giantim commented on src/main/java/cart/exception/ExceptionType.java
> +    ),
이 type 값들은 정의하신 BaseException의 경우에만 적용되나요?
UNAUTHORIZED_MEMBER는 사용처가 없는거 같은데 어느 경우를 위해 정의해두신 걸까요?

2023-06-07 11:14 UTC, miseongk commented on src/main/java/cart/domain/coupon/discountpolicy/FixedDiscountPolicy.java
> +        return isGreaterThanZero;
이 부분은 compareTo 메서드가 코드를 한번에 이해하는데 어렵다고 느껴져서 변수로 빼보았습니다!

2023-06-07 12:25 UTC, miseongk commented on src/main/java/cart/domain/Order.java
> +        this.id = null;
현재 id 필드는 final이여서 초기값을 설정하지 않으면 안되는걸로 알고있습니다..!
혹시 다른 의미로 피드백을 주신건가요??

2023-06-07 12:55 UTC, miseongk commented on src/main/java/cart/domain/Item.java
> +    }
장바구니에 담긴 상품의 수량을 변경하는 로직이 도메인 내부에 있지 않고, 불변객체로 만들고 CartItemService에서 수정된 객체를 새로 만들어서 데이터베이스에 저장해도 됩니다. 하지만 객체 지향적 관점에서 서비스에서 이런 로직을 처리하지 않고 객체가 스스로 일을 할 수 있도록 하는 것이 좋겠다고 생각했습니다. 그리고 수량이 변경되는 일은 자주 일어나는 일이기 때문에 그 때마다 새로운 객체를 생성하는 것이 좋지 않을것 같다고 생각했습니다.

2023-06-07 13:00 UTC, miseongk commented on src/main/java/cart/domain/coupon/MemberCoupon.java
> +        }
그렇네요! 수정했습니다.

2023-06-08 05:47 UTC, miseongk commented on src/main/java/cart/exception/ExceptionType.java
> +    ),
ExceptionType은 BaseException의 경우 외에도 모든 발생할 수 있는 예외 타입을 관리하는 Enum으로 만들었습니다!
UNAUTHORIZED_MEMBER는 지우는 것을 깜빡했네요.. 제거했습니다.

그런데 현재 도메인, Service, Repository에서 예외처리를 할 때 모두 ExceptionType을 가진 예외를 던지도록 하는 구조입니다. 그렇게 하니 모든 레이어에서 HttpStatus를 알게된다는 문제가 있다는 것을 알게되었습니다. 불필요한 HttpStatus를 가져도 큰 문제는 없지만 어색하다는 의견을 들었고, 저도 그렇게 생각해서 구조를 바꿔보았습니다. 
ExceptionType에는 예외 메세지 정도만 가지고 있고, ExceptionHandler에서 예외 처리해줄 때 해당 발생한 예외와 맞는 (HttpStatus를 가지고 있는) ExceptionStatus를 찾아와 HttpStatus를 반환하도록 수정했습니다. 

라빈은 이 부분에 대해서 어떻게 생각하시나요?? 이전 코드와 같이 HttpStatus를 가진 예외를 모든 레이어에서 발생시켜도 괜찮다고 생각하시나요?

2023-06-08 06:06 UTC, miseongk commented
안녕하세요 라빈!
피드백 주신 부분 이외에도 수정하고 싶은 부분들을 리팩토링했습니다.

먼저 prod환경과 local 환경의 DB를 분리했습니다.

그리고 원래는 MethodArgumentResolver에서 헤더로 들어온 사용자를 검증하고, email과 password를 가진 사용자 정보를 그대로 컨트롤러로 넘겨주었습니다. 그런데 이 Member는 컨트롤러, 서비스 등에서 모두 알고있고 password와 같은 정보를 들고 있어 그대로 노출되면 문제가 있지 않을까라는 의견을 들었습니다. 생각을 해보니 데이터베이스에서 member를 가져올 때 사용자의 password는 사용자 인증 이외에는 가져오면 안될거라는 생각이 들었습니다. 
그래서 고민을 하다가, MethodArgumentResolver에서만 password를 가진 AuthMember 객체를 가져오고, 그 이후에는 member의 주요 정보가 빠진 Member 객체를 사용하는 것으로 생각해보았습니다. 
```java
public class AuthMember {

    private final Member member;
    private final String password;
}
```
```java
public class Member {

    private final Long id;
    private final String email;
}
```

그리고 Order, CartItem, MemberCoupon과 같이 Member를 가지고 있는 도메인들도 password가 없는 Member를 들고 있게 했습니다.

현재 변경한 구조가 지금으로써 최선이라고 생각이 드는데, 어떻게 생각하시나요?
보통 현업에서도 이런 주요 정보들은 데이터베이스에서 가져오지 않을 것 같은데, 어떤식으로 설계가 되는지 궁금합니다! 

리뷰요청이 많이 늦어서 죄송합니다😢
감사합니다 잘 부탁드립니다!

2023-06-09 06:06 UTC, giantim commented on src/main/java/cart/domain/Item.java
> +    }
수량 변경 로직도 충분히 서비스가 아닌 도메인에 메시지를 던져서 처리할 수 있어 보이는데요!
그리고 아무리 자주 발생하는 수량 변경이어도 새로운 객체를 생성하고 없애는 일은 성능상 아무 영향이 없을거에요!

2023-06-09 06:07 UTC, giantim commented on src/main/java/cart/domain/Order.java
> +        this.id = null;
아하 final 때문이었군요~

2023-06-09 06:09 UTC, giantim commented on src/main/java/cart/domain/coupon/discountpolicy/FixedDiscountPolicy.java
> +        return isGreaterThanZero;
compareTo와 같이 오래된 인터페이스에 대해서는 굳이 변수로 도출하지 않고 간결하게 작성하는게 더 좋아보이는데요.
해당 정책을 사용하는 클라이언트 입장에서는 메소드 이름으로 충분히 어떤 동작을 할것임을 기대했기 때문에 내부 로직을 더 간결하게 작성해보는게 좋아보여요.

2023-06-09 06:28 UTC, giantim commented on src/main/java/cart/exception/ExceptionType.java
> +    ),
지금 구조처럼 정의하는게 이전 구조보다 괜찮아 보이네요.
밀리가 생각하신대로 모든 계층에 http 상태 코드가 퍼져있으면 통신 방법을 바꾸거나 했을 때 영향도가 클 수 있네요! 지금 구조로 리팩토링 잘 하신거 같아요 👍

다만 정의하신 ExpceptionStatus에 별도의 errorCode에 대한 정의가 꼭 필요한가에 대해서는 의문이에요. 지금보다 도메인 규모가 커지고 요구사항이 늘어났을 때 각 예외상황마다 별도의 코드를 관리해주고 이것에 대해 프론트나 API를 사용하는 다른 서버들과도 계속해서 협의해야하는 사항이기 때문에 유지보수할 사항이 늘어난것에 대해서는 고민이 있네요. 관련한 내용은 팀 협업을 해보시면서 크루분들과 논의해서 좋은 방향을 찾아나가보면 좋을것 같아요 😉

2023-06-09 06:30 UTC, giantim approved these changes
밀리 안녕하세요! 라빈입니다 👋
리뷰 남겨드린 내용 이외에 스스로 많은 부분을 리팩토링 해주셨네요 👏 리뷰 드렸던 내용 이외에도 수정한 부분들로 인해 전체적으로 더 좋은 방향으로 개선해주신것 같아요! 코멘트 남겨주신 내용에 대해서 제 의견 더 남겨드렸습니다. 참고해주시고 다음 단계에 도움 되셨으면 좋겠네요 😄
이번 단계는 여기서 마무리해도 좋을것 같고 고생 많으셨습니다 👋

2023-06-09 07:05 UTC, merged