[2단계 - 주문 기능 구현] 루카(백경환) 미션 제출합니다.
woowacourse/jwp-shopping-order pull request #81
Opened 2023-06-05 01:55 UTC by dooboocookie

안녕하세요 조앤😀
백엔드 5기 루카🐟입니다!!

이번에 장바구니 미션이 하면 할 수록 고려할 게 많더라구요..😭
그리고 프론트와의 협업 과정에서 일단 배포부터 시켜야된다는 시간 압박이 좀 있어서,
TDD나 단위테스트를 하지 못하고 먼저 기능부터 구현하는데 급급했습니다.

테스트를 짜면 시간안에 제출을 못할 것 같아서, 현재도 통합 테스트를 제외한 테스트는 있지 않는 상태입니다.. 양해 부탁드립니다.
제출 후 테스트 작성하고 피드백 주시면 그를 토대로 리팩토링해보겠습니다 😭

---

 # 설명
(리드미에 있는 내용들입니다)

### [API 명세](https://www.notion.so/wooteco-ash/API-6a650176015c4d76a76b9d3021c5b9df?pvs=4)
### DB 설계
![DB](https://github.com/woowacourse/jwp-shopping-order/assets/79090478/982be172-7915-49b0-b64a-8837a1db0b61)

---
# 질문 사항 및 고민인 부분

## 1. 🔗nullable한 FK
- 현재 `order`은 `member_coupon`의 외래키를 갖고 있습니다.
- 쿠폰을 사용하지 않은 주문이 존재할 수 있어서, 해당 컬럼은 nullable합니다.
- 그리고 그에 상응하는 도메인 객체 또한 `Order`가 `MemberCouopn`을 참조하고 있습니다.
- 여러 문제가 생길 수 있는 것 같습니다.
  - 도메인 로직을 실행시킬 떄 NPE의 위험성
    -  현재 이 문제는 기능을 하지 않는 MemberCoupon의 비어있는 구현체를 만들어서 해결한 상태입니다.
  - JdbcTemplate과 주고 받을 떄, 원할하지 않음
    - insert를 할 때, NPE를 터뜨려버리던가,
    - select를 할 때, null이아니라 0으로 변환해서 가져오는 등의 문제가 생깁니다. 
- 도메인 관련 문제는 저런 구현체로서 해결한다고하면, JdbcTemplate 관련 문제 때문에 `중간테이블`을 둔다던가 하는식으로 해결할까 고민을 했었는데, 이럴 때는 보통 어떻게 하는 것이 맞을까요? 

## 2. 🏋️‍♂️Repository가 무겁다
- `Order` 도메인 같은 경우 5개의 테이블을 조인해야 하나의 도메인을 만들 수 있습니다.
- 저는 DAO를 하나의 테이블과 연결하는 객체로 사용해서, sql JOIN을 사용하지 않습니다.
- 그래서 5번의 DB Connection이 생깁니다. 
  - 이 부분에서 성능상의 문제를 크게 고려해야될까요?
- 제 코드에서 개선할 부분
  - 비교적 앞에 짰던 Repository에서 어떤 도메인을 조회할 때, 참조하는 도메인을 findAll()한다음에, 자바코드로 entity의 FK로 찾아서 조립했는데요..
  - 나중에, 짠 부분에선 Enitities에서 FK에 대한 List<Long>을 뽑아서 그것들로 SELECT IN하는 쿼리를 날리는 식을 변경하였습니다.
  - 전자의 내용을 후자의 내용으로 변경해야될 것 같습니다.

## 3. 📄API 명세에 적은 모든 예외 상황을 테스트?
- API 명세에 모든 API마다 발생할 수 있는 예외 상황에 대해 정리하였습니다.
- 그리고 프론트분들에겐 약속된 예외 타입을 응답으로 주기로하였습니다.
- 그래서 모든 API마다 발생할 수 있는 예외 상황이 지금 예상이 되는 상황인데, 이 모든 케이스를 통합테스트에서 테스틀 해야될까요?
- 아니면 특정 서비스나 도메인에서 단위테스트를 진행해야 할까요?

## 4. 🛒주문/결제 창 &rarr; 주문
- 현재 `주문/결제`창에서 회원이 보고 있는 정보(`가격`, `수량`)이 달라지면 예외가 발생하도록 했습니다.
- 그래서 주문 시, cartItemId만 요청을 보내는 것이 아니라, `각 필드의 값`도 요청을 보냅니다.
- 그래서 cartItemId으로 DB에 저장된 값을 조회하고 `각 필드의 값`과 값을 비교합니다.
- 요청은 (`이름`, `이미지 주소`, `가격`, `수량`)을 받아오고, `가격`, `수량`을 비교합니다.
- 팀원들과 상의한 바 이는 자연스러운 플로우라는 판단이 들었는데,
- 실제 현업에서는 어떤 식으로 진행이 될 지 궁금합니다.
- 그리고 `이름`,`이미지 주소`이런값들도 값이 일치하는지 확인해야할까요?

---

# 추가적으로 구현할 내용

1. 테스트 작성
2. Request @Valid 추가
3. `금액` 같은 원시값 포장
4. Repository 에서 도메인 조립하려고 findAll()해온것 findByIds()로 수정

---
더 늦기 전에 리뷰를 보내야할 것 같아서 미흡하지만 PR 드립니다!

긴 글 읽어주셔서 감사합니다!!🙇‍♂️

2023-06-05 13:11 UTC, seovalue requested changes
안녕하세요, 루카! 조앤이에요ㅎㅎ
2단계 잘 수행해주셨네요~ 몇 가지 질문들 남겼는데 확인해보시고 다시 리뷰 요청 주세요! 말씀해주신 부분도 보완해주시면 좋을 것 같아요~

2023-06-05 13:11 UTC, seovalue commented on README.md
> +
1. nullable한 FK
우선 order가 그냥 member_coupon_id를 컬럼으로만 nullable하게 갖는 것이 아니라 fk까지 지정해주신 이유가 궁금해요.

2. 성능상의 문제
조회 1번에 쿼리 5번이 날아간다면, 만약 이 서비스가 굉장히 인기있어져 접속하는 사람이 굉장히 많아진다면 어떨까요?

3. 예외 상황 테스트
발생할 수 있는 예외 상황을 어디서 테스트 했을 때 더 적절할지 고민해보시면 좋을 것 같아요. 어디서 테스트를 해야 내가 더 믿고 이 프로그램을 실제 유저에게 선보일 수 있을지요

4. 4번에 대해서 api와 함께 덧붙여 말씀해주시면 이해하기가 좀 더 편리할 것 같아요. 저는 클라이언트 UI가 없어서요~~ 대략적으로 드는 생각은 어차피 서버에서 내려주는 값들인데 일일이 비교하기보다는 key값만 받아서 뒷단에서 확인하는게 좀더 깔끔한 플로우라는 생각은 드네요~

2023-06-05 13:11 UTC, seovalue commented on src/main/java/cart/ui/config/MemberArgumentResolver.java
> +package cart.ui.config;
막상 webMvcConfig는 밖에 있는데 resolver만 config 패키지에 두신 이유가 궁금해오~

2023-06-05 13:11 UTC, seovalue commented on src/main/java/cart/dto/AllCouponResponse.java
> +package cart.dto;
request/response 패키지를 구분해보는 건 어떨까요?

2023-06-05 13:11 UTC, seovalue commented on src/main/java/cart/ui/OrderApiController.java
> +            @RequestBody OrderRequest request,
`@Valid`를 사용하거나 혹은 request 내부에서 요청에 대한 validation을 하지 않는 이유가 궁금해요~

2023-06-05 13:11 UTC, seovalue commented on README.md
> +# API 명세
클라이언트와 api 명세는 어떤 식으로 주고받았나요? readme를 활용하신 건가요? api docs는 따로 만드시지 않은 이유가 궁금해요

2023-06-05 13:11 UTC, seovalue commented on src/main/java/cart/WebMvcConfig.java
> +                .maxAge(3000);
maxAge는 어떤 역할을 하나요?ㅎㅎ

2023-06-05 13:11 UTC, seovalue commented on src/main/java/cart/ui/OrderApiController.java
> +    @GetMapping("/coupons")
이 api는 orderController에 있는 맥락이 무엇인가요?

2023-06-05 13:11 UTC, seovalue commented on src/main/java/cart/application/OrderService.java
> +    public void cancelOrder(final Long orderId, final Member member) {
cancelOrder는 cud 작업이 포함되어있는데 왜 readOnly 인가요?

2023-06-05 13:11 UTC, seovalue commented on src/main/java/cart/ui/advcie/ControllerExceptionHandler.java
> +package cart.ui.advcie;
오타났어용

2023-06-05 13:11 UTC, seovalue commented on src/main/java/cart/ui/advcie/ControllerExceptionHandler.java
> +    public ResponseEntity<ErrorResponse> handlerAuthenticationException(Exception exception) {
메서드명이 다루는 예외와 불일치해요

2023-06-05 13:11 UTC, seovalue commented on src/main/java/cart/ui/advcie/ErrorType.java
> +public enum ErrorType {
errorType에 따른 예외 클래스들을 일일이 관리해주신 이유가 궁금해요! 실수로 다른 곳에 들어갔다면?

2023-06-05 13:11 UTC, seovalue commented on src/main/java/cart/application/ProductService.java
>          return products.stream().map(ProductResponse::of).collect(Collectors.toList());
특정 부분은 List로 반환하는 부분도 ProductResponse 안에서 다뤄보면 어떨까요?

2023-06-05 13:11 UTC, seovalue commented on src/main/java/cart/application/CouponService.java
> +    public Long issueCouponToMemberByCouponId(final Long couponId, final MemberCouponRequest request, final Member member) {
coupon의 만료일을 클라이언트에서 넘겨받는 이유가 무엇인가요?

2023-06-05 13:11 UTC, seovalue commented on src/main/java/cart/repository/MemberCouponRepository.java
> +                null
createdAt을 null로 주는 이유가 궁금해요!

2023-06-05 13:11 UTC, seovalue commented on src/main/java/cart/repository/MemberCouponRepository.java
> +        }
`usedMemberCoupon.isEmptyCoupon()` 과 같이 쿠폰에게 물어볼 순 없을까요?

2023-06-05 13:11 UTC, seovalue commented on src/main/java/cart/repository/OrderRepository.java
> +public class OrderRepository {
말씀해주신대로 Order가 다양한 값의 조합으로 이루어져있어서 굉장히 비대한데요, 전반적으로 메서드 분리도 되어있지 않아서 가독성이 매우 떨어지는 것 같아요! Order의 구조에 대해 다시 한번 고민해보시는 건 어떨까요?

2023-06-05 13:11 UTC, seovalue commented on src/test/java/cart/integration/AuthIntegrationTest.java
> +package cart.integration;
말씀해주신대로 테스트 보완해주세요~

2023-06-05 13:11 UTC, seovalue commented on src/main/java/cart/ui/OrderApiController.java
> +            @RequestBody OrderRequest request,
추가적으로 구현할 내용에 적어주셨군요ㅎㅎ

2023-06-09 02:27 UTC, dooboocookie commented on README.md
> +
답변 감사합니다!!

4번에 대해서 자세히 질문 드리지 못해서 죄송합니다!!
<img width="880" alt="image" src="https://github.com/woowacourse/jwp-shopping-order/assets/79090478/c42b1026-da60-4f9b-aace-7bda18110b24">
다음과 같이 장바구니나 주문결제 창에서 오래 머물다보면,
다른 브라우저에서 `수량을 올리거나` 관리자가 `가격을 올리거나`하면 유저가 보고있는 `가격 수량이 달라질 수 있다`있어서, 그런 경우에 에러를 발생한다는 시나리오였습니다!

2023-06-09 02:28 UTC, dooboocookie commented on src/main/java/cart/ui/config/MemberArgumentResolver.java
> +package cart.ui.config;
수정하겠습니다

2023-06-09 02:28 UTC, dooboocookie commented on src/main/java/cart/dto/AllCouponResponse.java
> +package cart.dto;
수정하겠습니다!

2023-06-09 02:28 UTC, dooboocookie commented on src/main/java/cart/ui/OrderApiController.java
> +            @RequestBody OrderRequest request,
추가하였습니다!

2023-06-09 02:30 UTC, dooboocookie commented on README.md
> +# API 명세
처음에는 구현한 api나 test가 없어서 클라이언트 분들과 설계를 하면서 노션에 정리하였습니다.
그래서 이미 잘 정리되고 있는 노션이 있었고, 변경사항이 있을 때마다 거기에 노션에 빠르게 수정하여 클라이언트와 내용을 공유하였습니다.
현재로서는 API가 어느정도 정착된 것  같으니, api docs를 쓰면 여러 오타 방지나, 깔끔하게 공유할 수 있을 것 같습니다.
하지만, 시간상 문제로 적용하지 못했습니다 ㅠㅠ

2023-06-09 02:39 UTC, dooboocookie commented on src/main/java/cart/WebMvcConfig.java
> +                .maxAge(3000);
CORS에서 사용되는 캐시를 유지하는 시간이라고 알고 있습니다.
저 부분은 딱히 어떤 이유가 있어서 3000초로 설정한 것은 아니고, 어떤 옵션이 있는지 학습하다가 못뺀 것 같습니다..ㅎ

2023-06-09 02:41 UTC, dooboocookie commented on src/main/java/cart/ui/OrderApiController.java
> +    @GetMapping("/coupons")
`장바구니`에서 `선택한 장바구니 목록`을 가지고 `주문 결제`창으로 넘어갈 때, `해당 주문에서 해당 멤버가 가진 쿠폰에 대한 사용가능여부`를 반환하는 api 입니다!

2023-06-09 02:41 UTC, dooboocookie commented on src/main/java/cart/application/OrderService.java
> +    public void cancelOrder(final Long orderId, final Member member) {
실수했습니다! 수정했습니다

2023-06-09 02:41 UTC, dooboocookie commented on src/main/java/cart/ui/advcie/ControllerExceptionHandler.java
> +package cart.ui.advcie;
헉 수정하겠습니다

2023-06-09 02:42 UTC, dooboocookie commented on src/main/java/cart/ui/advcie/ControllerExceptionHandler.java
> +    public ResponseEntity<ErrorResponse> handlerAuthenticationException(Exception exception) {
수정했습니다!!

2023-06-09 02:44 UTC, dooboocookie commented on src/main/java/cart/ui/advcie/ErrorType.java
> +public enum ErrorType {
errorType은 어플리케이션 레이어 안에서의 예외를 관리하기 보단,
 그 어플리케이션에서 발생한 예외를 `프리젠테이션 레이어`에서 응답할 때, `어떤 errorType을 응답`해야되는지에 대해서 `Exception과 ErrorType매핑` 하고싶었던 enum이였습니다...

2023-06-09 02:45 UTC, dooboocookie commented on src/main/java/cart/application/CouponService.java
> +    public Long issueCouponToMemberByCouponId(final Long couponId, final MemberCouponRequest request, final Member member) {
아직 쿠폰 발급에 대한 정책을 어떻게 할지에 대한 논의가 없어서 클라이언트에서 넘겨 받기로 했는데,

만약 더 논의가 된다면, 쿠폰 종류에 따라 유효기간을 가지고 있어서, 발급하는 시점에서 그 유효기간을 더한 날짜가 만료일이 될 것 같습니다

2023-06-09 02:48 UTC, dooboocookie commented on src/main/java/cart/repository/MemberCouponRepository.java
> +                null
처음에는 이 발급이라는 컬럼(필드)가 도메인에서 유의미한 값이라고 생각이 들지 않았습니다.
그래서 DB에서 언제 생성된 데이터인지 판단하는 값이라고 판단이 들어서 DB에서 디폴트로 들어가지는 timestamp값을 사용하였습니다.

2023-06-09 02:49 UTC, dooboocookie commented on src/main/java/cart/repository/MemberCouponRepository.java
> +        }
그런 메서드를 넣을까 했었는데, EmptyCoupon으로 인해서 다른 구현체에 전혀 상관이 없는듯한 메서드가 생기는 것이 좋을지 확신이 들지 않았습니다.

2023-06-09 02:49 UTC, dooboocookie commented on src/test/java/cart/integration/AuthIntegrationTest.java
> +package cart.integration;
넵 테스트 보완했습니다

2023-06-09 02:52 UTC, dooboocookie commented on src/main/java/cart/application/ProductService.java
>          return products.stream().map(ProductResponse::of).collect(Collectors.toList());
수정했습니다!!

2023-06-09 03:03 UTC, dooboocookie commented on src/main/java/cart/repository/OrderRepository.java
> +public class OrderRepository {
아직 Order 도메인 자체의 불필요한 정보가 있다는 생각이 들지 않습니다..
현재는 5개의 테이블을 조인해서 Order를 만들긴 하지만, 일단 다 필요에 의하여 있다고 생각해서, 일단 Repository의 private 메서드를 분리하여 가독성을 최대한 높였습니다...

2023-06-09 03:05 UTC, dooboocookie commented
안녕하세요 조앤!!

이번 너무 늦게 제출 드리네요 ㅠㅠ

열심히 하지 않았던 것은 아닌데, 기대했던 것 보다 많이 꼼꼼히 못하였고, 아쉬운 부분이 많은 것 같습니다.

말씀해주신 피드백에 대해서 최대한 적용해보았습니다!!

리뷰 감사합니다!!🙇‍♂️

2023-06-10 00:54 UTC, seovalue commented on src/main/java/cart/repository/MemberCouponRepository.java
> +                null
membercoupon 자체가 생성될 때인 LocalDateTime.now를 넣는게 더 유의미하지 않을까용?

2023-06-10 00:55 UTC, seovalue commented on src/main/java/cart/repository/MemberCouponRepository.java
> +        }
그럼 같은 MemberCoupon 객체로 묶으신 이유가 무엇인가요..?

2023-06-10 01:11 UTC, seovalue approved these changes
안녕하세요, 루카! 조앤이에요.
제출 텀이 길어 리뷰로 많이 코멘트를 주고받지 못한게 아쉽네요.
전반적으로 수정해주신 부분 확인해서 코멘트 남겨뒀어요.
추가로 schema에서 사용되는 table이 제거되어 프로그램 실행이 어려운데, 스키마는 중요한 부분이니 앞으론 꼭 확인 후 제출해주시면 좋을 것 같아요~
고생 많으셨어요~

2023-06-10 01:11 UTC, seovalue commented on src/main/java/cart/domain/member/Email.java
> +public class Email {
값들을 다 감싸주셨군요 👍

2023-06-10 01:11 UTC, seovalue commented on src/main/resources/schema.sql
> +CREATE TABLE member
흠 이거 프로그램 직접 실행해보신 건 맞는건가요? member 테이블이 두개라서 실행에 오류가 발생하는데 수정하지 않고 올리신 이유가 궁금해요

2023-06-10 01:11 UTC, seovalue commented on src/main/resources/schema.sql
> +    FOREIGN KEY (product_id) REFERENCES product (id)
product라는 테이블도 없는데 reference가 걸려있고요..

2023-06-10 01:11 UTC, seovalue commented on src/test/resources/test-schema.sql
> +DROP TABLE IF EXISTS product;
여기도 마찬가지로 product 테이블을 `test-data.sql`에서는 사용하는데 `schema` 에서는 전반적으로 없어서 테스트도 돌지 않고, 프로그램 실행도 안돼요.

<img width="527" alt="Screenshot 2023-06-10 at 10 04 34" src="https://github.com/woowacourse/jwp-shopping-order/assets/48412963/ce4b094e-aeb0-4fc9-97a9-2cb581f4bb10">

2023-06-10 01:11 UTC, seovalue commented on src/main/java/cart/dto/request/ProductRequest.java
> +    @NotNull
`javax.validation` 과 관련된 에러가 발생했을 때는 어떻게 응답이 떨어지는지 확인해보셨나요?

2023-06-10 01:11 UTC, seovalue commented on src/main/java/cart/exception/MemberException.java
> +    public static class EmptyEmail extends MemberException {
발생하는 모든 케이스에 대해 이렇게 클래스를 만들어 관리해주시는 이유가 궁금해요~

2023-06-10 01:11 UTC, seovalue commented on src/test/java/cart/repository/CartItemRepositoryTest.java
> +        assertThat(cartItem).isEqualTo(장바구니1);
테스트는 확인용도이니 가독성이 중요하다고 생각하는데요, `// given // when // then` 의 주석을 적어두는 것만으로도 가독성을 높일 수 있다고 생각해요.

2023-06-10 01:11 UTC, merged