[2단계 - 주문 기능 구현] 도기(김동호) 미션 제출합니다.
woowacourse/jwp-shopping-order pull request #82
Opened 2023-06-05 04:09 UTC by kdkdhoho

안녕하세요 영이!
우테코 첫 미션인 자동차 경주 미션 이후로 다시 뵙네요!!! 반갑습니다  🙌
그럼 리뷰 잘 부탁드립니다 :)

2023-06-06 01:59 UTC, choijy1705 requested changes
안녕하세요 도기
다시 만나게 되었네요!
전체적으로 잘 구현해주신것 같아요👍
다만 미션중에는 롬복 사용을 지양하면 좋을것 같습니다!
코멘트 반영 및 롬복 제거하여 다시 리뷰 요청 부탁드립니다~

2023-06-06 01:59 UTC, choijy1705 commented on src/main/java/cart/presentation/MemberArgumentResolver.java
> +        String[] credentials = encode(authHeader[AUTH_VALUE_INDEX]);
이전 미션들중 인터셉터와 리졸버의 역할을 분리해서 미션을 진행했던걸로 기억하는데
리졸버에서 인증과정까지 처리한 이유가 있나요?
클래스명과 역할이 잘 분리되지 않은것 같아서요

2023-06-06 01:59 UTC, choijy1705 commented on src/main/java/cart/exception/AuthenticationException.java
> +    }
새롭게 정의한 exception이 너무 많은건 아닐까요?
유지 보수 측면에서 별로 좋은점이 없을것 같습니다. 실제 실무라면 이런 방법으로 예외를 생성하면 100개는 넘을것 같아요
참고로 제 회사에서는 클라(프론트)와 특별한 협의를 하는게 아닌 경우은 기존 정의된 몇개의 exception만 사용하고 있습니다

2023-06-06 01:59 UTC, choijy1705 commented on src/main/java/cart/dto/request/CartItemAddRequest.java
> +@Getter
미션 중에는 롬복사용을 최대한 지양하라고 하더군요!

2023-06-06 01:59 UTC, choijy1705 commented on src/main/java/cart/domain/Product.java
> +    private final int price;
bigDecimal 사용을 고려해보면 어떨까요?
저는 돈과 관련된건 거의 필수라고 생각하는데요
int의 경우 서비스가 확장되어 달러가 들어오기만해도 문제가 생기고
소수점 연산에서 오차가 발생할 수 있을 것 같네요

2023-06-06 01:59 UTC, choijy1705 commented on src/main/java/cart/domain/Point.java
> +    private final int value;
얘도 소수점 연산이 들어간다면
bigDecimal이 좋겠네요

2023-06-06 01:59 UTC, choijy1705 commented on src/main/java/cart/domain/Quantity.java
> +public class Quantity {
quantity 보다는 price를 원시값포장하는게 적절할것 같네요!
quantity는 별다른 로직이없고 단지 validate만 하고 있어서요

2023-06-06 01:59 UTC, choijy1705 commented on src/main/java/cart/dto/request/CartItemInfoRequest.java
> +        this(null, null, null);
```suggestion
        this(null, null, null);
```
일반적이지 않은 코드같은데요
우선 롬복을 해제하고 생각해보죠!

2023-06-06 01:59 UTC, choijy1705 commented on src/main/java/cart/presentation/CartItemApiController.java
> +    @PatchMapping("/{cartItemId}")
특정 필드만 수정하는거라면
`/cartItemId/quantity` 가 좀더 적절할것 같네요

2023-06-06 01:59 UTC, choijy1705 commented on src/main/java/cart/presentation/CartItemApiController.java
> +        return ResponseEntity.created(URI.create("/cart-items/" + cartItemId)).build();
delete 를 제외한 create, update, read 의 경우는 body를 반환해주는게 좋고 일반적인것 같아요
큰 회사들의 developer문서들을 참고해보세요
https://shopify.dev/docs/api/admin-rest/2023-04/resources/product

2023-06-06 01:59 UTC, choijy1705 commented on src/main/java/cart/service/PointService.java
> +        Member foundMember = memberRepository.findById(member.getId());
파라미터로 넘어온 member는 완전한 member아닌가요?

2023-06-06 01:59 UTC, choijy1705 commented on src/main/java/cart/service/ProductService.java
> +    }
service에서 바로 response를 넘겨버리면 
해당 메서드는 다른 곳에서 호출하여 사용할 수 없을것 같네요

2023-06-06 01:59 UTC, choijy1705 commented on src/main/java/cart/service/ProductService.java
> +    }
변경 혹은 생성된 객체를 반환하여
response로 내려주면 좋을것 같네요

2023-06-06 01:59 UTC, choijy1705 commented on src/main/java/cart/repository/CartItemRepository.java
> +        CartItemEntity cartItemEntity = new CartItemEntity(cartItem.getMember().getId(), cartItem.getProduct().getId(), cartItem.getQuantityValue());
getMemberId, getProductId 
메서드를 별도로 만드는게 어떤가요
혹은
enttiy생성자에서 member, product를 받아 id를 get해서 저장할수도 있겠네요

2023-06-06 01:59 UTC, choijy1705 commented on src/main/java/cart/service/OrderService.java
> +    public long order(final Member member, final OrderRequest orderRequest) {
createOrder인지 updateOrder인지 명확한 메서드명을 정하면 좋을것 같습니다!

2023-06-06 01:59 UTC, choijy1705 commented on src/main/java/cart/service/OrderService.java
> +        validateTotalProductPrice(cartItemInfos, orderRequest.getTotalProductPrice());
request에 주문 금액을 프론트에서 다 계산해서 주나요?
금액 계산 및 포인트 계산은 주문이 생성되는 시점에 서버에서 해줘야할것 같은데 
request에는 어떤 상품이 주문되는지와 포인트 사용 유무만 담겨져오고
실제 결제 할 금액에대한 계산 및 포인트 사용은 주문이 생성되는 시점에 해야할것 같아요

2023-06-06 01:59 UTC, choijy1705 commented on src/main/java/cart/util/CurrentTimeUtil.java
> +    public static String asString() {
entity 에서 LocalDateTime 혹은 Instant로 관리되면 db에 시간은 잘 저장되지 않나요?

2023-06-07 02:54 UTC, kdkdhoho commented on src/main/java/cart/presentation/MemberArgumentResolver.java
> +        String[] credentials = encode(authHeader[AUTH_VALUE_INDEX]);
사실 기존에 제공된 뼈대 코드여서 별 의심 없이 사용했습니다 😅
말씀해주신대로 Interceptor를 두어, 검증과 인증에 대한 책임을 부여하겠습니다 !!

2023-06-07 03:24 UTC, kdkdhoho commented on src/main/java/cart/exception/AuthenticationException.java
> +    }
모든 상황에 대해 커스텀 예외를 생성한다면, 발생한 예외를 직접적으로 파악할 수 있을 것 같아요. 하지만 확실히 개수가 많아져 유지보수가 힘들어질 것 같습니다.
그렇다면, 커스텀 예외도 **추상화** 하는 것이 중요할 것 같은데요. 예를 들어, DB에 존재하지 않는 데이터를 조회할 때 발생하는 `~~NotFoundException`의 경우 `DataNotFoundException`로 통일하고 어떤 데이터를 찾지 못했는 지에 대한 정보는 message로 나타내는 것이 적절할까요?

2023-06-07 04:08 UTC, kdkdhoho commented on src/main/java/cart/domain/Product.java
> +    private final int price;
아무래도 금전과 관련된 도메인은 가장 중요한 것이 신뢰성 및 데이터의 확실성이니, 말씀하신대로 `BigDecimal` 타입이 필수불가결하겠네요.
앞으로 개발하는 데에 있어서 정말 필요한 인사이트를 알려주셔서 감사합니다 👍

2023-06-07 05:26 UTC, kdkdhoho commented on src/main/java/cart/domain/Quantity.java
> +public class Quantity {
동의합니다. 적용하겠습니다!

2023-06-07 06:19 UTC, kdkdhoho commented on src/main/java/cart/presentation/CartItemApiController.java
> +    @PatchMapping("/{cartItemId}")
해당 부분은 뼈대 코드로 제공된 코드입니다.

하지만, 일부 필드만을 수정하는 PATCH 메서드의 경우에 다른 필드를 수정하는 API가 존재할 수 있으니 말씀해주신 대로 URI에 필드를 명시하는 것이 적절하다고 판단되네요.

현재는 팀 API 명세로 약속되어 있는 부분이기에 변경은 어려울 것 같습니다.
앞으로 개발함에 있어서 참고하도록 하겠습니다 !

2023-06-07 06:27 UTC, kdkdhoho commented on src/main/java/cart/presentation/CartItemApiController.java
> +        return ResponseEntity.created(URI.create("/cart-items/" + cartItemId)).build();
저와는 다르게 보여주신 API 문서에는 cru 된 data를 body에 담아 응답하고 있네요!
팀에서 정한 API 명세와 갑자기 달라지는 것은 팀원들에게 의문을 던져줄 수 있으니, 다음 프로젝트부터 적용해 보겠습니다.

그런데 혹시 body를 반환해 주는 것이 좋다고 말씀하신 이유가 무엇인가요?
제 생각엔 팀에서 정한 규칙을 따르는 것이 가장 큰 이유가 될 것이라고 생각되는데요. 만약 body에 값을 담아서 응답하더라도 클라이언트(프론트)에서 불필요한 데이터라면 굳이 담아주지 않아도 된다고 생각합니다.

그리고 영이가 속한 회사에서도 위와 같은 응답을 내려주고 있는지 궁금합니다 !

2023-06-07 06:29 UTC, kdkdhoho commented on src/main/java/cart/service/PointService.java
> +        Member foundMember = memberRepository.findById(member.getId());
맞습니다..! 수정하겠습니다.

2023-06-07 07:02 UTC, kdkdhoho commented on src/main/java/cart/service/ProductService.java
> +    }
Request가 Service로 곧바로 들어가는 경우에 대한 트레이드 오프를 생각해본 적은 있지만, 반대로 반환하는 경우 Response가 반환될 때의 트레이드 오프를 생각해보지 못했네요..!
더군다나 Service는 비즈니스 로직 수행과 그에 따른 결과물 반환, Controller는 수행된 로직을 클라이언트에게 적절히 응답하는 역할에도 더욱 맞는다고 생각합니다.

수정하겠습니다 !

2023-06-07 07:03 UTC, kdkdhoho commented on src/main/java/cart/service/ProductService.java
> +    }
https://github.com/woowacourse/jwp-shopping-order/pull/82#discussion_r1218767488

위 코멘트에서 관련 질문을 남겨두었습니다!

2023-06-07 07:53 UTC, kdkdhoho commented on src/main/java/cart/service/OrderService.java
> +    public long order(final Member member, final OrderRequest orderRequest) {
아직까진 주문 수정 기능이 존재하지 않아, 단순히 **주문한다** 라는 의미로 `order`라고 명명했습니다.
하지만 충분히 주문과 관련된 여러 기능이 추가될 수 있음에 따라, 말씀하신대로 `createOrder`가 적절하겠네요 !

2023-06-07 08:02 UTC, kdkdhoho commented on src/main/java/cart/service/OrderService.java
> +        validateTotalProductPrice(cartItemInfos, orderRequest.getTotalProductPrice());
현재 프론트와 백엔드 모두 주문 금액을 계산해주고 있습니다.
이유는 사용자에게 보여줄 화면에 선택한 상품의 총 가격을 실시간으로 보여주기 위함과 동시에, 요청에 포함된 상품 가격과 실제 DB에 저장된 상품 가격이 다를 수 있다는 [issue](https://www.boannews.com/media/view.asp?idx=64364)를 바탕으로 해당 로직을 추가했습니다.

2023-06-07 08:12 UTC, kdkdhoho commented on src/main/java/cart/util/CurrentTimeUtil.java
> +    public static String asString() {
네, DB에 저장은 잘 됩니다.
하지만 API 명세에 따르면 'yyyy-MM-dd HH:mm:ss' 형식으로 반환을 해야 했습니다.
따라서 처음에 LocalDateTime으로 관리했을 때, DB에서 값을 꺼내오면 가운데에 'T' 가 추가되는 문제가 발생했습니다.

이 문제를 해결하고자 위와 같은 방법을 적용했습니다.
혹시 더 나은 방법이나 키워드가 있다면 알려주시면 감사하겠습니다 🙇‍♂️

2023-06-07 08:17 UTC, kdkdhoho commented
안녕하세요 영이~ 피드백 반영 해보았습니다.
중간에 궁금한 점들이 생겼는데요. 다음과 같습니다 !!

## Member Login 시, Interceptor와 ArgumentResolver의 역할은 어디까지인가?

Interceptor에서 AuthType이 Basic인지? null인지? 등을 체크하는 것은 문제없다고 생각합니다.
그런데 존재하는 회원인지? 비밀번호가 올바른지 체크하려면 DB에 접근해서 회원 정보를 가져온 후 진행되어야 합니다.
동시에, ArgumentResolver에서도 Member 객체로 변환해주려면 또 다시 DB에 접근해서 매핑해줘야 합니다.
결국 한 번의 로그인으로 DB에 2번 요청이 가게 되는 셈인데요.

따라서 스스로 판단하에, Interceptor에서는 Basic Type인지? null은 아닌지? 정도만 체크하고, DB에 접근 후에 이뤄지는 검증들은 ArgumentResolver에서 진행하는 식으로 결정했습니다.
다만, 아직도 ArgumentResolver에서 검증이 이뤄지기에 https://github.com/woowacourse/jwp-shopping-order/pull/82#discussion_r1218753080 에는 적절하지 않다고 생각합니다. 방법이 없을까요?

## 커스텀 예외의 추상화
를 진행해 보았는데요. 처음 해보는 방식이다 보니, 적절하게 수행했는지 확신이 잘 서지 않습니다.
제가 진행한 방식이 괜찮은 방식인지 판단 부탁드립니다!!

2023-06-07 15:01 UTC, choijy1705 commented on src/main/java/cart/presentation/CartItemApiController.java
> +        return ResponseEntity.created(URI.create("/cart-items/" + cartItemId)).build();
팀에서 정한 규칙이라기 보다 제 경험상 90%이상은 body를 내려줬어요
클라쪽에서 update 요청후 변경사항을 반영하기 위해서 새롭게 다시 조회하는 번거로움을 줄일 수 있을 것 같고요
변경사항을 view에 안보여주더라도 어떤 점이 변하였는지 나타낼 수 있을것 같네요!
그리고 예상치 못한 비즈니스 로직에 의해 원치않는 필드가 변경 혹은 변경되지 않을 수도 있는데 이런것을 확인할 수 있을것 같네요

2023-06-07 15:07 UTC, choijy1705 commented on src/main/java/cart/util/CurrentTimeUtil.java
> +    public static String asString() {
보통은 중간에 T 가 있는 UTC를 자주 사용하는것 같은데
`yyyy-MM-dd HH:mm:ss` 이 형식을 사용한 이유가 궁금합니다!🙏

2023-06-07 15:13 UTC, choijy1705 commented on src/main/java/cart/exception/AuthenticationException.java
> +    }
음 회사마다 정책이 다르겠지만
제 회사의 경우 클라이언트(프론트)쪽에서 에러 타입을 통해 별도로 핸들링이 필요하지 않는이상
기본 baseException을 정의하고 이를 활용합니다. 
서버 내에서 확인하는 용도는 결국 메세지 및 stacktrace가 중요하지 어떤 타입인지는 크게 중요하지 않을거라 생각합니다
유지보수 측면에서 확실히 커스텀 예외가 많아지면 번거로울것 같네요 
예외를 매번 생성하는 시간도 많이들테고 이를 위한 팀 컨벤션등도 필요하겠네요

2023-06-07 15:59 UTC, choijy1705 approved these changes
안녕하세요 도기!
미션 진행하시느라 고생많으셨어요👏
질문에 대한 답변과 몇가지 피드백 남겼습니다!
예외처리에 대해 고민하신것 같은데 무엇보다 중요한 controllerAdvice가 빠진것 같네요
여기서 머지는 하지만 다시 한번 챙겨보면 좋을것 같습니다

2023-06-07 15:59 UTC, choijy1705 commented on src/main/java/cart/config/WebMvcConfig.java
> +        registry.addInterceptor(new AuthValidateInterceptor())
interceptor는 보통 bean으로 등록하여 사용하는것 같습니다.
빈으로 등록된 interceptor라면 빈으로 등록된 memberReposiotry를 호출할 수 있을것이고 이를 활용해 interceptor에서 등록된 member인지를 확인할 수 있을것 같네요!

그리고 interceptor에서는 request.setAttribute 나 session 등을 활용하여서 email, password를 넘기고
argumentResolver에서는 member라는 객체를 만들어서 반환하면 좋을것 같네요

2023-06-07 15:59 UTC, choijy1705 commented on src/main/java/cart/config/WebMvcConfig.java
> +        resolvers.add(new MemberArgumentResolver(memberRepository));
스프링 빈으로 등록된 객체(memberRepository)를 스프링 빈이 아닌 memberArgumentResolver의 생성자로 넣어도 괜찮을까요?

2023-06-07 15:59 UTC, choijy1705 commented on src/main/java/cart/domain/Member.java
> +        point.validateUsePoint(usePoint);
subtract 메서드에서 체크해주면 더 안전하고 더 간결할것 같아요!

2023-06-07 15:59 UTC, choijy1705 commented on src/main/java/cart/domain/OrderItemEntity.java
> +            final int productPrice,
db저장시 bigDecimal을 굳이 int로 안바꿔도 될거에요

2023-06-07 15:59 UTC, choijy1705 commented on src/main/java/cart/domain/Point.java
> +    }
테스트코드에만 사용되는것 같아요

2023-06-07 15:59 UTC, choijy1705 commented on src/main/java/cart/domain/Product.java
> +    }
validateStock은 굳이 메서드로 안빼도 될것 같아요
너무 메서드를 잘게 나누는것도 가독성을 떨어뜨릴수 있을것 같습니다!

2023-06-07 15:59 UTC, choijy1705 commented on src/main/java/cart/dto/request/CartItemInfoRequest.java
> +        this(null, null, null);
빈 생성자가 parsing할때 꼭 필요 하던가요??
보통은 final을 빼고 빈생성자를 만들거나
빈생성자를 없애는 방향을 택하는것 같아요

2023-06-07 15:59 UTC, choijy1705 commented on src/main/java/cart/exception/OrderException.java
> +    }
이렇게 세분화 시킨게 프론트와 협의가 된걸까요?

2023-06-07 15:59 UTC, choijy1705 commented on src/main/java/cart/exception/OrderException.java
> +public class OrderException extends RuntimeException {
정작 중요한 controllerAdvice가 빠져있네요😭

2023-06-07 16:00 UTC, merged

2023-06-08 02:27 UTC, kdkdhoho commented on src/main/java/cart/exception/AuthenticationException.java
> +    }
말씀하신 baseException이라고 하면, `IllegalArgumentException` 같은 기본으로 제공되는 RuntimeException을 의미하시는걸까요? 또, 예외를 터트릴 때 어떠한 이유에서 발생했는 지 예외 메시지를 넣어주시나요??

2023-06-08 02:32 UTC, kdkdhoho commented on src/main/java/cart/dto/request/CartItemInfoRequest.java
> +        this(null, null, null);
인텔리제이에서 build tool로 intelliJ를 선택하면 발생하는 에러 때문에 레벨2 두 번째 미션부터 관습적으로 작성해왔습니다.

필요없는 것은 사실이지만 intelliJ를 선택해 사용하는 개발자들이 있기에 배려하고자는 차원에서 작성했습니다.
사실 저번 미션에서도 같은 부분으로 피드백을 받았었는데요. 불필요한 배려일까요..?

2023-06-08 02:38 UTC, kdkdhoho commented on src/main/java/cart/util/CurrentTimeUtil.java
> +    public static String asString() {
팀원 전체가 UTC 존재에 대해 잘 모르고 있어서 중간에 'T' 를 포함하지 않았던 것 같습니다.
보통은 프론트에게 반환할 때에도 중간에 'T'를 포함해서 반환하나요??