[2단계 - 주문 기능 구현] 블랙캣(송우석) 미션 제출합니다.
woowacourse/jwp-shopping-order pull request #92
Opened 2023-06-05 07:47 UTC by Songusika

안녕하세요 시카! 👋
이번 리뷰이 블랙캣입니다 🐈‍⬛
이번 페어 [바론](https://github.com/somsom13), [케로](https://github.com/jyeost)와 같이 구현한 장바구니 - 주문 미션 제출합니다!

이번 미션에서 서비스간 적절한 관심사를 분리해보고 싶어서 스프링 이벤트를 적용해봤습니다.
또한 미션을 구현하면서 몇가지 질문이 생겼는데요! 시카와 함께 고민해보고 싶습니다.

## 질문 사항
### Q1. 데이터베이스에 저장된 실제 값과 도메인에의 값이 달라도 괜찮을까요?
저희는 도메인을 분석하는 과정에서 상품 가격이 중요하다고 생각했습니다.
그래서 구매 당시 상품 가격을 데이터베이스의 주문_목록 테이블에 따로 저장을 하고 있습니다.

이후 주문 목록을 불러올 때 repository 계층에서 주문 목록에 포함된 상품을 객체를 생성하는데요!
이 때 실제 상품 가격이 아닌, 구매 당시 상품의 가격을 저장하여 객체를 생성하고 있습니다.

이렇게 되면 상품이 실제 데이터베이스에 해당 ID를 가진 상품과 다른 가격을 가진 객체가 생성됩니다.
여기서 약간의 괴리감이 느껴지더라구요, 이러한 방법도 괜찮을까요?

### Q2. dao의 JOIN VS repository 에서 여러 dao 의존, 조합

연관 관계를 가지고 있는 객체를 데이터베이스에서 조회하는 상황에서
 - 하나의 dao 에서 여러 테이블을 join
 - 하나의 repository에서 여러 dao를 사용해서 객체를 조합 

두 방법에 아래와 같은 장/단점이 있다고 생각이 들었습니다.

첫번째 방법은 
 - 하나의 쿼리만 사용해도 된다는 된다.
 - repository 에서 해당 객체를 쉽게 생성할 수 있다.
 - 단, join으로 인한 성능이 이슈가 생길 수 있다.

두번째 방법은 
 - join 으로 인한 성능 이슈를 고민하지 않아도 된다.
 - dao에서 하나의 테이블만 보기때문에 유지보수가 쉽다.
 - 단, repository 에서 해당 객체를 생성하기 어렵다.

시카는 어떤 방법을 선호하시는 편인가요?

###  Q3. 스프링 이벤트가 관심사를 분리할 수 있는 적절한 방법일까요?

`주문 -> 결제 -> 포인트 누적` 이라는 비즈니스 로직간 각 서비스가 다른 서비스를 의존하는 것을 방지하기 위해서
스프링 이벤트를 처음 적용해보았습니다.
하지만, `주문`, `결제`, `포인트 누적` 이라는 각 도메인은 어느정도 관심사가 겹칠 수 밖에 없다고 생각합니다.
그래서 `각 서비스 간 단일 방향 의존이 생겨도 괜찮을까?` 라는 생각이 들더라구요!
이 부분에 대해서 시카의 의견이 궁금합니다.

2023-06-06 06:31 UTC, dks301 requested changes
안녕하세요 블랙캣, 리뷰어 시카입니다. 😄

어려운 미션인데도 요구사항에 맞춰 잘 구현해주셨네요! 👍
몇 가지 코멘트 남겨드렸으니 확인부탁드려요.

추가로 궁금한 점이 생기면 언제든지 DM 주세요 ㅎㅎ

2023-06-06 06:31 UTC, dks301 commented on src/main/java/cart/WebMvcConfig.java
> +        registry.addMapping("/**").allowedOrigins("*").allowedMethods("*").exposedHeaders("Location");
전역 설정을 하셨는데요...! 각각 설정값에 대해서 찾아보고 개별적으로 적용해보면 어떨까요???

2023-06-06 06:31 UTC, dks301 commented on src/main/java/cart/application/Event/RequestPaymentEvent.java
> +public class RequestPaymentEvent {
1. class 이름인데 동사로 시작해서 어색한 부분이 있는 것 같아요...! 명사로 바꿔보면 어떨까요?
2. event들이 같은 패키지로구분되어 있는 만큼, 인터페이스로 추상화해보면 어떨까요??

2023-06-06 06:31 UTC, dks301 commented on src/main/java/cart/application/Event/RequestPaymentEvent.java
> +package cart.application.Event;
패키지명은 소문자로 통일하면 어떨까요?? ㅎㅎ

2023-06-06 06:31 UTC, dks301 commented on src/main/java/cart/application/MemberService.java
> +    public MemberResponse getMemberById(final Long id) {
사소하지만 getter와 헷갈릴 수 있는 부분이니 다른 이름을 사용해보면 어떨까요??

2023-06-06 06:31 UTC, dks301 commented on src/main/java/cart/application/MemberService.java
> +    public MemberResponse getMemberByEmail(final String email) {
전체적으로 Service에서 ResponseDto를 반환하도록 이야기된 것 같아요 ㅎㅎㅎ
각 서비스에서
1. dto를 반환
2. domain class를 반환
3. entity를 반환

각각을 사용할 떄 어떤 장단점이 있는지 고민해보면 어떨까요?? ㅎㅎ

2023-06-06 06:31 UTC, dks301 commented on src/main/java/cart/application/PaymentService.java
> +    }
이벤트 리스너로 각 이벤트에 대해서 validation만하고 pay(지불)하는 로직이 없는 것 같은데요! 🤔
제가 못찾은 걸까요...? 설명해주시면 좋을 것 같아요ㅎㅎ

2023-06-06 06:31 UTC, dks301 commented on src/main/java/cart/domain/cart/Cart.java
> +        this.cartItems = new ArrayList<>(cartItems);
```suggestion
        this.cartItems = cartItems;
```
카트아이템을 ArrayList로 굳이 명시하신 이유가 있나요??

2023-06-06 06:31 UTC, dks301 commented on src/main/java/cart/domain/point/Point.java
> +    private final Long point;
point의 경우 정수지만 적립률 계산하는 경우 소숫점이 나올수 있을 것 같은데요...!
위와 같은 경우의 수에 대한 정책을 정하셨을까요??

2023-06-06 06:31 UTC, dks301 commented on src/main/java/cart/domain/product/Price.java
> +    private final Long price;
만약 글로벌 서비스인 경우 소숫점 가격(ex 1.5$)와 같은 경우도 고려해야하는데요 ㅎㅎㅎ
1. 실제 계산에서 반올림하는 경우도 있으니 소숫점에 대응할 수 있는 데이터 타입을 사용하면 어떨까요??
2. 실무라면 돈과 관련된 경우 상하한이 있는 데이터 타입 사용은 지양해야하지 않을까요??

2023-06-07 05:10 UTC, Songusika commented on src/main/java/cart/application/Event/RequestPaymentEvent.java
> +package cart.application.Event;
앗 미처 확인하지 못했네요! 소문자로 변경하였습니다!

2023-06-07 07:11 UTC, Songusika commented on src/main/java/cart/application/PaymentService.java
> +    }
위에서 언급한것과 같이 현재 주문이라는 전체 비즈니스 로직 흐름을 본다면
`주문 -> 결제 -> 포인트 누적` 순서로 비즈니스 로직이 진행되는데요!

원래 처음 페어간 이야기 한 것은 결제 도메인이 없고 단순하게
`주문 -> 포인트 누적` 이었습니다.

페어간 주문 시 포인트와 관련된 검증을 아래와 같이 생각했습니다.
- 사용자가 보유한 포인트보다 많은 포인트 사용을 시도하였는지
- 구매하려는 총 가격보다 더 많은 포인트 사용을 시도하였는지

처음에는 해당 검증 로직을 `OrderService`에 두었지만,
구현을 하면서 주문 서비스에 과다한 책임을 부과하는 느낌이 들었고,
이는 추후 각 서비스의 변경/확장 등 유지보수 측면에서 좋지 않을거라고 판단하였습니다.

또한 실제로는 정상적인 결제가 이루어지고 나서, 주문이 들어가야한다고 판단하였습니다.
그래서 정확한 비즈니스 로직을 따져본다면, 아래와 같이 진행되어야한다고 생각했습니다.
`주문 요청 -> 결제 -> 주문 진행 -> 포인트 누적`

때문에 `PaymentService`를 새롭게 추가하였고 포인트 검증 로직 책임을 해당 서비스에 두었습니다.
그리고 질문하신 지불 로직은 실제로라면 결제 서비스를 제공하는 외부 API 를 사용할 것 같아 따로 두지 않았습니다!

지금 생각해보면 포인트 검증 로직 또한 `OrderService`에 두고
실제 지불해야하는 금액만 PaymentService에 두는게 조금 더 일반적이 비즈니스 흐름이 아니였을까 생각이드네요 😭

2023-06-07 07:13 UTC, Songusika commented on src/main/java/cart/domain/cart/Cart.java
> +        this.cartItems = new ArrayList<>(cartItems);
방어적 복사를 적용하고자 하였습니다!

2023-06-07 07:20 UTC, Songusika commented on src/main/java/cart/application/MemberService.java
> +    public MemberResponse getMemberById(final Long id) {
`find` 키워드로 수정하였습니다!

2023-06-07 07:22 UTC, Songusika commented on src/main/java/cart/domain/point/Point.java
> +    private final Long point;
페어 간 소숫점은 반올림하여 멤버에게 포인트를 부여하기로 정했습니다!

2023-06-07 07:25 UTC, Songusika commented on src/main/java/cart/domain/product/Price.java
> +    private final Long price;
상하한이 있는 데이터 타입을 사용했을 때 추후 발생할 수 있는 문제점을 생각하지 못했네요 😅
가격과 포인트 모두 `BigDecimal`  타입으로 변경하였습니다!

2023-06-08 08:23 UTC, Songusika commented on src/main/java/cart/WebMvcConfig.java
> +        registry.addMapping("/**").allowedOrigins("*").allowedMethods("*").exposedHeaders("Location");
메서드별 개별 설정 적용하였습니다!

2023-06-08 08:23 UTC, Songusika commented on src/main/java/cart/application/Event/RequestPaymentEvent.java
> +public class RequestPaymentEvent {
1. 각 이벤트를 명사형 네이밍으로 수정하였습니다.
2. 각 이벤트를 나타내는 인터페이스를 도출하였습니다!

2023-06-09 01:09 UTC, Songusika commented on src/main/java/cart/application/MemberService.java
> +    public MemberResponse getMemberByEmail(final String email) {
1. 서비스 계층에서 Controller 가 클라이언트에게 반환하는 DTO 반환
 - 장점: 컨트롤러 게층에서 클라이언트에게 바로 반환 할 수 있기 때문에 로직이 간단하다
 - 단점: 서비스 계층이 컨트롤러 계층을 의존할 수 있다.
 
2. 서비스 계층에서 Domain class 를 반환
 - 장점: 서비스 클래스를 여러 컨트롤러에서 사용할 수 있다.
 - 단점: 도메인 객체가 표현계층까지 넘어가며, 원하지 않는 도메인 정보가 노출 및 도메인 로직이 수행될 수 있다.
 
3. 서비스 계층에서 데이터베이스와 1:1 매핑되는 Entitiy를 반환
 - 장점: 단순한 쿼리 같은 경우 도메인 객체를 생성하지 않고 바로 반환할 수 있기 때문에 로직이 간단하다.
 - 단점: 원하지 않는 정보가 클라이언트에게 노출될 수 있으며, 테이블 변경이 컨트롤러까지 영향을 끼친다.

질문에 대해서 고민해봤는데, 지금과 같은 구조는 컨트롤러에서 사용하는 DTO 를 서비스 계층에서 의존하고 있는 상황이고,
이는 계층형 아키텍처에서 어색한 구조라고 생각합니다. 상위 계층의 변경이 하위 계층의 까지 영향을 줄 수 있기 때문이죠.
때문에 DTO를 서비스 계층에서 사용하고 싶다면, 서비스 계층의 DTO와 컨트롤러 계층의 DTO 를 나누고, Mapper 등을 컨트롤러 계층에 둘 것 같습니다!

2023-06-09 10:49 UTC, dks301 approved these changes
안녕하세요 블랙캣, 리뷰어 시카입니다. 😄

근로 프로젝트도 하고 바쁘실텐데 코멘트도 잘 반영해주셨네요! 👍
여러가지로 많이 고민하고 성장 하신 것 같아요.!
이번 미션은 여기서 머지하겠습니다 :)  레벨2 고생 많으셨습니다 🎉🎉

추가로 궁금한 점이 생기면 언제든지 DM 주세요 ㅎㅎ

2023-06-09 10:49 UTC, dks301 commented on src/main/java/cart/application/Event/RequestPaymentEvent.java
> +public class RequestPaymentEvent {
2번의 경우는 의도한 부분이 잘 전달되지 못한것 같아요.. 😢

조금더 자세하게 설명을 드리자면,
두 가지 인터페이스를 도출하고 각각을 1:1 대응되는 impl을 구현하는 것이 아닌 두 가지가 합쳐진 가칭 `interface ApplicationEvent`에 대해서 고민해보고
1. 이를 적용했을 때 어떠한 장단점이 있는지
2. 기존 두 class로 이용했을 때와는 어떤 다른점이 있는지

위와 같은 것에대해서 고민해보면 좋을 것 같아서 코멘트 드렸습니다 😄
물론 지금같이 하는 방식도 가능한 방식 중 하나이기에 추가해서 세가지 모두 비교해보고 고민해보면 어떨까요??

2023-06-09 10:49 UTC, dks301 commented on src/main/java/cart/application/MemberService.java
> +    public MemberResponse getMemberByEmail(final String email) {
각각의 장단점에 대해서 잘 정리해주셨네요...! 👍👍

>  도메인 객체가 표현계층까지 넘어가며, 원하지 않는 도메인 정보가 노출 및 도메인 로직이 수행될 수 있다.

어제 잠깐 말씀드렸지만, 이 부분에 대해서 한단계 나아가서 고민해보면 좋을 것 같아요...!
domain class를 표현계층까지 넘기더라도, 팀 모두가 편의성에 동의한다면? 표현계층에 domain class가 있는걸 인지하고 이를 변경하지 않을 수 있다면? domain class가 불변객체라면? 등등 여러가지로 고민해보면 어떨까요?? ㅎㅎ

2023-06-09 10:49 UTC, dks301 commented on src/main/java/cart/application/PaymentService.java
> +    }
고민해주신 부분이 Spring AOP의 단점이기도 한데요...!
실제로 대부분의 개발은 다양한 사람들과 개발하기에 가독성이나 예측가능성(?)이 중요합니다.
하지만, AOP의 경우 관점 지향으로 가독성과 유지보수성을 증가시킬 수 있지만 반대로 점차 프로젝트가 커지면 예측할 수 없는 동작이 발생한 후에 이러한 로직이 있다는 것을 발견하게되는 이슈가 종종 있는것 같아요 😅

따라서, `@Trasactional` 과 같이 보다 관용적인 위치, 클래스, 이름이 어떤건지 고민해보면 좋을 것 같아요!!

2023-06-09 10:49 UTC, dks301 commented on src/main/java/cart/domain/point/Point.java
> +    private final Long point;
우리가 일반적으로 알고있는 반올림도 있지만, 다른 반올림 방식도 존재하는데요...!
생각보다 빌링 실무에서는 일반적인 수학적으로 알고 있는 것보다 새롭게 알게되는 부분이 많고 소숫점아래의 정확성이 중요합니다 ㅎㅎㅎ
java.math에서 제공하는 [enum RoundingMode](https://docs.oracle.com/javase/8/docs/api/java/math/RoundingMode.html)가 있는데 가볍게 찾아보시고 키워드만 가져가시면 혹시 나중에 필요할 떄 검색해서 사용할 수 있을 것 같아요!!! 😄

2023-06-09 10:49 UTC, merged