[2단계 - 주문 기능 구현] 리오 미션 제출합니다.
woowacourse/jwp-shopping-order pull request #94
Opened 2023-06-05 07:56 UTC by Jaeyoung22

안녕하세요 다니!
이번에 리뷰를 받게 된 리오라고 합니다! 잘 부탁드려요!!

몸관리를 잘 못해서 아파가지고 리뷰 요청이 좀 늦어졌네요ㅠㅠ 아쉽고 죄송합니다!

질문은 아래와 같습니다!

### JOIN vs DB 접근
로직을 짜다보니, JOIN을 3~4번 하는 경우와 DB에 여러번 접근하여 데이터를 가져오는 경우에 대해서 trade-off를 고민할 일이 상당히 많았습니다...
물론 데이터의 양에 따라 다르겠지만, 보통 이 기준을 어떻게 잡는 것이 좋을까요?

### 상수들 DB 저장 기준
쿠폰은 여러 종류가 계속해서 추가될 수 있을 수 있으니까 db에 저장하는 것이 당연한 것 같은데,

2023-06-06 09:33 UTC, da-nyee requested changes
안녕하세요 리오! 다니입니다 🙌

구현할 사항이 많았는데 잘해주셨어요 👍
전반적으로 훑으면서 코드리뷰 남겼고, 질문답변도 했어요.

혹시 궁금한 점이 있으시면 코멘트나 슬랙 DM 주세요 🙇‍♀️

2023-06-06 09:33 UTC, da-nyee commented on build.gradle
> +    runtimeOnly 'com.mysql:connectorj:5.1.12'
<img width="1495" alt="image" src="https://github.com/woowacourse/jwp-shopping-order/assets/50176238/5d7214f0-89c7-47cf-af62-8fc0b526fd80">

테스트 실행하니까 요런 에러가 뜨는데, 한번 확인해주실 수 있나요?

2023-06-06 09:33 UTC, da-nyee commented on build.gradle
> +    runtimeOnly 'com.mysql:connectorj:5.1.12'
+) README도 작성하면 좋을 것 같아요.

2023-06-06 09:33 UTC, da-nyee commented on src/main/java/cart/ui/ControllerExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.FORBIDDEN).body(new ExceptionResponse(e.getExceptionType()));
401 Unauthorized와 403 Forbidden은 어떤 차이가 있을까요?

2023-06-06 09:33 UTC, da-nyee commented on src/main/java/cart/ui/MemberArgumentResolver.java
>      private final MemberDao memberDao;
ArgumentResolver -> Repository 직접 의존으로 controller - service - repository 계층 구조가 지켜지지 않고 있네요.

2023-06-06 09:33 UTC, da-nyee commented on src/main/java/cart/ui/MemberArgumentResolver.java
> +    public Object resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer,
메서드 길이를 10라인 이하로 줄여볼까요?

2023-06-06 09:33 UTC, da-nyee commented on src/main/java/cart/ui/MemberArgumentResolver.java
>              return null;
null 반환보다 예외를 던지는 건 어떨까요?

2023-06-06 09:33 UTC, da-nyee commented on src/main/java/cart/ui/OrderApiController.java
> +    @Operation(summary = "회원 모든 주문 내역 조회", description = "회원의 모든 주문 내역을 조회한다.")
Swagger로 API 명세를 관리하셨군요 👍

2023-06-06 09:33 UTC, da-nyee commented on src/main/java/cart/ui/OrderApiController.java
> +    @Operation(summary = "회원 모든 주문 내역 조회", description = "회원의 모든 주문 내역을 조회한다.")
REST Docs로도 API 문서를 만들 수 있는데요, Swagger를 선택한 이유가 있을까요?

2023-06-06 09:33 UTC, da-nyee commented on src/main/java/cart/application/OrderService.java
> +    private static void checkExistence(Coupon coupon) {
private 메서드는 사용하는 곳 가까이에 위치시키는 게 가독성 측면에서 더 좋은 것 같아요.

2023-06-06 09:33 UTC, da-nyee commented on src/main/java/cart/application/OrderService.java
> +        System.out.println(order.getMember().getEmail());
필요한 sout인가요?

2023-06-06 09:33 UTC, da-nyee commented on src/main/java/cart/dao/OrderDao.java
> +    public Order findWithoutOrderItems(Long orderId) {
메서드를 10라인 이하로 줄일 수 있을까요?

2023-06-06 09:33 UTC, da-nyee commented on src/main/java/cart/dao/OrderDao.java
> +            "LEFT JOIN coupon c ON mc.coupon_id = c.id " +
> JOIN vs DB 접근<br/>
로직을 짜다보니, JOIN을 3~4번 하는 경우와 DB에 여러번 접근하여 데이터를 가져오는 경우에 대해서 trade-off를 고민할 일이 상당히 많았습니다...
물론 데이터의 양에 따라 다르겠지만, 보통 이 기준을 어떻게 잡는 것이 좋을까요?

음.. 정답이 있는 문제가 아니어서 어렵네요 ㅜㅜ
저는 DB에 아주 많이 쿼리해야 하는 경우가 아니라면, DB join보다 DB 쿼리를 선택할 것 같아요.
DB join을 하다가 DB에 문제가 생기면, 이건 시스템 장애로 이어지는데요.
반면에 DB에 여러 번 쿼리하고 애플리케이션에서 데이터를 활용하다가 문제가 생기면, 이건 곧바로 시스템 장애로 이어지지 않고 애플리케이션 예외로 처리할 수 있기 때문이에요.

2023-06-06 09:33 UTC, da-nyee commented on src/main/java/cart/domain/Money.java
> +    private final int money;
원시값 포장 👍

2023-06-06 09:33 UTC, da-nyee commented on src/main/java/cart/application/MemberService.java
> +        String authorization = httpServletRequest.getHeader(HttpHeaders.AUTHORIZATION);
httpServletRequest가 service 계층까지 침투해도 괜찮을까요? controller 계층에서 처리하는 게 더 적절하지 않을까요?

2023-06-06 09:33 UTC, da-nyee commented on src/main/java/cart/ui/CouponApiController.java
> +    private final OrderService orderService;
CouponService가 아닌 OrderService를 사용한 이유가 있을까요?

2023-06-06 09:33 UTC, da-nyee commented on src/main/java/cart/dao/CouponDao.java
> +        return jdbcTemplate.query(sql, new Object[] {couponId}, rs -> {
<img width="920" alt="image" src="https://github.com/woowacourse/jwp-shopping-order/assets/50176238/4405af34-ee72-4002-b2fd-04d3cfeac2d8">

deprecated된 메서드네요.

2023-06-06 09:33 UTC, da-nyee commented on src/main/java/cart/domain/Coupon.java
> +            }
depth를 1로 만들어볼까요?

2023-06-06 09:33 UTC, da-nyee commented on src/main/java/cart/domain/Coupon.java
> +    public Money discount(Money money) {
일부 책임을 Money에게 위임하는 건 어떨까요?

2023-06-06 09:33 UTC, da-nyee commented on src/main/java/cart/domain/Order.java
> +        }
```suggestion
        if (memberCoupon == null) {
            return Money.noDiscount();
        }
```

요런 식으로 정적 팩토리 메서드를 활용할 수도 있어요.

2023-06-06 09:33 UTC, da-nyee commented on src/main/java/cart/domain/OrderItem.java
> +    public Long getOrderId() {
사용하지 않는 메서드네요.

2023-06-06 09:33 UTC, da-nyee commented on src/main/java/cart/domain/PriceCalculator.java
> +            .mapToInt(cartItem -> cartItem.getProduct().getPrice() * cartItem.getQuantity())
디미터의 법칙을 지켜볼까요?

2023-06-06 09:33 UTC, da-nyee commented on src/main/java/cart/domain/ShippingFeePolicy.java
> +public class ShippingFeePolicy {
> 상수들 DB 저장 기준<br/>
쿠폰은 여러 종류가 계속해서 추가될 수 있을 수 있으니까 db에 저장하는 것이 당연한 것 같은데,
배송비 등 어플리케이션 안에서 Enum으로 저장할 수 있는 것들은 db로 관리해야 하는지 잘 모르겠어요..
그런데 다른 크루들의 얘기를 들어보니까 배송비도 저장한 크루들도 있더라구요
이 기준을 어떻게 잡아야 할까요?

저라면 배송비도 DB에 저장할 것 같아요. 어떤 주문에 대한 배송비를 DB에 기록으로 남겨두는 거니까요.
쿠폰이 언제든지 추가될 수 있듯이 배송비도 언제든지 정책 등에 의해 변경될 수 있다고 생각해요.

데이터를 DB에 두고 어떤 방식으로든 활용할 수 있다면(e.g. DB 쿼리 시 where 조건에 활용 등), DB에 영속화시키는 게 맞는 것 같아요.

2023-06-06 09:33 UTC, da-nyee commented on src/main/java/cart/dto/request/ProductRequest.java
> +    @NotEmpty
bean validation 👍

2023-06-06 09:33 UTC, da-nyee commented on src/main/java/cart/dto/request/CartItemAddRequest.java
>      private Long productId;
ProductRequest처럼 bean validation을 사용해볼까요?

2023-06-06 09:33 UTC, da-nyee commented on src/test/java/cart/application/OrderServiceTest.java
> +public class OrderServiceTest {
다른 Service도 테스트를 작성해볼까요?

2023-06-06 09:33 UTC, da-nyee commented on src/test/java/cart/dao/CartItemDaoTest.java
> +    public void findByMemberId_ShouldReturnCartItems() {
`@DisplayName`을 추가하면 더 좋을 것 같아요.

2023-06-06 09:33 UTC, da-nyee commented on src/test/java/cart/integration/ProductIntegrationTest.java
> +        var response = given()
타입 추론 👍

2023-06-06 10:06 UTC, Jaeyoung22 commented on build.gradle
> +    runtimeOnly 'com.mysql:connectorj:5.1.12'
외부 서버 DB에 연결해보는 연습을 하면서 테스트를 신경쓰지 못했군요 ㅠㅠㅠ
수정하고, README도 작성했습니다!
협업하면서 이용했던 노션을 첨부했는데, README에 직접 작성을 하는 것이 더 나을까요?!

2023-06-06 10:07 UTC, Jaeyoung22 commented on src/main/java/cart/ui/ControllerExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.FORBIDDEN).body(new ExceptionResponse(e.getExceptionType()));
401은 해당 유저의 정보가 없을 때, (로그인 정보가 없을 때) 사용을 하고,
403은 해당 유저의 정보는 있지만, 권한이 없을 때 사용을 하기로 협업하면서 논의해봤습니다!

2023-06-06 10:15 UTC, Jaeyoung22 commented on src/main/java/cart/ui/MemberArgumentResolver.java
>      private final MemberDao memberDao;
앗!! 코치분들이 제공해주신 기존 뼈대 코드에 있는 내용이라 전혀 고려하지 못했네요ㅠㅠㅠㅠ

그런데, argumentResolver는 controller 계층이라고 봐야하는 걸까요?!
뭔가 명확한 계층이 있다고 이야기하기 어려운 개념으로 알고 있습니다...!

만약 argumentResolver가 controller 계층이라면, service를 의존하는 것은 괜찮은 건가요?!

2023-06-06 10:28 UTC, Jaeyoung22 commented on src/main/java/cart/ui/MemberArgumentResolver.java
> +    public Object resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer,
수정했습니다!!

2023-06-06 10:28 UTC, Jaeyoung22 commented on src/main/java/cart/ui/MemberArgumentResolver.java
>              return null;
확실히 그게 낫겠네요!! 수정했습니다!!

2023-06-06 10:30 UTC, Jaeyoung22 commented on src/main/java/cart/ui/OrderApiController.java
> +    @Operation(summary = "회원 모든 주문 내역 조회", description = "회원의 모든 주문 내역을 조회한다.")
더 예뻐서.... 해봤습니다..!

근데 확실히 프로덕션 코드에 문서화를 위한 어노테이션이 추가 되니까 가독성이 좀 떨어지는 부분이 있더라구요..!
그래서 다음에는 REST Docs도 사용해보려고 합니다!!

2023-06-06 10:33 UTC, Jaeyoung22 commented on src/main/java/cart/application/OrderService.java
> +    private static void checkExistence(Coupon coupon) {
아이고... 저도 완전 그렇게 생각해서, 다른 메서드들은 다 그렇게 해놨는데...
인텔리제이 단축기로 메서드 추출하면 이상하게 static 달려 나올때가 있고... 
그걸 확인 못하고, 또 인텔리제이 단축키로 코드 정렬하면.. static 달려 있어서 알아서 위로 올라가고 그러더라구요..... 
다음부터 더 꼼꼼히 확인하겠습니다..! 죄송합니다!

2023-06-06 10:34 UTC, Jaeyoung22 commented on src/main/java/cart/application/OrderService.java
> +        System.out.println(order.getMember().getEmail());
NPE 처리하려고 찍어보다가... 죄송합니다....

2023-06-06 10:43 UTC, Jaeyoung22 commented on src/main/java/cart/dao/OrderDao.java
> +    public Order findWithoutOrderItems(Long orderId) {
수정했습니다!

2023-06-06 10:47 UTC, Jaeyoung22 commented on src/main/java/cart/dao/OrderDao.java
> +            "LEFT JOIN coupon c ON mc.coupon_id = c.id " +
앗 그렇군요!
성능 뿐만 아니라 다니가 말씀해주신 문제도 있을 수 있겠네요!
다음에는 해당 문제도 고려해서 적절히 사용해보겠습니다!! 감사합니다!!

2023-06-06 10:51 UTC, Jaeyoung22 commented on src/main/java/cart/application/MemberService.java
> +        String authorization = httpServletRequest.getHeader(HttpHeaders.AUTHORIZATION);
앗 그렇네요..! 
학습해볼 기회가 됐습니다!!
감사합니다!! 수정했습니다!!

2023-06-06 10:56 UTC, Jaeyoung22 commented on src/main/java/cart/ui/CouponApiController.java
> +    private final OrderService orderService;
주문과 쿠폰이 큰 관련이 있다고 생각해서 따로 분리를 안했었는데,
다니의 커멘트를 보니 분리하는 것이 맞다고 생각이 드네요..! 
API 흐름 상 OrderService와 CouponService 중 어느 위치에 존재해야할지 애매한 메서드가 있어서 그랬던 것 같습니다..!
수정했습니다! 감사합니다!!

2023-06-06 11:08 UTC, Jaeyoung22 commented on src/main/java/cart/dao/CouponDao.java
> +        return jdbcTemplate.query(sql, new Object[] {couponId}, rs -> {
변경했습니다!

2023-06-06 11:11 UTC, Jaeyoung22 commented on src/main/java/cart/domain/Coupon.java
> +            }
우선 변경했습니다!

다만 이 정도의 depth와 로직은 같이 있는 것이 개인적으로는 읽기 쉬운 것 같아요...! 
오히려 메서드를 분리하는 것이 가독성을 해친다고 생각하는데, 다니는 어떻게 생각하실까요?

2023-06-06 12:27 UTC, Jaeyoung22 commented on src/main/java/cart/domain/Coupon.java
> +    public Money discount(Money money) {
만들어놓고 쓰지를 않았네요... 감사합니다!!

2023-06-06 12:28 UTC, Jaeyoung22 commented on src/main/java/cart/domain/Order.java
> +        }
네! 감사합니다!!

2023-06-06 12:30 UTC, Jaeyoung22 commented on src/main/java/cart/domain/OrderItem.java
> +    public Long getOrderId() {
정리하겠습니다!

2023-06-06 12:45 UTC, Jaeyoung22 commented on src/main/java/cart/domain/PriceCalculator.java
> +            .mapToInt(cartItem -> cartItem.getProduct().getPrice() * cartItem.getQuantity())
앗 그렇네요..! 감사합니다!!!

2023-06-06 12:46 UTC, Jaeyoung22 commented on src/main/java/cart/domain/ShippingFeePolicy.java
> +public class ShippingFeePolicy {
혹시 이 부분에 대해서, 매번 배송비 테이블에 접근해야하는 비용을 고려할 여지는 없을까요?
한번씩 더 db에 접근해야 하는 단점이 생길 수도 있을 것 같아요!

2023-06-06 12:54 UTC, Jaeyoung22 commented on src/main/java/cart/dto/request/CartItemAddRequest.java
>      private Long productId;
네! 수정했습니다!

2023-06-06 13:28 UTC, Jaeyoung22 commented on src/test/java/cart/application/OrderServiceTest.java
> +public class OrderServiceTest {
시간에 쫓겨서 인수 테스트만 작성했었네요ㅠㅠ
단위 테스트 추가하겠습니다!

2023-06-06 13:28 UTC, Jaeyoung22 commented on src/test/java/cart/dao/CartItemDaoTest.java
> +    public void findByMemberId_ShouldReturnCartItems() {
앗 빼먹은 부분들 전부 추가하겠습니다!

2023-06-08 14:05 UTC, da-nyee commented on build.gradle
> +    runtimeOnly 'com.mysql:connectorj:5.1.12'
<img width="1495" alt="image" src="https://github.com/woowacourse/jwp-shopping-order/assets/50176238/2475afad-9067-46d7-a7f7-a1db39ccc0ac">

DB 사용하는 테스트가 전부 깨지네요 ㅠㅠ

2023-06-08 14:06 UTC, da-nyee commented on build.gradle
> +    runtimeOnly 'com.mysql:connectorj:5.1.12'
엇 노션도 좋아요 ㅎㅎ

2023-06-08 14:12 UTC, da-nyee commented on src/main/java/cart/ui/OrderApiController.java
> +    @Operation(summary = "회원 모든 주문 내역 조회", description = "회원의 모든 주문 내역을 조회한다.")
근데 REST Docs를 사용하면.. 테스트 코드 지옥에 빠질 수도 있어요 😇
두 방식 모두 경험해보고 장단점을 잘 정리해두면 좋습니다 ㅎㅎ

2023-06-08 14:13 UTC, da-nyee commented on src/main/java/cart/application/OrderService.java
> +    private static void checkExistence(Coupon coupon) {
앗 죄송할 필요는 없어요...! 이해합니다 ㅎㅎ

2023-06-08 14:14 UTC, da-nyee commented on src/main/java/cart/application/OrderService.java
> +        System.out.println(order.getMember().getEmail());
요것도 죄송할 필요는 없어요...! 🙅‍♀️

2023-06-08 14:19 UTC, da-nyee commented on src/main/java/cart/domain/Coupon.java
> +            }
저도 요 정도는 괜찮다고 생각해요! 실제로 일하면서 depth 2는 종종 사용하고 있기도 하구요...!
다만 우테코는 교육 과정이라 레벨 1, 2 프로그래밍 요구사항을 최대한 맞춰서 구현하면 좋을 것 같아 리뷰드렸어요 ㅎㅎ

2023-06-08 14:20 UTC, da-nyee commented on src/main/java/cart/domain/Order.java
> +        }
오 Money.zero() 좋네요 👍

2023-06-08 14:23 UTC, da-nyee commented on src/main/java/cart/domain/ShippingFeePolicy.java
> +public class ShippingFeePolicy {
아니면 주문 테이블을 비정규화해서 배송비를 컬럼으로 관리할 수 있지 않을까요?

2023-06-08 14:35 UTC, da-nyee commented on src/main/java/cart/ui/MemberArgumentResolver.java
>      private final MemberDao memberDao;
<img width="1498" alt="image" src="https://github.com/woowacourse/jwp-shopping-order/assets/50176238/f48a33a0-9d8a-4be1-ad6e-059160b247fe">

[참고 - Spring ArgumentResolver](https://hipopatamus.tistory.com/113)

저는 ArgumentResolver가 DispatcherServlet과 연관되기 때문에 Controller 계층에 속한다고 생각해요.
그래서 Service 계층에 의존할 수 있다고 봅니다!

2023-06-08 14:47 UTC, da-nyee requested changes
안녕하세요 리오!
어제오늘 갑자기 조금 바빠져서 코드리뷰가 늦었네요ㅠㅠ 죄송해요 🥲

피드백 반영 잘해주셨어요 👍👍👍
이제 충분한 것 같아 이만 머지할까 했는데, 추가 코멘트 확인할 겸 리퀘스트 체인지 드립니다!
리뷰요청 한번 더 주시면 미션 진짜로 끝낼게요 ㅎㅎ

2023-06-08 23:25 UTC, Jaeyoung22 commented on build.gradle
> +    runtimeOnly 'com.mysql:connectorj:5.1.12'
h2에서는 테이블 포린키 제약 푸는 문법이 저게 아니어서 그런 거 같습니다..! application.properties 를 ignore해서 git에 안 올라가서 그런거 같아요..!

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL

application.properties 내부 입니다..!

2023-06-08 23:26 UTC, Jaeyoung22 commented on src/main/java/cart/ui/MemberArgumentResolver.java
>      private final MemberDao memberDao;
저는 argumentResolver가 handler에 대해서 AOP를 주로 수행하기는 하지만,
Service나 다른 클래스에 대해서도 사용할 수 있다고 알고있습니다..!
Interceptor라면 컨트롤러 계층이라고 생각하지만 ArgumentResolver는 뭔가 계층을 나누기가 어려운 모듈 같은 느낌이라고 생각하고 있습니다..!

2023-06-08 23:27 UTC, Jaeyoung22 commented on src/main/java/cart/ui/OrderApiController.java
> +    @Operation(summary = "회원 모든 주문 내역 조회", description = "회원의 모든 주문 내역을 조회한다.")
네!! 장단점을 정리해두고 적재적소에 활용할게요..! 감사합니다!!

2023-06-08 23:28 UTC, Jaeyoung22 commented on src/main/java/cart/domain/Coupon.java
> +            }
클린한 코드를 위해서 계속 노력하겠습니다..! 감사합니다!!

2023-06-08 23:29 UTC, Jaeyoung22 commented on src/main/java/cart/domain/ShippingFeePolicy.java
> +public class ShippingFeePolicy {
오 그런 방법도 있겠네요..! 그런데 배송비 `정책`에 대한 정보가 테이블에 있어야 하는지, enum으로 관리해야하는지에 대한 질문이었는데, 다니의 커멘트를 보고 계속 고민해보고 있습니다..! 감사합니다!

2023-06-09 08:06 UTC, da-nyee commented on src/main/java/cart/ui/MemberArgumentResolver.java
>      private final MemberDao memberDao;
오호 그런 관점이라면 계층을 확실하게 정하기 어렵긴 하네요 ㅠ

2023-06-09 08:08 UTC, da-nyee commented on build.gradle
> +    runtimeOnly 'com.mysql:connectorj:5.1.12'
<img width="1495" alt="image" src="https://github.com/woowacourse/jwp-shopping-order/assets/50176238/98ebb8a4-fe03-4a43-89fc-c94aafed0ec3">

properties 파일 추가하니까 전부 통과하네요 👍

2023-06-09 08:09 UTC, da-nyee approved these changes
안녕하세요 리오! 다니입니다 🙌

말씀하신대로 properties 파일 추가하니까 테스트 전부 통과하네요! 완벽합니다 👍👍👍
이번 미션은 이 정도면 충분한 것 같아 어프룹 & 머지하겠습니다!

레벨 2 수고 많으셨어요! 앞으로 남은 우테코 생활도 행복하고 알차게 보내시길 바랄게요 ✨

2023-06-09 08:09 UTC, merged