[2단계 - 주문 기능 구현] 케로(김지현) 미션 제출합니다.
woowacourse/jwp-shopping-order pull request #97
Opened 2023-06-05 08:10 UTC by jyeost

2023-06-05 17:11 UTC, sonypark requested changes
케로 안녕하세요!
꽤 까다로운 미션이었을텐데 고생하셨습니다.👍
질문주신 부분과 코드상 개선포인트에 코멘트 남겼으니 확인 부탁드립니다🙏

> Where 절에 in 사용

네 말씀하신대로 in 블록 안에 빈 리스트가 들어가면 sql 오류가 발생하기 때문에 방어로직이 필요합니다. 쿼리 실행 전에 빈 리스트에 대한 검증을 넣어주면 됩니다. 잘 구현하셨습니다. 👍 

> 회원과 포인트

프로시저는 실무에서 잘 사용하지는 않습니다.
여러가지 이유가 있겠지만 대표적으로
- 프로시저의 제한된 문법으로 객체지향적인 개념을 사용하기 어렵다.
- 스케일 아웃이 쉬운 편인 WAS와 달리 DB는 스케일 아웃이 어렵다.
- 디버깅이 어렵다.
- 등등이 있을 것 같네요.

현재는 회원가입 기능이 없다고 하셨으니, 회원과 포인트에 대해 초기 설정값을 수동으로 넣어줘야할텐데요.
data.sql로 초기 데이터를 넣어주는 방식이 가장 무난해보입니다. 또는 CommandLineRunner 를 사용하는 방법도 있습니다. (https://unluckyjung.github.io/spring/2022/03/16/Spring-Load-RunCode/)

> 테스트에 기본 값

네 테스트 데이터를 넣는 방법은 여러가지가 있습니다. data.sql 로 넣기도 하고 Fixture 클래스를 만들어 주입하기도 하는 등 다양한 방법이 있는데요. 지금처럼 data.sql로 매 테스트 동작시 주입해주는 방법도 많이 사용합니다. 잘 하셨습니다. (다만 이 방법은 테스트 데이터가 테스트 코드에서는 보이지 않기 때문에 해당 파일을 찾아봐야 알 수 있는 단점이 있습니다.)

2023-06-05 17:11 UTC, sonypark commented on src/main/java/cart/application/CartItemService.java
> +    public CartItemService(ProductRepository productRepository, ProductDao productDao, CartItemRepository cartItemRepository) {
ProductDao 는 사용 안하고 있는것 같네요!

2023-06-05 17:11 UTC, sonypark commented on src/main/java/cart/dao/CartItemDao.java
>      }
- 존재하지 않는 id로 delete, update 를 수행하면 어떻게 되나요?
- 에러가 발생하지 않는다면, 사용자에게 알리지 않아도 될까요?

2023-06-05 17:11 UTC, sonypark commented on src/main/java/cart/dao/CartItemDao.java
>          String sql = "DELETE FROM cart_item WHERE member_id = ? AND product_id = ?";
이 메서드는 사용하지 않는것 같군요

2023-06-05 17:11 UTC, sonypark commented on src/main/java/cart/application/OrderService.java
> +
- 요청한 품목이 모두 잘 조회되었는지 확인이 필요할 것 같은데, 요청으로 들어온 cartItemIds size와 DB에서 조회한 cartItem의 size가 같은지 검증하지 않아도 될까요?

2023-06-05 17:11 UTC, sonypark commented on src/main/java/cart/domain/Member/Email.java
> +
Email은 Password와 달리 따로 equals & hashcode를 재정의하지 않았네요. 이유가 있으신가요?

2023-06-05 17:11 UTC, sonypark commented on src/main/java/cart/application/OrderService.java
> +        cart.checkOwner(member);
서비스 코드에 `@RequestBody @Valid` 를 선언하는게 적절할까요?

2023-06-05 17:11 UTC, sonypark commented on src/main/java/cart/application/OrderService.java
> +        return orderId;
주문시 사용한 포인트 만큼 차감해서 totalPrice를 산정하는 로직이어야 할 것 같은데 그렇지 않아보이는데요. 제가 놓친 부분이 있을까요?

2023-06-05 17:11 UTC, sonypark commented on src/test/java/cart/dao/OrderDaoTest.java
> +    }
이 왜 테스트는 주석처리가 되어있을까요?

2023-06-05 17:11 UTC, sonypark commented on src/test/java/cart/integration/OrderIntegrationTest.java
> +
핵심 로직 중 하나인 포인트를 사용해서 주문하는 경우에 대한 테스트가 필요할것 같네요

2023-06-05 17:11 UTC, sonypark commented on src/main/java/cart/ui/OrderApiController.java
> +        return ResponseEntity.ok().body(AllOrdersByMember);
`List<OrderResponse> AllOrdersByMember = orderService.findByMember(member);`
변수명이 대문자네요😅

2023-06-05 17:11 UTC, sonypark commented on src/main/java/cart/exception/handler/ControllerExceptionHandler.java
> +            MethodArgumentNotValidException.class }
상태코드 정보만으로 어떤 예외가 발생했는지 판단할 수 있을까요?(통일된 에러응답구조에 어떤 예외인지 알수있도록 메시지를 넣으면 좋을 것 같아요)
ErrorResponse도 기본적으로 정해진 양식이 있습니다. (디테일한 부분은 팀마다 다를 수 있지만 기본적인 구조는 같습니다.)
Exception 관련해서는 아래 글에 자세히 나와있으니 참고해서 수정해보면 좋을 것 같습니다.
https://cheese10yun.github.io/spring-guide-exception/

2023-06-05 17:11 UTC, sonypark commented on README.md
> +  - [x] 주문한 상품들을 장바구니에서 지워준다.
이건 공통질문인데요 :) 
- 이번 미션은 백엔드 크루뿐 아니라 프론트 크루분들과 협업으로 진행했을텐데 API 명세나 구조를 정할때는 어떻게 하셨나요? 
    - API 문서가 필요했을텐데 API문서가 README에도 안 보이는것 같은데 혹시 어디에 정의하고 구현하셨나요? (+ swagger나 RestDocs도 고려하셨나요?)
- API 설계를 클라이언트(웹 프론트엔드, 모바일 안드로이드)와 논의했을 때와 기존에 백엔드 크루와 페어를 했을때 차이점이 있었나요?
- 서로 의견이 다른 점이 있을때 어떤 방식으로 조율하셨는지도 궁금하네요

2023-06-07 14:08 UTC, jyeost commented on src/main/java/cart/application/CartItemService.java
> +    public CartItemService(ProductRepository productRepository, ProductDao productDao, CartItemRepository cartItemRepository) {
수정하면서 놓친것 같아요 수정하였습니다 !

2023-06-07 15:24 UTC, jyeost commented on src/main/java/cart/dao/CartItemDao.java
>      }
- dao의 delete, update 문을 호출하는  service단에서 메서드 호출 전에 id에 해당하는 cartItem을 가져오면서 확인해주기 때문에 dao에서 확인로직을 추가하지 않았었는데요... 한 눈에 보이지 않는 로직도 있고 해서 dao에서 한 번 더 확인하도록 추가하였습니다 !

- 클라이언트에서 200코드를 받으면 페이지를 새로 로드하는 방식으로 구현할 예정이라고 했기때문에, 지금은 에러가 발생하지 않으면 ResponseEntity<Void>에 ok상태코드만 담아서 보내도 된다고 생각합니다

2023-06-07 15:25 UTC, jyeost commented on src/main/java/cart/dao/CartItemDao.java
>          String sql = "DELETE FROM cart_item WHERE member_id = ? AND product_id = ?";
뼈대 코드에서 사용하던 로직인데 놓친것 같습니다...
수정하였습니다 !

2023-06-08 20:24 UTC, jyeost commented on src/main/java/cart/application/OrderService.java
> +
검증해야 할 것 같습니다....
Cart에 사이즈 검증 로직 추가하였습니다..!!

2023-06-08 20:25 UTC, jyeost commented on src/main/java/cart/domain/Member/Email.java
> +
현재 구현에서 email의 값을 비교하는 로직이 없어서 빼먹은 것 같습니다.
VO객체들에 동등성 비교 로직 추가하였습니다!

2023-06-08 20:26 UTC, jyeost commented on src/main/java/cart/application/OrderService.java
> +        cart.checkOwner(member);
헉 아니요....ㅜㅜ 실수했습니다
수정 하였습니다 !

2023-06-08 20:27 UTC, jyeost commented on src/main/java/cart/application/OrderService.java
> +        return orderId;
포인트 로직이라고 생각하여 포인트 서비스에서 처리해주도록 하였습니다..!

2023-06-08 20:32 UTC, jyeost commented on src/test/java/cart/integration/OrderIntegrationTest.java
> +
PointIntegrationTest 에서 포인트를 사용하여 주문하는 테스트를 해주고 있었는데, 클래스명과 테스트 명에서 명확하게 드러나지 않았던것 같습니다! 수정하겠습니다

2023-06-08 20:33 UTC, jyeost commented on src/main/java/cart/ui/OrderApiController.java
> +        return ResponseEntity.ok().body(AllOrdersByMember);
ㅜㅜ 수정하였습니다 😂

2023-06-08 20:56 UTC, jyeost commented on README.md
> +  - [x] 주문한 상품들을 장바구니에서 지워준다.
- 다같이 회의를 통해 API를 설계하고, 노션에 정리하여 공유하였습니다 [링크](https://www.notion.so/API-f32dc8755ef34667894fa149cf1f59f4)

- 저는 swagger 와 RestDocs 을 알지 못했고, 팀 회의에도 나오지 않아서 고려하지 못했습니다... 😂 근데 다른 팀에서 프론트에서 swagger와 RestDocs을 모르셔서 가르쳐 드리면서 사용했다고 했는데, 클라이언트가 해당 기술을 잘 모르는 상황에서도 이런 것들을 이용하여 API를 문서화하는것이 이점이 있나용...??

- API 설계에서는 차이점을 느끼지 못한 것 같습니다 :)

- 저희는 이야기를 나눌때 의견 차이없이 수월하게 진행되어 아직 의견차이가 있을때 어떻게 조율하는지 아직은 잘 모르겠습니다.... ㅜㅜ 프론트와의 협업을 하면서 어떤 기능을 만들고자 서로 이야기를 할때, 프론트에서는 요청을 만들어 주고 응답을 처리하는 것을 상상하면서 말씀하시고, 저희는 요청을 받아서 응답을 만들어 주는것을 생각하면서 말하는 그런 간극이 재밌었습니다..ㅎ.ㅎ 

- 저희는 협업 중에 매일 그날의 어떤 작업을 했는지 서로 경과 보고를 하기로 했는데요... 프론트 분들은 스크린 샷을 찍어서 어떤것을 구현했는지 보여주셨는데 반해, 저는 제가 구현한 내용을 어떻게 프론트 분들이 이해할 수 있게 말할지 몰라서 기능 구현 단위로 끊어서 보고하다 보니, 매일 보고를 할 수 없었어요....ㅜㅜ 
예를 들어 하루종일 조인 쿼리로 dao에서 여러 객체를 만들어 주던 로직을 한 dao에는 한 테이블에 대한 쿼리만 존재하도록 고치고 repository레이어를 추가하여 이를 도메인으로 만들도록 수정했을때, 전부 설명하자고 하니... 못알아 들으실 것 같고.... 뼈대 코드 리팩토링 이라고 하자니 너무 한 일이 없어보이고... 그런 고민이 있었습니다.... ㅎㅎ
저희가 쓰는 코드를 어떻게 프론트 분들이 이해하기 쉽게 설명할 수 있을까용....

2023-06-09 14:58 UTC, sonypark commented on src/main/java/cart/dto/error/ErrorResponse.java
> +    }
👍👍

2023-06-09 14:58 UTC, sonypark commented on src/main/java/cart/domain/Cart.java
> +        }
좋네요 👍

2023-06-09 14:58 UTC, sonypark commented on README.md
> +  - [x] 주문한 상품들을 장바구니에서 지워준다.
> 클라이언트가 해당 기술을 잘 모르는 상황에서도 이런 것들을 이용하여 API를 문서화하는것이 이점이 있는지

swagger와 RestDocs를 사용하여 문서화를 하는 장점은 코드와 문서를 따로 관리할 필요가 없다는게 가장 클 것 같아요. 관리 포인트를 최소화하는게 유지보수면에서 중요합니다. RestDocs의 경우는 테스트를 통과해야만 문서가 만들어지기 때문에 API 변경이 있을때마다 정확한 문서를 제공해서 코드 최신화를 유지할 수 있다는 장점이 있습니다. 이번 미션은 API도 단순하고 변경이 많지 않아 노션에 적어서 공유하는것만으로 충분하다고 느끼셨을 수 있는데요. 위와 같은 문서화 툴을 이용하면 요청/응답 양식을 자동으로 만들어주고, swagger 같은 경우는 문서에서 API를 호출해서 테스트하는 기능을 제공하므로 요청/응답에 대한 테스트하기도 편리합니다. 또한 아직 API가 완성되기 전에 mock API를 만들어서 프론트에 제공하기도 편리합니다. 그런 의미에서 적용해볼만하다고 생각합니다. 사실 지금은 모르는 기술이 많은게 당연합니다. 그렇지만 모르는 기술에 대해 공부하고 장점이 있다면 적극적으로 적용해보면서 장단점을 경험하는게 현재 우테코 교육에서 공부를 하는 시기에 경험해야할 부분일 수 있을것 같아요! (실무에서는 더 보수적이 되어서 새로운 기술을 바로 적용하는게 더 어렵습니다..🥲 이런 기회에 많이 적용해보세요~ㅎㅎ)

2023-06-09 15:00 UTC, sonypark approved these changes
케로 안녕하세요!
레벨2 마지막 미션까지 수고 많으셨습니다.
이번 미션을 통해 프론트와의 협업 과정도 배우고, 앞으로 있을 팀플에 대해 맛보기 경험을 하는 좋은 시간이었길 바랍니다😃
앞으로 남은 미션들도 화이팅입니다! 수고하셨어요 :)

2023-06-09 15:00 UTC, merged

2023-06-09 15:04 UTC, sonypark commented on src/main/java/cart/dao/CartItemDao.java
>      }
- 사용자가 요청한 ID가 존재하지 않는 ID라 update, delete 가 이루어지지 않고, OK 응답을 받는게 적절할까요?
- 사용자는 OK 응답을 보고 정상적으로 수정/삭제가 일어났다고 판단할것 같아서요