[2단계 - 주문 기능 구현] 조이(김성연) 미션 제출합니다.
woowacourse/jwp-shopping-order pull request #99
Opened 2023-06-05 08:25 UTC by yeonkkk

2023-06-05 10:28 UTC, yeonkkk reviewed
이번에 안드로이드 크루들과 협업을 하면서 소통의 중요성을 깨닫게 되었습니다.  
기능 구현도 중요하지만, 함께 협의하는 과정이 더 중요하다고 느껴서 전체 회의를 많이 진행했는데요!
그런데 약 3시간 정도의 3~4회 정도 진행을 하니 생각보다 개발할 시간이 부족함이 느껴졌습니다..
그리고 실제로 서버를 배포한 뒤 추가적으로 발생하는 클라이언트의 요청을 처리하다보니 더 시간이 없다고 느꼈습니다. 
그 과정에서 몇가지 궁금증이 생겼습니다.
1. 실제로 일을 하게 되면 이와 같이 개발할 시간이 상대적으로 부족한지 궁금합니다..!
2. 소통 능력이 부족해서 회의가 길어져 더 어려움이 있었던 것 같습니다. 혹시 팀프로젝트 전 원활한 협업을 위해 어떤 능력을 향상시키면 좋을지, 그리고 능력을 향상시킬 수 있는 추천 방법이 있는지 궁금합니다ㅎㅎ

2023-06-05 10:28 UTC, yeonkkk commented on src/main/java/cart/repository/OrderRepositoryImpl.java
> +    }
현재 order에 대한 요청을 처리할 때, join을 통해 Order 데이터를 한 번에 가져오지 않고 repository에서 조립해주는 형태를 가지고 있습니다. join을 통해 객체를 생성하면, join 비용 뿐만 아니라 dao가 복잡해지는 문제가 있어서 이와 같이 작성해보았습니다.
그러나 이런 경우 쿼리를 여러번 날리기 때문에 성능 저하 문제를 피할 수 없다고 생각하지만 당장 경험해보지 않아서 상대적으로 복잡도가 낮은 방법을 선택하게 되었습니다.
정답이 없는 것은 알지만 실무에서 서비스를 제작할 때, 이러한 경우 어떤 방법을 더 많이 사용하는지 궁금합니다!

2023-06-05 10:28 UTC, yeonkkk commented on src/main/java/cart/dao/ProductDao.java
> +    }
현재 페이징을 위해 productDao와 cartItemDao에서 위와 같은 작업을 수행하고 있습니다. 한번에 전체 조회를 수행하지 않고, 요청한 페이지에 대한 데이터만 가져올 수 있기 위해 이 방법을 선택하였습니다. 그런데 이 방법을 사용하면 1) 페이지 정보 조회를 위한 쿼리, 2)해당 페이지에 포함되는 데이터들을 가져오는 쿼리가 필요해서 총 2회의 요청이 수행됩니다.
제 페어는 동일한 기능을 구현하기 위해 DB에서 전체 데이터를 가져와서 내부적으로 페이지에 대한 정보와 해당하는 데이터를 필터링해서 응답하는 방식을 사용하였습니다. 
이 역시 정답이 없는 문제이지만, 효율성이나 비용을 고려했을 때,  어떤 방법을 선택을 하는 것이 좋을지 토니의 의견이 궁금합니다!

2023-06-05 10:28 UTC, yeonkkk commented on src/main/java/cart/ui/api/CartItemApiController.java
> +        return ResponseEntity.ok().body(cartItemsResponse);
함께 협업을 진행한 안드로이드 크루들이 페이징을 요청하여 이번 미션에 적용을 해보았습니다! 그런데 작성을 하면서 하나 궁금한 점이 생겼습니다. 
서버에서 데이터를 줄 때 페이징을 해서 줄수도 있고, 클라이언트에서 처리할수도 있다고 들었는데 실무에서는 어떤 방식을 많이 사용하는지 궁금합니다 ㅎㅎ

2023-06-06 03:35 UTC, toneyparky commented on src/main/java/cart/application/OrderService.java
> +        CartItems subCartItems = cartItems.getSubCartItems(request.getCartItemIds());
`subCartItems` 은 어떤 개념인가요?

2023-06-06 03:35 UTC, toneyparky commented on src/main/java/cart/application/OrderService.java
> +    public OrderResponse findOrder(final Long orderId, final Member member) {
조이는 `@Transactional(readOnly = true)`에 대해 알고 계신가요? 해당 옵션은 어떤 기능을 하나요?

2023-06-06 03:35 UTC, toneyparky commented on src/test/java/cart/integration/OrderIntegrationTest.java
> +    @DisplayName("주문 정책을 조회한다.")
`discount-policies` 는 어떤 용어를 사용하여 표현하나요~?

2023-06-06 03:35 UTC, toneyparky commented on src/main/java/cart/ui/api/OrderApiController.java
> +public class OrderApiController {
노션을 이용하여 API 문서를 작성해주신 부분 좋네요~! 덕분에 API를 파악하기 쉬웠어요! 

조이가 잘 해주셨으니 여기서 한 단계 더 나아가보죠! 이렇게 코드가 아닌 별도의 문서를 통해 작성한 API 문서의 단점은 뭐라 생각하시나요? 댓글로 남겨주세요! 그리고 Swagger라는 API 문서 자동화 툴을 적용해보시죠 😊

2023-06-06 03:35 UTC, toneyparky commented on src/main/java/cart/ui/api/OrderApiController.java
> +        return ResponseEntity.created(URI.create("/order/" + orderId)).build();
Post 요청에 대한 응답으로 헤더에 Location을 보내주셨군요. 이는 어떤 의미에요?

2023-06-06 03:35 UTC, toneyparky commented on src/main/java/cart/ui/api/OrderApiController.java
> +    }
할인 정책을 따로 조회하고 할인된 주문의 가격을 프론트에서 계산하여 서버에 주문 요청을 보내는 구조인가요~?

2023-06-06 03:35 UTC, toneyparky commented on src/main/java/cart/ui/ControllerExceptionHandler.java
> +        logger.error("잘못된 요청: " + e, e);
로깅의 레벨 중 ERROR를 사용하셨군요..!

로깅에는 어떤 레벨이 있는지 정리해주세요. 그리고 그 중 왜 이곳에서는 ERROR를 사용하셨을까요?

2023-06-06 03:35 UTC, toneyparky commented on README.md
> +## 기능 구현 목록
질문에 대해 이야기해보죠 :

> 1. 실제로 일을 하게 되면 이와 같이 개발할 시간이 상대적으로 부족한지 궁금합니다..!

맞아요 부족해요..! 현업에서는 더 많은 이해관계자들과 이야기해야하기에 회의가 더 많답니다. 그리고 운영하고 있는 서비스에 대해서 유지보수도 해야하기에 그 쪽에도 시간을 소모하구요. 이 부분은 현업가서도 반복되는 상황이랍니다. 그렇기에 시간을 확보하고 주어진 개발을 집중해서 마무리하는 능력이 중요한 것 같아요.


> 2. 소통 능력이 부족해서 회의가 길어져 더 어려움이 있었던 것 같습니다. 혹시 팀프로젝트 전 원활한 협업을 위해 어떤 능력을 향상시키면 좋을지, 그리고 능력을 향상시킬 수 있는 추천 방법이 있는지 궁금합니다ㅎㅎ

조이가 생각하는 소통 능력은 어떤거에요? 그리고 협업이 원활하게 되는 팀은 어떤 팀이라 생각하시나요?

2023-06-06 03:35 UTC, toneyparky commented on src/main/java/cart/repository/OrderRepositoryImpl.java
> +    }
여러 테이블에 있는 정보로 하나의 객체를 만들 때에 조회 방식에 대해 질문해주셨군요. 이 부분은 애플리케이션의 규모와 특성에 따라 다를 것 같아요. 조이가 말해주신 것처럼 쿼리를 여러번 날리는게 대부분의 경우에는 성능이 안 좋을거에요. 다만 조인이라고 언제나 성능적으로 우위를 점하지 않을거에요. 만일 애플리케이션의 성능이 중요한 요소이고, 해당 쿼리가 자주 호출된다면 두가지 방법을 실제로 구현해보고 성능 테스트를 통해 데이터를 가지고 결정할 것 같아요. 만일 팀 프로젝트를 하며 고민이 되는 상황에 놓인다면 실제로 성능 테스트를 해보고 그 결과로 팀원들을 설득할 수 있을거에요. 면접과 같은 상황에서도 이야기할만한 내용이구요.

정답이 없음을 알고 계시겠지만 여쭤보셨으니 현업에서는 쿼리를 짜는 경우를 더 많이 본 것 같다는 문장도 덧붙일게요~!

2023-06-06 03:35 UTC, toneyparky commented on src/main/java/cart/dao/ProductDao.java
> +    }
현재 프로젝트가 기대하는 데이터의 처리량이 중요할거에요. 이 미션에서는 많아야 100개 정도의 데이터를 다루겠지만 현업에서는 더 많은 데이터를 다룰거에요. 현업의 데이터도 서비스의 규모에 따라 천차만별일거구요. 그렇기에 이것도 위의 답변처럼 두가지를 실제로 테스트해볼 것 같아요. 

이것도 의견을 여쭤봐주셨으니 답변드리자면 상품과 장바구니의 특성에 따라 다르게 구현할 것 같아요. 데이터의 양이 적거나 값이 자주 변하지 않는 경우는 페어처럼 구현하여 복잡도를 줄이고 그 대신 전체 데이터를 캐싱할 수 있을 것 같아요. 상품이 그런 경우겠죠? 관리자가 추가/제거하니까요. 하지만 장바구니는 사용자가 추가/제거하기에 자주 변하는 특성이 있을 것 같아요. 그렇기에 조이처럼 구현할까 해요. 여기서 더 깊게 가보면 장바구니는 특정 사람에 속한 정보만 보여주기에 개수 자체가 줄어들어서 굳이 페이징을 해야할까도 싶네요.

2023-06-06 03:35 UTC, toneyparky commented on src/main/java/cart/ui/api/CartItemApiController.java
> +        return ResponseEntity.ok().body(cartItemsResponse);
개인적으로 클라이언트에 많은 부하를 주는 로직을 넣기보다는 서버에서 최대한 처리해서 주는걸 선호해요. 만일 클라에서 처리한다면 모든 데이터를 넘기고 이를 브라우져에서 처리한다는 의미인데, 서버보다 성능이 좋지 않을테니 버벅일 가능성이 있고 이는 사용자에게 좋지 않은 경험을 제공할거에요.

협업 미션을 하며 지금까지는 생각해보지 못한 관점을 고민하셨군요! 좋네요~!

2023-06-06 03:36 UTC, toneyparky requested changes
안녕하세요 조이~! 

이번 협업 미션 잘 해주셨네요! 책임을 적절하게 나눠주어서 프로젝트가 깔끔하다 생각해요 👍
질문에 대한 답변과 제 의견도 적었으니 확인부탁해요!
그리고 궁금한 점은 편하게 DM 주세요!

2023-06-08 18:14 UTC, yeonkkk reviewed
안녕하세요 토니!
레벨 인터뷰로 인해 두번째 리뷰 요청도 늦어졌습니다..!
늦었지만 이번 리뷰도 잘 부탁드리겠습니다 🥲  
감사합니다!

2023-06-08 18:14 UTC, yeonkkk commented on README.md
> +## 기능 구현 목록
> 조이가 생각하는 소통 능력은 어떤거에요?   
기존에 제가 생각한 소통 능력은 서로의 기분이 상하지 않을 정도로 예의를 갖추고, 상대가 빠르게 의도를 파악할 수 있게 명확하게 소통하는 것이었습니다. 그런데 이번 협업 미션을 진행하면서 그 이상의 능력이 필요한 것이 아닐까 생각했습니다.   
1) 상대의 의도도 명확하게 파악해야 하는 것, 그리고 파악하지 못 했다면 빠르게 다시 확인해야 시간을 절약할 수 있다는 것  
2) 논의한 내용을 요약하거나 정리하는 능력  
3) 상대가 이해할 수 있는 용어를 사용하는 것   
협업을 하면서 위 3가지 능력에 대해서 추가로 생각해보게 되었던 것 같습니다!  

> 협업이 원활하게 되는 팀은 어떤 팀이라 생각하시나요?  

저는 아래 내용을 충족한다면 협업이 원활하게 되는 팀이라고 생각합니다.  

1) 서로 소통하는데 거리낌이 없어야 한다.  
2) 모두가 적절한 역할을 가지고, 그 책임에 맞게 작업을 수행한다.  
3) 새롭게 무언가를 적용하거나 기존 작업에 대한 수정을 할 때, 누구나 의견을 제시하고 반영할 수 있어야 한다.  
4) 체계나 규칙이 있어 모두가 효율적으로 일할 수 있어야 한다.

2023-06-08 18:14 UTC, yeonkkk commented on src/main/java/cart/application/OrderService.java
> +        CartItems subCartItems = cartItems.getSubCartItems(request.getCartItemIds());
`memberId`로 전체 `cartItem`을 조회하고, 그 중 주문 요청으로 들어온 `cartItemId`를 가진` CartItem`들을 모은 개념입니다.  
`getSubCartItems()` → `getSubCartItemsByIds()`, `subCartItems` → `orderedCartItems` 로 변경하는 것이 명확할 것 같아서 수정하였습니다.

2023-06-08 18:14 UTC, yeonkkk commented on src/main/java/cart/dao/ProductDao.java
> +    }
생각해보니 토니의 말씀처럼 장바구니에는 페이징이 적절하지 않을 수 있겠네요. 오히려 계속 누적되는 주문 내역 조회에 필요하지 않을까 싶습니다.🤔
이 부분은 클라이언트 크루들과 함께 정한 부분이라 이번 미션에서는 변경할 수 없겠지만, 이후에 페이징을 적용할 때 참고할 수 있겠습니다. 감사합니다 ㅎㅎ!

2023-06-08 18:14 UTC, yeonkkk commented on src/main/java/cart/repository/OrderRepositoryImpl.java
> +    }
현업에서는 쿼리로 진행하는 경우가 많군요.. 하지만 고민이 될 경우에는 성능 테스트를 해보는게 가장 좋겠네요..! 감사합니다 👍

2023-06-08 18:14 UTC, yeonkkk commented on src/main/java/cart/ui/api/OrderApiController.java
> +public class OrderApiController {
별도의 문서로 API 명세를 작성하면 클라이언트에 빠르게 전달할 수 있다는 장점이 있습니다. 하지만 변경 사항이 있을 때마다 수작업으로  수정해주어야 하는 불편함이 있을 것 같습니다. 그리고 그 과정에서 오타나 일부 변경을 놓치는 실수가 있을수도 있다는 단점이 있습니다(실제로 이번 협업 미션에서 겪었습니다🥲).  
swagger 사용하여 문서화 진행하였습니다.  
그런데 하나 궁금한 점은 토니가 swagger를 추천하신 이유가 궁금합니다!  
찾아보니 api 문서 자동화 툴로 swagger와 restDocs를 많이 사용하고, 그 장단점이 극명한 것 같다고 느꼈습니다.  
혹시 미션의 마감 시간을 고려해서 swagger를 추천해주신 걸까요? 아니면 특별한 장점이 있어서 추천해주신걸까요?  
매우 중요한 것은 아니지만 궁금해져서 여쭤봅니다 ㅎㅎ🙂

2023-06-08 18:14 UTC, yeonkkk commented on src/main/java/cart/ui/api/OrderApiController.java
> +        return ResponseEntity.created(URI.create("/order/" + orderId)).build();
1) 클라이언트에 생성된 자원의 정보 전달하기 위한 목적을 가집니다.    
2) 클라이언트에서 리다이렉트가 필요한 경우를 고려하였습니다.

2023-06-08 18:14 UTC, yeonkkk commented on src/main/java/cart/ui/api/OrderApiController.java
> +    }
네 맞습니다.  
다만 추가로 서버에서도 DB에서 조회한 주문 상품들의 가격을 계산해서 양쪽의 계산 결과가 동일할 경우 주문이 생성됩니다!

2023-06-08 18:14 UTC, yeonkkk commented on src/test/java/cart/integration/OrderIntegrationTest.java
> +    @DisplayName("주문 정책을 조회한다.")
제가 질문을 제대로 이해한 것인지 모르겠으나, 어떤 의미인지 물으시는 것이라면 `할인 정책`을 의미합니다!  
그런 의미에서 displayName에 적힌 부분이 모호한 것 같아서 수정하였습니다!

2023-06-08 18:14 UTC, yeonkkk commented on src/main/java/cart/application/OrderService.java
> +    public OrderResponse findOrder(final Long orderId, final Member member) {
네 알고있습니다. 
해당 옵션을 사용하면 조회 작업만 진행하는 경우 작업처리의 효율을 높일 수 있습니다(select문만 사용하는 경우).  
조회 기능들에 해당 옵션을 추가해주면 좋을 것 같아 이번에 추가하였습니다!

2023-06-08 18:14 UTC, yeonkkk commented on src/main/java/cart/ui/ControllerExceptionHandler.java
> +        logger.error("잘못된 요청: " + e, e);
> 로깅에는 어떤 레벨이 있는지 정리해주세요.   
로그 레벨은 trace, debug, info, warn, error가 있습니다.    
각 레벨을 정리해보면 아래와 같습니다.  
1) trace: 모든 레벨에 대한 로깅 추적/개발 단계에서 사용  
2) debug: 디버깅에 유용한 세분화된 정보/SQL 로깅 가능/개발 단계에서 사용  
3) info: 진행상황 등의 일반 정보  
4) warn: 잠재적으로 오류 원인이 될 수 있는 경고성 정보(당장 문제는 없으나 주의해야 하는 수준)  
5) error: 예상치 못한 문제/즉시 조취를 취해야하는 문제  

>  왜 이곳에서는 ERROR를 사용하셨을까요?    

배포 시 콘솔에는 info ~ error 레벨의 로그를 남기고, 로그 파일에 error 단계의 문제만 분류하고 싶어서, 로그 레벨을 error로 설정하였습니다.

2023-06-10 05:01 UTC, toneyparky commented on src/main/java/cart/dao/ProductDao.java
> +    }
네 주문 내역 조회 유즈케이스는 딱 적용하기 좋네요! 지금은 연습을 하는 과정이라 생각하기에 괜찮지만 추후에는 기술을 위해서 구현하기보다는 서비스에 맞는 요구사항을 이루기 위해 개발을 해야해요. 잘 이야기하다보면 생각하다보면 개발을 하지 않고 문제를 해결하는 경우도 생긴답니다. 팀 프로젝트에서 많이 고민해보시고 페이징이 필요할 때에 적절하게 적용해보시죠!

2023-06-10 05:02 UTC, toneyparky commented on src/main/java/cart/application/OrderService.java
> +        CartItems subCartItems = cartItems.getSubCartItems(request.getCartItemIds());
굳굳 훨씬 이해하기 좋아졌네요. `subCartItems`라는 개념이 장바구니 항목의 일부임은 알 수 있지만 이게 도메인적으로 어떤 의미인지 알기 어려웠어요. 잘 해주셨습니다 😬

2023-06-10 05:02 UTC, toneyparky commented on src/main/java/cart/application/OrderService.java
> +    public OrderResponse findOrder(final Long orderId, final Member member) {
네 해당 옵션을 이용하면 쿼리를 최적화한다던가(JPA 같은 특정 라이브러리까지 함께 사용해야하는 경우도 있지만요) 조회가 아닌 CUD 쿼리가 포함될 경우 에러가 발생한다던가하는 장점이 있어요. 또한 이외에도 이 메서드가 조회만을 담고 있기에 사이드 이펙트를 불러 일으키지 않음을 코드로 표현할 수 있는 방법이에요.

잘 추가해주셨습니다 !

2023-06-10 05:02 UTC, toneyparky commented on src/test/java/cart/integration/OrderIntegrationTest.java
> +    @DisplayName("주문 정책을 조회한다.")
의도를 잘 파악해주셨네요 👍  

저희가 개발을 한다함은 특정한 영역 내의 문제나 요구사항을 해결하기 위함이죠. 여기에서 특정 영역이 바로 도메인이라고 불리어요. 지금 미션에서의 도메인은 쇼핑, 그 중에서도 주문이라 생각해요. 

주문을 함에 있어 장바구니, 고객, 할인 정책 등등의 `용어`들이 등장하죠. 그리고 그 용어는 함께 개발하는 팀원들, 개발자를 넘어 기획자와 같은 비개발 직군의 팀원들까지 함께 이해하고 있어야해요. 이제 방학이 끝나면 팀 프로젝트가 진행될텐데 조이가 속한 팀의 용어 사전을 만들어서 도메인에 해당되는 어떤 용어가 존재하는지 분석해보고 이를 통해 팀원 모두가 같은 생각을 할 수 있을거에요. 한글, 영어 모두 정해야 문서, 코드 작성시 통일감 있고 이번 리뷰와 같은 사항을 피할 수 있을거에요.

2023-06-10 05:02 UTC, toneyparky commented on src/main/java/cart/ui/api/OrderApiController.java
> +public class OrderApiController {
> 미션의 마감 시간을 고려해서 swagger를 추천해주신 걸까요

현재 상황은 요게 맞아요~! ㅋㅋ 다른 코멘트도 그렇고 제 의도를 잘 파악하시는군요. 레스트독스는 아무래도 학습 곡선이 더 가팔라서 간단하게 적용해볼 수 있는 스웨거를 추천드렸습니다. 방학 동안 시간이 남는다면 하루 이틀정도 시간을 들여 레스트독스도 적용해보시고 장단점을 비교해보셔도 좋겠다 싶어요. 

개인적인 선호를 공유드리자면 사용하기 편리한 스웨거입니다. 운영 코드가 영향을 받는다는 단점은 사용해보니 그닥 크게 느껴지지 않아서요.

2023-06-10 05:02 UTC, toneyparky commented on src/main/java/cart/ui/api/OrderApiController.java
> +        return ResponseEntity.created(URI.create("/order/" + orderId)).build();
정확히 알고 계시군요~! 그렇다면 클라이언트는 해당 헤더로 들어온 엔드포인트로 자원을 접근할 수 있을거라 기대하겠네요!

그런데 지금은 `/orders/id`가 아닌 `/order/id`라 의도한 바를 수행할 수 없을 것 같아요. 다음에는 요런 부분까지 챙겨주시면 더 좋은 API가 될거 같아요 🙂

2023-06-10 05:02 UTC, toneyparky commented on src/main/java/cart/ui/api/OrderApiController.java
> +    }
굳굳 프론트만 믿고 주문 및 결제를 진행하는건 좋지 않다고 생각해요. 왜냐하면 프론트는 위조의 가능성이 크기 때문이에요. 백엔드에서 더블체크해주신 부분 꼼꼼함이 드러나네요!

2023-06-10 05:02 UTC, toneyparky commented on src/main/java/cart/ui/ControllerExceptionHandler.java
> +        logger.error("잘못된 요청: " + e, e);
그렇군요~! 적어주신 레벨의 정의에 따르면 사용자가 요청 시 값을 잘못 넣어주는 경우에 대해 서비스 운영자의 입장에서 즉시 조치를 취해야한다고 생각하시는걸까요~?

2023-06-10 05:02 UTC, toneyparky commented on README.md
> +## 기능 구현 목록
> 상대의 의도도 명확하게 파악해야 하는 것, 그리고 파악하지 못 했다면 빠르게 다시 확인해야 시간을 절약할 수 있다는 것
논의한 내용을 요약하거나 정리하는 능력
상대가 이해할 수 있는 용어를 사용하는 것

기존에 생각하셨던 소통 능력은 평소 대화에서 지켜야할 기초적인 능력으로 보여져요 (물론 중요하죠!) 하지만 업무적으로, 개발적으로 소통을 하다보니 위와 같은 내용을 고려하시게 된 것 같네요 👍 

업무에서의 대화는 결국 서로에게 명확한 내용을 이해시키고 이해하는거라 생각해요. 저도 어려워서 많이 배워야하는 부분입니다 🥲 
그래도 이런 고민을 하신다는 게 발전의 방향성을 잡았다고 느껴지네요! 

세가지를 하기 위해서는 가장 기본적인게 3번이라 생각해요. 용어가 명확해야 서로 같이 이해할 수 있으니까요. 제가 위에서 남겼던 용어에 대한 리뷰 같이 정확한 용어를 팀원끼리 공유하는거 부터 시작해보시죠! 

> 서로 소통하는데 거리낌이 없어야 한다.
모두가 적절한 역할을 가지고, 그 책임에 맞게 작업을 수행한다.
새롭게 무언가를 적용하거나 기존 작업에 대한 수정을 할 때, 누구나 의견을 제시하고 반영할 수 있어야 한다.
체계나 규칙이 있어 모두가 효율적으로 일할 수 있어야 한다.

이 부분은 소통을 넘어 팀 빌딩까지 고려해야해요. 팀 프로젝트는 이를 연습하기에 최적의 기회구요. 조이가 이번 레벨 3에서 팀이 원활하게 협업할 수 있도록 기여하는 역할을 맡는다면 많이 경험하시고 성장하실 수 있겠네요..! 
개인적으로 우테코 프로젝트를 하며 느낀바는 팀원간에 소통을 많이하고 친해질 시간을 가져야한다 생각해요. 그리고 모두가 합의하는 팀 규칙이 있어야하구요. 초반에 대화를 많이 나누시길 바라요 🙂

2023-06-10 05:03 UTC, toneyparky approved these changes
안녕하세요 조이~ 
마지막 미션에 제가 남긴 리뷰를 잘 반영해주셨어요. 머지하도록 할게요.
몇개는 추가로 질문을 드렸기에 확인하고 답변 남겨주시면 대화를 더 나누죠!
디엠 주셔도 좋구요
고생 많으셨습니다. 행복한 방학 보내세요!!

2023-06-10 05:03 UTC, merged

2023-06-12 06:37 UTC, yeonkkk reviewed
안녕하세요 토니! 조이입니다 ㅎㅎ
이번에도 친절하고 꼼꼼한 리뷰 감사드립니다.  
질문주신 내용에 대한 답과 추가적인 질문이 있어서 조금 남겨보았습니다.  
편하실 때 확인해주시면 감사하겠습니다.  
좋은 하루 보내세요!💕

2023-06-12 06:37 UTC, yeonkkk commented on src/main/java/cart/ui/ControllerExceptionHandler.java
> +        logger.error("잘못된 요청: " + e, e);
토니의 질문에 답을 하려니 빠르게 조치를 취해야하긴하지만 당장 조치를 취할 부분인지는 잘 모르겠네요..오히려 개선해야할 부분이 아닌가 싶습니다. 오히려 error 보다는 warn으로 레벨을 설정하는 것이 좋겠다는 생각이 드네요!

2023-06-12 06:37 UTC, yeonkkk commented on src/main/java/cart/ui/api/OrderApiController.java
> +public class OrderApiController {
그렇군요.. 감사합니다 토니 ㅎㅎ 둘 다 사용해보고 장단점을 확인해보는게 좋겠네요 !  
또 궁금한 점은 찾아보니 swagger와 rest docs를 같이 쓰는 경우도 있던데, 실제로는 어떤 방식을 많이 사용하나요?  
이렇게 코드를 통해 API 문서 자동화 하는 방법을 많이 사용하는지도 궁금합니다 ㅎㅎ(수기로 명세를 작성해서 주는 경우도 많이 있을 것 같아서요 !)

2023-06-18 03:48 UTC, toneyparky commented on src/main/java/cart/ui/api/OrderApiController.java
> +public class OrderApiController {
아이고 답변이 늦었군요..!

말씀해주신대로 같이 사용하는 경우도 있어요. 둘의 이점을 모두 누릴 수 있는 방법이죠. 각 팀마다, 프로젝트마다 특성이 다르기에 하나의 정답이 있는 질문은 아니에요. 저희 팀은 외부로 제공하는 API가 별로 없고 웹 클라이언트도 자체적으로 만들어요. 그러므로 API를 변경하기 쉽고 버그가 있어도 쉽게 고칠 수 있어요. 이에 따라 컨트롤러 테스트는 작성하지 않아 시간적인 효율성을 추구해요. 자연스레 더 간단하게 사용할 수 있는 스웨거를 사용하구요. 

다만 외부의 클라이언트에게 더 명확한 API를 제공해야하는 프로젝트라면 테스트를 작성하게 될테고 그에 따라 RestDocs를 사용하는게 더 나은 선택이 될 수도 있구요. 

두가지 방법 모두 결국 코드에 반영이 되어야 문서가 생기기에 수기로 작성/합의하고 초기에 공유하여 작업하기도 하는 걸로 알고 있어요. 

팀 프로젝트를 하면서 조이가 생각하는 최적의 방법을 제안하고 다른 방법 대비 어떤 장,단점이 있는지 비교해보면 좋겠네요 😉

2023-06-18 03:53 UTC, toneyparky commented on src/main/java/cart/ui/ControllerExceptionHandler.java
> +        logger.error("잘못된 요청: " + e, e);
개인적인 기준으로는 사용자가 잘못 입력한 상황에 대해 warn 레벨로도 로그를 찍을 필요가 있을까라는 생각이 들어요. 왜냐하면 서버의 에러가 아닌 사용자의 입력에 따른 에러이기 때문이에요. 숫자를 쿼리 파라미터로 넘겨야하는 API에서 사용자가 한글과 같은 문자열을 넘긴다고 하여 잠재적으로 오류의 원인이 될지를 잘 고려해보시면 좋겠어요. 오히려 사용자에게 명확한 예외 메시지를 보여주는 편이 더 낫지 않을까해요. (사용자가 조치해야하는 사항이니까요)